/*
목적
  SND_MEMBER_LIST ↔ OPEN/CLICK LOG 연결키의 실제 Snowflake Grain을 판정한다.

실행 주의
  - 모두 읽기 전용 SELECT다.
  - 대형 테이블이므로 필요하면 WHERE에 최근 기간 조건을 먼저 추가하되,
    전역 유일성 판정은 반드시 전체 범위에서도 실행한다.
  - 01_KEY_COLUMNS 결과에 REQ_SEQ_NO가 없으면 03~09는 실행하지 말고
    01~02 결과를 먼저 공유한다.
  - 결과 전체를 RESULT_SET 이름과 함께 공유한다.
*/

USE DATABASE GN_DW;
USE SCHEMA BRONZE_CRM;

-- 00. 실행 컨텍스트
SELECT
    '00_CONTEXT' AS RESULT_SET,
    CURRENT_ACCOUNT() AS ACCOUNT_NAME,
    CURRENT_ROLE() AS ROLE_NAME,
    CURRENT_WAREHOUSE() AS WAREHOUSE_NAME,
    CURRENT_DATABASE() AS DATABASE_NAME,
    CURRENT_SCHEMA() AS SCHEMA_NAME,
    CURRENT_TIMESTAMP() AS EXTRACTED_AT;

-- 01. 키 후보 컬럼의 실제 존재·타입
SELECT
    '01_KEY_COLUMNS' AS RESULT_SET,
    TABLE_NAME,
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COMMENT
FROM GN_DW.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'BRONZE_CRM'
  AND UPPER(TABLE_NAME) IN (
      'SND_REQ_MST',
      'SND_MEMBER_LIST',
      'SND_MEMBER_OPEN_LOG',
      'SND_MEMBER_MAIL_LINK_LOG'
  )
  AND UPPER(COLUMN_NAME) IN (
      'SEQ_NO', 'REQ_SEQ_NO', 'R_NUM', 'MBER_NO', 'LOG_SEQ',
      'SND_YN', 'SND_DT', 'REAL_SEND_DT', 'OPEN_DT', 'CLICK_DT'
  )
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- 02. 세 테이블 R_NUM 기본 프로파일
WITH P AS (
    SELECT 'SND_MEMBER_LIST' AS TABLE_NAME,
           COUNT(*) AS TOTAL_ROWS,
           COUNT_IF(R_NUM IS NULL) AS NULL_R_NUM_ROWS,
           COUNT(DISTINCT R_NUM) AS DISTINCT_R_NUMS
    FROM GN_DW.BRONZE_CRM.SND_MEMBER_LIST
    UNION ALL
    SELECT 'SND_MEMBER_OPEN_LOG', COUNT(*), COUNT_IF(R_NUM IS NULL), COUNT(DISTINCT R_NUM)
    FROM GN_DW.BRONZE_CRM.SND_MEMBER_OPEN_LOG
    UNION ALL
    SELECT 'SND_MEMBER_MAIL_LINK_LOG', COUNT(*), COUNT_IF(R_NUM IS NULL), COUNT(DISTINCT R_NUM)
    FROM GN_DW.BRONZE_CRM.SND_MEMBER_MAIL_LINK_LOG
)
SELECT
    '02_R_NUM_PROFILE' AS RESULT_SET,
    TABLE_NAME,
    TOTAL_ROWS,
    NULL_R_NUM_ROWS,
    DISTINCT_R_NUMS,
    TOTAL_ROWS - NULL_R_NUM_ROWS - DISTINCT_R_NUMS AS EXTRA_ROWS_OVER_DISTINCT_NON_NULL,
    IFF(TOTAL_ROWS - NULL_R_NUM_ROWS = DISTINCT_R_NUMS, 'UNIQUE_NON_NULL', 'DUPLICATED') AS NON_NULL_UNIQUENESS
FROM P
ORDER BY TABLE_NAME;

-- 03. SND_MEMBER_LIST에서 R_NUM 단독 중복
SELECT
    '03_MEMBER_R_NUM_DUPLICATES' AS RESULT_SET,
    R_NUM,
    COUNT(*) AS ROWS_PER_R_NUM,
    COUNT(DISTINCT REQ_SEQ_NO) AS REQUESTS_PER_R_NUM,
    COUNT(DISTINCT MBER_NO) AS MEMBERS_PER_R_NUM
FROM GN_DW.BRONZE_CRM.SND_MEMBER_LIST
WHERE R_NUM IS NOT NULL
GROUP BY R_NUM
HAVING COUNT(*) > 1
ORDER BY ROWS_PER_R_NUM DESC, R_NUM
LIMIT 100;

-- 04. SND_MEMBER_LIST의 (REQ_SEQ_NO, R_NUM) 복합키 중복
SELECT
    '04_MEMBER_COMPOSITE_DUPLICATES' AS RESULT_SET,
    REQ_SEQ_NO,
    R_NUM,
    COUNT(*) AS ROWS_PER_KEY,
    COUNT(DISTINCT MBER_NO) AS MEMBERS_PER_KEY
FROM GN_DW.BRONZE_CRM.SND_MEMBER_LIST
WHERE REQ_SEQ_NO IS NOT NULL
  AND R_NUM IS NOT NULL
GROUP BY REQ_SEQ_NO, R_NUM
HAVING COUNT(*) > 1
ORDER BY ROWS_PER_KEY DESC, REQ_SEQ_NO, R_NUM
LIMIT 100;

-- 05. 요청 마스터 ↔ 수신자 목록 미매칭
SELECT
    '05_REQUEST_MEMBER_UNMATCHED' AS RESULT_SET,
    COUNT(*) AS MEMBER_ROWS,
    COUNT_IF(M.REQ_SEQ_NO IS NULL) AS NULL_REQUEST_KEY_ROWS,
    COUNT_IF(M.REQ_SEQ_NO IS NOT NULL AND R.SEQ_NO IS NULL) AS UNMATCHED_MEMBER_ROWS,
    COUNT(DISTINCT IFF(M.REQ_SEQ_NO IS NOT NULL AND R.SEQ_NO IS NULL, M.REQ_SEQ_NO, NULL)) AS UNMATCHED_REQUEST_KEYS
FROM GN_DW.BRONZE_CRM.SND_MEMBER_LIST M
LEFT JOIN GN_DW.BRONZE_CRM.SND_REQ_MST R
  ON R.SEQ_NO = M.REQ_SEQ_NO;

-- 06. 복합키 기준 오픈 로그 미매칭
SELECT
    '06_OPEN_COMPOSITE_UNMATCHED' AS RESULT_SET,
    COUNT(*) AS LOG_ROWS,
    COUNT_IF(O.REQ_SEQ_NO IS NULL OR O.R_NUM IS NULL) AS NULL_KEY_ROWS,
    COUNT_IF(O.REQ_SEQ_NO IS NOT NULL AND O.R_NUM IS NOT NULL AND M.R_NUM IS NULL) AS UNMATCHED_LOG_ROWS,
    COUNT(DISTINCT IFF(M.R_NUM IS NULL, CONCAT_WS('|', O.REQ_SEQ_NO, O.R_NUM), NULL)) AS UNMATCHED_KEYS
FROM GN_DW.BRONZE_CRM.SND_MEMBER_OPEN_LOG O
LEFT JOIN GN_DW.BRONZE_CRM.SND_MEMBER_LIST M
  ON M.REQ_SEQ_NO = O.REQ_SEQ_NO
 AND M.R_NUM = O.R_NUM;

-- 07. 복합키 기준 클릭 로그 미매칭
SELECT
    '07_CLICK_COMPOSITE_UNMATCHED' AS RESULT_SET,
    COUNT(*) AS LOG_ROWS,
    COUNT_IF(C.REQ_SEQ_NO IS NULL OR C.R_NUM IS NULL) AS NULL_KEY_ROWS,
    COUNT_IF(C.REQ_SEQ_NO IS NOT NULL AND C.R_NUM IS NOT NULL AND M.R_NUM IS NULL) AS UNMATCHED_LOG_ROWS,
    COUNT(DISTINCT IFF(M.R_NUM IS NULL, CONCAT_WS('|', C.REQ_SEQ_NO, C.R_NUM), NULL)) AS UNMATCHED_KEYS
FROM GN_DW.BRONZE_CRM.SND_MEMBER_MAIL_LINK_LOG C
LEFT JOIN GN_DW.BRONZE_CRM.SND_MEMBER_LIST M
  ON M.REQ_SEQ_NO = C.REQ_SEQ_NO
 AND M.R_NUM = C.R_NUM;

-- 08. R_NUM 단독 조인과 복합키 조인의 행 수 차이
WITH OPEN_SINGLE AS (
    SELECT COUNT(*) AS JOIN_ROWS
    FROM GN_DW.BRONZE_CRM.SND_MEMBER_OPEN_LOG O
    JOIN GN_DW.BRONZE_CRM.SND_MEMBER_LIST M
      ON M.R_NUM = O.R_NUM
    WHERE O.R_NUM IS NOT NULL
), OPEN_COMPOSITE AS (
    SELECT COUNT(*) AS JOIN_ROWS
    FROM GN_DW.BRONZE_CRM.SND_MEMBER_OPEN_LOG O
    JOIN GN_DW.BRONZE_CRM.SND_MEMBER_LIST M
      ON M.REQ_SEQ_NO = O.REQ_SEQ_NO
     AND M.R_NUM = O.R_NUM
    WHERE O.REQ_SEQ_NO IS NOT NULL AND O.R_NUM IS NOT NULL
), CLICK_SINGLE AS (
    SELECT COUNT(*) AS JOIN_ROWS
    FROM GN_DW.BRONZE_CRM.SND_MEMBER_MAIL_LINK_LOG C
    JOIN GN_DW.BRONZE_CRM.SND_MEMBER_LIST M
      ON M.R_NUM = C.R_NUM
    WHERE C.R_NUM IS NOT NULL
), CLICK_COMPOSITE AS (
    SELECT COUNT(*) AS JOIN_ROWS
    FROM GN_DW.BRONZE_CRM.SND_MEMBER_MAIL_LINK_LOG C
    JOIN GN_DW.BRONZE_CRM.SND_MEMBER_LIST M
      ON M.REQ_SEQ_NO = C.REQ_SEQ_NO
     AND M.R_NUM = C.R_NUM
    WHERE C.REQ_SEQ_NO IS NOT NULL AND C.R_NUM IS NOT NULL
)
SELECT '08_JOIN_COMPARISON' AS RESULT_SET, 'OPEN' AS LOG_TYPE,
       S.JOIN_ROWS AS R_NUM_ONLY_JOIN_ROWS,
       C.JOIN_ROWS AS COMPOSITE_JOIN_ROWS,
       S.JOIN_ROWS - C.JOIN_ROWS AS EXCESS_ROWS_FROM_R_NUM_ONLY
FROM OPEN_SINGLE S CROSS JOIN OPEN_COMPOSITE C
UNION ALL
SELECT '08_JOIN_COMPARISON', 'CLICK', S.JOIN_ROWS, C.JOIN_ROWS,
       S.JOIN_ROWS - C.JOIN_ROWS
FROM CLICK_SINGLE S CROSS JOIN CLICK_COMPOSITE C;

-- 09. 수신자별 이벤트 중복도: 1:N 로그는 정상일 수 있으므로 상위 사례만 확인
WITH O AS (
    SELECT REQ_SEQ_NO, R_NUM, COUNT(*) AS EVENT_CNT
    FROM GN_DW.BRONZE_CRM.SND_MEMBER_OPEN_LOG
    WHERE REQ_SEQ_NO IS NOT NULL AND R_NUM IS NOT NULL
    GROUP BY REQ_SEQ_NO, R_NUM
), C AS (
    SELECT REQ_SEQ_NO, R_NUM, COUNT(*) AS EVENT_CNT
    FROM GN_DW.BRONZE_CRM.SND_MEMBER_MAIL_LINK_LOG
    WHERE REQ_SEQ_NO IS NOT NULL AND R_NUM IS NOT NULL
    GROUP BY REQ_SEQ_NO, R_NUM
)
SELECT '09_EVENT_MULTIPLICITY' AS RESULT_SET, 'OPEN' AS LOG_TYPE,
       COUNT(*) AS RECIPIENT_KEYS,
       COUNT_IF(EVENT_CNT > 1) AS REPEATED_EVENT_KEYS,
       MAX(EVENT_CNT) AS MAX_EVENTS_PER_KEY
FROM O
UNION ALL
SELECT '09_EVENT_MULTIPLICITY', 'CLICK', COUNT(*),
       COUNT_IF(EVENT_CNT > 1), MAX(EVENT_CNT)
FROM C;
