-- MSTR 1차 이관 검증 쿼리 (mstr_verify.py 가 문장마다 실행 · 기대값은 manifests/1차.json "baseline")
-- @CHECK fact_by_dvlp
SELECT DVLP_DIV_CD, COUNT(*) AS N, COUNT(DISTINCT MBER_NO) AS MBR, SUM(SPNSR_AMT) AS AMT
FROM GN_DW.MSTR.F_MM_SPNSR_DVLP_SUM
WHERE STRD_MT = '{YM}'
GROUP BY 1
ORDER BY 1;

-- @CHECK fixed_cols  (ExplCampList 제외 결정 X1 — 전건 고정값이어야 한다)
SELECT
  SUM(IFF(CMPGN_CLS1_CD <> '99', 1, 0)) AS CLS1_NOT_99,
  SUM(IFF(CMPGN_CLS2_CD <> '99', 1, 0)) AS CLS2_NOT_99,
  SUM(IFF(SPCL_CMPGN_YN <> 'N', 1, 0))  AS SPCL_NOT_N,
  SUM(IFF(ACMSLT_DEPT2_CD IS NULL, 1, 0)) AS DEPT_UNMAPPED
FROM GN_DW.MSTR.F_MM_SPNSR_DVLP_SUM
WHERE STRD_MT = '{YM}';

-- @CHECK report_summary  (05 리포트 [1] — 행수 · 합계 · 차원명 미매핑)
WITH R AS (
  SELECT a11.OCCRRNC_DE,
         MAX(a12.DVLP_DIV_NM) D1, MAX(a13.STRD_NM) D2, MAX(a14.CPR_DIV_NM) D3, MAX(a15.DEPT4_NM) D4,
         MAX(a16.DEPT_NM) D5, MAX(a17.BRND_NM) D6, MAX(a18.DEPT3_NM) D7, MAX(a19.UPPER_CMPGN_NM) D8,
         MAX(a110.SEX_NM) D9, MAX(a111.AGE_TERM_NM) D10, MAX(a112.CMPGN_NM) D11, MAX(a113.DEPT2_NM) D12,
         MAX(a114.PR_MTH_NM) D13, MAX(a115.SPNSR_BSNS_NM) D14, MAX(a116.SPNSR_BSNS_NM) D15, MAX(a117.STRD_NM) D16,
         SUM(a11.SPNSR_AMT_CNT) W1, COUNT(DISTINCT a11.MBER_NO) W2, SUM(a11.SPNSR_AMT) W3
  FROM GN_DW.MSTR.F_MM_SPNSR_DVLP_SUM a11
  LEFT JOIN GN_DW.MSTR.D_DVLP_DIV_CD     a12  ON a11.DVLP_DIV_CD     = a12.DVLP_DIV_CD
  LEFT JOIN GN_DW.MSTR.D_STRD_DE_CD      a13  ON a11.OCCRRNC_DE      = a13.STRD_DE
  LEFT JOIN GN_DW.MSTR.D_CPR_DIV_CD      a14  ON a11.CPR_DIV_CD      = a14.CPR_DIV_CD
  LEFT JOIN GN_DW.MSTR.D_DEPT4_CD        a15  ON a11.ACMSLT_DEPT4_CD = a15.DEPT4_ID
  LEFT JOIN GN_DW.MSTR.D_DEPT_CD         a16  ON a11.ACMSLT_DEPT_CD  = a16.DEPT_ID
  LEFT JOIN GN_DW.MSTR.D_BRND_CD         a17  ON a11.BRND_ID         = a17.BRND_ID
  LEFT JOIN GN_DW.MSTR.D_DEPT3_CD        a18  ON a11.ACMSLT_DEPT3_CD = a18.DEPT3_ID
  LEFT JOIN GN_DW.MSTR.D_UP_CMPGN_CD     a19  ON a11.UPPER_CMPGN_CD  = a19.UPPER_CMPGN_CD
  LEFT JOIN GN_DW.MSTR.D_SEX_CD          a110 ON a11.SEX             = a110.SEX_CD
  LEFT JOIN GN_DW.MSTR.D_AGE_TERM_CD     a111 ON a11.AGE_TERM_CD     = a111.AGE_TERM_CD
  LEFT JOIN GN_DW.MSTR.D_CMPGN_CD        a112 ON a11.CMPGN_CD        = a112.CMPGN_CD
  LEFT JOIN GN_DW.MSTR.D_DEPT2_CD        a113 ON a11.ACMSLT_DEPT2_CD = a113.DEPT2_ID
  LEFT JOIN GN_DW.MSTR.D_PR_MTH_CD       a114 ON a11.PR_MTH_CD       = a114.PR_MTH_CD
  LEFT JOIN GN_DW.MSTR.D_SPNSR_BSNS_INFO a115 ON a11.SPNSR_BSNS_ID   = a115.SPNSR_BSNS_ID
  LEFT JOIN GN_DW.MSTR.D_SPNSR_BSNS_INFO a116 ON a11.SPNSR_BSNS2_ID  = a116.SPNSR_BSNS_ID
  LEFT JOIN GN_DW.MSTR.D_STRD_MT_CD      a117 ON a11.STRD_MT         = a117.STRD_MT
  WHERE a11.OCCRRNC_DE BETWEEN '{YM}01' AND '{YM}31'
    AND a11.DVLP_DIV_CD IN ('1', '2', '4')
  GROUP BY a11.STRD_MT, a11.OCCRRNC_DE, a11.ACMSLT_DEPT4_CD, a11.ACMSLT_DEPT3_CD, a11.ACMSLT_DEPT2_CD,
           a11.DVLP_DIV_CD, a11.BRND_ID, a11.CMPGN_CD, a11.UPPER_CMPGN_CD, a11.PR_MTH_CD, a11.CPR_DIV_CD,
           a11.SPNSR_BSNS_ID, a11.SPNSR_BSNS2_ID, a11.ACMSLT_DEPT_CD, a11.SEX, a11.AGE_TERM_CD
)
SELECT COUNT(*) AS ROWS_OUT, SUM(W1) AS CNT, SUM(W3) AS AMT,
       SUM(IFF(D1 IS NULL OR D2 IS NULL OR D3 IS NULL OR D4 IS NULL OR D5 IS NULL OR D6 IS NULL
               OR D7 IS NULL OR D8 IS NULL OR D9 IS NULL OR D10 IS NULL OR D11 IS NULL OR D12 IS NULL
               OR D13 IS NULL OR D14 IS NULL OR D15 IS NULL OR D16 IS NULL, 1, 0)) AS ROWS_WITH_UNMAPPED
FROM R;
