-- GN_DW 0단계: RBAC 기반(웨어하우스·역할·계층·권한) + SERVING 스키마 + CoWork object 생성
-- Co-authored with CoCo
--
-- 정본 근거:
--   02_GN_DW_building/01_환경 Role.md  §1.2 웨어하우스 · §2 role_hierarchy/roles
--   02_GN_DW_building/03_GOLD_SERVING.md §3.8 grants (schema_grants) · P7 serving_separation
--   05_SV-Agent_ai/01_SV-Agent 작업계획.md §0단계 · §7 거버넌스
--   Snowflake docs: Snowflake CoWork object (CREATE SNOWFLAKE INTELLIGENCE)
--
-- 실행 전제(2026-07-21 확인): GN_DW.GOLD(24 base table + 9 view, ACCOUNTADMIN 소유) 배포 완료.
--   커스텀 역할 6종·웨어하우스 3종·SERVING 스키마·CoWork object 전부 미생성 → 본 스크립트가 전부 선행 구축.
-- 멱등: 전 구간 IF NOT EXISTS / OR REPLACE 사용. 반복 실행 안전.

/* =====================================================================
   A. 웨어하우스 (01_환경 Role.md §1.2)
   ===================================================================== */
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS GN_DW_ETL_WH
  WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'ETL / 데이터 적재 (프로시저·태스크 전용)';

CREATE WAREHOUSE IF NOT EXISTS GN_DW_ANALYTICS_WH
  WAREHOUSE_SIZE = 'MEDIUM' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = '분석가 쿼리 / SV·Agent 소비 (Analyst·Viewer·Service)';

CREATE WAREHOUSE IF NOT EXISTS GN_DW_DEV_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = '개발/테스트 (Engineer·Admin 기본)';

/* =====================================================================
   B. 역할 생성 + 계층 (01_환경 Role.md §2.1 role_hierarchy, P4: 최종 SYSADMIN 귀속)
      SYSADMIN
        └ GN_DW_ADMIN
             ├ GN_DW_ENGINEER
             ├ GN_DW_ANALYST ─ GN_DW_VIEWER
             ├ GN_DW_LOADER
             └ GN_DW_SERVICE
   ===================================================================== */
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS GN_DW_ADMIN    COMMENT = 'GN_DW DB/스키마 관리·DDL·SV/Agent 소유';
CREATE ROLE IF NOT EXISTS GN_DW_ENGINEER COMMENT = 'ETL 개발·프로시저/태스크';
CREATE ROLE IF NOT EXISTS GN_DW_ANALYST  COMMENT = '분석 쿼리(SELECT)·SV/Agent 소비';
CREATE ROLE IF NOT EXISTS GN_DW_VIEWER   COMMENT = '읽기 전용·SV/Agent/Streamlit 소비';
CREATE ROLE IF NOT EXISTS GN_DW_LOADER   COMMENT = '외부팀 BRONZE 적재';
CREATE ROLE IF NOT EXISTS GN_DW_SERVICE  COMMENT = '서비스 계정(API·Streamlit)';

-- 계층 (자식 role → 부모 role)
GRANT ROLE GN_DW_ADMIN    TO ROLE SYSADMIN;
GRANT ROLE GN_DW_ENGINEER TO ROLE GN_DW_ADMIN;
GRANT ROLE GN_DW_ANALYST  TO ROLE GN_DW_ADMIN;
GRANT ROLE GN_DW_LOADER   TO ROLE GN_DW_ADMIN;
GRANT ROLE GN_DW_SERVICE  TO ROLE GN_DW_ADMIN;
GRANT ROLE GN_DW_VIEWER   TO ROLE GN_DW_ANALYST;

/* =====================================================================
   C. 웨어하우스 USAGE 부여 (01_환경 Role.md §2.2 warehouse 매핑)
   ===================================================================== */
USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE GN_DW_DEV_WH       TO ROLE GN_DW_ADMIN;
GRANT USAGE ON WAREHOUSE GN_DW_ETL_WH       TO ROLE GN_DW_ADMIN;
GRANT USAGE ON WAREHOUSE GN_DW_ANALYTICS_WH TO ROLE GN_DW_ADMIN;

GRANT USAGE ON WAREHOUSE GN_DW_ETL_WH       TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON WAREHOUSE GN_DW_DEV_WH       TO ROLE GN_DW_ENGINEER;

GRANT USAGE ON WAREHOUSE GN_DW_ANALYTICS_WH TO ROLE GN_DW_ANALYST;
GRANT USAGE ON WAREHOUSE GN_DW_ANALYTICS_WH TO ROLE GN_DW_VIEWER;
GRANT USAGE ON WAREHOUSE GN_DW_ETL_WH       TO ROLE GN_DW_LOADER;
GRANT USAGE ON WAREHOUSE GN_DW_ANALYTICS_WH TO ROLE GN_DW_SERVICE;

/* =====================================================================
   D. 기존 스키마 권한 (03_GOLD_SERVING.md §3.8 schema_grants)
      스키마 소유자 = ACCOUNTADMIN → ACCOUNTADMIN으로 부여.
   ===================================================================== */
USE ROLE ACCOUNTADMIN;

-- D.1 DATABASE USAGE (6개 역할 전부)
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_ADMIN;
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_ANALYST;
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_VIEWER;
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_LOADER;
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_SERVICE;

-- D.2 GOLD (분석 소비 정본 — SV base = GOLD DIM/FACT; Cortex Analyst는 caller로 GOLD 직접 실행)
--   ADMIN: 전체
GRANT ALL PRIVILEGES ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS   IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE VIEWS  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ADMIN;
--   ENGINEER: USAGE + SELECT + CREATE VIEW
GRANT USAGE, CREATE VIEW ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL TABLES  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL VIEWS   IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
--   소비 3역할(ANALYST/VIEWER/SERVICE): USAGE + SELECT (+ FUTURE)
GRANT USAGE ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT USAGE ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT USAGE ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;
GRANT SELECT ON ALL TABLES  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT SELECT ON ALL VIEWS   IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT SELECT ON ALL TABLES  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT SELECT ON ALL VIEWS   IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT SELECT ON ALL TABLES  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;
GRANT SELECT ON ALL VIEWS   IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;

-- D.3 SILVER (ENGINEER 개발 + ANALYST 읽기)
GRANT ALL PRIVILEGES ON SCHEMA GN_DW.SILVER TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS  IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ADMIN;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION ON SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON SCHEMA GN_DW.SILVER TO ROLE GN_DW_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ANALYST;
GRANT SELECT ON ALL VIEWS  IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ANALYST;

-- D.4 BRONZE_* 4종 (ADMIN 전체 / ENGINEER 읽기 / LOADER 적재)
--   BRONZE_CRM
GRANT ALL PRIVILEGES ON SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_ADMIN;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
--   BRONZE_ERP
GRANT ALL PRIVILEGES ON SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_ADMIN;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;
--   BRONZE_AGENCY
GRANT ALL PRIVILEGES ON SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_ADMIN;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
--   BRONZE_GA4
GRANT ALL PRIVILEGES ON SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_ADMIN;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_LOADER;

/* =====================================================================
   E. SERVING 스키마 생성 (P7 serving_separation) — SV·Agent 배치 계층
      소유 = GN_DW_ADMIN (SV/Agent 생성·소유 역할).
      GOLD는 cross-schema 참조(SERVING→GOLD 단방향).
   ===================================================================== */
USE ROLE ACCOUNTADMIN;

-- ADMIN이 스키마를 만들 수 있도록 DB 레벨 CREATE SCHEMA 위임
GRANT CREATE SCHEMA ON DATABASE GN_DW TO ROLE GN_DW_ADMIN;

USE ROLE GN_DW_ADMIN;
USE WAREHOUSE GN_DW_DEV_WH;
CREATE SCHEMA IF NOT EXISTS GN_DW.SERVING
  COMMENT = 'Serving 계층 — Semantic View·Cortex Agent·Streamlit 배치(P7). GOLD DIM/FACT cross-schema 참조';

-- E.1 SERVING 소비 권한: ENGINEER USAGE / 소비 3역할 USAGE
USE ROLE GN_DW_ADMIN;
GRANT USAGE ON SCHEMA GN_DW.SERVING TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON SCHEMA GN_DW.SERVING TO ROLE GN_DW_ANALYST;
GRANT USAGE ON SCHEMA GN_DW.SERVING TO ROLE GN_DW_VIEWER;
GRANT USAGE ON SCHEMA GN_DW.SERVING TO ROLE GN_DW_SERVICE;

-- ⚠️ SV·Agent object USAGE는 FUTURE grant 미지원(USAGE ON FUTURE SEMANTIC VIEWS = SQL 컴파일 오류).
--    → SV/Agent별 USAGE는 3·5단계 CREATE 직후 대상 객체에 명시 부여한다:
--        GRANT USAGE ON SEMANTIC VIEW GN_DW.SERVING.<SV> TO ROLE GN_DW_ANALYST; (VIEWER/SERVICE 동일)
--        GRANT USAGE ON AGENT GN_DW.SERVING.<AGENT> TO ROLE GN_DW_ANALYST; (VIEWER/SERVICE 동일)

/* =====================================================================
   F. CoWork object (Snowflake Intelligence) — Agent 가시성 큐레이션
      계정당 1개·고정명 SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT.
      구 SNOWFLAKE_INTELLIGENCE.AGENTS 스키마는 deprecated → 미사용.
   ===================================================================== */
USE ROLE ACCOUNTADMIN;

CREATE SNOWFLAKE INTELLIGENCE IF NOT EXISTS SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT;

-- ADMIN이 5·6단계에서 ADD AGENT 할 수 있도록 MODIFY 위임
GRANT MODIFY ON SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT TO ROLE GN_DW_ADMIN;

-- 소비 역할에 CoWork object 가시성(USAGE)
GRANT USAGE ON SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT TO ROLE GN_DW_ANALYST;
GRANT USAGE ON SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT TO ROLE GN_DW_VIEWER;
GRANT USAGE ON SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT TO ROLE GN_DW_SERVICE;

-- 참고: Cortex 사용 권한(SNOWFLAKE.CORTEX_USER)은 기본 PUBLIC에 부여되어 있어 소비 역할이 상속.
--       선택적 제한이 필요하면 7단계에서 CORTEX_USER 회수 후 CORTEX_AGENT_USER 명시 부여.

/* =====================================================================
   G. SERVING helper 뷰 — SV fan-out 차단용 (04_SV_설계.md §0.1)
      소유 = GN_DW_ADMIN. SV relationship에서 이 뷰를 logical table로 참조.
   ===================================================================== */
USE ROLE GN_DW_ADMIN;
USE WAREHOUSE GN_DW_DEV_WH;

-- G.1 DIM_MONTH: 월팩트(FMM·FBD·FTG_D·FTG_B) 시간차원 — DIM_DATE 직접 조인 시 28~31× fan-out 방지
CREATE OR REPLACE VIEW GN_DW.SERVING.DIM_MONTH
  COMMENT = 'GOLD.DIM_DATE에서 월 grain DISTINCT 추출 — 월팩트 시간차원(fan-out 차단). PK=MONTH_KEY.'
AS
SELECT DISTINCT
    MONTH_KEY,
    YEAR,
    MONTH,
    QUARTER
FROM GN_DW.GOLD.DIM_DATE
WHERE MONTH_KEY IS NOT NULL;

-- G.2 DIM_MEMBER_CURRENT: SCD2 현재행만 — 회원당 4.5버전 fan-out 방지
CREATE OR REPLACE VIEW GN_DW.SERVING.DIM_MEMBER_CURRENT
  COMMENT = 'GOLD.DIM_MEMBER SCD2 현재행(IS_CURRENT=TRUE)만 추출 — 1:1 회원조인(fan-out 차단). PK=MEMBER_DK.'
AS
SELECT
    MEMBER_SK,
    MEMBER_DK,
    GENDER,
    REGION,
    AGE_BAND,
    MEMBER_STATUS,
    MEMBER_TYPE,
    NEW_EXISTING_FLAG,
    FIRST_JOIN_DATE,
    FIRST_CAMPAIGN,
    ENROLL_PATH,
    FIRST_SPONSORSHIP,
    LAST_STOP_DATE,
    LAST_CAMPAIGN,
    CURRENT_SPONSORSHIP,
    EFFECTIVE_FROM
FROM GN_DW.GOLD.DIM_MEMBER
WHERE IS_CURRENT = TRUE;

-- G.3 소비 권한: helper 뷰에 SELECT (SV caller가 접근)
GRANT SELECT ON VIEW GN_DW.SERVING.DIM_MONTH          TO ROLE GN_DW_ANALYST;
GRANT SELECT ON VIEW GN_DW.SERVING.DIM_MONTH          TO ROLE GN_DW_VIEWER;
GRANT SELECT ON VIEW GN_DW.SERVING.DIM_MONTH          TO ROLE GN_DW_SERVICE;
GRANT SELECT ON VIEW GN_DW.SERVING.DIM_MEMBER_CURRENT TO ROLE GN_DW_ANALYST;
GRANT SELECT ON VIEW GN_DW.SERVING.DIM_MEMBER_CURRENT TO ROLE GN_DW_VIEWER;
GRANT SELECT ON VIEW GN_DW.SERVING.DIM_MEMBER_CURRENT TO ROLE GN_DW_SERVICE;
