-- [DEPRECATED 2026-07-31] Agent 대행배포 실행 로그 — 09_1·09_2 로 분해된 포인터 스텁
-- Co-authored with CoCo
-- ============================================================================
-- 이 파일은 더 이상 실행 대상이 아니다. 두 파일로 쪼개졌다.
--
--   ▶ `09_1_AGENT_생성.sql`   — Agent **껍데기**만 만든다
--      최소 스펙(`models: orchestration: auto`)으로 CREATE + 소유권 + USAGE grant 6건
--      + CoWork SI 멱등 등록 + COMMENT/PROFILE(DDL 속성 정본) + 검증.
--      구 [1-ALT]·[2]·[3]·[4]·[5] 에 대응.
--
--   ▶ `09_2_AGENT_버전업.sql` — **yaml 정본으로 스펙 버전업**
--      `ALTER AGENT … ADD VERSION FROM <stage>` 로 워크스페이스의 정본 파일을 직접 읽는다.
--      live 선소진(멱등 COMMIT) → 버전 발행 → 검증 → 롤백 절차.
--      구 [4-B] 에 대응하되 **YAML 본문을 SQL 에 복사하지 않는다**.
--
--   전문 이력(YAML 사본 포함) = `_archive/09_AGENT_spec_구현_원본_20260722.sql`
--
-- ============================================================================
-- ▶ 왜 쪼갰는가 — drift 의 구조적 제거
-- ============================================================================
--   구 09 는 Agent 스펙 YAML 전문을 [1-ALT-a/b]·[4-B-a/b] **네 블록에 사본**으로 갖고 있었고,
--   8행에 "배포용 사본 → 정본 변경 시 반드시 함께 갱신" 이라는 규약을 달아 사람 손에 의존했다.
--   그 규약이 지켜지지 않아 **동일 유형 drift 가 4회 재발**했다(교훈 P23).
--   실제로 2026-07-31 SV COMMENT 수치 제거 작업에서도 정본 yaml 만 갱신되고 09 사본은
--   구 수치(514.4억·157,969원·96.03% 등)를 그대로 들고 있는 drift 가 다시 발생했다.
--
--   근본 원인은 "사본이 존재한다"는 구조 자체였다. 09_2 는 스펙을 **stage 에서 직접 읽으므로
--   SQL 파일에 사본이 0개**다 → 갱신 누락이 발생할 자리가 없다.
--
-- ============================================================================
-- ▶ 실행 순서 (2026-07-31 확정)
-- ============================================================================
--   1. 02_GN_DW_building/07_ENVIRONMENT_RBAC_setup.sql   -- WH·역할·SERVING·CoWork SI object
--   2. (dbt 파이프라인 BRONZE→GOLD)
--   3. 05_SV_DDL.sql                                     -- SV 6종 + helper 뷰 + §7 GRANT + §8 검증
--   4. 09_1_AGENT_생성.sql                                -- Agent 껍데기 + grant + SI 등록
--   5. 09_2_AGENT_버전업.sql                              -- 정본 yaml 로 스펙 발행 ★도구가 붙는 단계
--
--   ⚠ 4번만 하면 tool 이 없어 데이터 질문에 답하지 못한다. 5번까지가 1세트다.
--
--   ▶ 변경 시 — "무엇을 바꾸는가" 로 갈린다
--     · SV/데이터만 변경     → 05 통째 재실행 → 05 §8 스모크
--     · Agent 스펙 변경      → `cortex_project/agents/<AGENT>/agent_spec.yaml` 갱신 → **09_2**
--     · COMMENT·PROFILE 변경 → **09_1 [5]** (spec 이 아닌 DDL 속성이라 09_2 로는 안 바뀐다)
--     🔴 운영 중 Agent 에 09_1 [1] `CREATE OR REPLACE` 재실행 금지 — 버전 이력 초기화 +
--        USAGE grant·CoWork SI 등록 파괴. 스펙만 바꾸려면 반드시 09_2.
--
-- ============================================================================
-- ▶ 실측으로 확정한 규약 (2026-07-31 mq60369 · AGENT_ZZ_PROBE 검증 후 DROP)
-- ============================================================================
--   1) 스펙 파일명은 **`agent_spec.yaml`** 이다. 공식 문서(cortex-agents-versioning)의 GET 예시는
--      `agent.yaml` 로 적고 있으나 실제 버전 stage 를 LIST 하면 `agent_spec.yaml` 이며,
--      `agent.yaml` 로 두면 `No spec file present for the agent` 로 실패한다.
--   2) `ADD VERSION FROM` 의 인자는 **디렉터리**다(파일 경로가 아니다).
--   3) **live 가 있으면 거부**된다 — `There is already a live version. Please commit it first.`
--      → COMMIT 으로 live 를 소진한 뒤 ADD VERSION (09_2 [2] 멱등 블록).
--   4) `ADD VERSION FROM` 으로 만든 버전은 **자동 is_default=true**, 이전 버전은 보존.
--   5) `CREATE AGENT` 는 `FROM SPECIFICATION` 이 필수지만 `models: orchestration: auto` 최소
--      스펙만으로 생성된다 → 껍데기 생성 성립.
--   6) 성공 메시지 `Version nullsuccessfully created` 는 표시 버그다(버전은 정상 생성).
--   7) 워크스페이스에 새로 추가·수정한 파일은 `versions/live` 에 즉시 반영된다.
-- ============================================================================
