-- [1] 현재 Live(Draft) 버전이 있는 경우 확정 스냅샷으로 커밋하여 Live 상태 닫기
ALTER AGENT GN_DW.SERVING.AGENT_OVERALL COMMIT
  COMMENT = 'Final archive snapshot before migrating to AGENT_EXECUTIVE';

-- [2] 폐기/이관 상태임을 식별할 수 있도록 코멘트 변경
ALTER AGENT GN_DW.SERVING.AGENT_OVERALL SET
  COMMENT = 'DEPRECATED: Replaced by GN_DW.SERVING.AGENT_EXECUTIVE. Preserved for version history.';

-- [3] 운영 및 일반 역할의 호출/사용 권한 회수 (오호출 원천 차단)
SHOW GRANTS ON AGENT GN_DW.SERVING.AGENT_OVERALL;
REVOKE USAGE ON AGENT GN_DW.SERVING.AGENT_OVERALL FROM ROLE GN_DW_ANALYST;
REVOKE USAGE ON AGENT GN_DW.SERVING.AGENT_OVERALL FROM ROLE GN_DW_SERVICE;
REVOKE USAGE ON AGENT GN_DW.SERVING.AGENT_OVERALL FROM ROLE GN_DW_VIEWER;
-- (필요한 경우 모든 대상 역할에 대해 회수)

-- [4] 보존된 버전 이력 최종 확인
SHOW VERSIONS IN AGENT GN_DW.SERVING.AGENT_OVERALL;

-- 1. Snowflake Intelligence에서 기존 AGENT_OVERALL 제거
ALTER SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT
  DROP AGENT GN_DW.SERVING.AGENT_OVERALL;

-- 2. (확인용) 목록에서 제외되었는지 확인
SHOW AGENTS IN SNOWFLAKE INTELLIGENCE SNOWFLAKE_INTELLIGENCE_OBJECT_DEFAULT;