-- =============================================================================
-- 1. 권한 부여 (SECURITYADMIN 또는 GN_DW_ADMIN 역할로 실행)
-- =============================================================================
USE ROLE GN_DW_ADMIN;

-- (1) ML 스키마 내 모든 Stored Procedure 실행(USAGE) 권한 부여
GRANT USAGE ON ALL PROCEDURES IN SCHEMA GN_DW.ML TO ROLE GN_DW_LOADER;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GN_DW.ML TO ROLE GN_DW_LOADER;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_LOADER;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_LOADER;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;

-- (2) ML 스키마 내 머신러닝 모델/인스턴스 생성 권한 부여
GRANT CREATE MODEL ON SCHEMA GN_DW.ML TO ROLE GN_DW_LOADER;
GRANT CREATE SNOWFLAKE.ML.CLASSIFICATION ON SCHEMA GN_DW.ML TO ROLE GN_DW_LOADER;
GRANT CREATE SNOWFLAKE.ML.FORECAST ON SCHEMA GN_DW.ML TO ROLE GN_DW_LOADER;
GRANT CREATE SNOWFLAKE.ML.ANOMALY_DETECTION ON SCHEMA GN_DW.ML TO ROLE GN_DW_LOADER;

-- (3) 웨어하우스 권한: USAGE + MODIFY/OPERATE (프로시저 내부의 ALTER WAREHOUSE 문 실행용)
GRANT USAGE, OPERATE, MODIFY ON WAREHOUSE GN_DW_ML_WH TO ROLE GN_DW_LOADER;
GRANT USAGE ON WAREHOUSE GN_DW_ETL_WH TO ROLE GN_DW_LOADER;


-- =============================================================================
-- 2. 월마감 및 ML 파이프라인 재실행 (GN_DW_LOADER 역할로 실행)
-- =============================================================================
USE ROLE GN_DW_LOADER;
USE WAREHOUSE GN_DW_ETL_WH;

-- 2026년 9월 기준월(202609) 월마감 및 머신러닝 프로시저 재실행
CALL GN_DW.BRONZE_CRM.SP_EXEC_MONTH_END('202609');


-- =============================================================================
-- 3. 실행 결과 및 로그 확인
-- =============================================================================
SELECT 
    PROC_NAME,
    STDR_MT,
    START_TIME,
    END_TIME,
    DURATION_SEC,
    STATUS,
    ERROR_MSG
FROM GN_DW.ML.ML_PROCEDURE_LOG
WHERE START_TIME >= DATEADD('HOUR', -1, CURRENT_TIMESTAMP())
ORDER BY START_TIME DESC;
