-- GN_DW 운영 스크립트: 크레딧 확인, 권한 부여, 서비스 계정 생성
-- Co-authored with CoCo
-- 잔여 크레딧 확인
SELECT * 
FROM SNOWFLAKE.ORGANIZATION_USAGE.REMAINING_BALANCE_DAILY 
ORDER BY DATE DESC 
LIMIT 5;

-- GN_DW 운영 쿼리 및 GN_DW_LOADER 롤 권한 부여
-- 롤 권한 확인
SHOW GRANTS TO ROLE GN_DW_LOADER;


-- ============================================================
-- GN_DW_LOADER 롤: BRONZE_*(CRM, GA4, AGENCY, ERP) 적재 권한 부여
-- ============================================================
USE ROLE SECURITYADMIN;

-- 1) 데이터베이스 접근
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_LOADER;

-- 2) 스키마 접근 + 테이블/스테이지 생성 권한
GRANT USAGE ON SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_BIGQUERY TO ROLE GN_DW_LOADER;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;
GRANT CREATE TABLE ON SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT CREATE TABLE ON SCHEMA GN_DW.BRONZE_BIGQUERY TO ROLE GN_DW_LOADER;
GRANT CREATE TABLE ON SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
GRANT CREATE TABLE ON SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;
GRANT CREATE STAGE ON SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT CREATE STAGE ON SCHEMA GN_DW.BRONZE_BIGQUERY TO ROLE GN_DW_LOADER;
GRANT CREATE STAGE ON SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
GRANT CREATE STAGE ON SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;

-- 3) 기존 스테이지에 READ/WRITE 권한
GRANT READ, WRITE ON ALL STAGES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT READ, WRITE ON ALL STAGES IN SCHEMA GN_DW.BRONZE_BIGQUERY TO ROLE GN_DW_LOADER;
GRANT READ, WRITE ON ALL STAGES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
GRANT READ, WRITE ON ALL STAGES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;

-- 4) 향후 생성되는 스테이지에도 READ/WRITE 자동 부여
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA GN_DW.BRONZE_BIGQUERY TO ROLE GN_DW_LOADER;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
GRANT READ, WRITE ON FUTURE STAGES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;

-- 5) 기존 테이블에 INSERT, DELETE, SELECT 권한
GRANT INSERT, DELETE, SELECT ON ALL TABLES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT INSERT, DELETE, SELECT ON ALL TABLES IN SCHEMA GN_DW.BRONZE_BIGQUERY TO ROLE GN_DW_LOADER;
GRANT INSERT, DELETE, SELECT ON ALL TABLES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
GRANT INSERT, DELETE, SELECT ON ALL TABLES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;

-- 6) 향후 생성되는 테이블에도 자동으로 INSERT 부여
GRANT INSERT, DELETE, SELECT ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT INSERT, DELETE, SELECT ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_BIGQUERY TO ROLE GN_DW_LOADER;
GRANT INSERT, DELETE, SELECT ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
GRANT INSERT, DELETE, SELECT ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;

-- 7) 기존 프로시저 실행 권한
GRANT USAGE ON ALL PROCEDURES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA GN_DW.BRONZE_BIGQUERY TO ROLE GN_DW_LOADER;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;

-- 8) 향후 생성되는 프로시저에도 자동으로 실행 권한 부여
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GN_DW.BRONZE_BIGQUERY TO ROLE GN_DW_LOADER;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;

-- 9) 기존 파일 포맷 사용 권한
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA GN_DW.BRONZE_BIGQUERY TO ROLE GN_DW_LOADER;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;

-- 10) 향후 생성되는 파일 포맷에도 자동으로 사용 권한 부여
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA GN_DW.BRONZE_BIGQUERY TO ROLE GN_DW_LOADER;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;

-- ============================================================
-- RPA_ETL 서비스 계정 생성 (RSA 키 페어 인증 전용)
-- ============================================================
CREATE USER IF NOT EXISTS RPA_ETL
    TYPE = SERVICE
    RSA_PUBLIC_KEY = '<여기에_RSA_공개키_붙여넣기>'
    DEFAULT_ROLE = 'GN_DW_LOADER'
    DEFAULT_WAREHOUSE = 'GN_DW_ETL_WH'
    DEFAULT_NAMESPACE = 'GN_DW.BRONZE_ERP'
    COMMENT = '데이터 적재 담당 (ERP 외부팀)';

GRANT ROLE GN_DW_LOADER TO USER RPA_ETL;


-- SHARE WORKSPACE에 DBT용 롤의 접근 권한 주기
USE ROLE ACCOUNTADMIN;
GRANT READ, WRITE ON WORKSPACE "GNI_SHARE" TO ROLE GN_DW_ENGINEER;