USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS SANDBOX;
CREATE SCHEMA IF NOT EXISTS SANDBOX.TOOLS;

CREATE OR REPLACE STAGE SANDBOX.TOOLS.my_import_stage;

COPY FILES INTO 'snow://workspace/USER$.PUBLIC.DEFAULT$/versions/live'
FROM @SANDBOX.TOOLS.my_import_stage;