-- [5-5-B] GOLD 획득 캠페인명 vs 현재 캠페인 마스터명 일치 여부 대조
SELECT
    COUNT(*) AS "대조_행수",
    COUNT(CASE WHEN a.ACQ_CAMPAIGN_NAME <> c.CAMPAIGN_NAME
               THEN 1 END) AS "불일치_행수",
    COUNT(DISTINCT CASE WHEN a.ACQ_CAMPAIGN_NAME <> c.CAMPAIGN_NAME
                        THEN a.ACQ_CAMPAIGN_SK END) AS "불일치_캠페인수",
    COUNT(CASE WHEN a.ACQ_CAMPAIGN_NAME IS NULL THEN 1 END) AS "동결명_NULL_행수"
FROM GN_DW.GOLD.DIM_MEMBER_ACQUISITION a
JOIN GN_DW.GOLD.DIM_CAMPAIGN c
  ON c.CAMPAIGN_SK = a.ACQ_CAMPAIGN_SK;