CREATE DATABASE IF NOT EXISTS GN_DW;
CREATE SCHEMA   IF NOT EXISTS GN_DW.BRONZE_CRM;
CREATE SCHEMA   IF NOT EXISTS GN_DW.BRONZE_AGENCY;
CREATE SCHEMA   IF NOT EXISTS GN_DW.BRONZE_ERP;
CREATE SCHEMA   IF NOT EXISTS GN_DW.BRONZE_GA4;