CREATE DATABASE IF NOT EXISTS sandbox;
CREATE SCHEMA   IF NOT EXISTS sandbox.tools;
USE SCHEMA sandbox.tools;

-- 언로드 때와 동일한 CSV 규칙으로 적재 포맷 구성
CREATE OR REPLACE FILE FORMAT ff_csv_gzip
  TYPE = CSV
  COMPRESSION = GZIP
  FIELD_DELIMITER = ','
  RECORD_DELIMITER = '\n'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('\\N')
  EMPTY_FIELD_AS_NULL = FALSE
  SKIP_HEADER = 1              -- 언로드 시 HEADER=TRUE 였으므로 헤더 1줄 스킵
  TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS.FF9 TZH:TZM'
  DATE_FORMAT = 'YYYY-MM-DD'
  ESCAPE_UNENCLOSED_FIELD = NONE;

CREATE STAGE IF NOT EXISTS mig_load_stage FILE_FORMAT = ff_csv_gzip;

SELECT * FROM GN_DW.SILVER.CRM_MEMBER LIMIT 100;
SELECT * FROM GN_DW.GOLD.FACT_MEMBER_EVENT LIMIT 100;

