-- GN_DW SILVER CRM 정제 적재 쿼리 (STEP 3 INSERT OVERWRITE + 발송 PK ALTER). 테이블 정의 DDL 은 08_SILVER_테이블DDL_20260714.sql 참조.
-- Co-authored with CoCo
/*
================================================================================
  GN_DW.SILVER — CRM 21테이블 BRONZE→SILVER 정제 적재 (INSERT OVERWRITE = 멱등)
  ★ 구 silver_stepbystep_ddl.sql 분할본 — 2026-07-14. 08(구조 DDL) 실행 후 이 파일 실행.
  현재 상태 : CRM 21/21 전량 적재 완료 (Q5 발송키 이원화 · Q6 정기/일시 UNION 해소 포함).
  공통 규칙 : 코드 NULLIF(TRIM(x),'') 표준화 / DW_SOURCE_SYSTEM='CRM' /
              DW_LOAD_TS·DW_UPDATE_TS=CURRENT_TIMESTAMP() / 금액 원단위 보존.
  S-5 반영  : [G1] CRM_MEMBER_DEV·CRM_MEMBER_AMT_CHANGE 에 AREA_CD(CM018 라벨)·AGE 적재
              [G2] CRM_SEND_REQUEST SND 채널에 SEND_GBN_TOP/MID/BOT(+_NM) 적재(타 채널 NULL)
  선행 조건 : 08 로 21테이블 생성 완료. 하단 배치 4 상단 ALTER 로 발송 2테이블 복합 PK 전환.
================================================================================
*/
-- ── STEP 3 배치 1 — 마스터/차원 (검증: 행수 = BRONZE 일치) ──────────────────
-- CRM_CODE ← TC_CMMN_DTL_CD (5,834)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_CODE
(CD_ID, DTL_CD_ID, DTL_CD_NM, UPPER_CD_ID, SORT_ORDR, USE_YN,
 DW_SOURCE_SYSTEM, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT
  NULLIF(TRIM(CD_ID),''), NULLIF(TRIM(DTL_CD_ID),''), NULLIF(TRIM(DTL_CD_NM),''),
  NULLIF(TRIM(UPPER_CD_ID),''), SORT_ORDR, NULLIF(TRIM(USE_YN),''),
  'CRM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TC_CMMN_DTL_CD
WHERE CD_ID IS NOT NULL AND DTL_CD_ID IS NOT NULL;

-- CRM_ORG ← TM_CM_DEPT_INFO (1,314)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_ORG
(DEPT_ID, DEPT_NM, UPPER_DEPT_ID, ACMSLT_UPPER_DEPT_ID, ACMSLT_DEPT_YN,
 STATS_DEPT_LVL, USE_YN, SORT_ORDR, DW_SOURCE_SYSTEM, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT
  NULLIF(TRIM(DEPT_ID),''), NULLIF(TRIM(DEPT_NM),''), NULLIF(TRIM(UPPER_DEPT_ID),''),
  NULLIF(TRIM(ACMSLT_UPPER_DEPT_ID),''), NULLIF(TRIM(ACMSLT_DEPT_YN),''),
  STATS_DEPT_LVL, NULLIF(TRIM(USE_YN),''), SORT_ORDR,
  'CRM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_CM_DEPT_INFO
WHERE DEPT_ID IS NOT NULL;

-- CRM_SPONSORSHIP ← TM_CM_SPNSR_BSNS_INFO (50)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_SPONSORSHIP
(SPNSR_BSNS_ID, SPNSR_BSNS_NM, SPNSR_BSNS_ABRV_CD, SPNSR_DIV_CD, DNTN_TY_CD, CPR_DIV_CD,
 DW_SOURCE_SYSTEM, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT
  NULLIF(TRIM(SPNSR_BSNS_ID),''), NULLIF(TRIM(SPNSR_BSNS_NM),''), NULLIF(TRIM(SPNSR_BSNS_ABRV_CD),''),
  NULLIF(TRIM(SPNSR_DIV_CD),''), NULLIF(TRIM(DNTN_TY_CD),''), NULLIF(TRIM(CPR_DIV_CD),''),
  'CRM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_CM_SPNSR_BSNS_INFO
WHERE SPNSR_BSNS_ID IS NOT NULL;

-- CRM_DEV_TARGET ← TM_CM_MBER_DVLP_GOAL (25,344)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_DEV_TARGET
(STDYY, STDR_MT, MBER_DVLP_DIV_CD, DEPT_ID, GOAL_CNT,
 DW_SOURCE_SYSTEM, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT
  NULLIF(TRIM(STDYY),''), NULLIF(TRIM(STDR_MT),''), NULLIF(TRIM(MBER_DVLP_DIV_CD),''),
  NULLIF(TRIM(DEPT_ID),''), GOAL_CNT,
  'CRM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_CM_MBER_DVLP_GOAL
WHERE STDYY IS NOT NULL AND STDR_MT IS NOT NULL AND MBER_DVLP_DIV_CD IS NOT NULL AND DEPT_ID IS NOT NULL;

-- CRM_CAMPAIGN ← TM_CM_CMPGN_MNG + 브랜드/마케팅캠페인 LEFT JOIN (36,143)
--   Q16: MKTG_CMPGN_NM(NUMBER) ↔ MK_CMPGN_CD(TEXT) 조인키 불일치 → TO_VARCHAR 캐스팅 조인
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_CAMPAIGN
(CMPGN_CD, CMPGN_NM, UPPER_CMPGN_CD, UPPER_CMPGN_YN, BRND_ID, BRND_NM,
 PR_MTH_CD, SPNSR_BSNS_ID, CMPGN_CTGR_CD, CMPGN_TYPE1_BSN, CMPGN_TYPE2_BSN,
 MKTG_CMPGN_NM, MK_CMPGN_NM, CMPGN_STRT_DE,
 DW_SOURCE_SYSTEM, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT
  NULLIF(TRIM(c.CMPGN_CD),''), NULLIF(TRIM(c.CMPGN_NM),''), NULLIF(TRIM(c.UPPER_CMPGN_CD),''),
  NULLIF(TRIM(c.UPPER_CMPGN_YN),''), NULLIF(TRIM(c.BRND_ID),''), NULLIF(TRIM(b.BRND_NM),''),
  NULLIF(TRIM(c.PR_MTH_CD),''), NULLIF(TRIM(c.SPNSR_BSNS_ID),''),
  c.CMPGN_CTGR_CD, c.CMPGN_TYPE1_BSN, c.CMPGN_TYPE2_BSN,
  c.MKTG_CMPGN_NM, NULLIF(TRIM(m.MK_CMPGN_NM),''), NULLIF(TRIM(c.CMPGN_STRT_DE),''),
  'CRM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_CM_CMPGN_MNG c
LEFT JOIN GN_DW.BRONZE_CRM.TM_CM_BRND_MNG b ON c.BRND_ID = b.BRND_ID
LEFT JOIN GN_DW.BRONZE_CRM.TM_CM_MKTNG_CMPGN_MNG m ON TO_VARCHAR(c.MKTG_CMPGN_NM) = m.MK_CMPGN_CD
WHERE c.CMPGN_CD IS NOT NULL;

-- ── STEP 3 배치 2 — 회원 사건/약정/결연 (검증: 행수 = BRONZE 일치) ───────────
-- CRM_MEMBER_DEV ← TM_MM_FDRM_MBER_DVLP_AMT (3,594,843)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_MEMBER_DEV
(SPNSR_NO, SPNSR_BSNS_NO, OCCRRNC_DE, SER_NO, MBER_NO, SPNSR_BSNS_ID, SPNSR_AMT,
 DVLP_DIV_CD, ACT_DEPT_CD, ACMSLT_DEPT_CD, CMPGN_CD, SETLE_CD, AREA_CD, AREA_NM, AGE,
 DW_SOURCE_SYSTEM, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT
  NULLIF(TRIM(s.SPNSR_NO),''), s.SPNSR_BSNS_NO, NULLIF(TRIM(s.OCCRRNC_DE),''), s.SER_NO,
  NULLIF(TRIM(s.MBER_NO),''), NULLIF(TRIM(s.SPNSR_BSNS_ID),''), s.SPNSR_AMT,
  NULLIF(TRIM(s.DVLP_DIV_CD),''), NULLIF(TRIM(s.ACT_DEPT_CD),''), NULLIF(TRIM(s.ACMSLT_DEPT_CD),''),
  NULLIF(TRIM(s.CMPGN_CD),''), NULLIF(TRIM(s.SETLE_CD),''),
  NULLIF(TRIM(s.AREA_CD),''), a.DTL_CD_NM, s.AGE,
  'CRM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_DVLP_AMT s
LEFT JOIN GN_DW.SILVER.CRM_CODE a ON a.CD_ID='CM018' AND a.DTL_CD_ID=NULLIF(TRIM(s.AREA_CD),'')
WHERE s.SPNSR_NO IS NOT NULL AND s.SPNSR_BSNS_NO IS NOT NULL AND s.OCCRRNC_DE IS NOT NULL AND s.SER_NO IS NOT NULL;

-- CRM_MEMBER_AMT_CHANGE ← TM_MM_FDRM_MBER_IRSD (324,947)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_MEMBER_AMT_CHANGE
(OCCRRNC_DE, SER_NO, MBER_NO, SPNSR_AMT, RDCAMT_YN, ACMSLT_DEPT_CD, CMPGN_CD, AREA_CD, AREA_NM, AGE,
 DW_SOURCE_SYSTEM, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT
  NULLIF(TRIM(s.OCCRRNC_DE),''), s.SER_NO, NULLIF(TRIM(s.MBER_NO),''), s.SPNSR_AMT,
  NULLIF(TRIM(s.RDCAMT_YN),''), NULLIF(TRIM(s.ACMSLT_DEPT_CD),''), NULLIF(TRIM(s.CMPGN_CD),''),
  NULLIF(TRIM(s.AREA_CD),''), a.DTL_CD_NM, s.AGE,
  'CRM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_IRSD s
LEFT JOIN GN_DW.SILVER.CRM_CODE a ON a.CD_ID='CM018' AND a.DTL_CD_ID=NULLIF(TRIM(s.AREA_CD),'')
WHERE s.OCCRRNC_DE IS NOT NULL AND s.SER_NO IS NOT NULL;

-- CRM_MEMBER_DISCONTINUE ← TM_MM_FDRM_MBER_SPNSR_DSCNTC + MM005 라벨 (1,038,262)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_MEMBER_DISCONTINUE
(MBER_NO, SPNSR_DSCNTC_DE, SER_NO, DSCNTC_RSN_CD, DSCNTC_RSN_NM, DSCNTC_PATH, REGIST_DEPT_CD,
 DW_SOURCE_SYSTEM, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT
  NULLIF(TRIM(s.MBER_NO),''), NULLIF(TRIM(s.SPNSR_DSCNTC_DE),''), s.SER_NO,
  NULLIF(TRIM(s.DSCNTC_RSN_CD),''), cd.DTL_CD_NM, NULLIF(TRIM(s.DSCNTC_PATH),''),
  NULLIF(TRIM(s.REGIST_DEPT_CD),''),
  'CRM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_SPNSR_DSCNTC s
LEFT JOIN GN_DW.SILVER.CRM_CODE cd ON cd.CD_ID='MM005' AND cd.DTL_CD_ID = NULLIF(TRIM(s.DSCNTC_RSN_CD),'')
WHERE s.MBER_NO IS NOT NULL AND s.SPNSR_DSCNTC_DE IS NOT NULL AND s.SER_NO IS NOT NULL;

-- CRM_MEMBER_RESPONSOR ← TM_MM_FDRM_MBER_RE_SPNSR (115,254)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_MEMBER_RESPONSOR
(MBER_NO, SER_NO, RE_SPNSR_DE, REGIST_DEPT_CD,
 DW_SOURCE_SYSTEM, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT
  NULLIF(TRIM(MBER_NO),''), SER_NO, NULLIF(TRIM(RE_SPNSR_DE),''), NULLIF(TRIM(REGIST_DEPT_CD),''),
  'CRM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_RE_SPNSR
WHERE MBER_NO IS NOT NULL AND SER_NO IS NOT NULL AND RE_SPNSR_DE IS NOT NULL;

-- CRM_MEMBER_SPONSOR_BIZ ← TM_MM_FDRM_MBER_SPNSR_BSNS (2,170,572; PK dedup QUALIFY)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_MEMBER_SPONSOR_BIZ
(SPNSR_NO, SPNSR_BSNS_NO, SPNSR_BSNS_ID, SPNSR_AMT, SPNSR_DSCNTC_YN, SPNSR_DSCNTC_DE, SPNSR_DSCNTC_RSN_CD,
 DW_SOURCE_SYSTEM, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT
  NULLIF(TRIM(SPNSR_NO),''), SPNSR_BSNS_NO, NULLIF(TRIM(SPNSR_BSNS_ID),''), SPNSR_AMT,
  NULLIF(TRIM(SPNSR_DSCNTC_YN),''), NULLIF(TRIM(SPNSR_DSCNTC_DE),''), NULLIF(TRIM(SPNSR_DSCNTC_RSN_CD),''),
  'CRM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_SPNSR_BSNS
WHERE SPNSR_NO IS NOT NULL AND SPNSR_BSNS_NO IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY SPNSR_NO, SPNSR_BSNS_NO ORDER BY SPNSR_DSCNTC_DE DESC NULLS LAST) = 1;

-- CRM_SPONSOR_RELATION ← TM_RM_RELATNSP_MSTR_INFO + Q15 NO→ID 크로스워크 (862,610)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_SPONSOR_RELATION
(RELATNSP_KEY, SPNSR_NO, SPNSR_BSNS_NO, SPNSR_BSNS_ID, CHILD_CD, MBER_NO,
 RELATNSP_STRT_DE, RELATNSP_DSCNTC_DE, RELATNSP_DSCNTC_YN,
 DW_SOURCE_SYSTEM, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT
  r.RELATNSP_KEY, NULLIF(TRIM(r.SPNSR_NO),''), r.SPNSR_BSNS_NO, biz.SPNSR_BSNS_ID, r.CHILD_CD,
  NULLIF(TRIM(r.MBER_NO),''), r.RELATNSP_STRT_DE, r.RELATNSP_DSCNTC_DE, NULLIF(TRIM(r.RELATNSP_DSCNTC_YN),''),
  'CRM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_RM_RELATNSP_MSTR_INFO r
LEFT JOIN GN_DW.SILVER.CRM_MEMBER_SPONSOR_BIZ biz
  ON biz.SPNSR_NO = NULLIF(TRIM(r.SPNSR_NO),'') AND biz.SPNSR_BSNS_NO = r.SPNSR_BSNS_NO
WHERE r.RELATNSP_KEY IS NOT NULL;

-- ── STEP 3 배치 3 — 결제/행사/결연활동/상태이력 ────────────────────────────
-- CRM_PAYMENT_METHOD ← TM_PM_SETLE_INFO 현재상태 (SETLE_KEY dedup, 2,545,696)
--   SETLE_NM 라벨: PM040 조인(1=자동이체·2=신용카드·…·13=가상계좌즉시) — 코드그룹 확정(2026-07-14)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_PAYMENT_METHOD
(SETLE_KEY, MBER_NO, SETLE_CD, SETLE_NM, CARD_DIV_CD, FNLT_CD, WTDRW_STRT_DE, SETLE_STAT_CD,
 DW_SOURCE_SYSTEM, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT
  s.SETLE_KEY, NULLIF(TRIM(s.MBER_NO),''), NULLIF(TRIM(s.SETLE_CD),''), pm.DTL_CD_NM,
  NULLIF(TRIM(s.CARD_DIV_CD),''), NULLIF(TRIM(s.FNLT_CD),''), s.WTDRW_STRT_DE, NULLIF(TRIM(s.SETLE_STAT_CD),''),
  'CRM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_PM_SETLE_INFO s
LEFT JOIN GN_DW.SILVER.CRM_CODE pm ON pm.CD_ID='PM040' AND pm.DTL_CD_ID = NULLIF(TRIM(s.SETLE_CD),'')
WHERE s.SETLE_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY s.SETLE_KEY ORDER BY s.WTDRW_STRT_DE DESC NULLS LAST)=1;

-- CRM_EVENT ← TM_MS_EVENT ∪ TM_MS_CRMN (3,786)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_EVENT
(EVENT_KEY, EVENT_SOURCE, EVENT_DIV_CD, EVENT_NM, STRT_DE, END_DE, RCRIT_PSNNL_CO, BRNCH_DEPT_ID,
 DW_SOURCE_SYSTEM, DW_SOURCE_TABLE, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT 'EVENT_'||EVENT_CD, 'EVENT', NULLIF(TRIM(EVENT_DIV_CD),''), NULLIF(TRIM(EVENT_NM),''),
  NULLIF(TRIM(STRT_DATE),''), NULLIF(TRIM(END_DATE),''), NULL, NULL,
  'CRM','BRONZE_CRM.TM_MS_EVENT', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_MS_EVENT WHERE EVENT_CD IS NOT NULL
UNION ALL
SELECT 'CRMN_'||CRMN_CD, 'CRMN', NULLIF(TRIM(CRMN_DIV_CD),''), NULLIF(TRIM(CRMN_TIT),''),
  NULLIF(TRIM(CRMN_STRT_DE),''), NULLIF(TRIM(CRMN_END_DE),''), RCRIT_PSNNL_CO, NULLIF(TRIM(BRNCH_DEPT_ID),''),
  'CRM','BRONZE_CRM.TM_MS_CRMN', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_MS_CRMN WHERE CRMN_CD IS NOT NULL;

-- CRM_EVENT_PARTICIPATION ← TD_MS_EVENT_PRTCPNT_DTL ∪ TD_MS_CRMN_PRTCPNT (1,134,126; PK dedup)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_EVENT_PARTICIPATION
(EVENT_KEY, MBER_NO, PARTCPT_SEQ, PARTCPT_STAT_CD, PARTCPT_CHNNL_CD, PARTCPT_PATH_CD, PRZWIN_CD, RCPMNY_AMT, PARTCPT_DT,
 DW_SOURCE_SYSTEM, DW_SOURCE_TABLE, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT 'EVENT_'||EVENT_CD, NULLIF(TRIM(MBER_NO),''), PARTCPT_SEQ, NULLIF(TRIM(PARTCPT_STAT_CD),''),
  NULLIF(TRIM(PARTCPT_CHNNL_CD),''), NULLIF(TRIM(PARTCPT_PATH_CD),''), PRZWIN_CD, NULL, PARTCPT_DT,
  'CRM','BRONZE_CRM.TD_MS_EVENT_PRTCPNT_DTL', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TD_MS_EVENT_PRTCPNT_DTL WHERE MBER_NO IS NOT NULL AND PARTCPT_SEQ IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY EVENT_CD, MBER_NO, PARTCPT_SEQ ORDER BY PARTCPT_DT DESC NULLS LAST)=1
UNION ALL
SELECT 'CRMN_'||CRMN_CD, NULLIF(TRIM(MBER_NO),''), PRTCPNT_KEY, NULLIF(TRIM(PARTCPT_STAT_CD),''),
  NULL, NULLIF(TRIM(RQST_PATH_CD),''), NULL, RCPMNY_AMT, TRY_TO_TIMESTAMP(PARTCPT_DATE),
  'CRM','BRONZE_CRM.TD_MS_CRMN_PRTCPNT', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TD_MS_CRMN_PRTCPNT WHERE MBER_NO IS NOT NULL AND PRTCPNT_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY CRMN_CD, MBER_NO, PRTCPNT_KEY ORDER BY TRY_TO_TIMESTAMP(PARTCPT_DATE) DESC NULLS LAST)=1;

-- CRM_RELATION_ACTIVITY ← 서신 ∪ 선물금 (EHGT 제외, 388,153; PK dedup)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_RELATION_ACTIVITY
(ACTIVITY_KEY, ACTIVITY_TYPE, RELATNSP_KEY, MNG_NO, GFTMNEY, LETTER_DIV_CD, RCEPT_DE, SNDNG_DE,
 DW_SOURCE_SYSTEM, DW_SOURCE_TABLE, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT 'LETTER_'||RELATNSP_KEY||'_'||COALESCE(NULLIF(TRIM(MNG_NO),''),''), '서신', RELATNSP_KEY, NULLIF(TRIM(MNG_NO),''),
  NULL, LETTER_DIV_CD, RCEPT_DE, SNDNG_DE,
  'CRM','BRONZE_CRM.TM_RM_RELATNSP_LETTER_INFO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_RM_RELATNSP_LETTER_INFO WHERE RELATNSP_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY RELATNSP_KEY, MNG_NO ORDER BY RCEPT_DE DESC NULLS LAST)=1
UNION ALL
SELECT 'GFT_'||RELATNSP_KEY||'_'||COALESCE(NULLIF(TRIM(MNG_NO),''),''), '선물금', RELATNSP_KEY, NULLIF(TRIM(MNG_NO),''),
  GFTMNEY, NULL, NULL, SNDNG_DE,
  'CRM','BRONZE_CRM.TM_RM_RELATNSP_GFTMNEY_INFO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_RM_RELATNSP_GFTMNEY_INFO WHERE RELATNSP_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY RELATNSP_KEY, MNG_NO ORDER BY SNDNG_DE DESC NULLS LAST)=1;

-- CRM_MEMBER_STATUS_HIST ← TH_MM_FDRM_MBER_STNG_DTLS (SCD2, MM010 라벨, 7,501,761)
--   EFFECTIVE_FROM=FRST_REGIST_DT / EFFECTIVE_TO=LEAD(다음 상태전이) / IS_CURRENT=마지막 행
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_MEMBER_STATUS_HIST
(MBER_NO, SER_NO, BF_STAT_CD, BF_STAT_NM, CHN_STAT_CD, CHN_STAT_NM, EFFECTIVE_FROM, EFFECTIVE_TO, IS_CURRENT,
 DW_SOURCE_SYSTEM, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT
  s.MBER_NO, s.SER_NO, s.BF_STAT_CD, bf.DTL_CD_NM, s.CHN_STAT_CD, ch.DTL_CD_NM,
  s.FRST_REGIST_DT,
  LEAD(s.FRST_REGIST_DT) OVER (PARTITION BY s.MBER_NO ORDER BY s.SER_NO),
  (LEAD(s.FRST_REGIST_DT) OVER (PARTITION BY s.MBER_NO ORDER BY s.SER_NO) IS NULL),
  'CRM', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM (SELECT NULLIF(TRIM(MBER_NO),'') MBER_NO, SER_NO,
             NULLIF(TRIM(BF_STAT_CD),'') BF_STAT_CD, NULLIF(TRIM(CHN_STAT_CD),'') CHN_STAT_CD, FRST_REGIST_DT
      FROM GN_DW.BRONZE_CRM.TH_MM_FDRM_MBER_STNG_DTLS
      WHERE MBER_NO IS NOT NULL AND SER_NO IS NOT NULL) s
LEFT JOIN GN_DW.SILVER.CRM_CODE bf ON bf.CD_ID='MM010' AND bf.DTL_CD_ID=s.BF_STAT_CD
LEFT JOIN GN_DW.SILVER.CRM_CODE ch ON ch.CD_ID='MM010' AND ch.DTL_CD_ID=s.CHN_STAT_CD;

-- CRM_PAYMENT_BILLING ← TM_PM_MBRFEE_ACMSLT(회비) ∪ TM_PM_DNTN_DTLS(기부금) (47,521,872)
--   Q14: MBRFEE_KEY/DNTN_KEY = PK → PAY_KEY 접두 통합키. 청구=행 기준, 납입=PAY_AMT 보존.
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_PAYMENT_BILLING
(PAY_KEY, PAYMENT_TYPE, MBER_NO, SPNSR_BSNS_ID, RELATNSP_KEY, MBRFEE_MT, MBRFEE_SQNC,
 RQEST_AMT, RQEST_DE, PAY_AMT, PAY_DE, PAY_STAT_CD, SETLE_CD, GFT_DIV_CD,
 DW_SOURCE_SYSTEM, DW_SOURCE_TABLE, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT
  'MBRFEE_'||MBRFEE_KEY, '회비', NULLIF(TRIM(MBER_NO),''), NULLIF(TRIM(SPNSR_BSNS_ID),''), RELATNSP_KEY,
  NULLIF(TRIM(MBRFEE_MT),''), MBRFEE_SQNC, RQEST_AMT, RQEST_DE, PAY_AMT, PAY_DE,
  NULLIF(TRIM(PAY_STAT_CD),''), NULLIF(TRIM(SETLE_CD),''), NULLIF(TRIM(GFT_DIV_CD),''),
  'CRM','BRONZE_CRM.TM_PM_MBRFEE_ACMSLT', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_PM_MBRFEE_ACMSLT WHERE MBRFEE_KEY IS NOT NULL
UNION ALL
SELECT
  'DNTN_'||DNTN_KEY, '기부금', NULLIF(TRIM(ONCE_MBER_NO),''), NULLIF(TRIM(SPNSR_BSNS_ID),''), NULL,
  NULL, NULL, NULL, NULL, PAY_AMT, PAY_DE,
  NULLIF(TRIM(PAY_STAT_CD),''), NULLIF(TRIM(SETLE_CD),''), NULL,
  'CRM','BRONZE_CRM.TM_PM_DNTN_DTLS', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_PM_DNTN_DTLS WHERE DNTN_KEY IS NOT NULL;

-- ============================================================================
-- STEP 3 배치 4 — Q5/Q6 해소 후 적재 (2026-07-14, 정의서 업데이트 + 실측 프로파일링 근거)
--
--   Q6 [CRM_MEMBER] 실측 규칙:
--     · MEMBER_DK=VARCHAR(10), 정기(숫자)∪일시(비숫자) 번호충돌 0 → 접두 불요·UNION ALL
--     · SEX(코드그룹 CM013, 2026-07-14 확정): 1=국내남·2=국내여·3=외국인남·4=외국인여·5=외국인기타·6=단체·7=기업·8=기타
--       → 표준화 '1','3'→'M' · '2','4'→'F' · '5'~'8'→'U'(비개인·외국기타) · 공백/NULL→NULL
--     · MBER_DIV_NM: MM018 라벨(1=개인·2=기업·3=단체) 조인 채움
--     · 수신동의(EMAIL/PSTMTR) 정규화: 정기=콤마셋 → 공백제거·분리·DISTINCT·오름차순·재결합
--       (ARRAY_SORT/DISTINCT/REMOVE) ; 일시=Y/N 그대로 통과
--   Q5 [CRM_SEND_*] 실측 결론:
--     · SND_*(비즈뿌리오): SND_REQ_MST(SEQ_NO PK) → SND_MEMBER_LIST(REQ_SEQ_NO FK, orphan 0)
--     · TM_MS_*/TD_MS_*(레거시): EMAIL·MSG_AT·PSTMTR, 각 SNDNG_KEY
--     · 키 도메인 완전 분리(SEQ_NO∩SNDNG_KEY=0, 채널간=0) → SEND_CHANNEL을 PK에 포함(채널 안전)
--     · TM_MS_PSTMTR_SNDNG.SNDNG_STDR_DE·SND_REQ_MST.SEND_DATE = 실측 DATE형 → ::TIMESTAMP_NTZ
-- ============================================================================

-- Q5 채널 안전 PK 보정 (RESULT는 이미 (SNDNG_KEY,SEND_CHANNEL))
ALTER TABLE GN_DW.SILVER.CRM_SEND_REQUEST ALTER COLUMN SEND_CHANNEL SET NOT NULL;
ALTER TABLE GN_DW.SILVER.CRM_SEND_REQUEST DROP PRIMARY KEY;
ALTER TABLE GN_DW.SILVER.CRM_SEND_REQUEST ADD PRIMARY KEY (SNDNG_KEY, SEND_CHANNEL);
ALTER TABLE GN_DW.SILVER.CRM_SEND_MEMBER ALTER COLUMN SEND_CHANNEL SET NOT NULL;
ALTER TABLE GN_DW.SILVER.CRM_SEND_MEMBER DROP PRIMARY KEY;
ALTER TABLE GN_DW.SILVER.CRM_SEND_MEMBER ADD PRIMARY KEY (SNDNG_KEY, SNDNG_DTL_KEY, SEND_CHANNEL);

-- CRM_MEMBER ← TM_MM_FDRM_MBER_INFO(정기) ∪ TM_MM_ONCE_MBER_INFO(일시) (1,763,065)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_MEMBER
(MEMBER_DK, MEMBER_TYPE, MBER_DIV_CD, MBER_DIV_NM, CPR_DIV_CD, SEX, MBER_STAT_CD, MBER_STAT_NM,
 CMPGN_CD, ACT_DEPT_CD, REGIST_DEPT_CD, JOIN_PATH_CD, HMPG_ID, ENTRPS_NM, EMAIL_RECPTN, PSTMTR_RECPTN, JOIN_DT,
 DW_SOURCE_SYSTEM, DW_SOURCE_TABLE, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT
  NULLIF(TRIM(f.MBER_NO),''), 'FDRM', NULLIF(TRIM(f.MBER_DIV_CD),''), md.DTL_CD_NM, NULLIF(TRIM(f.CPR_DIV_CD),''),
  CASE WHEN f.SEX IN ('1','3') THEN 'M' WHEN f.SEX IN ('2','4') THEN 'F' WHEN NULLIF(TRIM(f.SEX),'') IS NULL THEN NULL ELSE 'U' END,
  NULLIF(TRIM(f.MBER_STAT_CD),''), st.DTL_CD_NM,
  NULLIF(TRIM(f.CMPGN_CD),''), NULLIF(TRIM(f.ACT_DEPT_CD),''), NULLIF(TRIM(f.REGIST_DEPT_CD),''),
  NULLIF(TRIM(f.JOIN_PATH_CD),''), NULLIF(TRIM(f.HMPG_ID),''), NULL,
  CASE WHEN NULLIF(TRIM(f.EMAIL_RECPTN_CD),'') IS NULL THEN NULL
       ELSE ARRAY_TO_STRING(ARRAY_SORT(ARRAY_DISTINCT(ARRAY_REMOVE(SPLIT(REPLACE(TRIM(f.EMAIL_RECPTN_CD),' ',''),','),TO_VARIANT('')))),',') END,
  CASE WHEN NULLIF(TRIM(f.PSTMTR_RECPTN_CD),'') IS NULL THEN NULL
       ELSE ARRAY_TO_STRING(ARRAY_SORT(ARRAY_DISTINCT(ARRAY_REMOVE(SPLIT(REPLACE(TRIM(f.PSTMTR_RECPTN_CD),' ',''),','),TO_VARIANT('')))),',') END,
  f.FRST_REGIST_DT,
  'CRM','BRONZE_CRM.TM_MM_FDRM_MBER_INFO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_INFO f
LEFT JOIN GN_DW.SILVER.CRM_CODE st ON st.CD_ID='MM010' AND st.DTL_CD_ID = NULLIF(TRIM(f.MBER_STAT_CD),'')
LEFT JOIN GN_DW.SILVER.CRM_CODE md ON md.CD_ID='MM018' AND md.DTL_CD_ID = NULLIF(TRIM(f.MBER_DIV_CD),'')
WHERE f.MBER_NO IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY NULLIF(TRIM(f.MBER_NO),'') ORDER BY f.FRST_REGIST_DT DESC NULLS LAST)=1
UNION ALL
SELECT
  NULLIF(TRIM(o.ONCE_MBER_NO),''), 'ONCE', NULLIF(TRIM(o.MBER_DIV_CD),''), md.DTL_CD_NM, NULLIF(TRIM(o.CPR_DIV_CD),''),
  CASE WHEN o.SEX IN ('1','3') THEN 'M' WHEN o.SEX IN ('2','4') THEN 'F' WHEN NULLIF(TRIM(o.SEX),'') IS NULL THEN NULL ELSE 'U' END,
  NULL, NULL,
  NULL, NULL, NULLIF(TRIM(o.REGIST_DEPT_CD),''),
  NULL, NULLIF(TRIM(o.HMPG_ID),''), NULLIF(TRIM(o.ENTRPS_NM),''),
  NULLIF(TRIM(o.EMAIL_RECPTN_YN),''), NULLIF(TRIM(o.PSTMTR_RECPTN_YN),''),
  o.FRST_REGIST_DT,
  'CRM','BRONZE_CRM.TM_MM_ONCE_MBER_INFO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM GN_DW.BRONZE_CRM.TM_MM_ONCE_MBER_INFO o
LEFT JOIN GN_DW.SILVER.CRM_CODE md ON md.CD_ID='MM018' AND md.DTL_CD_ID = NULLIF(TRIM(o.MBER_DIV_CD),'')
WHERE o.ONCE_MBER_NO IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY NULLIF(TRIM(o.ONCE_MBER_NO),'') ORDER BY o.FRST_REGIST_DT DESC NULLS LAST)=1;

-- CRM_SEND_REQUEST ← EMAIL ∪ MSG_AT ∪ PSTMTR ∪ SND (요청 마스터, 1,614,397)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_SEND_REQUEST
(SNDNG_KEY, SEND_CHANNEL, SNDNG_TY_CD,
 SEND_GBN_TOP, SEND_GBN_TOP_NM, SEND_GBN_MID, SEND_GBN_MID_NM, SEND_GBN_BOT, SEND_GBN_BOT_NM,
 TIT, SNDNG_STDR_DE, REQ_SEQ_NO,
 DW_SOURCE_SYSTEM, DW_SOURCE_TABLE, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT SNDNG_KEY,'EMAIL',NULLIF(TRIM(SNDNG_TY_CD),''),
  NULL,NULL,NULL,NULL,NULL,NULL,
  NULLIF(TRIM(TIT),''),SNDNG_STDR_DE::TIMESTAMP_NTZ,NULL,
  'CRM','BRONZE_CRM.TM_MS_EMAIL_SNDNG',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM GN_DW.BRONZE_CRM.TM_MS_EMAIL_SNDNG WHERE SNDNG_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY SNDNG_KEY ORDER BY SNDNG_STDR_DE DESC NULLS LAST)=1
UNION ALL
SELECT SNDNG_KEY,'MSG_AT',NULLIF(TRIM(SNDNG_TY_CD),''),
  NULL,NULL,NULL,NULL,NULL,NULL,
  NULLIF(TRIM(TIT),''),SNDNG_STDR_DE::TIMESTAMP_NTZ,NULL,
  'CRM','BRONZE_CRM.TM_MS_MSG_AT_SNDNG',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM GN_DW.BRONZE_CRM.TM_MS_MSG_AT_SNDNG WHERE SNDNG_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY SNDNG_KEY ORDER BY SNDNG_STDR_DE DESC NULLS LAST)=1
UNION ALL
SELECT SNDNG_KEY,'PSTMTR',NULLIF(TRIM(SNDNG_TY_CD),''),
  NULL,NULL,NULL,NULL,NULL,NULL,
  NULL,SNDNG_STDR_DE::TIMESTAMP_NTZ,NULL,
  'CRM','BRONZE_CRM.TM_MS_PSTMTR_SNDNG',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM GN_DW.BRONZE_CRM.TM_MS_PSTMTR_SNDNG WHERE SNDNG_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY SNDNG_KEY ORDER BY SNDNG_STDR_DE DESC NULLS LAST)=1
UNION ALL
SELECT SEQ_NO,'SND',NULL,
  NULLIF(TRIM(SEND_GBN_TOP),''),NULLIF(TRIM(SEND_GBN_TOP_NM),''),
  NULLIF(TRIM(SEND_GBN_MID),''),NULLIF(TRIM(SEND_GBN_MID_NM),''),
  NULLIF(TRIM(SEND_GBN_BOT),''),NULLIF(TRIM(SEND_GBN_BOT_NM),''),
  NULLIF(TRIM(SEND_TITLE),''),SEND_DATE::TIMESTAMP_NTZ,SEQ_NO,
  'CRM','BRONZE_CRM.SND_REQ_MST',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM GN_DW.BRONZE_CRM.SND_REQ_MST WHERE SEQ_NO IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY SEQ_NO ORDER BY SEND_DATE DESC NULLS LAST)=1;

-- CRM_SEND_RESULT ← 채널별 LQY 집계 ∪ SND 요청집계 (SNDNG_KEY+채널 GROUP BY, 1,611,758)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_SEND_RESULT
(SNDNG_KEY, SEND_CHANNEL, SNDNG_CNT, SUCCES_CNT, FAILR_CNT, TOT_CLICK_CNT,
 DW_SOURCE_SYSTEM, DW_SOURCE_TABLE, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT SNDNG_KEY,'EMAIL',SUM(SNDNG_CNT),SUM(SUCCES_CNT),SUM(FAILR_CNT)::NUMBER(10,0),NULL,
  'CRM','BRONZE_CRM.TD_MS_EMAIL_LQY_SNDNG',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM GN_DW.BRONZE_CRM.TD_MS_EMAIL_LQY_SNDNG WHERE SNDNG_KEY IS NOT NULL GROUP BY SNDNG_KEY
UNION ALL
SELECT SNDNG_KEY,'MSG_AT',SUM(SNDNG_CNT),SUM(SUCCES_CNT),SUM(AT_FAILR_CNT),SUM(TRY_TO_NUMBER(TOT_CLICK_CNT_CTNT)),
  'CRM','BRONZE_CRM.TD_MS_MSG_AT_LQY_SNDNG',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM GN_DW.BRONZE_CRM.TD_MS_MSG_AT_LQY_SNDNG WHERE SNDNG_KEY IS NOT NULL GROUP BY SNDNG_KEY
UNION ALL
SELECT SNDNG_KEY,'PSTMTR',SUM(SNDNG_CNT),NULL,NULL,NULL,
  'CRM','BRONZE_CRM.TD_MS_PSTMTR_LQY_SNDNG',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM GN_DW.BRONZE_CRM.TD_MS_PSTMTR_LQY_SNDNG WHERE SNDNG_KEY IS NOT NULL GROUP BY SNDNG_KEY
UNION ALL
SELECT SEQ_NO,'SND',SUM(TARGET_CNT),SUM(SEND_CNT),SUM(FAIL_CNT),NULL,
  'CRM','BRONZE_CRM.SND_REQ_MST',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM GN_DW.BRONZE_CRM.SND_REQ_MST WHERE SEQ_NO IS NOT NULL GROUP BY SEQ_NO;

-- CRM_SEND_MEMBER ← 채널별 상세 ∪ SND 회원리스트 (발송×회원, 38,471,525)
INSERT OVERWRITE INTO GN_DW.SILVER.CRM_SEND_MEMBER
(SNDNG_KEY, SNDNG_DTL_KEY, MBER_NO, SNDNG_DE, SNDNG_RST_CD, SEND_CHANNEL,
 DW_SOURCE_SYSTEM, DW_SOURCE_TABLE, DW_LOAD_TS, DW_UPDATE_TS, DW_BATCH_ID)
SELECT SNDNG_KEY, SNDNG_DTL_KEY, NULLIF(TRIM(MBER_NO),''), SNDNG_DE, NULLIF(TRIM(SNDNG_RST_CD),''), 'EMAIL',
  'CRM','BRONZE_CRM.TD_MS_EMAIL_SNDNG_DTLS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM GN_DW.BRONZE_CRM.TD_MS_EMAIL_SNDNG_DTLS WHERE SNDNG_KEY IS NOT NULL AND SNDNG_DTL_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY SNDNG_KEY, SNDNG_DTL_KEY ORDER BY SNDNG_DE DESC NULLS LAST)=1
UNION ALL
SELECT SNDNG_KEY, SNDNG_DTL_KEY, NULLIF(TRIM(MBER_NO),''), SNDNG_DT, NULLIF(TRIM(TRNSMS_STAT_CD),''), 'MSG_AT',
  'CRM','BRONZE_CRM.TD_MS_MSG_AT_SNDNG_DTLS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM GN_DW.BRONZE_CRM.TD_MS_MSG_AT_SNDNG_DTLS WHERE SNDNG_KEY IS NOT NULL AND SNDNG_DTL_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY SNDNG_KEY, SNDNG_DTL_KEY ORDER BY SNDNG_DT DESC NULLS LAST)=1
UNION ALL
SELECT SNDNG_KEY, SNDNG_DTL_KEY, NULLIF(TRIM(MBER_NO),''), SNDNG_DE, NULL, 'PSTMTR',
  'CRM','BRONZE_CRM.TD_MS_PSTMTR_SNDNG_DTL',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM GN_DW.BRONZE_CRM.TD_MS_PSTMTR_SNDNG_DTL WHERE SNDNG_KEY IS NOT NULL AND SNDNG_DTL_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY SNDNG_KEY, SNDNG_DTL_KEY ORDER BY SNDNG_DE DESC NULLS LAST)=1
UNION ALL
SELECT REQ_SEQ_NO, R_NUM, NULLIF(TRIM(MBER_NO),''), SND_DT, NULLIF(TRIM(SND_YN),''), 'SND',
  'CRM','BRONZE_CRM.SND_MEMBER_LIST',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM GN_DW.BRONZE_CRM.SND_MEMBER_LIST WHERE REQ_SEQ_NO IS NOT NULL AND R_NUM IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY REQ_SEQ_NO, R_NUM ORDER BY SND_DT DESC NULLS LAST)=1;

-- ============================================================================
-- STEP 3 완료 — CRM 21/21 테이블 전량 적재 (Q5·Q6 포함).
-- 데이터로 해소(2026-07-14): SEX(CM013)·MBER_DIV_NM(MM018)·SETLE_NM(PM040) 라벨 확정·채움 100%
--   · Q16 캠페인↔마케팅캠페인: MKTG_CMPGN_NM 원천 100% NULL → 데이터상 연결 없음(타입불일치 무관), MK_CMPGN_NM=NULL
-- 잔여(원천 코드체계/현업 라벨 부재): EVENT_DIV_CD·CRMN_DIV_CD 코드그룹(Q8) · Q2/Q3 캠페인 코드값 라벨
-- ============================================================================


