-- # A1
SELECT table_schema, table_name, row_count, bytes
FROM GN_DW.INFORMATION_SCHEMA.TABLES
WHERE table_type = 'BASE TABLE' AND table_schema LIKE 'BRONZE_%'
ORDER BY table_schema, table_name;
/*
BRONZE_AGENCY	DGT_AD_CMPGN_DTLS	205059	4089856
BRONZE_AGENCY	REBRDC_AD_CMPGN_DTLS	2070	120832
BRONZE_AGENCY	SYNC_ERR_INFO	5	1536
BRONZE_AGENCY	VIDEO_AD_CMPGN_DTLS	36416	1506816
BRONZE_CRM	SND_MEMBER_LIST	8300432	215469568
BRONZE_CRM	SND_REQ_MST	1707	115200
BRONZE_CRM	TC_CMMN_CD	338	14848
BRONZE_CRM	TC_CMMN_DTL_CD	5838	188416
BRONZE_CRM	TD_MS_AT_TMPLAT_BTN_LIST	5551	291840
BRONZE_CRM	TD_MS_CRMN_PRTCPNT	152132	5960192
BRONZE_CRM	TD_MS_EMAIL_LQY_SNDNG	497777	17102336
BRONZE_CRM	TD_MS_EMAIL_SNDNG_DTLS	7811125	68064768
BRONZE_CRM	TD_MS_EVENT_PRTCPNT_DTL	983971	34880512
BRONZE_CRM	TD_MS_MSG_AT_LQY_SNDNG	1113284	22250496
BRONZE_CRM	TD_MS_MSG_AT_SNDNG_DTLS	20561448	269157888
BRONZE_CRM	TD_MS_PSTMTR_LQY_SNDNG	2022	87040
BRONZE_CRM	TD_MS_PSTMTR_SNDNG_DTL	1798680	15661056
BRONZE_CRM	TH_MM_FDRM_MBER_STNG_DTLS	7501761	68199424
BRONZE_CRM	TH_PM_SETLE_INFO_HIST	1065053	82991616
BRONZE_CRM	TM_CM_BRND_MNG	103	5120
BRONZE_CRM	TM_CM_CMPGN_MNG	36143	1587200
BRONZE_CRM	TM_CM_DEPT_INFO	1314	29696
BRONZE_CRM	TM_CM_MBER_DVLP_GOAL	25344	311808
BRONZE_CRM	TM_CM_MKTNG_CMPGN_MNG	323	10240
BRONZE_CRM	TM_CM_SPNSR_BSNS_INFO	50	3072
BRONZE_CRM	TM_MM_FDRM_MBER_DVLP_AMT	3594843	91357696
BRONZE_CRM	TM_MM_FDRM_MBER_INFO	1587343	37532160
BRONZE_CRM	TM_MM_FDRM_MBER_IRSD	324947	5129216
BRONZE_CRM	TM_MM_FDRM_MBER_RELATNSP_DVLP_AMT	1134848	12634624
BRONZE_CRM	TM_MM_FDRM_MBER_RE_SPNSR	115254	1851904
BRONZE_CRM	TM_MM_FDRM_MBER_SPNSR	2228064	28464128
BRONZE_CRM	TM_MM_FDRM_MBER_SPNSR_BSNS	2170572	10806272
BRONZE_CRM	TM_MM_FDRM_MBER_SPNSR_DSCNTC	1038262	9715712
BRONZE_CRM	TM_MM_ONCE_MBER_INFO	175722	2964480
BRONZE_CRM	TM_MS_CRMN	3410	189440
BRONZE_CRM	TM_MS_EMAIL_SNDNG	498639	20250112
BRONZE_CRM	TM_MS_EMAIL_TMPLAT_MNG	446	900096
BRONZE_CRM	TM_MS_EVENT	376	20992
BRONZE_CRM	TM_MS_MSG_AT_SNDNG	1110250	35333120
BRONZE_CRM	TM_MS_PSTMTR_SNDNG	3801	103424
BRONZE_CRM	TM_PM_DNTN_DTLS	1130252	18800640
BRONZE_CRM	TM_PM_MBRFEE_ACMSLT	46391620	1557174272
BRONZE_CRM	TM_PM_SETLE_INFO	2545696	169969152
BRONZE_CRM	TM_RM_BPLC_MNG	377	70656
BRONZE_CRM	TM_RM_CHILD_MSTR_INFO	508051	4789760
BRONZE_CRM	TM_RM_RELATNSP_CHG_INFO	197061	1977856
BRONZE_CRM	TM_RM_RELATNSP_GFTMNEY_INFO	180664	4315136
BRONZE_CRM	TM_RM_RELATNSP_LETTER_INFO	207609	3514368
BRONZE_CRM	TM_RM_RELATNSP_MSTR_INFO	862610	14353408
BRONZE_ERP	BDGT_ACMSLT_LEDGER	4301	328704
BRONZE_GA4	SYNC_ERR_INFO	0	0
BRONZE_GA4	events_20260501	287025	54060032
BRONZE_GA4	events_20260719	289416	75846656
*/
-- # A2
SELECT table_schema,
       COUNT(*)        AS tables,
       SUM(row_count)  AS total_rows,
       SUM(bytes)      AS total_bytes
FROM GN_DW.INFORMATION_SCHEMA.TABLES
WHERE table_type = 'BASE TABLE' AND table_schema LIKE 'BRONZE_%'
GROUP BY 1 ORDER BY 1;
/*
BRONZE_AGENCY	4	243550	5719040
BRONZE_CRM	45	115875113	2834600960
BRONZE_ERP	1	4301	328704
BRONZE_GA4	3	576441	129906688
*/
-- # A3
SELECT GET_DDL('SCHEMA', 'GN_DW.BRONZE_CRM', TRUE);
/*
create or replace schema GN_DW.BRONZE_CRM with managed access COMMENT='원천 데이터 적재 - CRM (회원/납입/캠페인)';

create or replace TABLE GN_DW.BRONZE_CRM.SND_MEMBER_LIST (
	REQ_SEQ_NO NUMBER(19,0),
	R_NUM NUMBER(19,0),
	MBER_NO VARCHAR(255),
	SPNSR_CD VARCHAR(255),
	SPNSR_NM VARCHAR(255),
	CMPGN_CD VARCHAR(255),
	CMPGN_NM VARCHAR(255),
	GENDER VARCHAR(255),
	AGE VARCHAR(255),
	SETLE_CD VARCHAR(255),
	SETLE_NM VARCHAR(255),
	DSCNTC_PATH VARCHAR(255),
	DSCNTC_RSN_CD VARCHAR(255),
	DSCNTC_RSN_NM VARCHAR(255),
	CHILD_NO VARCHAR(255),
	LST_BRND_CD VARCHAR(255),
	LST_BRND_NM VARCHAR(255),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	MNG_NO VARCHAR(255),
	LETTER_DIV_CD VARCHAR(255),
	CHILD_DTL_CD VARCHAR(255),
	CHILD_DTL_NM VARCHAR(255),
	RELATNSP_DSCNTC_YN VARCHAR(255),
	FRST_SPNSR VARCHAR(255),
	FRST_BRND_CD VARCHAR(255),
	FRST_BRND_NM VARCHAR(255),
	RELATNSP_KEY NUMBER(19,0),
	LST_REGIST_DT TIMESTAMP_NTZ(9),
	PRIV_SUSP_YN VARCHAR(255),
	SND_YN VARCHAR(255),
	SND_MSG VARCHAR(16777216),
	REG_DATE TIMESTAMP_NTZ(9),
	SND_DT TIMESTAMP_NTZ(9),
	SND_HOUR VARCHAR(255),
	SND_MIN VARCHAR(255),
	EMAIL_RECPTN_CD VARCHAR(255),
	EMAIL_RECPTN_NM VARCHAR(255),
	NATION_CD VARCHAR(255),
	NATION_NM VARCHAR(255),
	BPLC_CD VARCHAR(255),
	BPLC_KOR_NM VARCHAR(255),
	DISCHARGE_REPORT_KOR VARCHAR(255),
	PAST_NATION_NM VARCHAR(255),
	PAST_BPLC_NM VARCHAR(255),
	PAST_CHILD_NO VARCHAR(255),
	FAMILY_DTL VARCHAR(255),
	FINAL_CHILD_SPNSR_START_DT TIMESTAMP_NTZ(9),
	NEW_CHILD_NO VARCHAR(255),
	NEW_CHILD_PROJECT_COUNTRY VARCHAR(255),
	NEW_CHILD_WORKPLACE_NM VARCHAR(255),
	NEW_CHILD_PIC VARCHAR(255),
	NEW_CHILD_GENDER VARCHAR(255),
	SPNSR_AMOUNT NUMBER(10,2),
	SPNSR_STRT_DT TIMESTAMP_NTZ(9),
	SPNSR_DSCNTC_DT TIMESTAMP_NTZ(9),
	RELATNSP_DT TIMESTAMP_NTZ(9),
	SPNSR_TYPE VARCHAR(255),
	CPR_DIV_CD VARCHAR(255),
	DEPT_CD VARCHAR(255),
	CURRENT_BRND VARCHAR(255),
	CURRENT_UPPER_CMPGN VARCHAR(255),
	CURRENT_CMPGN VARCHAR(255),
	FIRST_UPPER_CMPGN VARCHAR(255),
	FIRST_CMPGN VARCHAR(255),
	LAST_TOP_CMPGN VARCHAR(255),
	LAST_CMPGN VARCHAR(255),
	MSG_KEY VARCHAR(255),
	CINFO VARCHAR(255),
	RESPONSED_YN VARCHAR(255),
	RESPONSED_DT TIMESTAMP_NTZ(9),
	SYNCED_AT TIMESTAMP_NTZ(9),
	CALL_STATUS VARCHAR(30),
	REAL_SEND_DT TIMESTAMP_NTZ(9),
	LAST_UPPER_CMPGN VARCHAR(255),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.SND_REQ_MST (
	SEQ_NO NUMBER(19,0),
	SEND_GBN_TOP VARCHAR(255),
	SEND_GBN_MID VARCHAR(255),
	SEND_GBN_BOT VARCHAR(255),
	SEND_TITLE VARCHAR(255),
	MSG_TYPE VARCHAR(255),
	TMPL_CODE VARCHAR(255),
	AUTHOR VARCHAR(255),
	CREATE_DATE DATE,
	CONDITION_TITLE VARCHAR(255),
	CALL_NUMBER VARCHAR(255),
	ALT_SMS_YN VARCHAR(255),
	REGULARLY VARCHAR(255),
	PERIODIC VARCHAR(255),
	PERIODIC_WEEK VARCHAR(255),
	PERIODIC_DAY NUMBER(10,0),
	SEND_DATE DATE,
	SEND_TIME TIME(9),
	SEND_MIN VARCHAR(2),
	SEND_SPLIT_TYPE VARCHAR(255),
	DIVIDE NUMBER(10,0),
	DIVIDE_UNIT NUMBER(10,0),
	CORP_TYPE VARCHAR(255),
	AUTO_TYPE VARCHAR(255),
	USE_YN VARCHAR(255),
	REG_ID VARCHAR(255),
	MOD_DATE DATE,
	INIT_REG_DATE DATE,
	LAST_SEND_DATE DATE,
	APPR_STATUS VARCHAR(255),
	CREATE_DEPT VARCHAR(255),
	SENDER_EMAIL VARCHAR(255),
	RCPT_LIST VARCHAR(16777216),
	SEND_STATUS VARCHAR(255),
	SEND_CNT NUMBER(19,0),
	FAIL_CNT NUMBER(19,0),
	LAST_ERR VARCHAR(16777216),
	END_DATE DATE,
	PAPER_YEAR VARCHAR(255),
	MENU_CODE VARCHAR(255),
	SEND_GBN_TOP_NM VARCHAR(255),
	SEND_GBN_MID_NM VARCHAR(255),
	SEND_GBN_BOT_NM VARCHAR(255),
	TARGET_CNT NUMBER(19,0),
	SEND_ROUND NUMBER(10,0),
	EXTRA VARCHAR(255),
	ASSIGN_TARGET_CNT NUMBER(19,0),
	FIRST_SEQ_NO NUMBER(19,0),
	JOB_ID VARCHAR(255),
	SYNCED_AT VARCHAR(255),
	REG_NM VARCHAR(255),
	SERVICE_MENU_CODE VARCHAR(100),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TC_CMMN_CD (
	CD_ID VARCHAR(20),
	CD_NM VARCHAR(100),
	CD_DC VARCHAR(500),
	SORT_ORDR NUMBER(10,0),
	RM VARCHAR(1000),
	USE_YN VARCHAR(1),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TC_CMMN_DTL_CD (
	CD_ID VARCHAR(20),
	DTL_CD_ID VARCHAR(50),
	DTL_CD_NM VARCHAR(100),
	DTL_CD_DC VARCHAR(500),
	SORT_ORDR NUMBER(10,0),
	RM VARCHAR(1000),
	USE_YN VARCHAR(1),
	CD_ATRB1 VARCHAR(100),
	CD_ATRB2 VARCHAR(100),
	CD_ATRB3 VARCHAR(100),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	UPPER_CD_ID VARCHAR(20),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TD_MS_AT_TMPLAT_BTN_LIST (
	TMPLAT_ID VARCHAR(30),
	BTN_SEQ NUMBER(10,0),
	BTN_TY_CD VARCHAR(3),
	BTN_NM VARCHAR(16777216),
	ANDROID_URL VARCHAR(255),
	IOS_URL VARCHAR(255),
	MOBILE_URL VARCHAR(255),
	PC_URL VARCHAR(255),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TD_MS_CRMN_PRTCPNT (
	CRMN_CD NUMBER(10,0),
	PRTCPNT_KEY NUMBER(10,0),
	MBER_NO VARCHAR(10),
	RQST_PATH_CD VARCHAR(3),
	PARTCPT_TIME_CO NUMBER(10,0),
	PARTCPT_STAT_CD VARCHAR(3),
	SELF_PARTCPT_CD VARCHAR(3),
	RCPMNY_STAT_CD VARCHAR(3),
	RCPMNY_DATE VARCHAR(8),
	REFND_DATE VARCHAR(8),
	RQST_DATE VARCHAR(8),
	PARTCPT_DATE VARCHAR(8),
	RCPMNY_AMT NUMBER(19,0),
	ACMPNY_PARTCPT_CO NUMBER(10,0),
	RM VARCHAR(1000),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TD_MS_EMAIL_LQY_SNDNG (
	SNDNG_KEY NUMBER(10,0),
	MSG_ID VARCHAR(20),
	MKT_TRGET_CTNT VARCHAR(300),
	SNDNG_CNT NUMBER(10,0),
	SUCCES_CNT NUMBER(10,0),
	FAILR_CNT NUMBER(10,0),
	RECPTN_CNT NUMBER(10,0),
	SNDNG_STRT_DT TIMESTAMP_NTZ(9),
	SNDNG_END_DT TIMESTAMP_NTZ(9),
	INFLOW_PATH_CTNT VARCHAR(100),
	SNDNG_YEAR_CTNT VARCHAR(100),
	SNDNG_MT_CTNT VARCHAR(100),
	SNDNG_TEAM_CTNT VARCHAR(100),
	SUCCES_FAILR_CNT_CTNT VARCHAR(100),
	URL_OTHBC_CNT_CTNT VARCHAR(100),
	URL_OTHBC_RT_CTNT VARCHAR(100),
	SESION_VU_CTNT VARCHAR(300),
	SESION_PGE_CNT_CTNT VARCHAR(100),
	DVLP_ACMSLT_CNT_CTNT VARCHAR(100),
	CLOS_YN VARCHAR(1),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TD_MS_EMAIL_SNDNG_DTLS (
	SNDNG_KEY NUMBER(10,0),
	SNDNG_DTL_KEY NUMBER(10,0),
	SNDNG_DE TIMESTAMP_NTZ(9),
	MBER_NO VARCHAR(10),
	SNDNG_RST_CD VARCHAR(3),
	ATCHFL_ID VARCHAR(20),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TD_MS_EVENT_PRTCPNT_DTL (
	EVENT_CD NUMBER(10,0),
	MBER_NO VARCHAR(10),
	PARTCPT_SEQ NUMBER(10,0),
	EVENT_PARTCPT_DIV_CD VARCHAR(3),
	PRZWIN_CD NUMBER(10,0),
	PARTCPT_CHNNL_CD VARCHAR(3),
	PARTCPT_PATH_CD VARCHAR(3),
	PARTCPT_STAT_CD VARCHAR(3),
	PARTCPT_DT TIMESTAMP_NTZ(9),
	RM VARCHAR(1000),
	RM2 VARCHAR(1000),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TD_MS_MSG_AT_LQY_SNDNG (
	SNDNG_KEY NUMBER(10,0),
	DIVS_DTL_KEY NUMBER(10,0),
	SNDNG_CNT NUMBER(10,0),
	SUCCES_CNT NUMBER(10,0),
	AT_ALTRTV_SNDNG_CNT NUMBER(10,0),
	AT_FAILR_CNT NUMBER(10,0),
	RESVE_SNDNG_DE DATE,
	RESVE_HM VARCHAR(4),
	TOT_CLICK_CNT_CTNT VARCHAR(100),
	CLICK_CNT_CTNT1 VARCHAR(100),
	CLICK_CNT_CTNT2 VARCHAR(100),
	CLICK_CNT_CTNT3 VARCHAR(100),
	CLICK_CNT_CTNT4 VARCHAR(100),
	RM_VU_CTNT VARCHAR(100),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TD_MS_MSG_AT_SNDNG_DTLS (
	SNDNG_KEY NUMBER(10,0),
	SNDNG_DTL_KEY NUMBER(10,0),
	SNDNG_DT TIMESTAMP_NTZ(9),
	MBER_NO VARCHAR(10),
	SNDNG_NO NUMBER(10,0),
	TRNSMS_STAT_CD VARCHAR(3),
	TRNSMS_FAILR_CD_ID VARCHAR(20),
	FRST_RGSTR_ID VARCHAR(30),
	ALTRTV_MSG_SNDNG_YN VARCHAR(1),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	ATTACHED_FILE VARCHAR(100),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TD_MS_PSTMTR_LQY_SNDNG (
	SNDNG_KEY NUMBER(10,0),
	SNDNG_CNT NUMBER(10,0),
	SNDNG_SQNC NUMBER(3,0),
	SNDNG_TIT VARCHAR(255),
	SNDNG_MEMO_CTNT VARCHAR(4000),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TD_MS_PSTMTR_SNDNG_DTL (
	SNDNG_KEY NUMBER(10,0),
	SNDNG_DTL_KEY NUMBER(10,0),
	SNDNG_DE TIMESTAMP_NTZ(9),
	MBER_NO VARCHAR(10),
	RELATNSP_KEY NUMBER(10,0),
	MNG_NO VARCHAR(7),
	DTL_KEY NUMBER(10,0),
	BIZN_REQUST_KEY NUMBER(10,0),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TH_MM_FDRM_MBER_STNG_DTLS (
	MBER_NO VARCHAR(10),
	SER_NO NUMBER(10,0),
	BF_STAT_CD VARCHAR(3),
	CHN_STAT_CD VARCHAR(3),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TH_PM_SETLE_INFO_HIST (
	SETLE_KEY NUMBER(10,0),
	UPDT_DT TIMESTAMP_NTZ(9),
	UPDUSR_ID VARCHAR(30),
	UPDUSR_NM VARCHAR(100),
	MBER_NO VARCHAR(10),
	CPR_DIV_CD VARCHAR(3),
	SETLE_CD VARCHAR(3),
	WTDRW_STRT_DE DATE,
	WTDRW_ASMT_SQNC NUMBER(3,0),
	FNLT_DIV_CD VARCHAR(3),
	FNLT_CD VARCHAR(10),
	SETLE_ENTRPS_CD VARCHAR(10),
	CARD_TRMVT VARCHAR(6),
	ACNUT_SER_NO NUMBER(10,0),
	PAYER_NM VARCHAR(30),
	CARD_DIV_CD VARCHAR(3),
	ETC_CTTPC VARCHAR(14),
	ETC_CTTPC_REL_CD VARCHAR(3),
	PAYER_MBER_REL_CD VARCHAR(3),
	CRTFC_MTH_CD VARCHAR(3),
	CRTFC_FILE_NM VARCHAR(200),
	CRTFC_DATA_CTNT VARCHAR(4000),
	CRTFC_DE DATE,
	FILE_SIZE NUMBER(10,0),
	BILLKEY VARCHAR(50),
	SETLE_STAT_CD VARCHAR(3),
	BF_SETLE_STAT_CD VARCHAR(3),
	RQST_DIV_CD VARCHAR(3),
	RCEPT_DIV_CD VARCHAR(3),
	APRV_YN VARCHAR(1),
	APRV_REQUST_KEY NUMBER(19,0),
	APRV_RST_KEY NUMBER(19,0),
	FRST_BEGIN_DE DATE,
	RQEST_EXCL_YN VARCHAR(1),
	RQEST_EXCL_STRT_DE DATE,
	RQEST_EXCL_END_DE DATE,
	APPLCNT_NM VARCHAR(30),
	APPLCNT_ETC_CTTPC VARCHAR(14),
	APPLCNT_ETC_CTTPC_REL_CD VARCHAR(3),
	APPLCNT_MBER_REL_CD VARCHAR(3),
	BF_SETLE_KEY NUMBER(10,0),
	OPERT_DIV_CD VARCHAR(3),
	CRTFC_TY_CD VARCHAR(3),
	USE_YN VARCHAR(1),
	RGSTR_ID VARCHAR(30),
	RGSTR_NM VARCHAR(30),
	REGIST_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_CM_BRND_MNG (
	BRND_ID VARCHAR(30),
	BRND_NM VARCHAR(200),
	USE_DEPT_CD VARCHAR(10),
	USE_YN VARCHAR(1),
	PR_MTH_LIST VARCHAR(4000),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_CM_CMPGN_MNG (
	CMPGN_CD VARCHAR(20),
	CMPGN_NM VARCHAR(200),
	UPPER_CMPGN_CD VARCHAR(20),
	UPPER_CMPGN_YN VARCHAR(1),
	SPNSR_DIV_CD VARCHAR(3),
	CPR_DIV_CD VARCHAR(3),
	CMPGN_TRGET_CD VARCHAR(2),
	USE_DEPT_CD VARCHAR(10),
	USE_SCOPE VARCHAR(1),
	SPNSR_ENTRPRS_ID VARCHAR(20),
	BRND_ID VARCHAR(30),
	PR_MTH_CD VARCHAR(3),
	CMPGN_STRT_DE VARCHAR(8),
	MBRFEE_BNKB_LIST VARCHAR(4000),
	INICIS_ACNT_NO VARCHAR(50),
	USE_YN VARCHAR(1),
	REFER_URL VARCHAR(255),
	SPNSR_BSNS_ID VARCHAR(100),
	CMPGN_DC VARCHAR(500),
	EMRGNCY_AID_BPLC_CD NUMBER(10,0),
	CMPGN_PRPT_YN VARCHAR(1),
	ATCHFL_ID VARCHAR(20),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	RM VARCHAR(50),
	MBER_INFLOW_PATH_CD NUMBER(10,0),
	CMPGN_CTGR_CD NUMBER(10,0),
	CMPGN_TYPE1_BSN NUMBER(10,0),
	CMPGN_TYPE2_BSN NUMBER(10,0),
	MKTG_CMPGN_NM NUMBER(10,0),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_CM_DEPT_INFO (
	DEPT_ID VARCHAR(20),
	DEPT_NM VARCHAR(50),
	UPPER_DEPT_ID VARCHAR(20),
	SORT_ORDR NUMBER(10,0),
	USE_YN VARCHAR(1),
	ACMSLT_DEPT_YN VARCHAR(1),
	STATS_DEPT_LVL NUMBER(3,0),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	ACMSLT_UPPER_DEPT_ID VARCHAR(20),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_CM_MBER_DVLP_GOAL (
	STDYY VARCHAR(4),
	STDR_MT VARCHAR(6),
	MBER_DVLP_DIV_CD VARCHAR(1),
	DEPT_ID VARCHAR(20),
	GOAL_CNT NUMBER(10,0),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_CM_MKTNG_CMPGN_MNG (
	MK_CMPGN_CD VARCHAR(50),
	MK_CMPGN_NM VARCHAR(200),
	USE_YN VARCHAR(1),
	RM VARCHAR(500),
	FRST_RGSTR_ID VARCHAR(50),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(50),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_CM_SPNSR_BSNS_INFO (
	SPNSR_BSNS_ID VARCHAR(20),
	SPNSR_DIV_CD VARCHAR(3),
	SPNSR_BSNS_NM VARCHAR(50),
	SPNSR_BSNS_ABRV_CD VARCHAR(3),
	DNTN_TY_CD VARCHAR(3),
	SORT_ORDR NUMBER(10,0),
	CPR_DIV_CD VARCHAR(3),
	RM VARCHAR(1000),
	USE_YN VARCHAR(1),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_DVLP_AMT (
	SPNSR_NO VARCHAR(9),
	SPNSR_BSNS_NO NUMBER(19,0),
	OCCRRNC_DE VARCHAR(8),
	SER_NO NUMBER(10,0),
	MBER_NO VARCHAR(10),
	ACT_DEPT_CD VARCHAR(10),
	ACMSLT_DEPT_CD VARCHAR(10),
	CMPGN_CD VARCHAR(20),
	SETLE_CD VARCHAR(3),
	MBER_DIV_CD VARCHAR(3),
	SEX VARCHAR(2),
	AREA_CD VARCHAR(3),
	AGE NUMBER(10,0),
	SPNSR_TIME_CO NUMBER(10,0),
	SPNSR_AMT_CD VARCHAR(3),
	SPNSR_BSNS_ID VARCHAR(20),
	CANCL_RDCAMT_RSN_CD VARCHAR(3),
	SPNSR_AMT NUMBER(19,0),
	DVLP_DIV_CD VARCHAR(3),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_RGSTR_NM VARCHAR(100),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_INFO (
	MBER_NO VARCHAR(10),
	MBER_DIV_CD VARCHAR(3),
	CPR_DIV_CD VARCHAR(3),
	SLRCLD_LRR_CD VARCHAR(3),
	MOBLPHON_STAT_CD VARCHAR(3),
	TSTM_DIV_CD NUMBER(10,0),
	ETC_TSTM_DIV_CD NUMBER(10,0),
	ETC_CTTPC_REL_CD VARCHAR(3),
	ETC_CTTPC_STAT_CD VARCHAR(3),
	EMAIL_STAT_CD VARCHAR(3),
	PSTMTR_RECPTN_CD VARCHAR(100),
	EMAIL_RECPTN_CD VARCHAR(100),
	CHRCTR_RECPTN_YN VARCHAR(1),
	BL_ENTRPS_NO NUMBER(19,0),
	SPECL_MNG_CD1 VARCHAR(3),
	SPECL_MNG_CD2 VARCHAR(3),
	TNI_CU_BL_NO NUMBER(19,0),
	CMPGN_CD VARCHAR(20),
	MBER_STAT_CD VARCHAR(3),
	RELATNSP_DIV_CD VARCHAR(3),
	ACT_DEPT_CD VARCHAR(10),
	HMPG_ID VARCHAR(30),
	JOIN_PATH_CD VARCHAR(3),
	CTI_SYNCHRN_DIV_CD VARCHAR(3),
	STDR_DE DATE,
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	REGIST_DEPT_CD VARCHAR(10),
	FRST_RGSTR_ID VARCHAR(30),
	SEX VARCHAR(2),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_IRSD (
	OCCRRNC_DE VARCHAR(8),
	SER_NO NUMBER(10,0),
	ACMSLT_DEPT_CD VARCHAR(10),
	CMPGN_CD VARCHAR(20),
	MBER_NO VARCHAR(10),
	SPNSR_AMT NUMBER(19,0),
	SETLE_CD VARCHAR(3),
	MBER_DIV_CD VARCHAR(3),
	SEX VARCHAR(2),
	AREA_CD VARCHAR(3),
	AGE NUMBER(10,0),
	SPNSR_TIME_CO NUMBER(10,0),
	SPNSR_AMT_CD VARCHAR(3),
	RDCAMT_YN VARCHAR(1),
	FRST_RGSTR_ID VARCHAR(30),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_RELATNSP_DVLP_AMT (
	OCCRRNC_DE VARCHAR(8),
	SER_NO NUMBER(10,0),
	SPNSR_NO NUMBER(19,0),
	SPNSR_BSNS_NO NUMBER(19,0),
	MBER_NO VARCHAR(10),
	SPNSR_AMT NUMBER(19,0),
	BF_STAT_CD VARCHAR(3),
	AF_STAT_CD VARCHAR(3),
	RELATNSP_DVLP_DIV_CD VARCHAR(3),
	ACCNUT_STATS_CD VARCHAR(3),
	CHILD_STATS_CD VARCHAR(3),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_RE_SPNSR (
	MBER_NO VARCHAR(10),
	SER_NO NUMBER(10,0),
	RE_SPNSR_DE VARCHAR(8),
	REGIST_DEPT_CD VARCHAR(10),
	FRST_RGSTR_ID VARCHAR(30),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_SPNSR (
	SPNSR_NO VARCHAR(9),
	MBER_NO VARCHAR(10),
	CMPGN_CD VARCHAR(20),
	ACMSLT_DEPT_CD VARCHAR(10),
	JOIN_PATH_CD VARCHAR(3),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_SPNSR_BSNS (
	SPNSR_NO VARCHAR(9),
	SPNSR_BSNS_NO NUMBER(19,0),
	SPNSR_BSNS_ID VARCHAR(20),
	SPNSR_AMT NUMBER(19,0),
	SPNSR_DSCNTC_DE VARCHAR(8),
	SPNSR_DSCNTC_YN VARCHAR(1),
	SPNSR_DSCNTC_RSN_CD VARCHAR(3),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_SPNSR_DSCNTC (
	MBER_NO VARCHAR(10),
	SPNSR_DSCNTC_DE VARCHAR(8),
	SER_NO NUMBER(10,0),
	DSCNTC_RSN_CD VARCHAR(3),
	DSCNTC_PATH VARCHAR(1),
	REGIST_DEPT_CD VARCHAR(10),
	FRST_RGSTR_ID VARCHAR(30),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_MM_ONCE_MBER_INFO (
	ONCE_MBER_NO VARCHAR(10),
	MBER_DIV_CD VARCHAR(3),
	CPR_DIV_CD VARCHAR(3),
	SEX VARCHAR(2),
	TSTM_DIV_CD NUMBER(10,0),
	ETC_TSTM_DIV_CD NUMBER(10,0),
	REL_CD VARCHAR(3),
	ENTRPS_NM VARCHAR(200),
	HMPG_ID VARCHAR(30),
	PSTMTR_RECPTN_YN VARCHAR(1),
	EMAIL_RECPTN_YN VARCHAR(1),
	CHRCTR_RECPTN_YN VARCHAR(1),
	FDRM_MBER_TRNSFER_FG BOOLEAN,
	SPECL_MNG_CD1 VARCHAR(100),
	SPECL_MNG_CD2 VARCHAR(100),
	TNI_CU_BL_NO NUMBER(19,0),
	CTI_SYNCHRN_DIV_CD VARCHAR(3),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	REGIST_DEPT_CD VARCHAR(10),
	FRST_RGSTR_ID VARCHAR(100),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_MS_CRMN (
	CRMN_CD NUMBER(10,0),
	CRMN_DIV_CD VARCHAR(3),
	CRMN_TIT VARCHAR(100),
	CRMN_PLACE_NM VARCHAR(200),
	BRNCH_DEPT_ID VARCHAR(20),
	ATCHFL_ID VARCHAR(20),
	SITE_URL VARCHAR(255),
	CRMN_STRT_DE VARCHAR(8),
	CRMN_END_DE VARCHAR(8),
	CRMN_PART_STRT_DE VARCHAR(8),
	CRMN_PART_END_DE VARCHAR(8),
	TAT NUMBER(5,0),
	RCRIT_PSNNL_CO NUMBER(10,0),
	RESRCE_SRVC_FG BOOLEAN,
	CPR_DIV_CD VARCHAR(3),
	ENTRPS_CD NUMBER(10,0),
	RM VARCHAR(1000),
	CRMN_CTNT VARCHAR(4000),
	USE_YN VARCHAR(1),
	PART_USE_YN VARCHAR(1),
	TMPLAT_ID VARCHAR(30),
	TMPLAT_TIT VARCHAR(100),
	TMPLAT_PART_ID VARCHAR(30),
	TMPLAT_PART_TIT VARCHAR(100),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	SRVY VARCHAR(200),
	RM2 VARCHAR(1000),
	PROMO_CODE VARCHAR(255),
	TMPLAT_WIN_ID VARCHAR(30),
	TMPLAT_WIN_TIT VARCHAR(100),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_MS_EMAIL_SNDNG (
	SNDNG_KEY NUMBER(10,0),
	SNDNG_CD_ID VARCHAR(20),
	SNDNG_DTL_CD_ID VARCHAR(20),
	SNDNG_STDR_DE TIMESTAMP_NTZ(9),
	SNDNG_TY_CD VARCHAR(3),
	TIT VARCHAR(100),
	EMAIL_RM VARCHAR(4000),
	PRCS_DE TIMESTAMP_NTZ(9),
	PCPSN_ID VARCHAR(30),
	PRCS_YN VARCHAR(1),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_MS_EMAIL_TMPLAT_MNG (
	TMPLAT_KEY NUMBER(10,0),
	CPR_DIV_CD VARCHAR(3),
	SNDNG_CD_ID VARCHAR(20),
	SNDNG_DTL_CD_ID VARCHAR(20),
	ATMC_YN VARCHAR(1),
	TIT VARCHAR(100),
	EMAIL_CTNT VARCHAR(16777216),
	WRITNG_DEPT_ID VARCHAR(20),
	WRITNG_DEPT_NM VARCHAR(30),
	CHRG_DEPT_ID VARCHAR(20),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_MS_EVENT (
	EVENT_CD NUMBER(10,0),
	EVENT_DIV_CD VARCHAR(3),
	EVENT_NM VARCHAR(200),
	STRT_DATE VARCHAR(8),
	END_DATE VARCHAR(8),
	PRZWIN_PSNNL_CO NUMBER(10,0),
	PRZWIN_GFT_SNDNG_DE VARCHAR(8),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_MS_MSG_AT_SNDNG (
	SNDNG_KEY NUMBER(10,0),
	SNDNG_CD_ID VARCHAR(20),
	SNDNG_DTL_CD_ID VARCHAR(20),
	SNDNG_STDR_DE TIMESTAMP_NTZ(9),
	SNDNG_TY_CD VARCHAR(3),
	SNDNG_TIME_DIV_CD VARCHAR(3),
	MSG_DIV_CD VARCHAR(3),
	TIT VARCHAR(100),
	MSG_AT_RM VARCHAR(4000),
	PRCS_DE TIMESTAMP_NTZ(9),
	PCPSN_ID VARCHAR(20),
	ATCHFL_ID VARCHAR(20),
	TMPLAT_ID VARCHAR(30),
	ALTRTV_MSG_SNDNG_YN VARCHAR(1),
	ALTRTV_MSG_ATCHFL_ID VARCHAR(20),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_MS_PSTMTR_SNDNG (
	SNDNG_KEY NUMBER(10,0),
	SNDNG_CD_ID VARCHAR(20),
	SNDNG_DTL_CD_ID VARCHAR(20),
	SNDNG_STDR_DE DATE,
	SNDNG_TY_CD VARCHAR(3),
	PRCS_DE DATE,
	PCPSN_ID VARCHAR(20),
	PRCS_STAT_CD VARCHAR(3),
	LQY_YN VARCHAR(1),
	RE_SNDNG_YN VARCHAR(1),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_PM_DNTN_DTLS (
	DNTN_KEY NUMBER(19,0),
	ONCE_MBER_NO VARCHAR(10),
	CPR_DIV_CD VARCHAR(3),
	SETLE_CD VARCHAR(3),
	ONCE_CMPGN_CD VARCHAR(20),
	ELCTR_SETLE_KEY NUMBER(19,0),
	SETLE_ENTRPS_CD VARCHAR(10),
	SETLE_CMPNY_ACNT_NO NUMBER(10,0),
	MBRFEE_BNKB_KEY NUMBER(19,0),
	ACNUT_SER_NO NUMBER(10,0),
	FNLT_CD VARCHAR(10),
	PAYER_NM VARCHAR(30),
	PAY_AMT NUMBER(10,0),
	PAY_DE DATE,
	PAY_STAT_CD VARCHAR(3),
	PRCS_STAT_CD VARCHAR(3),
	USE_YN VARCHAR(1),
	TRNSFER_MBRFEE_KEY NUMBER(10,0),
	TRNSFER_RSN_CD VARCHAR(3),
	RETUN_DNTN_KEY NUMBER(19,0),
	RETUN_RSN_CD VARCHAR(3),
	RETUN_KEY NUMBER(10,0),
	RM VARCHAR(1000),
	ACMSLT_DEPT_CD VARCHAR(10),
	REGIST_DE DATE,
	RGSTR_ID VARCHAR(50),
	RGSTR_NM VARCHAR(30),
	SPNSR_BSNS_ID VARCHAR(20),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_PM_MBRFEE_ACMSLT (
	MBRFEE_KEY NUMBER(19,0),
	MBER_DIV_CD VARCHAR(3),
	MBER_NO VARCHAR(10),
	CPR_DIV_CD VARCHAR(3),
	SPNSR_NO VARCHAR(9),
	SPNSR_BSNS_NO NUMBER(19,0),
	SPNSR_BSNS_ID VARCHAR(20),
	RELATNSP_KEY NUMBER(10,0),
	OVSEA_AID_KEY NUMBER(10,0),
	MBRFEE_MT VARCHAR(6),
	MBRFEE_SQNC NUMBER(3,0),
	RQEST_MT VARCHAR(6),
	RQEST_SQNC NUMBER(3,0),
	MBRFEE_DIV_CD VARCHAR(3),
	GFT_DIV_CD VARCHAR(3),
	GFTMNEY_CHILD_CD NUMBER(10,0),
	ONCE_CMPGN_CD VARCHAR(20),
	TOGETH_WTDRW_REQUST_KEY NUMBER(10,0),
	TOGETH_WTDRW_YN VARCHAR(1),
	SETLE_KEY NUMBER(10,0),
	SETLE_CD VARCHAR(3),
	SETLE_ENTRPS_CD VARCHAR(10),
	PAYER_NM VARCHAR(30),
	RQEST_DIV_CD VARCHAR(3),
	RQEST_AMT NUMBER(19,0),
	RQEST_DE DATE,
	PAY_AMT NUMBER(10,0),
	PAY_DE DATE,
	PAY_STAT_CD VARCHAR(3),
	PRCS_STAT_CD VARCHAR(3),
	RQST_KEY NUMBER(19,0),
	RST_KEY NUMBER(19,0),
	ELCTR_SETLE_KEY NUMBER(19,0),
	SETLE_CMPNY_ACNT_NO NUMBER(10,0),
	MBRFEE_BNKB_KEY NUMBER(19,0),
	ACNUT_SER_NO NUMBER(10,0),
	FNLT_CD VARCHAR(10),
	BILLKEY VARCHAR(50),
	RQEST_RST_CD VARCHAR(50),
	PRCS_RST_CD VARCHAR(10),
	TRNSFER_REQUST_KEY NUMBER(10,0),
	TRNSFER_MBRFEE_KEY NUMBER(10,0),
	TRNSFER_DNTN_KEY NUMBER(10,0),
	TRNSFER_RSN_CD VARCHAR(3),
	RETUN_REQUST_KEY NUMBER(10,0),
	RETUN_MBRFEE_KEY NUMBER(10,0),
	RETUN_RSN_CD VARCHAR(3),
	RM VARCHAR(1000),
	USE_YN VARCHAR(1),
	OPERTOR_ID VARCHAR(100),
	OPERTOR_NM VARCHAR(100),
	OPERT_DE DATE,
	OPERT_DIV_CD VARCHAR(3),
	OPER_KEY NUMBER(10,0),
	OPER_RST_KEY NUMBER(10,0),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_PM_SETLE_INFO (
	SETLE_KEY NUMBER(10,0),
	MBER_NO VARCHAR(10),
	CPR_DIV_CD VARCHAR(3),
	SETLE_CD VARCHAR(3),
	WTDRW_STRT_DE DATE,
	WTDRW_ASMT_SQNC NUMBER(3,0),
	WTDRW_ASMT_SQNC_UPDT_DE DATE,
	FNLT_DIV_CD VARCHAR(3),
	FNLT_CD VARCHAR(10),
	SETLE_ENTRPS_CD VARCHAR(10),
	CARD_TRMVT VARCHAR(6),
	ACNUT_SER_NO NUMBER(10,0),
	PAYER_NM VARCHAR(30),
	CARD_DIV_CD VARCHAR(3),
	MBTLNUM VARCHAR(20),
	ETC_CTTPC VARCHAR(14),
	ETC_CTTPC_REL_CD VARCHAR(3),
	PAYER_MBER_REL_CD VARCHAR(3),
	CRTFC_MTH_CD VARCHAR(3),
	CRTFC_FILE_NM VARCHAR(200),
	CRTFC_DATA_CTNT VARCHAR(4000),
	CRTFC_DE DATE,
	FILE_SIZE NUMBER(10,0),
	BILLKEY VARCHAR(50),
	SETLE_STAT_CD VARCHAR(3),
	RQST_DIV_CD VARCHAR(3),
	RCEPT_DIV_CD VARCHAR(3),
	APRV_YN VARCHAR(1),
	APRV_REQUST_KEY NUMBER(19,0),
	APRV_RST_KEY NUMBER(19,0),
	FRST_BEGIN_DE DATE,
	RQEST_EXCL_YN VARCHAR(1),
	RQEST_EXCL_STRT_DE DATE,
	RQEST_EXCL_END_DE DATE,
	APPLCNT_NM VARCHAR(30),
	APPLCNT_MBTLNUM VARCHAR(20),
	APPLCNT_ETC_CTTPC VARCHAR(14),
	APPLCNT_ETC_CTTPC_REL_CD VARCHAR(3),
	APPLCNT_MBER_REL_CD VARCHAR(3),
	BF_SETLE_KEY NUMBER(10,0),
	OPERT_DIV_CD VARCHAR(3),
	CRTFC_TY_CD VARCHAR(3),
	USE_YN VARCHAR(1),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_RGSTR_NM VARCHAR(100),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDUSR_NM VARCHAR(100),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_RM_BPLC_MNG (
	BPLC_CD VARCHAR(8),
	NATION_CD VARCHAR(3),
	BPLC_KORNM VARCHAR(200),
	BPLC_ENGNM VARCHAR(200),
	BSNS_STRT_DE DATE,
	BSNS_END_DE DATE,
	RELATNSP_BSNS_YN VARCHAR(1),
	RELATNSP_BSNS_DSCNTC_DE DATE,
	GFTMNEY_PSBL_YN VARCHAR(1),
	LETTER_PSBL_YN VARCHAR(1),
	BPLC_DC VARCHAR(4000),
	WTWK_FROM_DSTNC NUMBER(10,0),
	CNCSN_RSN VARCHAR(100),
	BPLC_MTCHG_MNG_YN VARCHAR(1),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_UPDUSR_ID VARCHAR(30),
	LAST_UPDT_DT TIMESTAMP_NTZ(9),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_RM_CHILD_MSTR_INFO (
	CHILD_CD NUMBER(10,0),
	CHILD_NO VARCHAR(30),
	BPLC_CD VARCHAR(8),
	SEX VARCHAR(2),
	RELATNSP_STAT_CD VARCHAR(3),
	CHILD_STAT_CD VARCHAR(3),
	CHILD_DTL_STAT_CD VARCHAR(3),
	REGIST_DIV_CD VARCHAR(3),
	FRST_REGIST_DT TIMESTAMP_NTZ(9),
	LAST_REGIST_DT TIMESTAMP_NTZ(9),
	RE_UPDT_DT TIMESTAMP_NTZ(9),
	MNYRS_NATION_CD VARCHAR(3),
	CMS_CHILD_NO VARCHAR(30),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_RM_RELATNSP_CHG_INFO (
	RELATNSP_KEY NUMBER(10,0),
	CHG_YN VARCHAR(1),
	CHG_RSN_CD NUMBER(10,0),
	CHG_RST_CD NUMBER(10,0),
	CHG_PERSON_ID VARCHAR(20),
	CHG_DE DATE,
	CHG_RELATNSP_KEY NUMBER(10,0),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_RM_RELATNSP_GFTMNEY_INFO (
	RELATNSP_KEY NUMBER(10,0),
	MNG_NO VARCHAR(7),
	MBRFEE_KEY NUMBER(10,0),
	SETLE_DE DATE,
	SETLE_CD VARCHAR(3),
	SETLE_BANK_CD VARCHAR(10),
	GFTMNEY NUMBER(10,0),
	GFT_DIV_CD VARCHAR(3),
	KOREAN_RM_CTNT VARCHAR(1000),
	ENGL_RM_CTNT VARCHAR(1000),
	SNDNG_DE DATE,
	EHGT VARCHAR(30),
	GFTMNEY_DOLLAR_AMT VARCHAR(30),
	APRV_DE DATE,
	UNREPLY_RSN_CD NUMBER(10,0),
	TRNSFER_KEY NUMBER(10,0),
	TRNSFER_YN VARCHAR(1),
	TRNSFER_AFTER_RELATNSP_KEY NUMBER(10,0),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_RM_RELATNSP_LETTER_INFO (
	RELATNSP_KEY NUMBER(10,0),
	MNG_NO VARCHAR(7),
	LETTER_DIV_CD NUMBER(10,0),
	CTNT VARCHAR(4000),
	RCEPT_DE DATE,
	SNDNG_DE DATE,
	ONLINE_POST_WRITNG_YN VARCHAR(1),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DE DATE,
	EXCEL_SER_NO NUMBER(10,0),
	UNREPLY_RSN_CD NUMBER(10,0),
	LANG_CD VARCHAR(10),
	ONLINE_INFLOW_CD NUMBER(10,0),
	LETTER_STAT_CD NUMBER(3,0),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
create or replace TABLE GN_DW.BRONZE_CRM.TM_RM_RELATNSP_MSTR_INFO (
	RELATNSP_KEY NUMBER(10,0),
	SPNSR_NO VARCHAR(9),
	SPNSR_BSNS_NO NUMBER(19,0),
	CHILD_CD NUMBER(10,0),
	RELATNSP_STRT_DE DATE,
	RELATNSP_DSCNTC_DE DATE,
	RELATNSP_DSCNTC_YN VARCHAR(1),
	RELATNSP_DSCNTC_RSN_CD NUMBER(10,0),
	FRST_RGSTR_ID VARCHAR(30),
	FRST_REGIST_DE DATE,
	MBER_NO VARCHAR(10),
	_LOAD_DT TIMESTAMP_NTZ(9),
	_BATCH_ID VARCHAR(50)
);
*/
-- # A4
SELECT GET_DDL('SCHEMA', 'GN_DW.BRONZE_GA4', TRUE);
/*
create or replace schema GN_DW.BRONZE_GA4 with managed access COMMENT='원천 데이터 적재 - GA4 (웹/앱 방문, Google 광고)';

create or replace sequence GN_DW.BRONZE_GA4.SEQ_SYNC_ERR_INFO start with 1 increment by 1 noorder;
create or replace TABLE GN_DW.BRONZE_GA4.SYNC_ERR_INFO (
	ERR_SEQ NUMBER(38,0) DEFAULT GN_DW.BRONZE_GA4.SEQ_SYNC_ERR_INFO.NEXTVAL,
	ERR_DATETIME TIMESTAMP_NTZ(9),
	DATA_TYPE VARCHAR(16777216),
	ERR_INFO VARCHAR(16777216)
);
create or replace TABLE GN_DW.BRONZE_GA4."events_20260501" (
	"event_date" VARCHAR(16777216),
	"event_timestamp" NUMBER(38,0),
	"event_name" VARCHAR(16777216),
	"event_params" VARIANT,
	"event_previous_timestamp" NUMBER(38,0),
	"event_value_in_usd" FLOAT,
	"event_bundle_sequence_id" NUMBER(38,0),
	"event_server_timestamp_offset" NUMBER(38,0),
	"user_id" VARCHAR(16777216),
	"user_pseudo_id" VARCHAR(16777216),
	"privacy_info" VARIANT,
	"user_properties" VARIANT,
	"user_first_touch_timestamp" NUMBER(38,0),
	"user_ltv" VARIANT,
	"device" VARIANT,
	"geo" VARIANT,
	"app_info" NUMBER(38,0),
	"traffic_source" VARIANT,
	"stream_id" VARCHAR(16777216),
	"platform" VARCHAR(16777216),
	"event_dimensions" NUMBER(38,0),
	"ecommerce" VARIANT,
	"items" VARIANT,
	"collected_traffic_source" VARIANT,
	"is_active_user" BOOLEAN,
	"batch_event_index" NUMBER(38,0),
	"batch_page_id" NUMBER(38,0),
	"batch_ordering_id" NUMBER(38,0),
	"session_traffic_source_last_click" VARIANT,
	"publisher" NUMBER(38,0)
);
create or replace TABLE GN_DW.BRONZE_GA4."events_20260719" (
	"event_date" VARCHAR(16777216),
	"event_timestamp" NUMBER(38,0),
	"event_name" VARCHAR(16777216),
	"event_params" VARIANT,
	"event_previous_timestamp" NUMBER(38,0),
	"event_value_in_usd" FLOAT,
	"event_bundle_sequence_id" NUMBER(38,0),
	"event_server_timestamp_offset" NUMBER(38,0),
	"user_id" VARCHAR(16777216),
	"user_pseudo_id" VARCHAR(16777216),
	"privacy_info" VARIANT,
	"user_properties" VARIANT,
	"user_first_touch_timestamp" NUMBER(38,0),
	"user_ltv" VARIANT,
	"device" VARIANT,
	"geo" VARIANT,
	"app_info" NUMBER(38,0),
	"traffic_source" VARIANT,
	"stream_id" VARCHAR(16777216),
	"platform" VARCHAR(16777216),
	"event_dimensions" NUMBER(38,0),
	"ecommerce" VARIANT,
	"items" VARIANT,
	"collected_traffic_source" VARIANT,
	"is_active_user" BOOLEAN,
	"batch_event_index" NUMBER(38,0),
	"batch_page_id" NUMBER(38,0),
	"batch_ordering_id" NUMBER(38,0),
	"session_traffic_source_last_click" VARIANT,
	"publisher" NUMBER(38,0),
	"event_original_occurrence_timestamp" NUMBER(38,0)
);
CREATE OR REPLACE PROCEDURE GN_DW.BRONZE_GA4.SP_LOAD_BIGQUERY("INPUT_YYYYMMDD" VARCHAR DEFAULT null)
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.12'
PACKAGES = ('snowflake-snowpark-python','pandas','google-cloud-bigquery','google-cloud-bigquery-storage','google-auth','db-dtypes')
HANDLER = 'main'
IMPORTS = ('@GN_DW.BRONZE_GA4.CREDENTIALS_STAGE/gn_google_bq_service_account.json')
EXTERNAL_ACCESS_INTEGRATIONS = (GOOGLE_BQ_ACCESS_INTEGRATION)
EXECUTE AS CALLER
AS '
import json
import pandas
import os
import sys
from datetime import datetime, timedelta
from google.cloud import bigquery
from google.cloud import bigquery_storage
from google.oauth2 import service_account

def main(session, input_yyyymmdd=None):
    logs = []
    project_id = ''snowflakegdconnector''

    try:
        # input_yyyymmdd가 None인 경우 처리
        if input_yyyymmdd is None:
            yesterday = datetime.now() - timedelta(days=1)
            input_yyyymmdd = yesterday.strftime("%Y%m%d")
            logs.append(f"[안내] 시작일이 None이므로 실행 전날 날짜({input_yyyymmdd})로 대체합니다.")

        # 시작일의 날짜 형식 유효성 검사
        if len(str(input_yyyymmdd)) != 8:
            raise Exception(f"[오류] 날짜의 길이가 올바르지 않습니다. (입력값: {input_yyyymmdd})")
        try:
            current_date = datetime.strptime(str(input_yyyymmdd), "%Y%m%d")
        except ValueError:
            raise Exception(f"[오류] 잘못된 날짜 형식입니다. 실제 날짜로 변경 가능한지 확인하세요. 입력값: ({input_yyyymmdd})")

        # 서비스 계정 인증 및 BigQuery 클라이언트 생성 (IMPORTS 파일 사용)
        import_dir = sys._xoptions.get("snowflake_import_directory", "/tmp")
        sa_file_path = os.path.join(import_dir, ''gn_google_bq_service_account.json'')
        with open(sa_file_path, ''r'') as f:
            sa_info = json.load(f)
        credentials = service_account.Credentials.from_service_account_info(sa_info)

        bq_client = bigquery.Client(project=project_id, credentials=credentials)
        bqstorage_client = bigquery_storage.BigQueryReadClient(credentials=credentials)
        logs.append("빅쿼리 인증 성공 및 클라이언트 생성 완료!")

        # 대상 테이블 지정
        BQ_PROJECT_ID = "snowflakegdconnector"
        BQ_DATASET_ID = "todayreport_goodneighbors_ga4"
        BQ_TABLE_ID = f"events_{current_date.strftime(''%Y%m%d'')}"

        table_ref = f"{BQ_PROJECT_ID}.{BQ_DATASET_ID}.{BQ_TABLE_ID}"
        start_time = datetime.now()
        logs.append(f"{table_ref} 인입 시작 시간 : {start_time}")

        # Storage API를 사용하여 데이터프레임으로 변환
        df = bq_client.list_rows(table_ref).to_dataframe(bqstorage_client=bqstorage_client)

        # 6. Snowflake 적재
        session.write_pandas(
            df=df,
            database="GN_DW",
            schema="BRONZE_GA4",
            table_name=BQ_TABLE_ID,
            auto_create_table=True,
            overwrite=True
        )
        end_time = datetime.now()
        logs.append(f"{table_ref} 인입 종료 시간 : {end_time}")

    except Exception as global_err:
        try:
            error_msg = str(global_err).replace("''", "''''")
            error_query = f"INSERT INTO GN_DW.BRONZE_GA4.SYNC_ERR_INFO VALUES (CURRENT_TIMESTAMP(), ''{error_msg}'')"
            session.sql(error_query).collect()
        except:
            pass
        return f"ERROR: {str(global_err)}"

    logs.append("[완료] 데이터 적재가 정상적으로 완료되었습니다.")
    if not logs:
        return "결과가 없음"
    return "\\n".join(logs)
';
*/
-- # A5
SELECT GET_DDL('SCHEMA', 'GN_DW.BRONZE_ERP', TRUE);
/*
create or replace schema GN_DW.BRONZE_ERP with managed access COMMENT='원천 데이터 적재 - ERP (SMS/알림톡/마케팅 발송)';

create or replace TABLE GN_DW.BRONZE_ERP.BDGT_ACMSLT_LEDGER (
	YEAR VARCHAR(16777216) COMMENT '연도',
	INCOME_EXPS_DIV_NM VARCHAR(16777216) COMMENT '수지구분',
	BDGT_UNIT_NM VARCHAR(16777216) COMMENT '예산단위',
	JANG_NM VARCHAR(16777216) COMMENT '장',
	KWAN_NM VARCHAR(16777216) COMMENT '관',
	HANG_NM VARCHAR(16777216) COMMENT '항',
	MOK_NM VARCHAR(16777216) COMMENT '목',
	DTL_ITEM_NM VARCHAR(16777216) COMMENT '세목',
	SUBDTL_ITEM_NM VARCHAR(16777216) COMMENT '세세목',
	FUND_SOURCE_NM VARCHAR(16777216) COMMENT '재원',
	BDGT_ITEM_NM VARCHAR(16777216) COMMENT '예산과목',
	DVLP_INBOUND_PATH VARCHAR(16777216) COMMENT '개발인입경로',
	MNYRS_COST_DIV_YN VARCHAR(16777216) COMMENT '모금비구분',
	YEAR_BDGT_TOT_AMT NUMBER(38,0) COMMENT '연예산_합계',
	CHN_BDGT_TOT_AMT NUMBER(38,0) COMMENT '변경예산_합계',
	ADJ_BDGT_TOT_AMT NUMBER(38,0) COMMENT '조정예산_합계',
	EXEC_TOT_AMT NUMBER(38,0) COMMENT '집행금액_합계',
	YEAR_BDGT_AMT_1 NUMBER(38,0) COMMENT '연예산_01',
	CHN_BDGT_AMT_1 NUMBER(38,0) COMMENT '변경예산_01',
	ADJ_BDGT_AMT_1 NUMBER(38,0) COMMENT '조정예산_01',
	EXEC_AMT_1 NUMBER(38,0) COMMENT '집행금액_01',
	YEAR_BDGT_AMT_2 NUMBER(38,0) COMMENT '연예산_02',
	CHN_BDGT_AMT_2 NUMBER(38,0) COMMENT '변경예산_02',
	ADJ_BDGT_AMT_2 NUMBER(38,0) COMMENT '조정예산_02',
	EXEC_AMT_2 NUMBER(38,0) COMMENT '집행금액_02',
	YEAR_BDGT_AMT_3 NUMBER(38,0) COMMENT '연예산_03',
	CHN_BDGT_AMT_3 NUMBER(38,0) COMMENT '변경예산_03',
	ADJ_BDGT_AMT_3 NUMBER(38,0) COMMENT '조정예산_03',
	EXEC_AMT_3 NUMBER(38,0) COMMENT '집행금액_03',
	YEAR_BDGT_AMT_4 NUMBER(38,0) COMMENT '연예산_04',
	CHN_BDGT_AMT_4 NUMBER(38,0) COMMENT '변경예산_04',
	ADJ_BDGT_AMT_4 NUMBER(38,0) COMMENT '조정예산_04',
	EXEC_AMT_4 NUMBER(38,0) COMMENT '집행금액_04',
	YEAR_BDGT_AMT_5 NUMBER(38,0) COMMENT '연예산_05',
	CHN_BDGT_AMT_5 NUMBER(38,0) COMMENT '변경예산_05',
	ADJ_BDGT_AMT_5 NUMBER(38,0) COMMENT '조정예산_05',
	EXEC_AMT_5 NUMBER(38,0) COMMENT '집행금액_05',
	YEAR_BDGT_AMT_6 NUMBER(38,0) COMMENT '연예산_06',
	CHN_BDGT_AMT_6 NUMBER(38,0) COMMENT '변경예산_06',
	ADJ_BDGT_AMT_6 NUMBER(38,0) COMMENT '조정예산_06',
	EXEC_AMT_6 NUMBER(38,0) COMMENT '집행금액_06',
	YEAR_BDGT_AMT_7 NUMBER(38,0) COMMENT '연예산_07',
	CHN_BDGT_AMT_7 NUMBER(38,0) COMMENT '변경예산_07',
	ADJ_BDGT_AMT_7 NUMBER(38,0) COMMENT '조정예산_07',
	EXEC_AMT_7 NUMBER(38,0) COMMENT '집행금액_07',
	YEAR_BDGT_AMT_8 NUMBER(38,0) COMMENT '연예산_08',
	CHN_BDGT_AMT_8 NUMBER(38,0) COMMENT '변경예산_08',
	ADJ_BDGT_AMT_8 NUMBER(38,0) COMMENT '조정예산_08',
	EXEC_AMT_8 NUMBER(38,0) COMMENT '집행금액_08',
	YEAR_BDGT_AMT_9 NUMBER(38,0) COMMENT '연예산_09',
	CHN_BDGT_AMT_9 NUMBER(38,0) COMMENT '변경예산_09',
	ADJ_BDGT_AMT_9 NUMBER(38,0) COMMENT '조정예산_09',
	EXEC_AMT_9 NUMBER(38,0) COMMENT '집행금액_09',
	YEAR_BDGT_AMT_10 NUMBER(38,0) COMMENT '연예산_10',
	CHN_BDGT_AMT_10 NUMBER(38,0) COMMENT '변경예산_10',
	ADJ_BDGT_AMT_10 NUMBER(38,0) COMMENT '조정예산_10',
	EXEC_AMT_10 NUMBER(38,0) COMMENT '집행금액_10',
	YEAR_BDGT_AMT_11 NUMBER(38,0) COMMENT '연예산_11',
	CHN_BDGT_AMT_11 NUMBER(38,0) COMMENT '변경예산_11',
	ADJ_BDGT_AMT_11 NUMBER(38,0) COMMENT '조정예산_11',
	EXEC_AMT_11 NUMBER(38,0) COMMENT '집행금액_11',
	YEAR_BDGT_AMT_12 NUMBER(38,0) COMMENT '연예산_12',
	CHN_BDGT_AMT_12 NUMBER(38,0) COMMENT '변경예산_12',
	ADJ_BDGT_AMT_12 NUMBER(38,0) COMMENT '조정예산_12',
	EXEC_AMT_12 NUMBER(38,0) COMMENT '집행금액_12'
)COMMENT='예산 실적 원장'
;
CREATE OR REPLACE FILE FORMAT GN_DW.BRONZE_ERP.GN_CSV_FORMAT
	SKIP_HEADER = 1
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
;
CREATE OR REPLACE FILE FORMAT GN_DW.BRONZE_ERP.GN_CSV_FORMAT_EUCKR
	SKIP_HEADER = 2
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
	ENCODING = 'EUC-KR'
;
CREATE OR REPLACE PROCEDURE GN_DW.BRONZE_ERP.SP_LOAD_BUDGET_BY_YEAR("P_YEAR" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
DECLARE
    v_file_name VARCHAR;
    v_delete_sql VARCHAR;
    v_copy_sql VARCHAR;
BEGIN
    USE WAREHOUSE GN_DW_ETL_WH;
    -- P_YEAR YYYY 형태 검증 (4자리 숫자)
    IF (:P_YEAR IS NULL OR LENGTH(:P_YEAR) != 4 OR TRY_TO_NUMBER(:P_YEAR) IS NULL) THEN
        RETURN ''ERROR: P_YEAR는 YYYY 형태의 4자리 연도여야 합니다 (입력값: '' || NVL(:P_YEAR, ''NULL'') || '')'';
    END IF;

    -- 디렉터리 메타데이터 갱신
    ALTER STAGE GN_DW.BRONZE_ERP.CSV_UPLOAD_STAGE REFRESH;

    -- P_YEAR로 시작하고 _budget.csv로 끝나는 파일 중 가장 최근 업로드된 파일 선택
    SELECT RELATIVE_PATH INTO :v_file_name
    FROM DIRECTORY(@GN_DW.BRONZE_ERP.CSV_UPLOAD_STAGE)
    WHERE RELATIVE_PATH LIKE :P_YEAR || ''%_budget.csv''
    ORDER BY LAST_MODIFIED DESC
    LIMIT 1;

    IF (v_file_name IS NULL) THEN
        RETURN :P_YEAR || ''_budget.csv 패턴에 맞는 파일을 찾을 수 없습니다'';
    END IF;

    -- 해당 연도 기존 데이터 삭제
    v_delete_sql := ''DELETE FROM GN_DW.BRONZE_ERP.BDGT_ACMSLT_LEDGER WHERE YEAR = '''''' || :P_YEAR || '''''''';
    EXECUTE IMMEDIATE v_delete_sql;

    -- 해당 파일 데이터 적재
    v_copy_sql := ''
        COPY INTO GN_DW.BRONZE_ERP.BDGT_ACMSLT_LEDGER
        FROM (
            SELECT
                '''''' || :P_YEAR || '''''',$1,$2,$3,$4,
                $5,$6,$7,$8,$9,
                $10,$11,$12,
                NVL(TRY_TO_NUMBER(REPLACE($13, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($14, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($15, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($16, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($17, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($18, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($19, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($20, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($21, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($22, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($23, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($24, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($25, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($26, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($27, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($28, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($29, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($30, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($31, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($32, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($33, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($34, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($35, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($36, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($37, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($38, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($39, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($40, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($41, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($42, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($43, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($44, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($45, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($46, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($47, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($48, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($49, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($50, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($51, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($52, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($53, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($54, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($55, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($56, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($57, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($58, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($59, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($60, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($61, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($62, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($63, '''','''', '''''''')), 0),
                NVL(TRY_TO_NUMBER(REPLACE($64, '''','''', '''''''')), 0)
            FROM @GN_DW.BRONZE_ERP.CSV_UPLOAD_STAGE
            (FILE_FORMAT => ''''GN_DW.BRONZE_ERP.GN_CSV_FORMAT_EUCKR'''', PATTERN => ''''.*'' || v_file_name || '''''')
        ) FORCE = TRUE'';
    EXECUTE IMMEDIATE v_copy_sql;

    RETURN :P_YEAR || '': '' || v_file_name || '' 적재완료'';
END;
';
*/
-- # A6
SELECT GET_DDL('SCHEMA', 'GN_DW.BRONZE_AGENCY', TRUE);
/*
create or replace schema GN_DW.BRONZE_AGENCY with managed access COMMENT='원천 데이터 적재 - 대행사 (디지털/DRTV/재송출 광고)';

create or replace sequence GN_DW.BRONZE_AGENCY.SEQ_SYNC_ERR_INFO start with 1 increment by 1 noorder;
create or replace TABLE GN_DW.BRONZE_AGENCY.DGT_AD_CMPGN_DTLS (
	TIME VARCHAR(16777216) COMMENT '시간',
	YEAR VARCHAR(16777216) COMMENT '연도',
	CPR_NM VARCHAR(16777216) COMMENT '법인',
	DMST_OVSEA_DIV_NM VARCHAR(16777216) COMMENT '국내해외구분',
	BSNS_CASE_DIV_NM VARCHAR(16777216) COMMENT '사업사례구분',
	CMPGN_TY_NM VARCHAR(16777216) COMMENT '캠페인유형',
	AD_TY_NM VARCHAR(16777216) COMMENT '광고유형',
	MONTH VARCHAR(16777216) COMMENT '월',
	DEVICE VARCHAR(16777216) COMMENT '기기',
	MEDIA_NM VARCHAR(16777216) COMMENT '매체',
	WEEK VARCHAR(16777216) COMMENT '주차',
	DAY VARCHAR(16777216) COMMENT '일자',
	DOW VARCHAR(16777216) COMMENT '요일',
	CMPGN_NM VARCHAR(16777216) COMMENT '캠페인명',
	MATR VARCHAR(16777216) COMMENT '소재',
	MATR_TY_NM VARCHAR(16777216) COMMENT '소재유형',
	EXPS_CNT FLOAT COMMENT '노출수',
	CLICK_CNT FLOAT COMMENT '클릭수',
	GA_AD_COST FLOAT COMMENT '광고비',
	GA_CONV_MBER_CNT FLOAT COMMENT '후원자수(명)',
	CONV_VU_CNT FLOAT COMMENT '전환가치(건)',
	CPA FLOAT COMMENT 'CPA',
	DEV_UNIT_PRICE FLOAT COMMENT '개발단가',
	CTR FLOAT COMMENT 'CTR',
	CVR FLOAT COMMENT 'CVR',
	CPC FLOAT COMMENT 'CPC',
	CPM FLOAT COMMENT 'CPM',
	UPPER_CMPGN_NM VARCHAR(16777216) COMMENT '상위캠페인',
	READ_CNT FLOAT COMMENT '조회수',
	MEDIA_PTNT_CUST_CNT FLOAT COMMENT '잠재고객수(매체)',
	DATE DATE COMMENT '날짜',
	VTR FLOAT COMMENT 'VTR',
	PAGE_TYPE_NM VARCHAR(16777216) COMMENT '지면구분',
	CRM_DVLP_CNT FLOAT COMMENT 'CRM개발건수',
	AD_GRP_NM VARCHAR(16777216) COMMENT '광고그룹',
	GRP_DIV_NM VARCHAR(16777216) COMMENT '그룹구분'
)COMMENT='디지털 광고 성과 내역'
;
create or replace TABLE GN_DW.BRONZE_AGENCY.REBRDC_AD_CMPGN_DTLS (
	RE_BRDC_TY_NM VARCHAR(16777216) COMMENT '재송출유형',
	DIV_NM VARCHAR(16777216) COMMENT '구분',
	YEAR VARCHAR(16777216) COMMENT '년도',
	BRDC_MT VARCHAR(16777216) COMMENT '방송월',
	CHNNL_CMPNY VARCHAR(16777216) COMMENT '채널사',
	BRDC_NM VARCHAR(16777216) COMMENT '방송명',
	BRDC_DIV_NM VARCHAR(16777216) COMMENT '본방송구분',
	DATE DATE COMMENT '날짜',
	DOW VARCHAR(16777216) COMMENT '요일',
	BRDC_TIME VARCHAR(16777216) COMMENT '방송시간',
	INBOUND_CALL_CNT VARCHAR(16777216) COMMENT '인입콜',
	DVLP_MBER_CNT FLOAT COMMENT '회원개발(명)',
	DVLP_CNT FLOAT COMMENT '회원개발(건)',
	BRDC_SCHDL_COST FLOAT COMMENT '방송편성비',
	WEEK VARCHAR(16777216) COMMENT '주차',
	AD_CNT FLOAT COMMENT '횟수',
	TIME_RNG_DIV_NM VARCHAR(16777216) COMMENT '시간대구분',
	CELEB_NM VARCHAR(16777216) COMMENT '셀럽',
	DMST_OVSEA_DIV_NM VARCHAR(16777216) COMMENT '국내/해외구분',
	CASE1_BSNS_DIV_NM VARCHAR(16777216) COMMENT '사업구분1',
	CASE1_FAM_TY_NM VARCHAR(16777216) COMMENT '가정유형1',
	CASE1_APPEAL_POINT_NM VARCHAR(16777216) COMMENT '소구포인트1',
	CASE1_CHILD_NM VARCHAR(16777216) COMMENT '아동명1',
	CASE1_CASE_DIV_NM VARCHAR(16777216) COMMENT '사례구분1',
	CASE2_BSNS_DIV_NM VARCHAR(16777216) COMMENT '사업구분2',
	CASE2_FAM_TY_NM VARCHAR(16777216) COMMENT '가정유형2',
	CASE2_APPEAL_POINT_NM VARCHAR(16777216) COMMENT '소구포인트2',
	CASE2_CHILD_NM VARCHAR(16777216) COMMENT '아동명2',
	CASE2_CASE_DIV_NM VARCHAR(16777216) COMMENT '사례구분2',
	CASE3_BSNS_DIV_NM VARCHAR(16777216) COMMENT '사업구분3',
	CASE3_FAM_TY_NM VARCHAR(16777216) COMMENT '가정유형3',
	CASE3_APPEAL_POINT_NM VARCHAR(16777216) COMMENT '소구포인트3',
	CASE3_CHILD_NM VARCHAR(16777216) COMMENT '아동명3',
	CASE3_CASE_DIV_NM VARCHAR(16777216) COMMENT '사례구분3'
)COMMENT='재송출 광고 성과 내역'
;
create or replace TABLE GN_DW.BRONZE_AGENCY.SYNC_ERR_INFO (
	ERR_SEQ NUMBER(38,0) DEFAULT GN_DW.BRONZE_AGENCY.SEQ_SYNC_ERR_INFO.NEXTVAL,
	ERR_DATETIME TIMESTAMP_NTZ(9),
	DATA_TYPE VARCHAR(16777216),
	ERR_INFO VARCHAR(16777216)
);
create or replace TABLE GN_DW.BRONZE_AGENCY.VIDEO_AD_CMPGN_DTLS (
	CHNNL_NM VARCHAR(16777216) COMMENT '채널',
	DOW VARCHAR(16777216) COMMENT '요일',
	BRDC_DATE DATE COMMENT '방송일자',
	TIME_RNG VARCHAR(16777216) COMMENT '시간대',
	DAY_DIV_NM VARCHAR(16777216) COMMENT '주중/토/일',
	PRG_STRT_TIME VARCHAR(16777216) COMMENT '프로그램시작시간',
	SCHDL_NM VARCHAR(16777216) COMMENT '편성명',
	CM VARCHAR(16777216) COMMENT 'CM',
	CM_AREA VARCHAR(16777216) COMMENT 'CM위치',
	AD_STRT_TIME VARCHAR(16777216) COMMENT '광고시작시간',
	AD_END_TIME VARCHAR(16777216) COMMENT '광고종료시간',
	SPOT_TY VARCHAR(16777216) COMMENT 'SpotType',
	AD_VIEW_RT FLOAT COMMENT '광고시청률',
	AD_CNT NUMBER(38,0) COMMENT '횟수',
	AD_SEC VARCHAR(16777216) COMMENT '초수',
	ACTL_PUR_AD_COST_KRW NUMBER(38,0) COMMENT '실구매광고비(원)',
	INBOUND_CALL_CNT NUMBER(38,0) COMMENT '인입콜',
	CPC VARCHAR(16777216) COMMENT 'CPC',
	UPPER_CMPGN_NM VARCHAR(16777216) COMMENT '상위캠페인',
	MATR_NM VARCHAR(16777216) COMMENT '소재명',
	CMPGN_TY_NM VARCHAR(16777216) COMMENT '캠페인유형',
	DUR_PD_MATR_CHN VARCHAR(16777216) COMMENT '중도소재변경',
	CHNNL_CMPNY_TY_NM VARCHAR(16777216) COMMENT '채널사유형',
	WEEK VARCHAR(16777216) COMMENT '주차',
	CONV_CALL_CNT FLOAT COMMENT '전환콜',
	BRDC_MT VARCHAR(16777216) COMMENT '방송월',
	YEAR VARCHAR(16777216) COMMENT '해당연도',
	CTV_DIV_NM VARCHAR(16777216) COMMENT 'CTV 구분',
	MKT_CMPGN_NM VARCHAR(16777216) COMMENT '마케팅 캠페인명',
	SPNSR_BSNS_NM VARCHAR(16777216) COMMENT '후원사업구분',
	DMST_OVSEA_DIV_NM VARCHAR(16777216) COMMENT '캠페인유형(국내/해외)',
	BSNS_CASE_DIV_NM VARCHAR(16777216) COMMENT '캠페인유형(사업/사례)'
)COMMENT='영상 광고 성과 내역'
;
CREATE OR REPLACE FILE FORMAT GN_DW.BRONZE_AGENCY.GN_CSV_FORMAT
	SKIP_HEADER = 1
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
;
CREATE OR REPLACE PROCEDURE GN_DW.BRONZE_AGENCY.SP_LOAD_DGT_AD_FROM_GSHEET("INPUT_YYYYMM" VARCHAR DEFAULT null)
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.12'
PACKAGES = ('snowflake-snowpark-python','pandas','requests','pyjwt','cryptography')
HANDLER = 'main'
IMPORTS = ('@GN_DW.BRONZE_AGENCY.CREDENTIALS_STAGE/gn_google_service_account.json')
EXTERNAL_ACCESS_INTEGRATIONS = (GOOGLE_API_ACCESS)
EXECUTE AS CALLER
AS '
import sys
import os
import json
import time
import pandas
import requests
import jwt
from cryptography.hazmat.primitives import serialization
from datetime import datetime, timedelta

def get_google_access_token(sa_info):
    """서비스 계정 JSON으로 JWT를 생성하고 Google OAuth2 토큰을 발급받는다."""
    scopes = [
        ''https://www.googleapis.com/auth/drive.readonly'',
        ''https://www.googleapis.com/auth/spreadsheets.readonly''
    ]
    now = int(time.time())
    payload = {
        "iss": sa_info["client_email"],
        "scope": " ".join(scopes),
        "aud": "https://oauth2.googleapis.com/token",
        "iat": now,
        "exp": now + 3600
    }
    private_key = serialization.load_pem_private_key(
        sa_info["private_key"].encode(), password=None
    )
    encoded_jwt = jwt.encode(payload, private_key, algorithm="RS256")

    resp = requests.post(
        "https://oauth2.googleapis.com/token",
        data={
            "grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer",
            "assertion": encoded_jwt
        }
    )
    if resp.status_code != 200:
        raise Exception(f"Google OAuth2 토큰 발급 실패: {resp.status_code} - {resp.text}")
    return resp.json()["access_token"]


def drive_list_files(access_token, folder_id):
    """Google Drive API로 폴더 내 스프레드시트 파일 목록을 가져온다."""
    query = f"''{folder_id}'' in parents and mimeType=''application/vnd.google-apps.spreadsheet''"
    url = "https://www.googleapis.com/drive/v3/files"
    params = {
        "q": query,
        "fields": "files(id, name)",
        "supportsAllDrives": "true",
        "includeItemsFromAllDrives": "true"
    }
    headers = {"Authorization": f"Bearer {access_token}"}
    resp = requests.get(url, headers=headers, params=params)
    if resp.status_code != 200:
        raise Exception(f"Drive API 오류: {resp.status_code} - {resp.text}")
    return resp.json().get("files", [])


def sheets_get_metadata(access_token, spreadsheet_id):
    """스프레드시트의 시트(탭) 메타데이터를 가져온다."""
    url = f"https://sheets.googleapis.com/v4/spreadsheets/{spreadsheet_id}"
    params = {"fields": "sheets.properties"}
    headers = {"Authorization": f"Bearer {access_token}"}
    resp = requests.get(url, headers=headers, params=params)
    if resp.status_code != 200:
        raise Exception(f"Sheets metadata API 오류: {resp.status_code} - {resp.text}")
    return resp.json().get("sheets", [])


def sheets_get_values(access_token, spreadsheet_id, range_str):
    """스프레드시트의 특정 범위 값을 가져온다."""
    url = f"https://sheets.googleapis.com/v4/spreadsheets/{spreadsheet_id}/values/{range_str}"
    headers = {"Authorization": f"Bearer {access_token}"}
    resp = requests.get(url, headers=headers)
    if resp.status_code != 200:
        raise Exception(f"Sheets values API 오류: {resp.status_code} - {resp.text}")
    return resp.json().get("values", [])


def main(session, input_yyyymm=None):
    logs = []

    if not input_yyyymm:
        input_yyyymm = (datetime.now() - timedelta(days=1)).strftime(''%Y%m'')
    logs.append(f"[작업 기준월] {input_yyyymm} 데이터 수집 프로세스를 시작합니다.")

    try:
        table_name = ''DGT_AD_CMPGN_DTLS''
        # 구글 서비스 계정 인증 (JWT 방식)
        import_dir = sys._xoptions.get("snowflake_import_directory", "/tmp")
        sa_file_path = os.path.join(import_dir, "gn_google_service_account.json")
        with open(sa_file_path, ''r'') as f:
            sa_info = json.load(f)
        access_token = get_google_access_token(sa_info)
        logs.append(f"구글 API 인증 성공")

        # 구글 드라이브 파일 목록 가져오기
        folder_id = "1D0tCZdM0oquThfviLoLowC4eSuZexfvC"
        files = drive_list_files(access_token, folder_id)

        if not files:
            raise Exception("접근 가능한 스프레드시트 파일이 구글 드라이브에 존재하지 않습니다.")

        logs.append(f"총 {len(files)}개의 파일을 찾았습니다.")

        metadata_cache = {}
        FILTER_TARGET_COLUMN = "소재"
        HEADER_ROW_NUM = 3

        # 파일 목록 순회
        for file in files:
            file_id = file[''id'']
            file_name = file[''name'']
            logs.append(f"--- [파일명: {file_name}] (ID: {file_id}) ---")

            parts = file_name.split(''_'')
            if len(parts) < 2:
                logs.append(f"[-] 파일명 형식이 규칙에 맞지 않아 패스합니다. (구분자 ''_'' 부족)")
                continue

            file_type = parts[0].upper()
            file_yyyymm = parts[1]

            if input_yyyymm != file_yyyymm:
                logs.append(f"[-] 해당 월에 해당 안되는 파일 패스합니다. [파일명]: ''{file_name}''")
                continue
            if file_type != ''DIGITAL'' or input_yyyymm != file_yyyymm:
                raise Exception(f"파라미터 오류 [파일명]: ''{file_name}'' / [대상년월 파라미터] : {input_yyyymm}")

            # 메타데이터(컬럼 정보) 가져오기 (캐시 활용)
            if table_name not in metadata_cache:
                metadata_query = f"""
                    SELECT COLUMN_NAME, DATA_TYPE, COMMENT
                    FROM GN_DW.INFORMATION_SCHEMA.COLUMNS
                    WHERE TABLE_SCHEMA = ''BRONZE_AGENCY''
                        AND TABLE_NAME = ''{table_name}''
                    ORDER BY ORDINAL_POSITION
                """
                db_rows = session.sql(metadata_query).collect()
                if not db_rows:
                    raise Exception(f"Snowflake DB에 ''{table_name}'' 테이블이 없거나 컬럼 설정(메타데이터)이 존재하지 않습니다.")

                comment_to_eng_map = {}
                eng_col_to_type_map = {}

                for row in db_rows:
                    eng_col = row[''COLUMN_NAME''].strip().upper()
                    dtype = row[''DATA_TYPE''].strip().upper()
                    comment = row[''COMMENT''].strip().upper() if row[''COMMENT''] else eng_col

                    comment_to_eng_map[comment] = eng_col
                    eng_col_to_type_map[eng_col] = dtype

                db_all_columns_eng = [row[''COLUMN_NAME''].strip().upper() for row in db_rows]

                metadata_cache[table_name] = {
                    "map": comment_to_eng_map,
                    "types": eng_col_to_type_map,
                    "set": set(comment_to_eng_map.keys()),
                    "eng_cols": db_all_columns_eng
                }

            current_meta = metadata_cache[table_name]
            comment_to_eng_map = current_meta["map"]
            db_comments_set = current_meta["set"]
            db_all_columns_eng = current_meta["eng_cols"]
            eng_col_to_type_map = current_meta["types"]

            # 대상 월의 기존 데이터 삭제
            delete_query = f"DELETE FROM GN_DW.BRONZE_AGENCY.{table_name} WHERE TO_CHAR(DATE, ''YYYYMM'') = ''{input_yyyymm}''"
            delete_result = session.sql(delete_query).collect()
            deleted_cnt = delete_result[0][0] if delete_result else 0
            logs.append(f"기존 {input_yyyymm} 데이터 삭제 완료 ({deleted_cnt} 건 처리)")

            # 스프레드시트의 내부 탭(시트) 목록 조회
            sheets_list = sheets_get_metadata(access_token, file_id)

            for sheet in sheets_list:
                properties = sheet.get(''properties'', {})
                sheet_title = properties.get(''title'')

                if properties.get(''hidden'', False):
                    continue

                logs.append(f"  [탭 탐색] {sheet_title}")

                # 탭별 데이터 호출 (범위: B3부터 끝까지)
                range_str = f"''{sheet_title}''!B{HEADER_ROW_NUM}:ZZ"
                raw_values = sheets_get_values(access_token, file_id, range_str)

                if not raw_values or len(raw_values) < 2:
                    logs.append(f"  [-] [{sheet_title}] 유효한 데이터가 부족하여 패스합니다.")
                    continue

                # 헤더 정제 및 검증
                if not raw_values[0] or all(str(col).strip() == "" for col in raw_values[0]):
                    raise Exception(f"시트 헤더 정의 오류 파일: ''{file_name}'' -> 탭: ''{sheet_title}'' [원인] 헤더 행({HEADER_ROW_NUM}번째 행)")

                header_columns_clean = [
                    "".join(str(col).split()).upper()
                    for col in raw_values[0] if str(col).strip() != ""
                ]
                header_set = set(header_columns_clean)

                if not header_set.issubset(db_comments_set):
                    missing_cols = header_set - db_comments_set
                    raise Exception(f"DB 매핑 오류 파일: ''{file_name}'' -> 탭: ''{sheet_title}'' [원인] DB COMMENT에 정의되지 않은 컬럼: {list(missing_cols)}")

                # 필터링 기준 컬럼 인덱스 찾기
                target_upper = FILTER_TARGET_COLUMN.strip().upper()
                target_idx = -1
                if target_upper in header_columns_clean:
                    target_idx = header_columns_clean.index(target_upper)

                # 유령 행 및 특정 열 빈값 필터링
                valid_data_rows = []
                for offset, row in enumerate(raw_values[1:], start=1):
                    if not row or all(str(cell).strip() == "" for cell in row):
                        continue

                    if target_idx != -1:
                        if len(row) <= target_idx or str(row[target_idx]).strip() == "" or str(row[target_idx]).strip() == "-":
                            continue

                    actual_row_num = HEADER_ROW_NUM + offset
                    valid_data_rows.append((actual_row_num, row))

                if not valid_data_rows:
                    logs.append(f" [{sheet_title}] 적재할 유효한 행이 없습니다.")
                    continue

                # Pandas DataFrame 생성
                row_numbers = [r[0] for r in valid_data_rows]
                data_contents = [r[1] for r in valid_data_rows]

                df = pandas.DataFrame(data=data_contents, columns=header_columns_clean, index=row_numbers)

                # 데이터 타입별 전처리 및 로우 레벨 상세 예외 추적
                for col in df.columns:
                    if col not in comment_to_eng_map:
                        df[col] = None
                        continue

                    eng_col_name = comment_to_eng_map[col]
                    db_type = eng_col_to_type_map[eng_col_name]

                    df[col] = df[col].fillna("").astype(str).str.strip()
                    df[col] = df[col].apply(lambda x: "" if x.upper() in [''-'', ''NULL'', ''NAN''] else x)

                    if ''CHAR'' in db_type or ''TEXT'' in db_type:
                        df[col] = df[col].apply(lambda x: '''' if x == "" else x)

                    elif any(num_type in db_type for num_type in [''INT'', ''BIGINT'', ''NUMBER'', ''FLOAT'', ''DECIMAL'']):
                        df[col] = df[col].str.replace('','', '''', regex=False)

                        has_percent = df[col].str.contains(''%'', regex=False)
                        if has_percent.any():
                            df[col] = df[col].str.replace(''%'', '''', regex=False)
                            df[col] = df[col].apply(lambda x: ''0'' if x == "" else x)

                            for idx, val in df[col].items():
                                try:
                                    df.at[idx, col] = float(val) / 100
                                except ValueError:
                                    raise Exception(f"데이터 형변환 에러 파일: ''{file_name}'' -> 탭: ''{sheet_title}'' -> 행: [{idx}행] [원인] ''{col}'' 속성에 잘못된 퍼센트 값(''{val}%'')이 입력되었습니다. (DB 타입: {db_type})")
                        else:
                            df[col] = df[col].apply(lambda x: ''0'' if x == "" else x)

                            for idx, val in df[col].items():
                                try:
                                    if ''INT'' in db_type:
                                        df.at[idx, col] = int(float(val))
                                    else:
                                        df.at[idx, col] = float(val)
                                except ValueError:
                                    raise Exception(f"데이터 형변환 에러 [위치] 파일: ''{file_name}'' -> 탭: ''{sheet_title}'' -> 행: [{idx}행] [원인] ''{col}'' 속성에 숫자가 아닌 값(''{val}'')이 입력되었습니다. (DB 타입: {db_type})")

                # CMPGN_TY_NM 컬럼 분리
                if ''캠페인유형'' in df.columns:
                    split_data = df[''캠페인유형''].str.split('' '', n=1, expand=True)
                    df[''국내해외구분''] = split_data[0]
                    df[''사업사례구분''] = split_data[1] if len(split_data.columns) > 1 else ""

                # YEAR, MONTH, DAY 날짜 조합
                if all(col in df.columns for col in [''연도'', ''월'', ''일자'']):
                    if ''날짜'' not in df.columns:
                        clean_year = df[''연도''].astype(str).str.strip()
                        clean_month = df[''월''].astype(str).str.strip().str.zfill(2)
                        clean_day = df[''일자''].astype(str).str.strip().str.zfill(2)
                        df[''날짜''] = clean_year + ''-'' + clean_month + ''-'' + clean_day

                # 스키마 동기화 및 구조화
                df_eng_named = df.rename(columns=comment_to_eng_map)
                df_cleaned = df_eng_named.reindex(columns=db_all_columns_eng, fill_value=None)

                # 15. Snowflake 최종 적재 실행
                session.write_pandas(
                    df=df_cleaned,
                    database="GN_DW",
                    schema="BRONZE_AGENCY",
                    table_name=table_name,
                    overwrite=False
                )

                logs.append(f"  [성공] [{table_name}] 테이블에 적재 완료! {len(df_cleaned)} 행 인입!")

    except Exception as global_err:
        error_msg = str(global_err).replace("''", "''''")
        logs.append(f"[ERROR] {global_err}")

        try:
            error_query = f"INSERT INTO GN_DW.BRONZE_AGENCY.SYNC_ERR_INFO (ERR_DATETIME, DATA_TYPE, ERR_INFO) VALUES (CURRENT_TIMESTAMP(), ''디지털'', ''{error_msg}'')"
            session.sql(error_query).collect()
            logs.append("에러 로그 [SYNC_ERR_INFO]에 기록 완료.")
        except Exception as log_err:
            logs.append(f"에러 로그 DB 기록 실패: {log_err}")

        return "\\n".join(logs)

    logs.append("[완료] 모든 데이터 적재가 정상적으로 완료되었습니다.")
    return "\\n".join(logs)
';
CREATE OR REPLACE PROCEDURE GN_DW.BRONZE_AGENCY.SP_LOAD_REBRDC_FROM_SHAREPOINT()
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.12'
PACKAGES = ('snowflake-snowpark-python','pandas','requests')
HANDLER = 'main'
EXTERNAL_ACCESS_INTEGRATIONS = (MS_GRAPH_ACCESS)
EXECUTE AS CALLER
AS '
import pandas as pd
import requests

def main(session):
    log_messages = []
    table_name = ''REBRDC_AD_CMPGN_DTLS''

    try:
        # 설정 정보
        TENANT_ID = "7670f1d7-520b-47f5-b0ef-597be6581d8d"
        CLIENT_ID = "04b07795-8ddb-461a-bbee-02f9e1bf7b46"
        USERNAME = "sp_connector@gni.kr"
        PASSWORD = "J.733333642334us"
        SITE_ID = "gnikor.sharepoint.com,c2614570-b029-4496-a297-f68558cb87f0,83fbf0c7-cfc1-4332-88c9-1aa0be4d3dd8"
        ITEM_ID = "01TYTKR3XGYLL4L4FZHZH3CSTG2V7NZD4T"

        # 엑세스 토큰 발급
        token_res = requests.post(
            f"https://login.microsoftonline.com/{TENANT_ID}/oauth2/v2.0/token",
            data={
                "grant_type": "password",
                "client_id": CLIENT_ID,
                "username": USERNAME,
                "password": PASSWORD,
                "scope": "https://graph.microsoft.com/.default",
            },
        ).json()

        if "access_token" not in token_res:
            return f"ERROR: 토큰 획득 실패 - {token_res}"

        token = token_res["access_token"]
        headers = {"Authorization": f"Bearer {token}"}

        # 워크시트 목록 조회
        ws_res = requests.get(
            f"https://graph.microsoft.com/v1.0/sites/{SITE_ID}/drive/items/{ITEM_ID}/workbook/worksheets",
            headers=headers,
        )

        if ws_res.status_code != 200:
            raise Exception(f"워크시트 목록 조회 실패: {ws_res.json()}")

        worksheets = ws_res.json().get("value", [])
        if not worksheets:
            raise Exception("대상 엑셀 파일 내에 워크시트(탭)가 존재하지 않습니다.")

        # 메타데이터 조회
        metadata_query = f"""
            SELECT COLUMN_NAME, ORDINAL_POSITION, COMMENT
            FROM GN_DW.INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_SCHEMA = ''BRONZE_AGENCY''
              AND TABLE_NAME = ''{table_name}''
            ORDER BY ORDINAL_POSITION
        """
        db_rows = session.sql(metadata_query).collect()
        if not db_rows:
            raise Exception(f"''{table_name}'' 테이블 메타데이터 없음")

        comment_to_eng_map = {
            row["COMMENT"].strip().replace("\\n", "").replace(" ", "").upper(): row["COLUMN_NAME"].strip().upper()
            for row in db_rows
            if row["COMMENT"]
        }
        db_all_columns_eng = [row["COLUMN_NAME"].strip().upper() for row in db_rows]
        db_comments_set = set(comment_to_eng_map.keys())

        # 기존 데이터 삭제
        delete_result = session.sql(f"DELETE FROM GN_DW.BRONZE_AGENCY.{table_name}").collect()
        deleted_cnt = delete_result[0][0] if delete_result else 0
        log_messages.append(f"[삭제] 기존 {deleted_cnt}건 삭제 완료")

        # 대상 시트 순회 및 데이터 정제/적재
        TARGET_SHEET_NAMES = ["데이터관리 양식(특집)", "데이터관리 양식(재송출)"]

        for sheet in worksheets:
            sheet_name = sheet.get("name")

            if sheet_name not in TARGET_SHEET_NAMES:
                continue

            if sheet_name == ''데이터관리 양식(특집)'':
                TARGET_RANGE = "A2:CQ5000"
            else:
                TARGET_RANGE = "A2:AZ5000"

            data_res = requests.get(
                f"https://graph.microsoft.com/v1.0/sites/{SITE_ID}/drive/items/{ITEM_ID}/workbook/worksheets/{sheet_name}/range(address=''{TARGET_RANGE}'')",
                headers=headers,
            )

            if data_res.status_code != 200:
                log_messages.append(f"[-] ''{sheet_name}'' 데이터 조회 실패")
                continue

            all_rows = data_res.json().get("values", [])
            if not all_rows or len(all_rows) <= 1:
                log_messages.append(f"[-] ''{sheet_name}'' 데이터 없음")
                continue

            # DataFrame 변환
            header_cols = all_rows[0]
            data_rows = all_rows[1:]
            df = pd.DataFrame(data_rows, columns=header_cols)
            df = df.replace(r"^\\s*$", None, regex=True).infer_objects(copy=False)
            df = df[df["방송명"].astype(str).str.strip() != ""]
            df = df[df["날짜"].notna()]

            if df.empty:
                log_messages.append(f"[-] ''{sheet_name}'' 유효 데이터 없음")
                continue

            # ''사례구분3'' 이후 컬럼 제거
            col_list_clean = [str(c).replace("\\n", "").replace(" ", "").strip() for c in df.columns]
            target_col = "사례구분3"
            if target_col in col_list_clean:
                target_index = col_list_clean.index(target_col)
                columns_after_target = df.columns[target_index + 1:]
                if len(columns_after_target) > 0:
                    df.drop(columns=columns_after_target, errors="ignore", inplace=True)

            # 컬럼 정제
            columns_to_drop = []
            renamed_columns_map = {}

            for col in df.columns:
                col_str = str(col).strip()
                if "Unnamed:" in col_str:
                    columns_to_drop.append(col)
                    continue
                clean_col = col_str.replace("\\n", "").replace(" ", "").strip().upper()

                if col_str == "방송시간":
                    cleaned_values = []
                    for val in df[col]:
                        if pd.isnull(val) or val is None:
                            cleaned_values.append(None)
                        elif type(val).__name__ in [''time'', ''datetime'', ''date'']:
                            cleaned_values.append(val.strftime(''%H:%M:%S''))
                        else:
                            val_str = str(val).strip()
                            if val_str.replace(''.'', '''', 1).isdigit():
                                try:
                                    serial_f = float(val_str)
                                    if serial_f >= 0:
                                        total_seconds = round(serial_f * 24 * 3600)
                                        hours = total_seconds // 3600
                                        minutes = (total_seconds % 3600) // 60
                                        seconds = total_seconds % 60
                                        val_str = f"{hours:02d}:{minutes:02d}:{seconds:02d}"
                                except ValueError:
                                    pass
                            if " " in val_str and "-" in val_str and ":" in val_str:
                                val_str = val_str.split(" ")[1] if "1900-01-01" in val_str else val_str.split(" ")[0]
                            if val_str in [0, 1, ''0'', ''1'']:
                                val_str = "00:00:00" if val_str in [0, ''0''] else "24:00:00"
                            cleaned_values.append(val_str)
                    df[col] = cleaned_values

                elif col_str == "날짜":
                    cleaned_dates = []
                    for val in df[col]:
                        if pd.isnull(val) or val is None:
                            cleaned_dates.append(None)
                        elif type(val).__name__ in [''datetime'', ''date'']:
                            cleaned_dates.append(val.strftime(''%Y-%m-%d''))
                        else:
                            val_str = str(val).strip()
                            if val_str.replace(''.0'', '''', 1).isdigit():
                                try:
                                    excel_date = pd.to_datetime(float(val_str), unit=''D'', origin=''1899-12-30'')
                                    val_str = excel_date.strftime(''%Y-%m-%d'')
                                except Exception:
                                    pass
                            elif " " in val_str:
                                val_str = val_str.split(" ")[0]
                            cleaned_dates.append(val_str)
                    df[col] = cleaned_dates

                if clean_col in db_comments_set:
                    renamed_columns_map[col] = clean_col
                else:
                    columns_to_drop.append(col)

            if columns_to_drop:
                df.drop(columns=columns_to_drop, errors="ignore", inplace=True)
            df.rename(columns=renamed_columns_map, inplace=True)
            current_columns = [str(col) for col in df.columns]
            header_set = set(current_columns)

            if not header_set.issubset(db_comments_set):
                missing_cols = header_set - db_comments_set
                raise Exception(f"[검증 실패] DB COMMENT에 없는 컬럼: {list(missing_cols)}")

            df.columns = current_columns
            if ''본방송구분'' not in df.columns:
                df[''본방송구분''] = None
            df.rename(columns=comment_to_eng_map, inplace=True)

            if ''RE_BRDC_TY_NM'' not in df.columns:
                if sheet_name.upper() == ''데이터관리 양식(특집)'':
                    df.insert(loc=0, column=''RE_BRDC_TY_NM'', value=''특집'')
                else:
                    df.insert(loc=0, column=''RE_BRDC_TY_NM'', value=''재송출'')

            if ''INBOUND_CALL_CNT'' in df.columns:
                df[''INBOUND_CALL_CNT''] = df[''INBOUND_CALL_CNT''].fillna('''').astype(str)
                df[''INBOUND_CALL_CNT''] = df[''INBOUND_CALL_CNT''].apply(
                    lambda x: None if x in ['''', ''None'', ''NaN''] else x
                )

            # Snowflake 적재
            session.write_pandas(
                df=df,
                table_name=table_name,
                database="GN_DW",
                schema="BRONZE_AGENCY",
                overwrite=False
            )
            log_messages.append(f"[+] ''{sheet_name}'' {len(df)}건 적재 완료")

    except Exception as global_err:
        try:
            error_msg = str(global_err).replace("''", "''''")
            error_query = f"INSERT INTO GN_DW.BRONZE_AGENCY.SYNC_ERR_INFO (ERR_DATETIME, DATA_TYPE, ERR_INFO) VALUES (CURRENT_TIMESTAMP(), ''재송출'', ''{error_msg}'')"
            session.sql(error_query).collect()
        except:
            pass
        return f"ERROR: {str(global_err)}"

    if not log_messages:
        return "처리 결과 없음"
    return "\\n".join(log_messages)
';
CREATE OR REPLACE PROCEDURE GN_DW.BRONZE_AGENCY.SP_LOAD_VIDEO_AD_FROM_GDRIVE("INPUT_YYYYMM" VARCHAR DEFAULT null)
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = '3.12'
PACKAGES = ('snowflake-snowpark-python','pandas','openpyxl','requests','PyJWT','cryptography')
HANDLER = 'main'
IMPORTS = ('@GN_DW.BRONZE_AGENCY.CREDENTIALS_STAGE/gn_google_service_account.json')
EXTERNAL_ACCESS_INTEGRATIONS = (GOOGLE_API_ACCESS)
EXECUTE AS CALLER
AS '
import io
import json
import os
import sys
import time
import requests
import openpyxl
import pandas
import datetime as dt
from datetime import datetime, timedelta
import jwt
from cryptography.hazmat.primitives import serialization


def get_access_token(sa_info):
    now = int(time.time())
    payload = {
        "iss": sa_info["client_email"],
        "scope": "https://www.googleapis.com/auth/drive.readonly",
        "aud": "https://oauth2.googleapis.com/token",
        "iat": now,
        "exp": now + 3600
    }
    private_key = serialization.load_pem_private_key(
        sa_info["private_key"].encode(), password=None
    )
    encoded_jwt = jwt.encode(payload, private_key, algorithm="RS256")
    resp = requests.post("https://oauth2.googleapis.com/token", data={
        "grant_type": "urn:ietf:params:oauth:grant-type:jwt-bearer",
        "assertion": encoded_jwt
    })
    if resp.status_code != 200:
        raise Exception(f"Google OAuth2 토큰 발급 실패: {resp.status_code} - {resp.text}")
    return resp.json()["access_token"]


def drive_list_files(token, folder_id):
    q = f"''{folder_id}'' in parents and mimeType=''application/vnd.openxmlformats-officedocument.spreadsheetml.sheet''"
    resp = requests.get(
        "https://www.googleapis.com/drive/v3/files",
        headers={"Authorization": f"Bearer {token}"},
        params={
            "q": q,
            "fields": "files(id,name)",
            "supportsAllDrives": "true",
            "includeItemsFromAllDrives": "true"
        }
    )
    resp.raise_for_status()
    return resp.json().get("files", [])


def drive_download(token, file_id):
    resp = requests.get(
        f"https://www.googleapis.com/drive/v3/files/{file_id}?alt=media",
        headers={"Authorization": f"Bearer {token}"}
    )
    resp.raise_for_status()
    return io.BytesIO(resp.content)


def main(session, input_yyyymm=None):
    if not input_yyyymm:
        input_yyyymm = (datetime.now() - timedelta(days=1)).strftime(''%Y%m'')

    log_messages = []
    log_messages.append(f"[작업 기준월] {input_yyyymm} 데이터 수집 프로세스를 시작합니다.")
    try:
        # Google 인증 (스테이지에서 IMPORT한 JSON 파일 읽기)
        import_dir = sys._xoptions.get("snowflake_import_directory", "/tmp")
        sa_file_path = os.path.join(import_dir, "gn_google_service_account.json")
        with open(sa_file_path, ''r'') as f:
            sa_info = json.load(f)
        token = get_access_token(sa_info)
        log_messages.append(f"구글 API 인증 성공")
        
        # 대상 월 문자열 (예: "2026년 7월")
        try:
            target_yyyy = input_yyyymm[:4]
            target_mm = input_yyyymm[4:]
            clean_mm = str(int(target_mm))
            date_match_string = f"{target_yyyy}년 {clean_mm}월"
        except Exception as date_err:
            print(f"[-] input_yyyymm({input_yyyymm}) 파싱 중 오류 발생: {date_err}")
            raise Exception(f"input_yyyymm({input_yyyymm}) 파싱 중 오류 발생: {date_err}")
        # Google Drive 파일 목록
        folder_id = "1NO0ZAOWEoHjclENDrmzSzAgiWp7fNkLi"
        files = drive_list_files(token, folder_id)

        if not files:
            raise Exception("접근 가능한 엑셀(.xlsx) 파일이 없습니다.")

        log_messages.append(f"[+] 총 {len(files)}개 파일 발견")

        # 상수
        table_name = ''VIDEO_AD_CMPGN_DTLS''
        HEADER_ROW_NUM = 1
        metadata_cache = {}

        for file in files:
            file_id = file[''id'']
            file_name = file[''name'']

            if date_match_string not in file_name:
                log_messages.append(f"[-] 해당 월에 해당 안되는 파일 패스합니다. [파일명]: ''{file_name}''")
                continue

            try:
                # 메타데이터 캐시
                if table_name not in metadata_cache:
                    metadata_query = f"""
                        SELECT COLUMN_NAME, ORDINAL_POSITION, COMMENT
                        FROM GN_DW.INFORMATION_SCHEMA.COLUMNS
                        WHERE TABLE_SCHEMA = ''BRONZE_AGENCY''
                          AND TABLE_NAME = ''{table_name}''
                        ORDER BY ORDINAL_POSITION
                    """
                    db_rows = session.sql(metadata_query).collect()
                    if not db_rows:
                        log_messages.append(f"[-] ''{table_name}'' 메타데이터 없음")
                        raise Exception(f"[-] ''{table_name}'' 메타데이터 없음")

                    comment_to_eng_map = {}
                    db_comments_set_clean = set()
                    for row in db_rows:
                        if row[''COMMENT'']:
                            clean_comment = str(row[''COMMENT'']).replace("\\n", "").replace(" ", "").strip().upper()
                            comment_to_eng_map[clean_comment] = row[''COLUMN_NAME''].strip().upper()
                            db_comments_set_clean.add(clean_comment)

                    db_all_columns_eng = [row[''COLUMN_NAME''].strip().upper() for row in db_rows]
                    metadata_cache[table_name] = {
                        "map": comment_to_eng_map,
                        "set": db_comments_set_clean,
                        "eng_cols": db_all_columns_eng
                    }

                current_meta = metadata_cache[table_name]
                comment_to_eng_map = current_meta["map"].copy()
                db_comments_set_clean = current_meta["set"]
                db_all_columns_eng = current_meta["eng_cols"]

                # 기존 데이터 삭제
                delete_query = f"DELETE FROM GN_DW.BRONZE_AGENCY.{table_name} WHERE TO_CHAR(BRDC_DATE, ''YYYYMM'') = ''{input_yyyymm}''"
                delete_result = session.sql(delete_query).collect()
                deleted_cnt = delete_result[0][0] if delete_result else 0
                log_messages.append(f"[삭제] {input_yyyymm} 기존 {deleted_cnt}건 삭제")

                # 파일 다운로드
                file_stream = drive_download(token, file_id)

                wb = openpyxl.load_workbook(file_stream, read_only=True)
                sheet_names = [s for s in wb.sheetnames if wb[s].sheet_state == ''visible'']
                wb.close()

                for sheet_title in sheet_names:
                    if sheet_title != ''전체송출내역(집계용)'':
                        continue

                    file_stream.seek(0)
                    df_raw = pandas.read_excel(
                        file_stream,
                        sheet_name=sheet_title,
                        skiprows=HEADER_ROW_NUM,
                        usecols=lambda col_idx: 0 <= col_idx <= 25,
                        header=None
                    )

                    if df_raw.empty or len(df_raw) < 2:
                        continue

                    # 헤더 정제
                    header_columns_clean = []
                    header_counts = {}
                    for idx, col in enumerate(df_raw.iloc[0]):
                        if pandas.notnull(col) and str(col).strip().upper() != ''NAN'' and str(col).strip() != "":
                            clean_name = str(col).replace("\\n", "").replace(" ", "").strip().upper()
                        else:
                            clean_name = f"EMPTY_COL_{idx}"
                        if clean_name in header_counts:
                            header_counts[clean_name] += 1
                            header_columns_clean.append(f"{clean_name}_{header_counts[clean_name]}")
                        else:
                            header_counts[clean_name] = 0
                            header_columns_clean.append(clean_name)

                    header_set = {c.split(''_'')[0] for c in header_columns_clean if not c.startswith("EMPTY_COL_")}
                    if not header_set.issubset(db_comments_set_clean):
                        missing_cols = header_set - db_comments_set_clean
                        log_messages.append(f"[-] ''{file_name}'' 미정의 컬럼: {list(missing_cols)}")
                        continue

                    # 데이터 클렌징
                    df = df_raw.iloc[1:].dropna(how=''all'')
                    if df.empty:
                        continue
                    df.columns = header_columns_clean
                    df = df.astype(object).where(pandas.notnull(df), None)

                    # 캠페인유형 분리
                    if ''캠페인유형'' in df.columns:
                        split_data = df[''캠페인유형''].str.split('' '', n=1, expand=True)
                        df[''국내해외구분''] = split_data[0]
                        df[''사업사례구분''] = split_data[1] if split_data.shape[1] > 1 else ""

                    for col in header_columns_clean:
                        if col not in comment_to_eng_map:
                            comment_to_eng_map[col] = col

                    df_cleaned = df.rename(columns=comment_to_eng_map).reindex(columns=db_all_columns_eng, fill_value=None)

                    # PRG_STRT_TIME 정제
                    if ''PRG_STRT_TIME'' in df_cleaned.columns:
                        cleaned_times = []
                        for val in df_cleaned[''PRG_STRT_TIME'']:
                            val_str_raw = str(val).strip()
                            if val is None or val_str_raw in ['''', ''None'', ''NaN'', ''nat'', ''NaT'']:
                                cleaned_times.append(None)
                                continue
                            val_str = val_str_raw
                            if " " in val_str:
                                val_str = val_str.split(" ")[1]
                            cleaned_times.append(val_str)
                        df_cleaned[''PRG_STRT_TIME''] = cleaned_times

                    # BRDC_DATE 정제
                    if ''BRDC_DATE'' in df_cleaned.columns:
                        cleaned_dates = []
                        for val in df_cleaned[''BRDC_DATE'']:
                            val_str_raw = str(val).strip()
                            if val is None or val_str_raw in ['''', ''None'', ''NaN'', ''nat'', ''NaT'']:
                                cleaned_dates.append(None)
                                continue
                            val_str = val_str_raw
                            if " " in val_str:
                                val_str = val_str.split(" ")[0]
                            cleaned_dates.append(val_str)
                        df_cleaned[''BRDC_DATE''] = cleaned_dates

                    session.write_pandas(
                        df=df_cleaned,
                        database="GN_DW",
                        schema="BRONZE_AGENCY",
                        table_name=table_name,
                        overwrite=False
                    )
                    log_messages.append(f"[+] ''{file_name}'' [{sheet_title}] {len(df_cleaned)}건 적재 완료")

            except Exception as file_err:
                log_messages.append(f"[-] ''{file_name}'' 오류: {str(file_err)}")
                raise Exception(f"input_yyyymm({input_yyyymm}) 파싱 중 오류 발생: {file_err}")

    except Exception as global_err:
        try:
            error_msg = str(global_err).replace("''", "''''")
            error_query = f"INSERT INTO GN_DW.BRONZE_AGENCY.SYNC_ERR_INFO (ERR_DATETIME, DATA_TYPE, ERR_INFO) VALUES (CURRENT_TIMESTAMP(), ''영상매체'', ''{error_msg}'')"
            session.sql(error_query).collect()
        except:
            pass
        return f"ERROR: {str(global_err)}"

    if not log_messages:
        return f"''{date_match_string}'' 결과가 없음"
    return "\\n".join(log_messages)
';
*/