------------------------------------------------------
-- 2. 유저 & Role 세팅
------------------------------------------------------
USE ROLE SECURITYADMIN;

-- 2.1 Role 생성
CREATE ROLE IF NOT EXISTS GN_DW_ADMIN
    COMMENT = 'GN_DW DB 관리자 - DDL, 스키마 관리';

CREATE ROLE IF NOT EXISTS GN_DW_ENGINEER
    COMMENT = 'ETL 개발 - 프로시저, 태스크 운영';

CREATE ROLE IF NOT EXISTS GN_DW_ANALYST
    COMMENT = '분석가 - SELECT on SILVER/GOLD';

CREATE ROLE IF NOT EXISTS GN_DW_VIEWER
    COMMENT = '읽기 전용 - GOLD만 접근';

CREATE ROLE IF NOT EXISTS GN_DW_LOADER
    COMMENT = '외부팀 적재 - BRONZE 쓰기 전용';

CREATE ROLE IF NOT EXISTS GN_DW_SERVICE
    COMMENT = '서비스 계정 - API, Streamlit 등';

-- 2.2 Role 계층 구조 설정
GRANT ROLE GN_DW_VIEWER   TO ROLE GN_DW_ANALYST;
GRANT ROLE GN_DW_ANALYST  TO ROLE GN_DW_ADMIN;
GRANT ROLE GN_DW_ENGINEER TO ROLE GN_DW_ADMIN;
GRANT ROLE GN_DW_LOADER   TO ROLE GN_DW_ADMIN;
GRANT ROLE GN_DW_SERVICE  TO ROLE GN_DW_ADMIN;
GRANT ROLE GN_DW_ADMIN    TO ROLE SYSADMIN;

-- 2.3 Warehouse 사용 권한 (Role별 할당)
GRANT USAGE ON WAREHOUSE GN_DW_ETL_WH       TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON WAREHOUSE GN_DW_ETL_WH       TO ROLE GN_DW_LOADER;
GRANT USAGE ON WAREHOUSE GN_DW_DEV_WH       TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON WAREHOUSE GN_DW_DEV_WH       TO ROLE GN_DW_ADMIN;
GRANT USAGE ON WAREHOUSE GN_DW_ANALYTICS_WH TO ROLE GN_DW_ANALYST;
GRANT USAGE ON WAREHOUSE GN_DW_ANALYTICS_WH TO ROLE GN_DW_VIEWER;
GRANT USAGE ON WAREHOUSE GN_DW_ANALYTICS_WH TO ROLE GN_DW_SERVICE;

-- 2.4 태스크/프로시저 실행 권한 (ACCOUNTADMIN으로 실행)
USE ROLE ACCOUNTADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE GN_DW_ENGINEER;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE GN_DW_ENGINEER;
USE ROLE SECURITYADMIN;

-- 2.5 유저 생성 템플릿 (실제 유저 정보로 교체하여 사용)

-- 엔지니어 유저 예시
-- CREATE USER IF NOT EXISTS GN_ENGINEER_01
--     PASSWORD = '<초기비밀번호>'
--     DEFAULT_ROLE = 'GN_DW_ENGINEER'
--     DEFAULT_WAREHOUSE = 'GN_DW_DEV_WH'
--     DEFAULT_NAMESPACE = 'GN_DW.BRONZE'
--     MUST_CHANGE_PASSWORD = TRUE
--     COMMENT = '데이터 엔지니어';
-- GRANT ROLE GN_DW_ENGINEER TO USER GN_ENGINEER_01;

-- 분석가 유저 예시
-- CREATE USER IF NOT EXISTS GN_ANALYST_01
--     PASSWORD = '<초기비밀번호>'
--     DEFAULT_ROLE = 'GN_DW_ANALYST'
--     DEFAULT_WAREHOUSE = 'GN_DW_ANALYTICS_WH'
--     DEFAULT_NAMESPACE = 'GN_DW.GOLD'
--     MUST_CHANGE_PASSWORD = TRUE
--     COMMENT = '데이터 분석가';
-- GRANT ROLE GN_DW_ANALYST TO USER GN_ANALYST_01;

-- 외부팀(BRONZE 적재) 유저 예시
-- CREATE USER IF NOT EXISTS GN_LOADER_01
--     PASSWORD = '<초기비밀번호>'
--     DEFAULT_ROLE = 'GN_DW_LOADER'
--     DEFAULT_WAREHOUSE = 'GN_DW_ETL_WH'
--     DEFAULT_NAMESPACE = 'GN_DW.BRONZE'
--     MUST_CHANGE_PASSWORD = TRUE
--     COMMENT = '데이터 적재 담당 (외부팀)';
-- GRANT ROLE GN_DW_LOADER TO USER GN_LOADER_01;
