------------------------------------------------------
-- 6. 테스트
------------------------------------------------------
-- 권한/Warehouse 매핑(02_유저_Role_세팅.sql 기준):
--   ENGINEER·LOADER → GN_DW_ETL_WH,  ANALYST·VIEWER → GN_DW_ANALYTICS_WH,  ADMIN → GN_DW_DEV_WH
--   Role 전환 시 해당 Role이 USAGE 보유한 Warehouse로 반드시 함께 전환해야 함
--   (그렇지 않으면 권한 부족이 아닌 Warehouse 접근 오류로 테스트가 잘못 실패함)
USE SECONDARY ROLES NONE;

-- [사전 준비] 6.1의 SILVER SELECT 테스트는 SILVER 테이블이 존재해야 동작함
--   아래 정제 프로시저를 먼저 1회 실행 (이미 6.2 E2E를 수행했다면 생략 가능)
USE ROLE GN_DW_ENGINEER;
USE WAREHOUSE GN_DW_ETL_WH;
CALL GN_DW.SILVER.SP_RUN_ALL_REFINEMENT(); -- 기대: 'ALL REFINEMENT COMPLETED SUCCESSFULLY'

------------------------------------------------------
-- 6.1 권한 테스트
------------------------------------------------------

-- [TEST] GN_DW_ENGINEER: BRONZE SELECT 가능
USE ROLE GN_DW_ENGINEER;
USE WAREHOUSE GN_DW_ETL_WH;
SELECT COUNT(*) FROM GN_DW.BRONZE.DIM_CAMPAIGN_CODE; -- 기대: 성공

-- [TEST] GN_DW_ANALYST: BRONZE SELECT 불가
USE ROLE GN_DW_ANALYST;
USE WAREHOUSE GN_DW_ANALYTICS_WH;
SELECT COUNT(*) FROM GN_DW.BRONZE.DIM_CAMPAIGN_CODE; -- 기대: 에러 (Insufficient privileges)

-- [TEST] GN_DW_LOADER: BRONZE INSERT 가능
USE ROLE GN_DW_LOADER;
USE WAREHOUSE GN_DW_ETL_WH;
INSERT INTO GN_DW.BRONZE.DIM_MEMBER_ATTRIBUTE VALUES ('TEST001', '남', '30대', '서울');
-- 기대: 성공. 테스트 데이터 정리는 ENGINEER Role로 실행

-- [TEST] GN_DW_ANALYST: BRONZE INSERT 불가
USE ROLE GN_DW_ANALYST;
USE WAREHOUSE GN_DW_ANALYTICS_WH;
INSERT INTO GN_DW.BRONZE.DIM_MEMBER_ATTRIBUTE VALUES ('TEST002', '여', '20대', '부산');
-- 기대: 에러 (Insufficient privileges)

-- [정리] 테스트 데이터 삭제 (ADMIN으로 실행)
USE ROLE GN_DW_ADMIN;
USE WAREHOUSE GN_DW_DEV_WH;
DELETE FROM GN_DW.BRONZE.DIM_MEMBER_ATTRIBUTE WHERE "회원번호" = 'TEST001';

-- [TEST] GN_DW_ANALYST: SILVER SELECT 가능
USE ROLE GN_DW_ANALYST;
USE WAREHOUSE GN_DW_ANALYTICS_WH;
SELECT COUNT(*) FROM GN_DW.SILVER.DIM_MEMBER_ATTRIBUTE; -- 기대: 성공

-- [TEST] GN_DW_VIEWER: SILVER SELECT 불가 (GOLD만 접근)
USE ROLE GN_DW_VIEWER;
USE WAREHOUSE GN_DW_ANALYTICS_WH;
SELECT COUNT(*) FROM GN_DW.SILVER.DIM_MEMBER_ATTRIBUTE; -- 기대: 에러

-- [TEST] GN_DW_VIEWER: GOLD SELECT 가능
USE ROLE GN_DW_VIEWER;
USE WAREHOUSE GN_DW_ANALYTICS_WH;
SELECT COUNT(*) FROM GN_DW.GOLD.V_PAYMENT_ANALYSIS; -- 기대: 성공

-- [TEST] GN_DW_VIEWER: GOLD CREATE VIEW 불가
USE ROLE GN_DW_VIEWER;
USE WAREHOUSE GN_DW_ANALYTICS_WH;
CREATE VIEW GN_DW.GOLD.V_TEST AS SELECT 1 AS COL; -- 기대: 에러

-- [TEST] GN_DW_ANALYST: Semantic View 사용 가능
USE ROLE GN_DW_ANALYST;
USE WAREHOUSE GN_DW_ANALYTICS_WH;
-- Semantic View는 Agent/CoWork 통해 사용, USAGE 확인:
SHOW SEMANTIC VIEWS IN SCHEMA GN_DW.GOLD; -- 기대: 목록 표시

-- [TEST] GN_DW_VIEWER: Agent 사용 가능
USE ROLE GN_DW_VIEWER;
USE WAREHOUSE GN_DW_ANALYTICS_WH;
SHOW AGENTS IN SCHEMA GN_DW.GOLD; -- 기대: GN_DW_AGENT 표시

-- [TEST] GN_DW_LOADER: Agent 사용 불가
USE ROLE GN_DW_LOADER;
USE WAREHOUSE GN_DW_ETL_WH;
SHOW AGENTS IN SCHEMA GN_DW.GOLD; -- 기대: 에러 또는 빈 목록

------------------------------------------------------
-- 6.2 파이프라인 E2E 테스트
------------------------------------------------------
USE ROLE GN_DW_ENGINEER;
USE WAREHOUSE GN_DW_ETL_WH;

-- Step 1: BRONZE에 샘플 데이터 존재 확인
SELECT 'DIM_CAMPAIGN_CODE' AS TBL, COUNT(*) AS CNT FROM GN_DW.BRONZE.DIM_CAMPAIGN_CODE
UNION ALL
SELECT 'FACT_PAYMENT_HISTORY', COUNT(*) FROM GN_DW.BRONZE.FACT_PAYMENT_HISTORY
UNION ALL
SELECT 'FACT_MEMBER_DEV_ALL', COUNT(*) FROM GN_DW.BRONZE.FACT_MEMBER_DEV_ALL;

-- Step 2: 정제 프로시저 실행
CALL GN_DW.SILVER.SP_RUN_ALL_REFINEMENT();
-- 기대: 'ALL REFINEMENT COMPLETED SUCCESSFULLY'

-- Step 3: SILVER 테이블 생성 확인
SELECT 'DIM_CAMPAIGN_CODE' AS TBL, COUNT(*) AS CNT FROM GN_DW.SILVER.DIM_CAMPAIGN_CODE
UNION ALL
SELECT 'FACT_PAYMENT_HISTORY', COUNT(*) FROM GN_DW.SILVER.FACT_PAYMENT_HISTORY
UNION ALL
SELECT 'FACT_MEMBER_DEV_ALL', COUNT(*) FROM GN_DW.SILVER.FACT_MEMBER_DEV_ALL;

-- Step 4: GOLD View 조회 확인
SELECT COUNT(*) AS PAYMENT_VIEW_CNT FROM GN_DW.GOLD.V_PAYMENT_ANALYSIS;
SELECT COUNT(*) AS MEMBER_DEV_CNT FROM GN_DW.GOLD.V_MEMBER_DEV_DETAIL;

-- Step 5: ETL_LOG 확인
SELECT * FROM GN_DW.SILVER.ETL_LOG ORDER BY STARTED_AT DESC LIMIT 10;

-- Step 6: 태스크 수동 실행 (선택) - Root 실행 시 전체 DAG(VALIDATE→REFINEMENT→FORECAST→FINALIZER) 트리거
-- EXECUTE TASK GN_DW.SILVER.TASK_VALIDATE_BRONZE;
-- 실행 후 확인 (Root 기준 그래프 실행 이력):
-- SELECT * FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(TASK_NAME => 'TASK_VALIDATE_BRONZE')) ORDER BY SCHEDULED_TIME DESC LIMIT 10;
-- 또는 그래프 전체 이력:
-- SELECT * FROM TABLE(INFORMATION_SCHEMA.COMPLETE_TASK_GRAPHS()) ORDER BY SCHEDULED_TIME DESC LIMIT 5;

------------------------------------------------------
-- 6.3 데이터 정합성 검증
------------------------------------------------------

-- Row count 비교: BRONZE vs SILVER
SELECT
    'DIM_CAMPAIGN_CODE' AS TABLE_NAME,
    (SELECT COUNT(*) FROM GN_DW.BRONZE.DIM_CAMPAIGN_CODE) AS BRONZE_CNT,
    (SELECT COUNT(*) FROM GN_DW.SILVER.DIM_CAMPAIGN_CODE) AS SILVER_CNT
UNION ALL
SELECT
    'DIM_MEMBER_ATTRIBUTE',
    (SELECT COUNT(*) FROM GN_DW.BRONZE.DIM_MEMBER_ATTRIBUTE),
    (SELECT COUNT(*) FROM GN_DW.SILVER.DIM_MEMBER_ATTRIBUTE)
UNION ALL
SELECT
    'FACT_PAYMENT_HISTORY',
    (SELECT COUNT(*) FROM GN_DW.BRONZE.FACT_PAYMENT_HISTORY),
    (SELECT COUNT(*) FROM GN_DW.SILVER.FACT_PAYMENT_HISTORY)
UNION ALL
SELECT
    'FACT_MEMBER_DEV_ALL',
    (SELECT COUNT(*) FROM GN_DW.BRONZE.FACT_MEMBER_DEV_ALL),
    (SELECT COUNT(*) FROM GN_DW.SILVER.FACT_MEMBER_DEV_ALL)
UNION ALL
SELECT
    'FACT_DISCONTINUED_MEMBER',
    (SELECT COUNT(*) FROM GN_DW.BRONZE.FACT_DISCONTINUED_MEMBER),
    (SELECT COUNT(*) FROM GN_DW.SILVER.FACT_DISCONTINUED_MEMBER);

-- NULL PK 체크: SILVER 테이블 핵심 키 컬럼
SELECT 'SILVER.DIM_CAMPAIGN_CODE' AS TBL,
       SUM(CASE WHEN "세부캠페인코드" IS NULL THEN 1 ELSE 0 END) AS NULL_KEY_CNT
FROM GN_DW.SILVER.DIM_CAMPAIGN_CODE
UNION ALL
SELECT 'SILVER.DIM_MEMBER_ATTRIBUTE',
       SUM(CASE WHEN "회원번호" IS NULL THEN 1 ELSE 0 END)
FROM GN_DW.SILVER.DIM_MEMBER_ATTRIBUTE
UNION ALL
SELECT 'SILVER.FACT_PAYMENT_HISTORY',
       SUM(CASE WHEN "회원번호" IS NULL THEN 1 ELSE 0 END)
FROM GN_DW.SILVER.FACT_PAYMENT_HISTORY;

-- 타입 캐스팅 검증: DATE 변환 실패율
SELECT
    '납입일자 NULL' AS CHECK_ITEM,
    ROUND(SUM(CASE WHEN "납입일자" IS NULL AND "납입일" IS NOT NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS FAIL_PCT
FROM GN_DW.SILVER.FACT_PAYMENT_HISTORY
UNION ALL
SELECT
    '후원신청일자 NULL',
    ROUND(SUM(CASE WHEN "후원신청일자" IS NULL AND "후원신청일" IS NOT NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2)
FROM GN_DW.SILVER.FACT_MEMBER_DEV_ALL
UNION ALL
SELECT
    '가입일자 NULL',
    ROUND(SUM(CASE WHEN "가입일자" IS NULL AND "가입일" IS NOT NULL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2)
FROM GN_DW.SILVER.FACT_DISCONTINUED_MEMBER;

-- Semantic View + Agent 동작 테스트
-- (CoWork에서 Agent에 질문하여 SQL 생성/결과 반환 확인)
-- 예: "2025년 상위캠페인별 총납입금액을 알려줘"
