-- CRM_SEND_REQUEST: 발송요청 마스터 = EMAIL ∪ MSG_AT ∪ PSTMTR ∪ SND (채널별 dedup), 정본 09 STEP3.
-- Co-authored with CoCo
-- [2026-08-03 G3] 정본 코드컬럼 raw 전파 3종 신설. 채널별로 원천 컬럼 보유가 다르므로 미보유 채널은 NULL 이다.
--   MSG_DIV_CD(MS010)·SNDNG_TIME_DIV_CD(MS267) = MSG_AT 전용 · PSTMTR_PRCS_STAT_CD(MS061) = PSTMTR 전용.
--   ⚠️ 0 이나 '' 로 채우지 않는다 — 채널에 개념이 부재한 것이므로 NULL 이 정확하다(P21).
--   [O26] PSTMTR 접두 = 원천 테이블 TM_MS_PSTMTR_SNDNG 변별토큰. CRM_PAYMENT_BILLING.MBRFEE_PRCS_STAT_CD(PM013)와
--   동명이의였다 — 실측 도메인 0,1 vs R,F,S 로 완전 분리. 라벨은 수요 확인 후 별도 배선(스캐폴드 금지).
SELECT SNDNG_KEY AS SNDNG_KEY, 'EMAIL' AS SEND_CHANNEL, NULLIF(TRIM(SNDNG_TY_CD),'') AS SNDNG_TY_CD,
  NULL AS SEND_GBN_TOP, NULL AS SEND_GBN_TOP_NM, NULL AS SEND_GBN_MID, NULL AS SEND_GBN_MID_NM,
  NULL AS SEND_GBN_BOT, NULL AS SEND_GBN_BOT_NM,
  NULLIF(TRIM(TIT),'') AS TIT, SNDNG_STDR_DE::TIMESTAMP_NTZ AS SNDNG_STDR_DE, NULL AS REQ_SEQ_NO,
  CAST(NULL AS VARCHAR) AS MSG_DIV_CD, CAST(NULL AS VARCHAR) AS PSTMTR_PRCS_STAT_CD, CAST(NULL AS VARCHAR) AS SNDNG_TIME_DIV_CD,
  'CRM' AS DW_SOURCE_SYSTEM, 'BRONZE_CRM.TM_MS_EMAIL_SNDNG' AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP() AS DW_LOAD_TS, CURRENT_TIMESTAMP() AS DW_UPDATE_TS, NULL AS DW_BATCH_ID
FROM {{ source('bronze_crm','TM_MS_EMAIL_SNDNG') }} WHERE SNDNG_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY SNDNG_KEY ORDER BY SNDNG_STDR_DE DESC NULLS LAST)=1
UNION ALL
SELECT SNDNG_KEY,'MSG_AT',NULLIF(TRIM(SNDNG_TY_CD),''), NULL,NULL,NULL,NULL,NULL,NULL,
  NULLIF(TRIM(TIT),''),SNDNG_STDR_DE::TIMESTAMP_NTZ,NULL,
  NULLIF(TRIM(MSG_DIV_CD),''), NULL, NULLIF(TRIM(SNDNG_TIME_DIV_CD),''),
  'CRM','BRONZE_CRM.TM_MS_MSG_AT_SNDNG',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM {{ source('bronze_crm','TM_MS_MSG_AT_SNDNG') }} WHERE SNDNG_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY SNDNG_KEY ORDER BY SNDNG_STDR_DE DESC NULLS LAST)=1
UNION ALL
SELECT SNDNG_KEY,'PSTMTR',NULLIF(TRIM(SNDNG_TY_CD),''), NULL,NULL,NULL,NULL,NULL,NULL,
  NULL,SNDNG_STDR_DE::TIMESTAMP_NTZ,NULL,
  NULL, NULLIF(TRIM(PRCS_STAT_CD),''), NULL,
  'CRM','BRONZE_CRM.TM_MS_PSTMTR_SNDNG',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM {{ source('bronze_crm','TM_MS_PSTMTR_SNDNG') }} WHERE SNDNG_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY SNDNG_KEY ORDER BY SNDNG_STDR_DE DESC NULLS LAST)=1
UNION ALL
SELECT SEQ_NO,'SND',NULL,
  NULLIF(TRIM(SEND_GBN_TOP),''),NULLIF(TRIM(SEND_GBN_TOP_NM),''),
  NULLIF(TRIM(SEND_GBN_MID),''),NULLIF(TRIM(SEND_GBN_MID_NM),''),
  NULLIF(TRIM(SEND_GBN_BOT),''),NULLIF(TRIM(SEND_GBN_BOT_NM),''),
  NULLIF(TRIM(SEND_TITLE),''),SEND_DATE::TIMESTAMP_NTZ,SEQ_NO,
  NULL, NULL, NULL,
  'CRM','BRONZE_CRM.SND_REQ_MST',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM {{ source('bronze_crm','SND_REQ_MST') }} WHERE SEQ_NO IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY SEQ_NO ORDER BY SEND_DATE DESC NULLS LAST)=1
