-- CRM_RELATION_ACTIVITY: 결연활동 = 서신 ∪ 선물금 (EHGT 제외, PK dedup), 정본 09 STEP3.
-- Co-authored with CoCo
SELECT 'LETTER_'||RELATNSP_KEY||'_'||COALESCE(NULLIF(TRIM(MNG_NO),''),'') AS ACTIVITY_KEY,
  '서신'                           AS ACTIVITY_TYPE,
  RELATNSP_KEY                     AS RELATNSP_KEY,
  NULLIF(TRIM(MNG_NO),'')          AS MNG_NO,
  NULL                             AS GFTMNEY,
  LETTER_DIV_CD                    AS LETTER_DIV_CD,
  RCEPT_DE                         AS RCEPT_DE,
  SNDNG_DE                         AS SNDNG_DE,
  'CRM'                            AS DW_SOURCE_SYSTEM,
  'BRONZE_CRM.TM_RM_RELATNSP_LETTER_INFO' AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP()              AS DW_LOAD_TS,
  CURRENT_TIMESTAMP()              AS DW_UPDATE_TS,
  NULL                             AS DW_BATCH_ID
FROM {{ source('bronze_crm','TM_RM_RELATNSP_LETTER_INFO') }} WHERE RELATNSP_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY RELATNSP_KEY, MNG_NO ORDER BY RCEPT_DE DESC NULLS LAST)=1
UNION ALL
SELECT 'GFT_'||RELATNSP_KEY||'_'||COALESCE(NULLIF(TRIM(MNG_NO),''),''), '선물금', RELATNSP_KEY, NULLIF(TRIM(MNG_NO),''),
  GFTMNEY, NULL, NULL, SNDNG_DE,
  'CRM','BRONZE_CRM.TM_RM_RELATNSP_GFTMNEY_INFO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM {{ source('bronze_crm','TM_RM_RELATNSP_GFTMNEY_INFO') }} WHERE RELATNSP_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY RELATNSP_KEY, MNG_NO ORDER BY SNDNG_DE DESC NULLS LAST)=1
