-- CRM_CAMPAIGN_SPONSOR_BIZ_BRIDGE: 캠페인 ↔ 후원사업 다대다(1:N) 브릿지 정규화 (DEC-45).
-- Co-authored with CoCo
WITH split_base AS (
  SELECT
    NULLIF(TRIM(CMPGN_CD),'')          AS CMPGN_CD,
    NULLIF(TRIM(f.value::TEXT),'')     AS SPNSR_BSNS_ID,
    'CRM'                              AS DW_SOURCE_SYSTEM,
    'BRONZE_CRM.TM_CM_CMPGN_MNG'       AS DW_SOURCE_TABLE
  FROM {{ source('bronze_crm','TM_CM_CMPGN_MNG') }},
  LATERAL FLATTEN(INPUT => SPLIT(SPNSR_BSNS_ID, ',')) f
  WHERE NULLIF(TRIM(CMPGN_CD),'') IS NOT NULL
    AND NULLIF(TRIM(f.value::TEXT),'') IS NOT NULL
)
SELECT
  CMPGN_CD,
  SPNSR_BSNS_ID,
  DW_SOURCE_SYSTEM,
  DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP()                  AS DW_LOAD_TS,
  CURRENT_TIMESTAMP()                  AS DW_UPDATE_TS,
  NULL                                 AS DW_BATCH_ID
FROM split_base
QUALIFY ROW_NUMBER() OVER (PARTITION BY CMPGN_CD, SPNSR_BSNS_ID ORDER BY DW_SOURCE_TABLE) = 1
