-- WIDE_AD_PERFORMANCE: 광고 성과 **코어** 팩트(FAD) 평탄화 소비뷰 — ref() 거버넌스 (정본 09_빅테이블 VIEW.md §3.7)
-- Co-authored with CoCo
-- ⚠️ [2026-07-28 순서9-I DEC-8] 코어에서 위성으로 이관된 방송 degen 5종
--    (TIME_BAND·CM_POSITION·RT_TYPE·AD_START_TIME·BROADCAST_DATE)을 본 뷰에서 **제거**했다.
--    본 뷰는 팩트와 1:1 대응 원칙을 지키며 **코어 컬럼만** 평탄화한다.
--    → 방송 고유속성은 `WIDE_AD_BROADCAST` · 디지털은 `WIDE_AD_DIGITAL` · 사례는 `WIDE_AD_BROADCAST_CASE`.
-- ⚠️ 명명 충돌 해소: `AD_SOURCE_TYPE`(코어 degen = 원천 출처축 DIGITAL/VIDEO/REBROADCAST)과
--    `AD_CREATIVE_TYPE`(DIM_AD_CREATIVE 소재 광고유형)은 **다른 개념**이다. 종전 두 컬럼이 모두
--    `AD_TYPE` 이라 혼동 소지가 있었으므로 내용에 맞게 분리 명명했다(소비자 부재 확인 후 적용).
-- ⚠️ CAMPAIGN_SK·AD_CREATIVE_SK 는 여전히 0 스캐폴드(Q10 이름매칭·소재 부분키 대기) → 관련 컬럼 NULL.
--    DEVICE_SK 는 DEC-10 으로 실배선 완료(방송행은 `(해당없음)` 멤버).
{{ config(
    materialized='view',
    post_hook=[
      "COMMENT ON VIEW {{ this }} IS '광고 성과 코어 팩트 평탄화 (FAD × DATE·CAMPAIGN·AD_CREATIVE·DEVICE, grain=AD_PERF_DK). DIM_DATE 파생은 PERF_ 접두. 유형 고유속성은 WIDE_AD_BROADCAST/DIGITAL/BROADCAST_CASE 참조.'",
      "ALTER VIEW {{ this }} ALTER COLUMN AD_PERF_DK COMMENT '광고성과 행 식별자(grain) — 위성 뷰 조인키', COLUMN PERF_DATE_SK COMMENT '광고 실적일 YYYYMMDD', COLUMN AD_COST COMMENT '광고비(원)', COLUMN IMPRESSIONS COMMENT '노출수(디지털 전용)', COLUMN CLICKS COMMENT '클릭수(디지털 전용)', COLUMN INBOUND_CALL COMMENT '인입콜수', COLUMN GA_CONV_MEMBERS COMMENT 'GA전환수(명) — 디지털 전용(O16 교정: 재방송 개발실적 제외)', COLUMN GA_CONV_CNT COMMENT 'GA전환수(건/VU) — 디지털 전용(O16 교정: 재방송 개발실적 제외)', COLUMN DAY_OF_WEEK COMMENT '요일(팩트 degen)', COLUMN WEEK_OF_YEAR COMMENT '주차(팩트 degen)', COLUMN AD_SOURCE_TYPE COMMENT '광고 원천유형 DIGITAL/VIDEO/REBROADCAST — 출처 명시축(팩트 degen, DEC-8)', COLUMN DW_SOURCE_SYSTEM COMMENT '원천 시스템 식별 (GA4/AGENCY/GADS)', COLUMN PERF_FULL_DATE COMMENT 'DIM_DATE.FULL_DATE — 실적일 일자', COLUMN PERF_YEAR COMMENT 'DIM_DATE.YEAR — 실적일 년', COLUMN PERF_MONTH COMMENT 'DIM_DATE.MONTH — 실적일 월', COLUMN PERF_QUARTER COMMENT 'DIM_DATE.QUARTER — 실적일 분기', COLUMN PERF_IS_HOLIDAY COMMENT 'DIM_DATE.IS_HOLIDAY — 실적일 휴일여부', COLUMN CAMPAIGN_BK COMMENT 'DIM_CAMPAIGN.CAMPAIGN_BK — 캠페인 업무키', COLUMN CAMPAIGN_BRAND COMMENT 'DIM_CAMPAIGN.BRAND — 공통브랜드 (#117)', COLUMN CAMPAIGN_PARENT COMMENT 'DIM_CAMPAIGN.PARENT_CAMPAIGN — 공통상위캠페인 (#119)', COLUMN CAMPAIGN_NAME COMMENT 'DIM_CAMPAIGN.CAMPAIGN_NAME — 캠페인명 (#120)', COLUMN CAMPAIGN_PROMO_METHOD COMMENT 'DIM_CAMPAIGN.PROMO_METHOD — 홍보방법 (#118)', COLUMN CAMPAIGN_TYPE COMMENT 'DIM_CAMPAIGN.CAMPAIGN_TYPE — 캠페인 유형 (#17)', COLUMN AD_CREATIVE_BK COMMENT 'DIM_AD_CREATIVE.AD_CREATIVE_BK — 광고소재 업무키', COLUMN AD_MEDIA_NAME COMMENT 'DIM_AD_CREATIVE.MEDIA_NAME — 매체명 (#11)', COLUMN AD_PLATFORM COMMENT 'DIM_AD_CREATIVE.PLATFORM — 플랫폼 (#12)', COLUMN AD_PLATFORM_TYPE COMMENT 'DIM_AD_CREATIVE.PLATFORM_TYPE — 플랫폼/매체유형 (#13)', COLUMN AD_CREATIVE COMMENT 'DIM_AD_CREATIVE.CREATIVE — 소재 (#20)', COLUMN AD_CREATIVE_TYPE COMMENT 'DIM_AD_CREATIVE.AD_TYPE — 소재 광고유형 (⚠️AD_SOURCE_TYPE 과 다른 개념)', COLUMN AD_TARGET_GROUP COMMENT 'DIM_AD_CREATIVE.TARGET_GROUP — 타겟그룹', COLUMN DEVICE_TYPE COMMENT 'DIM_DEVICE.DEVICE_TYPE — PC / M / (해당없음)방송 / (unknown)', COLUMN DEVICE_SCOPE_DESC COMMENT 'DIM_DEVICE.DEVICE_SCOPE_DESC — 기기 멤버 의미 자기설명(DEC-10)'"
    ]
) }}

select
    f.AD_PERF_DK,
    f.PERF_DATE_SK,
    f.AD_COST, f.IMPRESSIONS, f.CLICKS, f.INBOUND_CALL,
    f.GA_CONV_MEMBERS, f.GA_CONV_CNT,
    f.DAY_OF_WEEK, f.WEEK_OF_YEAR,
    f.AD_SOURCE_TYPE,
    f.DW_SOURCE_SYSTEM,
    d.FULL_DATE           as PERF_FULL_DATE,
    d.YEAR                as PERF_YEAR,
    d.MONTH               as PERF_MONTH,
    d.QUARTER             as PERF_QUARTER,
    d.IS_HOLIDAY          as PERF_IS_HOLIDAY,
    c.CAMPAIGN_BK         as CAMPAIGN_BK,
    c.BRAND               as CAMPAIGN_BRAND,
    c.PARENT_CAMPAIGN     as CAMPAIGN_PARENT,
    c.CAMPAIGN_NAME       as CAMPAIGN_NAME,
    c.PROMO_METHOD        as CAMPAIGN_PROMO_METHOD,
    c.CAMPAIGN_TYPE       as CAMPAIGN_TYPE,
    ac.AD_CREATIVE_BK     as AD_CREATIVE_BK,
    ac.MEDIA_NAME         as AD_MEDIA_NAME,
    ac.PLATFORM           as AD_PLATFORM,
    ac.PLATFORM_TYPE      as AD_PLATFORM_TYPE,
    ac.CREATIVE           as AD_CREATIVE,
    ac.AD_TYPE            as AD_CREATIVE_TYPE,   -- 소재 광고유형 (≠ AD_SOURCE_TYPE)
    ac.TARGET_GROUP       as AD_TARGET_GROUP,
    dv.DEVICE_TYPE        as DEVICE_TYPE,
    dv.DEVICE_SCOPE_DESC  as DEVICE_SCOPE_DESC
from {{ ref('FACT_AD_PERFORMANCE') }} f
left join {{ ref('DIM_DATE') }}        d  on f.PERF_DATE_SK   = d.DATE_SK
left join {{ ref('DIM_CAMPAIGN') }}    c  on f.CAMPAIGN_SK    = c.CAMPAIGN_SK
left join {{ ref('DIM_AD_CREATIVE') }} ac on f.AD_CREATIVE_SK = ac.AD_CREATIVE_SK
left join {{ ref('DIM_DEVICE') }}      dv on f.DEVICE_SK      = dv.DEVICE_SK
