-- WIDE_MEMBER_EVENT: 회원 이벤트 팩트(FME) 평탄화 소비뷰 — ref() 거버넌스 (정본 09_빅테이블 VIEW.md §3.2)
-- Co-authored with CoCo
{{ config(
    materialized='view',
    post_hook=[
      "COMMENT ON VIEW {{ this }} IS '회원 이벤트 팩트 평탄화 (FME × DATE·MEMBER[현재버전]·CAMPAIGN·SPONSORSHIP·ORG[as-was]·REASON).'",
      "ALTER VIEW {{ this }} ALTER COLUMN DATE_SK COMMENT '사건일 YYYYMMDD', COLUMN MEMBER_DK COMMENT '상태전이 대상 회원 (불변키)', COLUMN EVENT_TYPE COMMENT '상태전이 유형(개발/중단/증액/미납중단)', COLUMN DEV_CNT COMMENT '개발(건) (#149)', COLUMN DEV_MEMBERS COMMENT '개발(명) (#148)', COLUMN STOP_CNT COMMENT '중단(건) (#35)', COLUMN STOP_MEMBERS COMMENT '중단(명)', COLUMN UNPAID_STOP_CNT COMMENT '미납중단(건)', COLUMN UNPAID_STOP_MEMBERS COMMENT '미납중단(명)', COLUMN JOIN_DATE COMMENT '가입일', COLUMN STOP_DATE COMMENT '중단일', COLUMN STOP_REASON COMMENT '중단사유', COLUMN STOP_CHANNEL COMMENT '중단채널', COLUMN NEW_EXISTING_FLAG COMMENT '신규기존', COLUMN DW_SOURCE_SYSTEM COMMENT '원천 시스템 식별', COLUMN FULL_DATE COMMENT 'DIM_DATE.FULL_DATE — 실제 일자', COLUMN YEAR COMMENT 'DIM_DATE.YEAR — 년', COLUMN MONTH COMMENT 'DIM_DATE.MONTH — 월', COLUMN DAY_OF_WEEK COMMENT 'DIM_DATE.DAY_OF_WEEK — 요일', COLUMN WEEK_OF_YEAR COMMENT 'DIM_DATE.WEEK_OF_YEAR — 주차', COLUMN QUARTER COMMENT 'DIM_DATE.QUARTER — 분기', COLUMN IS_HOLIDAY COMMENT 'DIM_DATE.IS_HOLIDAY — 휴일여부', COLUMN MEMBER_GENDER COMMENT 'DIM_MEMBER.GENDER — 성별 (#130)', COLUMN MEMBER_REGION COMMENT 'DIM_MEMBER.REGION — 지역 (#131)', COLUMN MEMBER_AGE_BAND COMMENT 'DIM_MEMBER.AGE_BAND — 연령대', COLUMN MEMBER_STATUS COMMENT 'DIM_MEMBER.MEMBER_STATUS — 회원상태 (#132)', COLUMN MEMBER_TYPE COMMENT 'DIM_MEMBER.MEMBER_TYPE — 회원구분', COLUMN MEMBER_ENROLL_PATH COMMENT 'DIM_MEMBER.ENROLL_PATH — 가입경로', COLUMN CAMPAIGN_BK COMMENT 'DIM_CAMPAIGN.CAMPAIGN_BK — 캠페인 업무키', COLUMN CAMPAIGN_BRAND COMMENT 'DIM_CAMPAIGN.BRAND — 공통브랜드 (#117)', COLUMN CAMPAIGN_PARENT COMMENT 'DIM_CAMPAIGN.PARENT_CAMPAIGN — 공통상위캠페인 (#119)', COLUMN CAMPAIGN_NAME COMMENT 'DIM_CAMPAIGN.CAMPAIGN_NAME — 캠페인명 (#120)', COLUMN CAMPAIGN_PROMO_METHOD COMMENT 'DIM_CAMPAIGN.PROMO_METHOD — 홍보방법 (#118)', COLUMN SPONSORSHIP_BK COMMENT 'DIM_SPONSORSHIP.SPONSORSHIP_BK — 후원사업 업무키', COLUMN SPONSORSHIP_NAME COMMENT 'DIM_SPONSORSHIP.SPONSORSHIP_NAME — 후원사업 전체 (#123)', COLUMN ORG_CORP COMMENT 'DIM_ORG.CORP — 법인 (as-was #114)', COLUMN ORG_DIVISION COMMENT 'DIM_ORG.DIVISION — 본부/지부 (as-was #115)', COLUMN ORG_DEPARTMENT COMMENT 'DIM_ORG.DEPARTMENT — 부서 (as-was #116)', COLUMN ORG_TEAM COMMENT 'DIM_ORG.TEAM — 팀 (as-was)', COLUMN REASON_CODE COMMENT 'DIM_REASON.REASON_CODE — 사유코드', COLUMN REASON_NAME COMMENT 'DIM_REASON.REASON_NAME — 중단/미납사유', COLUMN REASON_TYPE COMMENT 'DIM_REASON.REASON_TYPE — 중단/미납 구분'"
    ]
) }}

select
    f.DATE_SK, f.MEMBER_DK, f.EVENT_TYPE,
    f.DEV_CNT, f.DEV_MEMBERS,
    f.STOP_CNT, f.STOP_MEMBERS,
    f.UNPAID_STOP_CNT, f.UNPAID_STOP_MEMBERS,
    f.JOIN_DATE, f.STOP_DATE, f.STOP_REASON, f.STOP_CHANNEL, f.NEW_EXISTING_FLAG,
    f.DW_SOURCE_SYSTEM,
    d.FULL_DATE, d.YEAR, d.MONTH, d.DAY_OF_WEEK, d.WEEK_OF_YEAR, d.QUARTER, d.IS_HOLIDAY,
    m.GENDER              as MEMBER_GENDER,
    m.REGION              as MEMBER_REGION,
    m.AGE_BAND            as MEMBER_AGE_BAND,
    m.MEMBER_STATUS       as MEMBER_STATUS,
    m.MEMBER_TYPE         as MEMBER_TYPE,
    m.ENROLL_PATH         as MEMBER_ENROLL_PATH,
    c.CAMPAIGN_BK         as CAMPAIGN_BK,
    c.BRAND               as CAMPAIGN_BRAND,
    c.PARENT_CAMPAIGN     as CAMPAIGN_PARENT,
    c.CAMPAIGN_NAME       as CAMPAIGN_NAME,
    c.PROMO_METHOD        as CAMPAIGN_PROMO_METHOD,
    s.SPONSORSHIP_BK      as SPONSORSHIP_BK,
    s.SPONSORSHIP_NAME    as SPONSORSHIP_NAME,
    o.CORP                as ORG_CORP,
    o.DIVISION            as ORG_DIVISION,
    o.DEPARTMENT          as ORG_DEPARTMENT,
    o.TEAM                as ORG_TEAM,
    r.REASON_CODE         as REASON_CODE,
    r.REASON_NAME         as REASON_NAME,
    r.REASON_TYPE         as REASON_TYPE
from {{ ref('FACT_MEMBER_EVENT') }} f
left join {{ ref('DIM_DATE') }} d on f.DATE_SK = d.DATE_SK
left join (
    select MEMBER_DK, GENDER, REGION, AGE_BAND, MEMBER_STATUS, MEMBER_TYPE, ENROLL_PATH
    from {{ ref('DIM_MEMBER') }}
    where IS_CURRENT = TRUE
    qualify ROW_NUMBER() OVER (PARTITION BY MEMBER_DK
        ORDER BY EFFECTIVE_FROM DESC NULLS LAST, MEMBER_SK DESC) = 1
) m on f.MEMBER_DK = m.MEMBER_DK
left join {{ ref('DIM_CAMPAIGN') }}    c on f.CAMPAIGN_SK    = c.CAMPAIGN_SK
left join {{ ref('DIM_SPONSORSHIP') }} s on f.SPONSORSHIP_SK = s.SPONSORSHIP_SK
left join {{ ref('DIM_ORG') }}         o on f.ORG_SK         = o.ORG_SK
left join {{ ref('DIM_REASON') }}      r on f.REASON_SK      = r.REASON_SK
