-- WIDE_MEMBER_EVENT: 회원 이벤트 팩트(FME) 평탄화 소비뷰 — ref() 거버넌스 (정본 09_빅테이블 VIEW.md §3.2)
-- Co-authored with CoCo
{{ config(
    materialized='view',
    post_hook=[
      "COMMENT ON VIEW {{ this }} IS '회원 이벤트 팩트 평탄화 (FME × DATE·MEMBER[현재버전]·CAMPAIGN·SPONSORSHIP·ORG[as-was]·REASON).'",
      "ALTER VIEW {{ this }} ALTER COLUMN DATE_SK COMMENT '사건일 YYYYMMDD', COLUMN MEMBER_DK COMMENT '상태전이 대상 회원 (불변키)', COLUMN EVENT_TYPE COMMENT '원천 계통 구분: DEV=개발원천 / STOP=중단원천. 상태는 DVLP_DIV_NM 참조 (O24)', COLUMN DVLP_DIV_CD COMMENT '개발구분코드 raw (정본 MM015: 1신규 2증액 3감액 4재후원 5후원중단). 중단원천 행은 NULL', COLUMN DVLP_DIV_NM COMMENT '개발구분명 (신규/증액/감액/재후원/후원중단). ⚠️ ''후원중단''은 EVENT_TYPE=''STOP''과 동일 사건 중복 → 합산 금지 (O24)', COLUMN SPNSR_AMT COMMENT '후원금액(원) raw — 감액·후원중단은 음수. (건) 지표는 금액÷10,000 (정본 공#38·#151)', COLUMN DEV_CNT COMMENT '개발(건) (#149) — 정본 공#121 = 신규·증액·재후원 한정 (O24 교정)', COLUMN DEV_MEMBERS COMMENT '개발(명) (#148) — 코드 1·2·4 한정', COLUMN STOP_CNT COMMENT '중단(건) (#35)', COLUMN STOP_MEMBERS COMMENT '중단(명)', COLUMN UNPAID_STOP_CNT COMMENT '미납중단(건)', COLUMN UNPAID_STOP_MEMBERS COMMENT '미납중단(명)', COLUMN JOIN_DATE COMMENT '가입일', COLUMN STOP_DATE COMMENT '중단일', COLUMN STOP_REASON COMMENT '중단사유', COLUMN STOP_CHANNEL COMMENT '중단채널', COLUMN STOP_REASON_NM COMMENT '중단사유명 (정본 공#162) — MM005 라벨. 코드는 STOP_REASON. 개발원천 행은 개념 부재로 NULL (O25)', COLUMN STOP_CHANNEL_NM COMMENT '중단경로명 — MM287 라벨(SYSTEM/CRM/홈페이지). 코드는 STOP_CHANNEL. 개발원천 행은 NULL (O25)', COLUMN NEW_EXISTING_FLAG COMMENT '신규기존', COLUMN DW_SOURCE_SYSTEM COMMENT '원천 시스템 식별', COLUMN FULL_DATE COMMENT 'DIM_DATE.FULL_DATE — 실제 일자', COLUMN YEAR COMMENT 'DIM_DATE.YEAR — 년', COLUMN MONTH COMMENT 'DIM_DATE.MONTH — 월', COLUMN DAY_OF_WEEK COMMENT 'DIM_DATE.DAY_OF_WEEK — 요일', COLUMN WEEK_OF_YEAR COMMENT 'DIM_DATE.WEEK_OF_YEAR — 주차', COLUMN QUARTER COMMENT 'DIM_DATE.QUARTER — 분기', COLUMN IS_HOLIDAY COMMENT 'DIM_DATE.IS_HOLIDAY — 휴일여부', COLUMN SEX COMMENT 'DIM_MEMBER.SEX — 성별 코드 raw(CM013 0~8: 1국내남·2국내여·3외국남·4외국여·5외국기타·6단체·7기업·8기타). 라벨=SEX_NM(원천)·MEMBER_GENDER_NAME(분석)', COLUMN SEX_NM COMMENT 'DIM_MEMBER.SEX_NM — CM013 원천 라벨. 국내/외국인 축 보존', COLUMN MEMBER_GENDER_NAME COMMENT 'DIM_MEMBER.GENDER_NAME — 성별 (#130) CM017 분석 라벨: 남자/여자/기타/단체/기업', COLUMN MEMBER_AREA_CD COMMENT 'DIM_MEMBER.AREA_CD — 지역 코드 raw(CM018 18종 + sentinel ''0''). 라벨=MEMBER_REGION', COLUMN MEMBER_REGION COMMENT 'DIM_MEMBER.REGION — 지역 (#131) CM018 약칭 라벨(서울/경기/인천…). ⚠️개발약정 **시점 스냅샷**이라 SCD2 버전별로 다를 수 있다(O27). ONCE(일시회원)는 개발약정 부재로 NULL', COLUMN MEMBER_AGE_CD COMMENT 'DIM_MEMBER.AGE — 연령대 코드 raw(CM014 1~12). 🔴연속형 나이가 아니다(1=10대미만…9=70대이상·10=단체·11=기업·12=기타). 라벨=MEMBER_AGE_BAND', COLUMN MEMBER_AGE_BAND COMMENT 'DIM_MEMBER.AGE_BAND — 연령대 CM014 라벨. ⚠️개발약정 **시점 스냅샷**(O27). ONCE 는 NULL', COLUMN MBER_STAT_CD COMMENT 'DIM_MEMBER.MBER_STAT_CD — 회원상태 코드 raw(MM010). 라벨=MEMBER_STATUS_NAME', COLUMN PREV_MBER_STAT_CD COMMENT 'DIM_MEMBER.PREV_MBER_STAT_CD — 상태전이 **이전상태** 코드(MM010). 원천 STATUS_HIST.BF_STAT_CD 100%·12/12 일치. 이력 미보유행은 NULL', COLUMN PREV_MEMBER_STATUS_NAME COMMENT 'DIM_MEMBER.PREV_MEMBER_STATUS_NAME — 이전상태 라벨(MM010). 현재상태와 짝지어 전이 분석에 쓴다', COLUMN MEMBER_STATUS_NAME COMMENT 'DIM_MEMBER.MEMBER_STATUS_NAME — 회원상태 (#132) MM010 라벨', COLUMN MBER_DIV_CD COMMENT 'DIM_MEMBER.MBER_DIV_CD — 회원구분 코드 raw(MM018). 라벨=MEMBER_TYPE_NAME', COLUMN MEMBER_TYPE_NAME COMMENT 'DIM_MEMBER.MEMBER_TYPE_NAME — 회원구분 MM018 라벨(개인/기업/단체)', COLUMN JOIN_PATH_CD COMMENT 'DIM_MEMBER.JOIN_PATH_CD — 가입경로 코드 raw(MM014). 라벨=MEMBER_ENROLL_PATH_NAME', COLUMN MEMBER_ENROLL_PATH_NAME COMMENT 'DIM_MEMBER.ENROLL_PATH_NAME — 가입경로 MM014 라벨', COLUMN CAMPAIGN_BK COMMENT 'DIM_CAMPAIGN.CAMPAIGN_BK — 캠페인 업무키', COLUMN CAMPAIGN_BRAND COMMENT 'DIM_CAMPAIGN.BRAND — 공통브랜드 (#117)', COLUMN CAMPAIGN_PARENT COMMENT 'DIM_CAMPAIGN.PARENT_CAMPAIGN — 공통상위캠페인 (#119)', COLUMN CAMPAIGN_NAME COMMENT 'DIM_CAMPAIGN.CAMPAIGN_NAME — 캠페인명 (#120)', COLUMN CAMPAIGN_PROMO_METHOD COMMENT 'DIM_CAMPAIGN.PROMO_METHOD — 홍보방법 (#118)', COLUMN CAMPAIGN_CATEGORY COMMENT 'DIM_CAMPAIGN.CAMPAIGN_TYPE — 캠페인카테고리 (MM294)', COLUMN CAMPAIGN_INFLOW_PATH COMMENT 'DIM_CAMPAIGN.INFLOW_PATH — 주요캠페인/개발인입경로 (MM293)', COLUMN SPONSORSHIP_BK COMMENT 'DIM_SPONSORSHIP.SPONSORSHIP_BK — 후원사업 업무키', COLUMN SPONSORSHIP_NAME COMMENT 'DIM_SPONSORSHIP.SPONSORSHIP_NAME — 후원사업 전체 (#123)', COLUMN ORG_CORP COMMENT 'DIM_ORG.CORP — 법인 (as-was #114)', COLUMN ORG_DIVISION COMMENT 'DIM_ORG.DIVISION — 본부/지부 (as-was #115)', COLUMN ORG_DEPARTMENT COMMENT 'DIM_ORG.DEPARTMENT — 부서 (as-was #116)', COLUMN ORG_TEAM COMMENT 'DIM_ORG.TEAM — 팀 (as-was)', COLUMN REASON_CODE COMMENT 'DIM_REASON.REASON_CODE — 사유코드', COLUMN REASON_NAME COMMENT 'DIM_REASON.REASON_NAME — 중단/미납사유', COLUMN REASON_TYPE COMMENT 'DIM_REASON.REASON_TYPE — 사유 코드그룹 ID. ⚠️''중단/미납 구분'' 아님 — 실제값은 CRM 코드그룹 ID 336종(O21 교정, 2026-08-03 재확증: 336/336 전건 CRM_CODE.CD_ID 매칭)'"
    ]
) }}

select
    f.DATE_SK, f.MEMBER_DK, f.EVENT_TYPE,
    -- [2026-08-03 O24] 개발구분 축 노출. 컬럼명은 BRONZE 원천명 그대로(현업 혼동 방지).
    --   ⚠️ DVLP_DIV_NM='후원중단' 과 EVENT_TYPE='STOP' 은 동일 사건 중복 → 합산 금지.
    f.DVLP_DIV_CD, f.DVLP_DIV_NM, f.SPNSR_AMT,
    f.DEV_CNT, f.DEV_MEMBERS,
    f.STOP_CNT, f.STOP_MEMBERS,
    f.UNPAID_STOP_CNT, f.UNPAID_STOP_MEMBERS,
    f.JOIN_DATE, f.STOP_DATE, f.STOP_REASON, f.STOP_CHANNEL,
    -- [2026-08-03 O25] 중단사유·중단경로 라벨 노출. 종전엔 raw 코드(1/14/16 · 1/2/3)만 있어
    --   현업이 WIDE 를 조회하면 숫자만 보였다. 계보 계약(04_컬럼계보매핑 §4)이 STOP_REASON 을
    --   "사유코드→라벨"로 명시한 것과 실적재가 어긋난 상태를 해소한다(정본 공#162).
    f.STOP_REASON_NM, f.STOP_CHANNEL_NM,
    f.NEW_EXISTING_FLAG,
    f.DW_SOURCE_SYSTEM,
    d.FULL_DATE, d.YEAR, d.MONTH, d.DAY_OF_WEEK, d.WEEK_OF_YEAR, d.QUARTER, d.IS_HOLIDAY,
    -- [2026-08-03 O26] 회원 속성 노출 재구성 — 코드=BRONZE 원천명 · 라벨=분석 용어.
    --   종전은 코드만(`MEMBER_GENDER`=M/F/U 등) 노출해 현업이 WIDE 에서 코드만 보던 상태였다.
    m.SEX                 as SEX,                     -- CM013 코드 raw
    m.SEX_NM              as SEX_NM,                  -- CM013 원천 라벨(국내/외국인 축)
    m.GENDER_NAME         as MEMBER_GENDER_NAME,      -- CM017 분석 라벨 = 정본 공#130
    m.AREA_CD             as MEMBER_AREA_CD,          -- [O27] CM018 코드 raw (라벨=MEMBER_REGION)
    m.REGION              as MEMBER_REGION,
    m.AGE                 as MEMBER_AGE_CD,           -- [O27] CM014 코드 raw. ⚠️연속형 나이 아님
    m.AGE_BAND            as MEMBER_AGE_BAND,
    m.MBER_STAT_CD        as MBER_STAT_CD,            -- MM010 코드 raw
    m.MEMBER_STATUS_NAME  as MEMBER_STATUS_NAME,      -- MM010 분석 라벨(#132)
    m.PREV_MBER_STAT_CD   as PREV_MBER_STAT_CD,       -- [O27] 상태전이 이전상태 코드(MM010)
    m.PREV_MEMBER_STATUS_NAME as PREV_MEMBER_STATUS_NAME,  -- [O27] 이전상태 라벨(MM010)
    m.MBER_DIV_CD         as MBER_DIV_CD,             -- MM018 코드 raw
    m.MEMBER_TYPE_NAME    as MEMBER_TYPE_NAME,        -- MM018 분석 라벨
    m.JOIN_PATH_CD        as JOIN_PATH_CD,            -- MM014 코드 raw
    m.ENROLL_PATH_NAME    as MEMBER_ENROLL_PATH_NAME, -- MM014 분석 라벨
    c.CAMPAIGN_BK         as CAMPAIGN_BK,
    c.BRAND               as CAMPAIGN_BRAND,
    c.PARENT_CAMPAIGN     as CAMPAIGN_PARENT,
    c.CAMPAIGN_NAME       as CAMPAIGN_NAME,
    c.PROMO_METHOD        as CAMPAIGN_PROMO_METHOD,
    -- [2026-07-30 D2] 캠페인 분석 2축 노출. DIM_CAMPAIGN 컬럼명↔업무용어 매핑에 주의:
    --   CAMPAIGN_TYPE(MM294 CMPGN_CTGR_NM) = 캠페인'카테고리'  → CAMPAIGN_CATEGORY 로 노출
    --   INFLOW_PATH(MM293 MBER_INFLOW_PATH_NM) = 현업 '주요캠페인' → CAMPAIGN_INFLOW_PATH 로 노출
    c.CAMPAIGN_TYPE       as CAMPAIGN_CATEGORY,
    c.INFLOW_PATH         as CAMPAIGN_INFLOW_PATH,
    s.SPONSORSHIP_BK      as SPONSORSHIP_BK,
    s.SPONSORSHIP_NAME    as SPONSORSHIP_NAME,
    o.CORP                as ORG_CORP,
    o.DIVISION            as ORG_DIVISION,
    o.DEPARTMENT          as ORG_DEPARTMENT,
    o.TEAM                as ORG_TEAM,
    r.REASON_CODE         as REASON_CODE,
    r.REASON_NAME         as REASON_NAME,
    r.REASON_TYPE         as REASON_TYPE
from {{ ref('FACT_MEMBER_EVENT') }} f
left join {{ ref('DIM_DATE') }} d on f.DATE_SK = d.DATE_SK
left join (
    select MEMBER_DK, SEX, SEX_NM, GENDER_NAME, AREA_CD, REGION, AGE, AGE_BAND, MBER_STAT_CD, MEMBER_STATUS_NAME, PREV_MBER_STAT_CD, PREV_MEMBER_STATUS_NAME, MBER_DIV_CD, MEMBER_TYPE_NAME, JOIN_PATH_CD, ENROLL_PATH_NAME
    from {{ ref('DIM_MEMBER') }}
    where IS_CURRENT = TRUE
    qualify ROW_NUMBER() OVER (PARTITION BY MEMBER_DK
        ORDER BY EFFECTIVE_FROM DESC NULLS LAST, MEMBER_SK DESC) = 1
) m on f.MEMBER_DK = m.MEMBER_DK
left join {{ ref('DIM_CAMPAIGN') }}    c on f.CAMPAIGN_SK    = c.CAMPAIGN_SK
left join {{ ref('DIM_SPONSORSHIP') }} s on f.SPONSORSHIP_SK = s.SPONSORSHIP_SK
left join {{ ref('DIM_ORG') }}         o on f.ORG_SK         = o.ORG_SK
left join {{ ref('DIM_REASON') }}      r on f.REASON_SK      = r.REASON_SK
