-- WIDE_GA_BEHAVIOR: GA 행동 팩트(FGA) 평탄화 소비뷰 — ref() 거버넌스 (정본 09_빅테이블 VIEW.md §3.6)
-- Co-authored with CoCo
-- 2026-07-15: DIM_MEMBER_IDENTITY 활성화 → IDENTITY_* 4컬럼 실조인 복원(f.IDENTITY_SK = DIM_MEMBER_IDENTITY.IDENTITY_SK).
--    ⚠️[G-5 재확인] 현재 GA4 1일 샤드 기반(회원 매칭 커버리지 ~4.2%). 전기간 입고 시 재실행·재검증 필요(문서50 G-5 게이트).
{{ config(
    materialized='view',
    post_hook=[
      "COMMENT ON VIEW {{ this }} IS 'GA 행동 팩트 평탄화 (FGA × DATE·IDENTITY·GA_EVENT·GA_SOURCE·DEVICE·CAMPAIGN). 비가산 지표(율·평균·사용자수) 상위 재합산 금지.'",
      "ALTER VIEW {{ this }} ALTER COLUMN DATE_SK COMMENT '행동 발생일 YYYYMMDD', COLUMN PAGE_PATH COMMENT '페이지경로 — 🔴 쿼리문자열 제외됨(산식 = SPLIT_PART(PAGE_LOCATION,「?」,1) · 실측 「?」 포함 0행). 정본 #105「페이지경로+쿼리문자열」 미충족이며 정본 #122 결연아동코드(childnum=) 파생 불가', COLUMN PAGE_LOCATION COMMENT '페이지위치 (#106) — 🔴 grain 내 MAX() 대표값(URL 전체 아님). 원천 distinct 75,474종 → GOLD 8,408종만 생존(67,066종·88.9% 소실). childnum 594→352종 · memnum 1,589→680종. 특정 URL 유무 판정 금지', COLUMN VISITS COMMENT '방문수 — 가산(실측 배수 1.0000)', COLUMN EVENT_CNT COMMENT '이벤트수 — 가산(실측 배수 1.0000)', COLUMN VIEW_CNT COMMENT '조회수 — 가산(실측 배수 1.0000)', COLUMN SESSION_CNT COMMENT '세션수 (#97) — 🔴 비가산(non-additive). 산식 = COUNT(DISTINCT USER_PSEUDO_ID||GA_SESSION_ID) 이며 집계 grain 에서 같은 세션이 여러 행에 반복된다. SUM 시 3.15배 과대계상(실측 원천 77,172 → 합계 243,156). 재합산 금지', COLUMN ENGAGED_SESSIONS COMMENT '참여세션수 — 🔴 비가산(non-additive). 산식 = COUNT(DISTINCT …) 이며 SUM 시 4.30배 과대계상(실측 원천 37,505 → 합계 161,117). 재합산 금지', COLUMN SCROLL_DEPTH COMMENT '[비가산] 스크롤깊이 — 재합산 금지', COLUMN ACTIVE_USERS COMMENT '[비가산] 활성사용자 — 재합산 금지', COLUMN TOTAL_USERS COMMENT '[비가산] 총사용자 — 재합산 금지', COLUMN AVG_SESSION_DURATION COMMENT '[비가산] 평균세션시간 — 재합산 금지 (#98)', COLUMN BOUNCE_RATE COMMENT '[비가산] 이탈율 — 재합산 금지 (#108)', COLUMN ENGAGEMENT_RATE COMMENT '[비가산] 참여율 — 재합산 금지', COLUMN AVG_ENGAGEMENT_TIME_PER_SESSION COMMENT '[비가산] 세션당 평균참여시간 — 재합산 금지', COLUMN DW_SOURCE_SYSTEM COMMENT '원천 시스템 식별', COLUMN FULL_DATE COMMENT 'DIM_DATE.FULL_DATE — 실제 일자', COLUMN YEAR COMMENT 'DIM_DATE.YEAR — 년', COLUMN MONTH COMMENT 'DIM_DATE.MONTH — 월', COLUMN DAY_OF_WEEK COMMENT 'DIM_DATE.DAY_OF_WEEK — 요일', COLUMN WEEK_OF_YEAR COMMENT 'DIM_DATE.WEEK_OF_YEAR — 주차', COLUMN IS_HOLIDAY COMMENT 'DIM_DATE.IS_HOLIDAY — 휴일여부', COLUMN IDENTITY_MEMBER_DK COMMENT 'DIM_MEMBER_IDENTITY.MEMBER_DK — 불변 회원키 (매칭분·미매칭 NULL, ⚠️G-5 재검증)', COLUMN IDENTITY_MEMBER_NO COMMENT 'DIM_MEMBER_IDENTITY.MEMBER_NO — 회원번호 (#110)', COLUMN IDENTITY_MEMNUM COMMENT 'DIM_MEMBER_IDENTITY.MEMNUM — 🔴 전건 NULL(미배선). 정본 #111. 원천 실재 = SILVER.GA4_EVENT.PAGE_LOCATION 의 memnum=(17,795행·1,589종) — 조회 시 항상 0행', COLUMN IDENTITY_GA_MEMBER_ID COMMENT 'DIM_MEMBER_IDENTITY.GA_MEMBER_ID — GA member_id (#112)', COLUMN GA_EVENT_CATEGORY COMMENT 'DIM_GA_EVENT.EVENT_CATEGORY — 이벤트 카테고리 (#99)', COLUMN GA_EVENT_LABEL COMMENT 'DIM_GA_EVENT.EVENT_LABEL — 이벤트 라벨 (#100)', COLUMN GA_EVENT_ACTION COMMENT 'DIM_GA_EVENT.EVENT_ACTION — 이벤트 액션 (#101)', COLUMN GA_UTM_SOURCE COMMENT 'DIM_GA_SOURCE.UTM_SOURCE — source', COLUMN GA_UTM_MEDIUM COMMENT 'DIM_GA_SOURCE.UTM_MEDIUM — medium', COLUMN GA_UTM_CONTENT COMMENT 'DIM_GA_SOURCE.UTM_CONTENT — 세션 수동 광고 콘텐츠 (#103)', COLUMN GA_UTM_TERM COMMENT 'DIM_GA_SOURCE.UTM_TERM — 세션 수동 검색어 (#104)', COLUMN GA_SOURCE_MEDIUM COMMENT 'DIM_GA_SOURCE.SOURCE_MEDIUM — 세션 소스/매체 (#109)', COLUMN DEVICE_TYPE COMMENT 'DIM_DEVICE.DEVICE_TYPE — PC / M / APP', COLUMN CAMPAIGN_BK COMMENT 'DIM_CAMPAIGN.CAMPAIGN_BK — 🔴 전건 「(미매핑)」. FACT_GA_BEHAVIOR.CAMPAIGN_SK 가 상수 0 하드코딩이라 캠페인축이 도달 불가하다(실측 distinct 1). GA 캠페인은 SILVER.GA4_EVENT.UTM_CAMPAIGN(244종·채움 88.0%)에 있고 미배선 — 조회 금지', COLUMN CAMPAIGN_BRAND COMMENT 'DIM_CAMPAIGN.BRAND — 🔴 전건 NULL(센티넬 행). CAMPAIGN_BK 참조 — 조회 금지', COLUMN CAMPAIGN_NAME COMMENT 'DIM_CAMPAIGN.CAMPAIGN_NAME — 🔴 전건 「(미매핑)」. CAMPAIGN_BK 참조 — 조회 금지'"
    ]
) }}

select
    f.DATE_SK, f.PAGE_PATH, f.PAGE_LOCATION,
    f.VISITS, f.EVENT_CNT, f.VIEW_CNT, f.SESSION_CNT, f.ENGAGED_SESSIONS,
    f.SCROLL_DEPTH, f.ACTIVE_USERS, f.TOTAL_USERS,
    f.AVG_SESSION_DURATION, f.BOUNCE_RATE, f.ENGAGEMENT_RATE,
    f.AVG_ENGAGEMENT_TIME_PER_SESSION,
    f.DW_SOURCE_SYSTEM,
    d.FULL_DATE, d.YEAR, d.MONTH, d.DAY_OF_WEEK, d.WEEK_OF_YEAR, d.IS_HOLIDAY,
    -- DIM_MEMBER_IDENTITY 활성(2026-07-15) → 실제 조인. ⚠️[G-5] GA4 1일 기반·커버리지 ~4.2%, 전기간 입고 시 재검증(문서50)
    mi.MEMBER_DK          as IDENTITY_MEMBER_DK,
    mi.MEMBER_NO          as IDENTITY_MEMBER_NO,
    mi.MEMNUM             as IDENTITY_MEMNUM,
    mi.GA_MEMBER_ID       as IDENTITY_GA_MEMBER_ID,
    ge.EVENT_CATEGORY     as GA_EVENT_CATEGORY,
    ge.EVENT_LABEL        as GA_EVENT_LABEL,
    ge.EVENT_ACTION       as GA_EVENT_ACTION,
    gs.UTM_SOURCE         as GA_UTM_SOURCE,
    gs.UTM_MEDIUM         as GA_UTM_MEDIUM,
    gs.UTM_CONTENT        as GA_UTM_CONTENT,
    gs.UTM_TERM           as GA_UTM_TERM,
    gs.SOURCE_MEDIUM      as GA_SOURCE_MEDIUM,
    dv.DEVICE_TYPE        as DEVICE_TYPE,
    c.CAMPAIGN_BK         as CAMPAIGN_BK,
    c.BRAND               as CAMPAIGN_BRAND,
    c.CAMPAIGN_NAME       as CAMPAIGN_NAME
from {{ ref('FACT_GA_BEHAVIOR') }} f
left join {{ ref('DIM_DATE') }}      d  on f.DATE_SK      = d.DATE_SK
left join {{ ref('DIM_GA_EVENT') }}  ge on f.GA_EVENT_SK  = ge.GA_EVENT_SK
left join {{ ref('DIM_GA_SOURCE') }} gs on f.GA_SOURCE_SK = gs.GA_SOURCE_SK
left join {{ ref('DIM_DEVICE') }}    dv on f.DEVICE_SK    = dv.DEVICE_SK
left join {{ ref('DIM_CAMPAIGN') }}  c  on f.CAMPAIGN_SK  = c.CAMPAIGN_SK
left join {{ ref('DIM_MEMBER_IDENTITY') }} mi on f.IDENTITY_SK = mi.IDENTITY_SK
