-- WIDE_AD_PERFORMANCE: 광고 성과 팩트(FAD) 평탄화 소비뷰 — ref() 거버넌스 (정본 09_빅테이블 VIEW.md §3.7)
-- Co-authored with CoCo
-- ⚠️ FACT_AD_PERFORMANCE 는 스캐폴드(measure/날짜만, CAMPAIGN_SK=0·차원FK 미해소). 캠페인 매칭(Q10)·GA전환정의(O5) 회신 전 부분 공백 반영.
{{ config(
    materialized='view',
    post_hook=[
      "COMMENT ON VIEW {{ this }} IS '광고 성과 팩트 평탄화 (FAD × DATE·CAMPAIGN·AD_CREATIVE·DEVICE). DIM_DATE 파생은 PERF_ 접두.'",
      "ALTER VIEW {{ this }} ALTER COLUMN PERF_DATE_SK COMMENT '광고 실적일 YYYYMMDD', COLUMN AD_COST COMMENT '광고비(원)', COLUMN IMPRESSIONS COMMENT '노출수', COLUMN CLICKS COMMENT '클릭수', COLUMN INBOUND_CALL COMMENT '인입콜수', COLUMN GA_CONV_MEMBERS COMMENT 'GA전환수(명)', COLUMN GA_CONV_CNT COMMENT 'GA전환수(건)', COLUMN DAY_OF_WEEK COMMENT '요일(팩트 degen)', COLUMN WEEK_OF_YEAR COMMENT '주차(팩트 degen)', COLUMN TIME_BAND COMMENT '시간대(팩트 degen)', COLUMN CM_POSITION COMMENT 'CM위치(팩트 degen, #21)', COLUMN RT_TYPE COMMENT 'RT유형(팩트 degen)', COLUMN AD_START_TIME COMMENT '광고시작시간(팩트 degen)', COLUMN BROADCAST_DATE COMMENT '송출일(팩트 degen, 실적일과 다를 수 있음)', COLUMN DW_SOURCE_SYSTEM COMMENT '원천 시스템 식별 (GA4/AGENCY/GADS)', COLUMN PERF_FULL_DATE COMMENT 'DIM_DATE.FULL_DATE — 실적일 일자', COLUMN PERF_YEAR COMMENT 'DIM_DATE.YEAR — 실적일 년', COLUMN PERF_MONTH COMMENT 'DIM_DATE.MONTH — 실적일 월', COLUMN PERF_QUARTER COMMENT 'DIM_DATE.QUARTER — 실적일 분기', COLUMN PERF_IS_HOLIDAY COMMENT 'DIM_DATE.IS_HOLIDAY — 실적일 휴일여부', COLUMN CAMPAIGN_BK COMMENT 'DIM_CAMPAIGN.CAMPAIGN_BK — 캠페인 업무키', COLUMN CAMPAIGN_BRAND COMMENT 'DIM_CAMPAIGN.BRAND — 공통브랜드 (#117)', COLUMN CAMPAIGN_PARENT COMMENT 'DIM_CAMPAIGN.PARENT_CAMPAIGN — 공통상위캠페인 (#119)', COLUMN CAMPAIGN_NAME COMMENT 'DIM_CAMPAIGN.CAMPAIGN_NAME — 캠페인명 (#120)', COLUMN CAMPAIGN_PROMO_METHOD COMMENT 'DIM_CAMPAIGN.PROMO_METHOD — 홍보방법 (#118)', COLUMN CAMPAIGN_TYPE COMMENT 'DIM_CAMPAIGN.CAMPAIGN_TYPE — 캠페인 유형 (#17)', COLUMN AD_CREATIVE_BK COMMENT 'DIM_AD_CREATIVE.AD_CREATIVE_BK — 광고소재 업무키', COLUMN AD_MEDIA_NAME COMMENT 'DIM_AD_CREATIVE.MEDIA_NAME — 매체명 (#11)', COLUMN AD_PLATFORM COMMENT 'DIM_AD_CREATIVE.PLATFORM — 플랫폼 (#12)', COLUMN AD_PLATFORM_TYPE COMMENT 'DIM_AD_CREATIVE.PLATFORM_TYPE — 플랫폼/매체유형 (#13)', COLUMN AD_CREATIVE COMMENT 'DIM_AD_CREATIVE.CREATIVE — 소재 (#20)', COLUMN AD_TYPE COMMENT 'DIM_AD_CREATIVE.AD_TYPE — 광고유형', COLUMN AD_TARGET_GROUP COMMENT 'DIM_AD_CREATIVE.TARGET_GROUP — 타겟그룹', COLUMN DEVICE_TYPE COMMENT 'DIM_DEVICE.DEVICE_TYPE — PC / M / APP'"
    ]
) }}

select
    f.PERF_DATE_SK,
    f.AD_COST, f.IMPRESSIONS, f.CLICKS, f.INBOUND_CALL,
    f.GA_CONV_MEMBERS, f.GA_CONV_CNT,
    f.DAY_OF_WEEK, f.WEEK_OF_YEAR, f.TIME_BAND,
    f.CM_POSITION, f.RT_TYPE, f.AD_START_TIME, f.BROADCAST_DATE,
    f.DW_SOURCE_SYSTEM,
    d.FULL_DATE           as PERF_FULL_DATE,
    d.YEAR                as PERF_YEAR,
    d.MONTH               as PERF_MONTH,
    d.QUARTER             as PERF_QUARTER,
    d.IS_HOLIDAY          as PERF_IS_HOLIDAY,
    c.CAMPAIGN_BK         as CAMPAIGN_BK,
    c.BRAND               as CAMPAIGN_BRAND,
    c.PARENT_CAMPAIGN     as CAMPAIGN_PARENT,
    c.CAMPAIGN_NAME       as CAMPAIGN_NAME,
    c.PROMO_METHOD        as CAMPAIGN_PROMO_METHOD,
    c.CAMPAIGN_TYPE       as CAMPAIGN_TYPE,
    ac.AD_CREATIVE_BK     as AD_CREATIVE_BK,
    ac.MEDIA_NAME         as AD_MEDIA_NAME,
    ac.PLATFORM           as AD_PLATFORM,
    ac.PLATFORM_TYPE      as AD_PLATFORM_TYPE,
    ac.CREATIVE           as AD_CREATIVE,
    ac.AD_TYPE            as AD_TYPE,
    ac.TARGET_GROUP       as AD_TARGET_GROUP,
    dv.DEVICE_TYPE        as DEVICE_TYPE
from {{ ref('FACT_AD_PERFORMANCE') }} f
left join {{ ref('DIM_DATE') }}        d  on f.PERF_DATE_SK   = d.DATE_SK
left join {{ ref('DIM_CAMPAIGN') }}    c  on f.CAMPAIGN_SK    = c.CAMPAIGN_SK
left join {{ ref('DIM_AD_CREATIVE') }} ac on f.AD_CREATIVE_SK = ac.AD_CREATIVE_SK
left join {{ ref('DIM_DEVICE') }}      dv on f.DEVICE_SK      = dv.DEVICE_SK
