-- WIDE_MEMBER_MONTHLY: 회원 월 팩트(FMM) 평탄화 소비뷰 — ref() 거버넌스 (정본 09_빅테이블 VIEW.md §3.1)
-- Co-authored with CoCo
{{ config(
    materialized='view',
    post_hook=[
      "COMMENT ON VIEW {{ this }} IS '회원 월 팩트 평탄화 (FMM × MEMBER[현재버전]·CAMPAIGN·SPONSORSHIP·PAYMENT·REASON). 월 grain=MONTH_KEY.'",
      "ALTER VIEW {{ this }} ALTER COLUMN CAL_YEAR COMMENT 'FLOOR(MONTH_KEY/100) — 연도', COLUMN CAL_MONTH COMMENT 'MOD(MONTH_KEY,100) — 월', COLUMN MONTH_KEY COMMENT 'YYYYMM', COLUMN MEMBER_DK COMMENT '불변 회원키(조인용)', COLUMN DEV_CNT COMMENT '개발(건) SUM(금액)/10000 (#4·5·149)', COLUMN DEV_MEMBERS COMMENT '개발(명) COUNT (#148)', COLUMN STOP_CNT COMMENT '중단(건) (#35, FME 롤업)', COLUMN UNPAID_CNT COMMENT '미납(건) (#36)', COLUMN ACTIVE_CNT COMMENT '활동(건) (#37·157)', COLUMN ACTIVE_MEMBERS COMMENT '활동(명) (#156)', COLUMN ACTIVE_CUM_CNT COMMENT '활동누계(건) (#159)', COLUMN ACTIVE_CUM_MEMBERS COMMENT '활동누계(명) (#158)', COLUMN INCREASE_CNT COMMENT '증액(건) (#151)', COLUMN INCREASE_MEMBERS COMMENT '증액(명) (#150)', COLUMN DECREASE_CNT COMMENT '감액(건) SUM(감액금액)/10000 (#38)', COLUMN CHURN_CNT COMMENT '이탈(건) SUM(취소+감액)/10000 (신규#20)', COLUMN YEAR_START_ACTIVE_CNT COMMENT '연도초 활동회원(건) (#49)', COLUMN YEAR_END_ACTIVE_CNT COMMENT '연도말 활동회원(건) (#50)', COLUMN MONTH_END_ACTIVE_CNT COMMENT '월말활동회원(건) (#52)', COLUMN PREV_MONTH_END_ACTIVE_CNT COMMENT '전월말 활동회원(건) (#53)', COLUMN CAMPAIGN_UNPAID_CNT COMMENT '캠페인별 미납(건) (#83)', COLUMN STATUS_UNPAID_CNT COMMENT '회원상태별 미납(건) (#84)', COLUMN REGULAR_FEE COMMENT '정기회비(원) (#66)', COLUMN REGULAR_ONETIME_FEE COMMENT '정기회원 일시회비(원) (#67)', COLUMN ONETIME_ONETIME_FEE COMMENT '일시회원 일시회비(원) (#68)', COLUMN PAID_FEE COMMENT '납입회비(원) (#69·70 단일화)', COLUMN BILLED_AMT COMMENT '청구(원) (#71)', COLUMN INBOUND_CALL_CNT COMMENT '인바운드콜수 (overview)', COLUMN TS_CALL_CNT COMMENT 'TS콜수 (overview)', COLUMN DEV_TYPE COMMENT '개발구분 (#121)', COLUMN NEW_FLAG COMMENT '신규여부 (#32)', COLUMN INCREASE_FLAG COMMENT '증액여부 (#33)', COLUMN REDONATE_FLAG COMMENT '재후원여부 (#34)', COLUMN JOIN_DATE COMMENT '캠페인 가입일 (#27)', COLUMN STOP_DATE COMMENT '가입캠페인 중단일 (#26)', COLUMN AMOUNT_BAND1 COMMENT '후원금액대1 5만 (#72)', COLUMN AMOUNT_BAND2 COMMENT '후원금액대2 1만 (#73)', COLUMN PERIOD_BAND1 COMMENT '후원기간대1 5년 (#74)', COLUMN PERIOD_BAND2 COMMENT '후원기간대2 1년 (#75)', COLUMN SPONSOR_MONTHS COMMENT '후원기간(개월) (#127)', COLUMN SPONSOR_YEARS COMMENT '후원기간(년) (#128)', COLUMN PAID_MONTHS COMMENT '납입개월수 (#129)', COLUMN NEW_EXISTING_FLAG COMMENT '신규/기존(시점귀속, #113)', COLUMN UNPAID_FLAG_BOM COMMENT '월초 미납회원 여부(=전월말 상태, #80)', COLUMN UNPAID_FLAG_EOM COMMENT '월말 미납회원 여부 (#80)', COLUMN DW_SOURCE_SYSTEM COMMENT '원천 시스템 식별', COLUMN MEMBER_GENDER COMMENT 'DIM_MEMBER.GENDER — 성별 (#130)', COLUMN MEMBER_REGION COMMENT 'DIM_MEMBER.REGION — 지역 (#131)', COLUMN MEMBER_AGE_BAND COMMENT 'DIM_MEMBER.AGE_BAND — 연령대', COLUMN MEMBER_STATUS COMMENT 'DIM_MEMBER.MEMBER_STATUS — 회원상태 (#132)', COLUMN MEMBER_TYPE COMMENT 'DIM_MEMBER.MEMBER_TYPE — 회원구분', COLUMN MEMBER_NEW_EXISTING COMMENT 'DIM_MEMBER.NEW_EXISTING_FLAG — 신규기존(현재버전, #113)', COLUMN MEMBER_FIRST_JOIN_DATE COMMENT 'DIM_MEMBER.FIRST_JOIN_DATE — 최초가입일 (#28)', COLUMN MEMBER_FIRST_CAMPAIGN COMMENT 'DIM_MEMBER.FIRST_CAMPAIGN — 최초캠페인 (#29)', COLUMN MEMBER_ENROLL_PATH COMMENT 'DIM_MEMBER.ENROLL_PATH — 가입경로', COLUMN MEMBER_FIRST_SPONSORSHIP COMMENT 'DIM_MEMBER.FIRST_SPONSORSHIP — 최초후원사업', COLUMN MEMBER_CURRENT_SPONSORSHIP COMMENT 'DIM_MEMBER.CURRENT_SPONSORSHIP — 현재후원사업', COLUMN CAMPAIGN_BK COMMENT 'DIM_CAMPAIGN.CAMPAIGN_BK — 캠페인 업무키', COLUMN CAMPAIGN_BRAND COMMENT 'DIM_CAMPAIGN.BRAND — 공통브랜드 (#117)', COLUMN CAMPAIGN_PARENT COMMENT 'DIM_CAMPAIGN.PARENT_CAMPAIGN — 공통상위캠페인 (#119)', COLUMN CAMPAIGN_NAME COMMENT 'DIM_CAMPAIGN.CAMPAIGN_NAME — 캠페인명 (#120)', COLUMN CAMPAIGN_PROMO_METHOD COMMENT 'DIM_CAMPAIGN.PROMO_METHOD — 홍보방법 (#118)', COLUMN CAMPAIGN_TYPE COMMENT 'DIM_CAMPAIGN.CAMPAIGN_TYPE — 캠페인 유형 (#17)', COLUMN SPONSORSHIP_BK COMMENT 'DIM_SPONSORSHIP.SPONSORSHIP_BK — 후원사업 업무키', COLUMN SPONSORSHIP_NAME COMMENT 'DIM_SPONSORSHIP.SPONSORSHIP_NAME — 후원사업 전체 (#123)', COLUMN SPONSORSHIP_ABBR COMMENT 'DIM_SPONSORSHIP.SPONSORSHIP_ABBR — 약칭 (#124)', COLUMN PAYMENT_METHOD COMMENT 'DIM_PAYMENT.PAYMENT_METHOD — 납입방식 (#125)', COLUMN PAYMENT_SETTLE_METHOD COMMENT 'DIM_PAYMENT.SETTLE_METHOD — 결제방식', COLUMN PAYMENT_FEE_TYPE COMMENT 'DIM_PAYMENT.FEE_TYPE — 회비유형(정기/일시)', COLUMN REASON_CODE COMMENT 'DIM_REASON.REASON_CODE — 사유코드', COLUMN REASON_NAME COMMENT 'DIM_REASON.REASON_NAME — 중단사유·미납사유 (#162·#82)', COLUMN REASON_TYPE COMMENT 'DIM_REASON.REASON_TYPE — 중단/미납 구분'"
    ]
) }}

select
    f.MONTH_KEY,
    FLOOR(f.MONTH_KEY / 100)   as CAL_YEAR,
    MOD(f.MONTH_KEY, 100)      as CAL_MONTH,
    f.MEMBER_DK,
    f.DEV_CNT, f.DEV_MEMBERS,
    f.STOP_CNT, f.UNPAID_CNT,
    f.ACTIVE_CNT, f.ACTIVE_MEMBERS,
    f.ACTIVE_CUM_CNT, f.ACTIVE_CUM_MEMBERS,
    f.INCREASE_CNT, f.INCREASE_MEMBERS,
    f.DECREASE_CNT, f.CHURN_CNT,
    f.YEAR_START_ACTIVE_CNT, f.YEAR_END_ACTIVE_CNT,
    f.MONTH_END_ACTIVE_CNT, f.PREV_MONTH_END_ACTIVE_CNT,
    f.CAMPAIGN_UNPAID_CNT, f.STATUS_UNPAID_CNT,
    f.REGULAR_FEE, f.REGULAR_ONETIME_FEE, f.ONETIME_ONETIME_FEE,
    f.PAID_FEE, f.BILLED_AMT,
    f.INBOUND_CALL_CNT, f.TS_CALL_CNT,
    f.DEV_TYPE, f.NEW_FLAG, f.INCREASE_FLAG, f.REDONATE_FLAG,
    f.JOIN_DATE, f.STOP_DATE,
    f.AMOUNT_BAND1, f.AMOUNT_BAND2, f.PERIOD_BAND1, f.PERIOD_BAND2,
    f.SPONSOR_MONTHS, f.SPONSOR_YEARS, f.PAID_MONTHS,
    f.NEW_EXISTING_FLAG, f.UNPAID_FLAG_BOM, f.UNPAID_FLAG_EOM,
    f.DW_SOURCE_SYSTEM,
    m.GENDER              as MEMBER_GENDER,
    m.REGION              as MEMBER_REGION,
    m.AGE_BAND            as MEMBER_AGE_BAND,
    m.MEMBER_STATUS       as MEMBER_STATUS,
    m.MEMBER_TYPE         as MEMBER_TYPE,
    m.NEW_EXISTING_FLAG   as MEMBER_NEW_EXISTING,
    m.FIRST_JOIN_DATE     as MEMBER_FIRST_JOIN_DATE,
    m.FIRST_CAMPAIGN      as MEMBER_FIRST_CAMPAIGN,
    m.ENROLL_PATH         as MEMBER_ENROLL_PATH,
    m.FIRST_SPONSORSHIP   as MEMBER_FIRST_SPONSORSHIP,
    m.CURRENT_SPONSORSHIP as MEMBER_CURRENT_SPONSORSHIP,
    c.CAMPAIGN_BK         as CAMPAIGN_BK,
    c.BRAND               as CAMPAIGN_BRAND,
    c.PARENT_CAMPAIGN     as CAMPAIGN_PARENT,
    c.CAMPAIGN_NAME       as CAMPAIGN_NAME,
    c.PROMO_METHOD        as CAMPAIGN_PROMO_METHOD,
    c.CAMPAIGN_TYPE       as CAMPAIGN_TYPE,
    s.SPONSORSHIP_BK      as SPONSORSHIP_BK,
    s.SPONSORSHIP_NAME    as SPONSORSHIP_NAME,
    s.SPONSORSHIP_ABBR    as SPONSORSHIP_ABBR,
    p.PAYMENT_METHOD      as PAYMENT_METHOD,
    p.SETTLE_METHOD       as PAYMENT_SETTLE_METHOD,
    p.FEE_TYPE            as PAYMENT_FEE_TYPE,
    r.REASON_CODE         as REASON_CODE,
    r.REASON_NAME         as REASON_NAME,
    r.REASON_TYPE         as REASON_TYPE
from {{ ref('FACT_MEMBER_MONTHLY') }} f
left join (
    select MEMBER_DK, GENDER, REGION, AGE_BAND, MEMBER_STATUS, MEMBER_TYPE,
           NEW_EXISTING_FLAG, FIRST_JOIN_DATE, FIRST_CAMPAIGN, ENROLL_PATH,
           FIRST_SPONSORSHIP, CURRENT_SPONSORSHIP
    from {{ ref('DIM_MEMBER') }}
    where IS_CURRENT = TRUE
    qualify ROW_NUMBER() OVER (PARTITION BY MEMBER_DK
        ORDER BY EFFECTIVE_FROM DESC NULLS LAST, MEMBER_SK DESC) = 1
) m on f.MEMBER_DK = m.MEMBER_DK
left join {{ ref('DIM_CAMPAIGN') }}     c on f.CAMPAIGN_SK    = c.CAMPAIGN_SK
left join {{ ref('DIM_SPONSORSHIP') }}  s on f.SPONSORSHIP_SK = s.SPONSORSHIP_SK
left join {{ ref('DIM_PAYMENT') }}      p on f.PAYMENT_SK     = p.PAYMENT_SK
left join {{ ref('DIM_REASON') }}       r on f.REASON_SK      = r.REASON_SK
