-- WIDE_SERVICE_EVENT: 서비스/발송 팩트(FSE) 평탄화 소비뷰 — ref() 거버넌스 (정본 09_빅테이블 VIEW.md §3.5)
-- Co-authored with CoCo
{{ config(
    materialized='view',
    post_hook=[
      "COMMENT ON VIEW {{ this }} IS '서비스/발송 팩트 평탄화 (FSE × DATE·MEMBER[현재버전]·SERVICE·CAMPAIGN).'",
      "ALTER VIEW {{ this }} ALTER COLUMN DATE_SK COMMENT '발송일 YYYYMMDD', COLUMN MEMBER_DK COMMENT '발송 대상 회원 (불변키)', COLUMN SEND_MEMBERS COMMENT '발송수(명) (#85)', COLUMN SUCCESS_MEMBERS COMMENT '성공수(명) (#86)', COLUMN FAIL_MEMBERS COMMENT '실패수(명) (#87)', COLUMN OPEN_MEMBERS COMMENT '오픈(명) (overview)', COLUMN LETTER_PART_MEMBERS COMMENT '서신참여(명) (#88)', COLUMN LETTER_PART_CNT COMMENT '서신참여(건) (#89)', COLUMN GIFT_PART_MEMBERS COMMENT '선물금참여(명) (#90)', COLUMN GIFT_PART_AMT COMMENT '선물금참여(원) (#91)', COLUMN D5_LETTER_PART_MEMBERS COMMENT '+5일차 서신참여(명) (#139)', COLUMN D5_LETTER_PART_CNT COMMENT '+5일차 서신참여(건) (#140)', COLUMN D5_GIFT_PART_MEMBERS COMMENT '+5일차 선물금참여(명) (#141)', COLUMN D5_GIFT_PART_CNT COMMENT '+5일차 선물금참여(건) (#142)', COLUMN D5_INCREASE_PART_MEMBERS COMMENT '+5일차 증액참여(명) (#143)', COLUMN D5_INCREASE_PART_CNT COMMENT '+5일차 증액참여(건) (#144)', COLUMN D5_STOP_MEMBERS COMMENT '+5일차 중단(명) (#145)', COLUMN D5_STOP_CNT COMMENT '+5일차 중단(건) (#146)', COLUMN SERVICE_MEMBERS COMMENT '서비스(명) (#160)', COLUMN SERVICE_CNT COMMENT '서비스(건) (#161)', COLUMN SEND_TITLE COMMENT '제목 (#136)', COLUMN SEND_STATUS COMMENT '발송상태 (#138)', COLUMN SEND_STATUS2 COMMENT '발송상태2', COLUMN SEND_TYPE COMMENT '발송유형', COLUMN MAIL_RECEIVE_FLAG COMMENT '메일수신여부', COLUMN MEMBER_STOP_FLAG COMMENT '결연회원 중단여부', COLUMN DW_SOURCE_SYSTEM COMMENT '원천 시스템 식별', COLUMN FULL_DATE COMMENT 'DIM_DATE.FULL_DATE — 실제 일자', COLUMN YEAR COMMENT 'DIM_DATE.YEAR — 년', COLUMN MONTH COMMENT 'DIM_DATE.MONTH — 월', COLUMN DAY_OF_WEEK COMMENT 'DIM_DATE.DAY_OF_WEEK — 요일', COLUMN WEEK_OF_YEAR COMMENT 'DIM_DATE.WEEK_OF_YEAR — 주차', COLUMN IS_HOLIDAY COMMENT 'DIM_DATE.IS_HOLIDAY — 휴일여부', COLUMN MEMBER_GENDER COMMENT 'DIM_MEMBER.GENDER — 성별 (#130)', COLUMN MEMBER_REGION COMMENT 'DIM_MEMBER.REGION — 지역 (#131)', COLUMN MEMBER_AGE_BAND COMMENT 'DIM_MEMBER.AGE_BAND — 연령대', COLUMN MEMBER_STATUS COMMENT 'DIM_MEMBER.MEMBER_STATUS — 회원상태 (#132)', COLUMN MEMBER_TYPE COMMENT 'DIM_MEMBER.MEMBER_TYPE — 회원구분', COLUMN SERVICE_SEND_TYPE_L COMMENT 'DIM_SERVICE.SEND_TYPE_L — 발송구분 대 (#133)', COLUMN SERVICE_SEND_TYPE_M COMMENT 'DIM_SERVICE.SEND_TYPE_M — 발송구분 중 (#134)', COLUMN SERVICE_SEND_TYPE_S COMMENT 'DIM_SERVICE.SEND_TYPE_S — 발송구분 소 (#135)', COLUMN SERVICE_SUBTYPE COMMENT 'DIM_SERVICE.SUBTYPE — 발송/참여 subtype', COLUMN SERVICE_CHANNEL COMMENT 'DIM_SERVICE.CHANNEL — CRM_UMS / ADMIN', COLUMN CAMPAIGN_BK COMMENT 'DIM_CAMPAIGN.CAMPAIGN_BK — 캠페인 업무키', COLUMN CAMPAIGN_BRAND COMMENT 'DIM_CAMPAIGN.BRAND — 공통브랜드 (#117)', COLUMN CAMPAIGN_PARENT COMMENT 'DIM_CAMPAIGN.PARENT_CAMPAIGN — 공통상위캠페인 (#119)', COLUMN CAMPAIGN_NAME COMMENT 'DIM_CAMPAIGN.CAMPAIGN_NAME — 캠페인명 (#120)', COLUMN CAMPAIGN_PROMO_METHOD COMMENT 'DIM_CAMPAIGN.PROMO_METHOD — 홍보방법 (#118)'"
    ]
) }}

select
    f.DATE_SK, f.MEMBER_DK,
    f.SEND_MEMBERS, f.SUCCESS_MEMBERS, f.FAIL_MEMBERS, f.OPEN_MEMBERS,
    f.LETTER_PART_MEMBERS, f.LETTER_PART_CNT,
    f.GIFT_PART_MEMBERS, f.GIFT_PART_AMT,
    f.D5_LETTER_PART_MEMBERS, f.D5_LETTER_PART_CNT,
    f.D5_GIFT_PART_MEMBERS, f.D5_GIFT_PART_CNT,
    f.D5_INCREASE_PART_MEMBERS, f.D5_INCREASE_PART_CNT,
    f.D5_STOP_MEMBERS, f.D5_STOP_CNT,
    f.SERVICE_MEMBERS, f.SERVICE_CNT,
    f.SEND_TITLE, f.SEND_STATUS, f.SEND_STATUS2, f.SEND_TYPE,
    f.MAIL_RECEIVE_FLAG, f.MEMBER_STOP_FLAG,
    f.DW_SOURCE_SYSTEM,
    d.FULL_DATE, d.YEAR, d.MONTH, d.DAY_OF_WEEK, d.WEEK_OF_YEAR, d.IS_HOLIDAY,
    m.GENDER              as MEMBER_GENDER,
    m.REGION              as MEMBER_REGION,
    m.AGE_BAND            as MEMBER_AGE_BAND,
    m.MEMBER_STATUS       as MEMBER_STATUS,
    m.MEMBER_TYPE         as MEMBER_TYPE,
    sv.SEND_TYPE_L        as SERVICE_SEND_TYPE_L,
    sv.SEND_TYPE_M        as SERVICE_SEND_TYPE_M,
    sv.SEND_TYPE_S        as SERVICE_SEND_TYPE_S,
    sv.SUBTYPE            as SERVICE_SUBTYPE,
    sv.CHANNEL            as SERVICE_CHANNEL,
    c.CAMPAIGN_BK         as CAMPAIGN_BK,
    c.BRAND               as CAMPAIGN_BRAND,
    c.PARENT_CAMPAIGN     as CAMPAIGN_PARENT,
    c.CAMPAIGN_NAME       as CAMPAIGN_NAME,
    c.PROMO_METHOD        as CAMPAIGN_PROMO_METHOD
from {{ ref('FACT_SERVICE_EVENT') }} f
left join {{ ref('DIM_DATE') }} d on f.DATE_SK = d.DATE_SK
left join (
    select MEMBER_DK, GENDER, REGION, AGE_BAND, MEMBER_STATUS, MEMBER_TYPE
    from {{ ref('DIM_MEMBER') }}
    where IS_CURRENT = TRUE
    qualify ROW_NUMBER() OVER (PARTITION BY MEMBER_DK
        ORDER BY EFFECTIVE_FROM DESC NULLS LAST, MEMBER_SK DESC) = 1
) m on f.MEMBER_DK = m.MEMBER_DK
left join {{ ref('DIM_SERVICE') }}  sv on f.SERVICE_SK  = sv.SERVICE_SK
left join {{ ref('DIM_CAMPAIGN') }} c  on f.CAMPAIGN_SK = c.CAMPAIGN_SK
