-- AGENCY_AD_CREATIVE: 광고소재 차원 = 3소스 매체/소재 DISTINCT (MD5 복합키), 정본 09 STEP5.
-- Co-authored with CoCo
SELECT DISTINCT
  MD5(SOURCE_SYSTEM||'|'||COALESCE(MEDIA_CHANNEL_NM,'')||'|'||COALESCE(CREATIVE_NM,'')||'|'||
      COALESCE(CREATIVE_TYPE_NM,'')||'|'||COALESCE(CM_AREA_NM,'')||'|'||COALESCE(AD_SEC_NM,'')) AS CREATIVE_DK,
  SOURCE_SYSTEM       AS SOURCE_SYSTEM,
  MEDIA_CHANNEL_NM    AS MEDIA_CHANNEL_NM,
  CREATIVE_NM         AS CREATIVE_NM,
  CREATIVE_TYPE_NM    AS CREATIVE_TYPE_NM,
  CM_AREA_NM          AS CM_AREA_NM,
  AD_SEC_NM           AS AD_SEC_NM,
  'AGENCY'            AS DW_SOURCE_SYSTEM,
  DW_SOURCE_TABLE     AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP() AS DW_LOAD_TS,
  CURRENT_TIMESTAMP() AS DW_UPDATE_TS,
  NULL                AS DW_BATCH_ID
FROM (
  SELECT 'DIGITAL' SOURCE_SYSTEM, NULLIF(TRIM(MEDIA_NM),'') MEDIA_CHANNEL_NM, NULLIF(TRIM(MATR),'') CREATIVE_NM,
         NULLIF(TRIM(MATR_TY_NM),'') CREATIVE_TYPE_NM, CAST(NULL AS VARCHAR) CM_AREA_NM, CAST(NULL AS VARCHAR) AD_SEC_NM,
         'BRONZE_AGENCY.DGT_AD_CMPGN_DTLS' DW_SOURCE_TABLE FROM {{ source('bronze_agency','DGT_AD_CMPGN_DTLS') }}
  UNION ALL
  SELECT 'REBROADCAST', NULLIF(TRIM(CHNNL_CMPNY),''), NULLIF(TRIM(BRDC_NM),''), NULLIF(TRIM(RE_BRDC_TY_NM),''),
         NULL, NULL, 'BRONZE_AGENCY.REBRDC_AD_CMPGN_DTLS' FROM {{ source('bronze_agency','REBRDC_AD_CMPGN_DTLS') }}
  UNION ALL
  SELECT 'VIDEO', NULLIF(TRIM(CHNNL_NM),''), NULLIF(TRIM(MATR_NM),''), NULLIF(TRIM(CMPGN_TY_NM),''),
         NULLIF(TRIM(CM_AREA),''), NULLIF(TRIM(AD_SEC),''), 'BRONZE_AGENCY.VIDEO_AD_CMPGN_DTLS' FROM {{ source('bronze_agency','VIDEO_AD_CMPGN_DTLS') }}
)
