-- AGENCY_AD_PERFORMANCE: 광고성과 = DIGITAL ∪ REBROADCAST ∪ VIDEO (원천 1행 grain, NULL 패딩), 정본 09 STEP5.
-- Co-authored with CoCo
-- 연·월 = DATE 파생(텍스트 파싱 금지) · _SOURCE_SYSTEM 테이블기반 · 인입콜 TRY_TO_NUMBER · 파생지표 미적재.
SELECT 'DIGITAL' AS SOURCE_SYSTEM, DATE AS AD_DATE, YEAR(DATE) AS AD_YEAR, MONTH(DATE) AS AD_MONTH,
  NULLIF(TRIM(CMPGN_NM),'') AS CAMPAIGN_NM, NULLIF(TRIM(UPPER_CMPGN_NM),'') AS UPPER_CAMPAIGN_NM,
  NULLIF(TRIM(MEDIA_NM),'') AS MEDIA_CHANNEL_NM, NULLIF(TRIM(DEVICE),'') AS DEVICE_NM,
  NULLIF(TRIM(MATR),'') AS CREATIVE_NM, NULL AS PROGRAM_NM,
  EXPS_CNT AS IMPRESSION_CNT, CLICK_CNT AS CLICK_CNT, GA_CONV_MBER_CNT AS CONV_MEMBER_CNT, CONV_VU_CNT AS CONV_UNIT_CNT,
  NULL AS INBOUND_CALL_CNT, NULL AS CONV_CALL_CNT, NULL AS AD_CNT, GA_AD_COST AS AD_COST, 'GA' AS COST_TYPE,
  'AGENCY' AS DW_SOURCE_SYSTEM, 'BRONZE_AGENCY.DGT_AD_CMPGN_DTLS' AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP() AS DW_LOAD_TS, CURRENT_TIMESTAMP() AS DW_UPDATE_TS, NULL AS DW_BATCH_ID
FROM {{ source('bronze_agency','DGT_AD_CMPGN_DTLS') }}
UNION ALL
SELECT 'REBROADCAST', DATE, YEAR(DATE), MONTH(DATE),
  NULL, NULL, NULLIF(TRIM(CHNNL_CMPNY),''), NULL,
  NULLIF(TRIM(BRDC_NM),''), NULLIF(TRIM(BRDC_NM),''), NULL, NULL, DVLP_MBER_CNT, DVLP_CNT, TRY_TO_NUMBER(INBOUND_CALL_CNT),
  NULL, AD_CNT, BRDC_SCHDL_COST, '편성', 'AGENCY','BRONZE_AGENCY.REBRDC_AD_CMPGN_DTLS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM {{ source('bronze_agency','REBRDC_AD_CMPGN_DTLS') }}
UNION ALL
SELECT 'VIDEO', BRDC_DATE, YEAR(BRDC_DATE), MONTH(BRDC_DATE),
  NULLIF(TRIM(MKT_CMPGN_NM),''), NULLIF(TRIM(UPPER_CMPGN_NM),''), NULLIF(TRIM(CHNNL_NM),''), NULL,
  NULLIF(TRIM(MATR_NM),''), NULLIF(TRIM(SCHDL_NM),''), NULL, NULL, NULL, NULL, INBOUND_CALL_CNT,
  CONV_CALL_CNT, AD_CNT, ACTL_PUR_AD_COST_KRW, '집행', 'AGENCY','BRONZE_AGENCY.VIDEO_AD_CMPGN_DTLS',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),NULL
FROM {{ source('bronze_agency','VIDEO_AD_CMPGN_DTLS') }}
