CREATE FUNCTION [dbo].[FN_MM_ACT_DATE]
(
	@STRD_MT 		AS CHAR(6)
)
RETURNS TABLE
AS 
RETURN 
(
SELECT t1.MBER_NO, t1.STDR_DE, t1.FRST_REGIST_DT, SPNSR_DSCNTC_DE, t2.RE_SPNSR_DE, actualdt FROM
			MSTR_ODS.DBO.TM_MM_FDRM_MBER_INFO t1
			INNER JOIN (SELECT DISTINCT MBER_NO FROM MART.D_SPNSR_BSNS_V WHERE FST_DE <= @STRD_MT + '31' AND ( DSC_DE IS NULL OR DSC_DE > @STRD_MT + '31')) t3 ON t1.MBER_NO = t3.MBER_NO
			LEFT OUTER JOIN
			(
				SELECT t1.MBER_NO, t1.SPNSR_DSCNTC_DE, t2.RE_SPNSR_DE,
					CASE WHEN RE_SPNSR_DE IS NULL THEN DateAdd(d, -1, SPNSR_DSCNTC_DE)
						ELSE
							CASE
								WHEN SPNSR_DSCNTC_DE > RE_SPNSR_DE THEN DateAdd(d, -1, SPNSR_DSCNTC_DE) ELSE
								
								CASE WHEN RE_SPNSR_DE < DATEADD( DD, -1, DATEADD(MM, 1,CONVERT( DATE,@STRD_MT + '01'))) THEN DATEADD( DD, -1, DATEADD(MM, 1,CONVERT( DATE,@STRD_MT + '01'))) ELSE RE_SPNSR_DE END
							END
					END AS actualdt
				FROM
				(
					SELECT MBER_NO, SPNSR_DSCNTC_DE
					FROM
					(
					SELECT *, ROW_NUMBER() OVER(PARTITION BY MBER_NO ORDER BY SPNSR_DSCNTC_DE DESC) AS rnum FROM MSTR_ODS.DBO.TM_MM_FDRM_MBER_SPNSR_DSCNTC WHERE SPNSR_DSCNTC_DE <= @STRD_MT + '31'
					) t1
					WHERE t1.rnum = 1
				) t1
				LEFT OUTER JOIN 
				(
					SELECT MBER_NO, RE_SPNSR_DE
					FROM
					(
					SELECT *, ROW_NUMBER() OVER(PARTITION BY MBER_NO ORDER BY RE_SPNSR_DE DESC) AS rnum FROM MSTR_ODS.DBO.TM_MM_FDRM_MBER_RE_SPNSR WHERE RE_SPNSR_DE <= @STRD_MT + '31'
					) t1
					WHERE t1.rnum = 1
				) t2
				ON t1.MBER_NO = t2.MBER_NO
			) t2 ON t1.MBER_NO = t2.MBER_NO
		WHERE DATEADD( DD, -1, DATEADD(MM, 1,CONVERT( DATE,@STRD_MT + '01'))) BETWEEN CONVERT(DATE,FRST_REGIST_DT) AND CONVERT(DATE, ISNULL(actualdt,'9999-12-31'))
 )
GO

-- ======================================================================

CREATE FUNCTION [dbo].[FN_MM_SPNSR_DVLP]
(
	@STRD_MT 		AS CHAR(6)
)
RETURNS TABLE
AS 
RETURN
SELECT 
	ACMSLT_DEPT_CD2,
	DVLP_DIV_CD2,
	RNUM ,
	SAMT,
	MAMT,
	STRD_MT,
	SPNSR_NO,
	SPNSR_BSNS_NO,
	OCCRRNC_DE,
	SER_NO,
	MBER_NO,
	ACT_DEPT_CD,
	ISNULL( ACMSLT_DEPT_CD2 ,'Z~')  AS ACMSLT_DEPT_CD,
	CMPGN_CD,
	SETLE_CD,
	MBER_DIV_CD,
	SEX,
	AREA_CD,
	AGE,
	SPNSR_TIME_CO,
	SPNSR_AMT_CD,
	SPNSR_BSNS_ID,
	CANCL_RDCAMT_RSN_CD,
	CASE WHEN DVLP_DIV_CD2 = '2' THEN RAMT WHEN DVLP_DIV_CD2 IN ( '3','5' ) THEN MAMT ELSE SPNSR_AMT END SPNSR_AMT ,
	DVLP_DIV_CD2 AS DVLP_DIV_CD,
	FRST_RGSTR_ID,
	FRST_RGSTR_NM,
	LAG(CMPGN_CD , 1) OVER ( PARTITION BY SPNSR_NO, SPNSR_BSNS_NO  ORDER BY  OCCRRNC_DE ) PRE_CMPGN_CD
FROM (
    -- 신규 / 재후원 
   SELECT  ACMSLT_DEPT_CD AS ACMSLT_DEPT_CD2,*
	 FROM (
			  SELECT DVLP_DIV_CD AS DVLP_DIV_CD2,
			         1 RNUM,
					 0 RAMT, --증액과 항목 맞추기
					 0 AAMT, --증액과 항목 맞추기
					 0 DAMT, --증액과 항목 맞추기
					 0 SAMT, --증액과 항목 맞추기
					  SUM( A.SPNSR_AMT) OVER ( PARTITION BY  A.SPNSR_NO, A.SPNSR_BSNS_NO, LEFT( A.OCCRRNC_DE, 6)  ) MAMT ,
					 --SUM(SPNSR_AMT) OVER ( PARTITION BY SPNSR_NO, SPNSR_BSNS_NO, OCCRRNC_DE  ) MAMT ,
					 LEFT( A.OCCRRNC_DE, 6) STRD_MT ,A.*
				FROM MSTR_ODS.DBO.TM_MM_FDRM_MBER_DVLP_AMT  A
				--JOIN (  SELECT MBER_NO MBER_NO2 FROM MART.D_SPNSR_BSNS_V  WHERE  DSC_DE > @STRD_MT + '31' GROUP BY MBER_NO )  B 
				--  ON A.MBER_NO = B.MBER_NO2 
				JOIN MART.D_SPNSR_BSNS_V  B
				  ON  A.SPNSR_NO = B.SPNSR_NO 
				  AND A.SPNSR_BSNS_NO = B.SPNSR_BSNS_NO 
				  AND B.DSC_DE > LEFT(A.OCCRRNC_DE, 6) +  '31' 
				--  ON A.MBER_NO = B.MBER_NO2 
				WHERE A.DVLP_DIV_CD IN ( '1' ,'4' ) 
		) A
   WHERE A.MAMT > 0 

   UNION ALL  -- 증액  
              -- 처리순서 1. 회원별 SUM > 0 으로 증액회원 구분하고 후원번호별 증액 과 후원사업별 감액 선별  
              -- 처리순서 2. 후원사업별 증액만 선별하고 감액은 증액SUM 값은 증액여부 판단하기 위해 가져감
              -- 처리순서 3. 회원별 후원사업별 누적 > 0 큰 것만 선별
			  -- 처리순서 4. 누적금 , 후원금SUM , 회원SUM 값중 가장 작은 것 선택  
              -- AAMT : 회원별 후원사업별 후원금 누적  DAMT : 회원별 감액  SAMT : 후원사업별 SUM  MAMT : 회원별 SUM  
   SELECT *
     FROM (    
	   SELECT DISTINCT ACMSLT_DEPT_CD ACMSLT_DEPT_CD2,
			  '2'  DVLP_DIV_CD2, 
			   ROW_NUMBER() OVER ( PARTITION BY STRD_MT, SPNSR_NO, SPNSR_BSNS_NO  ORDER BY SER_NO ) RNUM,  -- 항목 맞추기 
			   CASE WHEN  MAMT <= SAMT AND  AAMT + DAMT <= MAMT THEN  AAMT + DAMT
					WHEN  MAMT >  SAMT AND  AAMT + DAMT <= SAMT THEN  AAMT + DAMT 
					WHEN  MAMT <= SAMT THEN MAMT ELSE SAMT END   RAMT,*
		 FROM ( 
				  SELECT 
						  SUM( SAMT ) OVER ( PARTITION BY MBER_NO ,STRD_MT  ORDER BY  OCCRRNC_DE ,SER_NO ) AAMT ,*
				   FROM ( 
						  SELECT  SUM( CASE WHEN DVLP_DIV_CD IN ( '3' )    THEN SPNSR_AMT  ELSE 0 END ) OVER ( PARTITION BY MBER_NO ,STRD_MT ) DAMT ,* 
							FROM ( 
									SELECT  SUM( CASE WHEN DVLP_DIV_CD IN ( '2','3') THEN  SPNSR_AMT ELSE 0 END ) OVER ( PARTITION BY  SPNSR_NO, SPNSR_BSNS_NO , LEFT(OCCRRNC_DE, 6)  ) SAMT, 
											SUM(SPNSR_AMT) OVER ( PARTITION BY MBER_NO , LEFT(OCCRRNC_DE, 6) ) MAMT, 
											LEFT(OCCRRNC_DE, 6) STRD_MT ,*
										FROM MSTR_ODS.DBO.TM_MM_FDRM_MBER_DVLP_AMT  
										WHERE DVLP_DIV_CD IN ( '2','3','5') 
								) A
							WHERE 1 = 1
							  AND MAMT > 0
							  AND (( SAMT > 0 AND  DVLP_DIV_CD = '2' ) OR ( SAMT < 0 AND  DVLP_DIV_CD = '3'))
						) B  
				   WHERE  DVLP_DIV_CD = '2'
			  ) C
		WHERE  AAMT - ABS(DAMT)  > 0
	) D
    WHERE RNUM = 1	

   UNION ALL  -- 감액
   SELECT ACMSLT_DEPT_CD AS ACMSLT_DEPT_CD2, 
          '3'  DVLP_DIV_CD2,
		   *
     FROM ( 
		   SELECT ROW_NUMBER() OVER (  PARTITION BY A.MBER_NO , LEFT(OCCRRNC_DE, 6) ORDER BY SPNSR_NO DESC )  SNUM,
		          0 RAMT, --증액과 항목 맞추기
				  0 AAMT, --증액과 항목 맞추기
				  0 DAMT, --증액과 항목 맞추기
		          0 SAMT, --증액과 항목 맞추기
				  SUM(SPNSR_AMT) OVER ( PARTITION BY A.MBER_NO , LEFT(OCCRRNC_DE, 6) ) MAMT, 
				  LEFT(OCCRRNC_DE, 6) STRD_MT ,A.*
			 FROM MSTR_ODS.DBO.TM_MM_FDRM_MBER_DVLP_AMT  A 
			WHERE DVLP_DIV_CD IN ( '2','3') 
		   ) A
	WHERE MAMT < 0 
	  AND SNUM = 1
   UNION ALL -- 중단
	SELECT ACMSLT_DEPT_CD AS ACMSLT_DEPT_CD2, 
		   DVLP_DIV_CD AS DVLP_DIV_CD2,
		   *
	 FROM ( 
            SELECT ROW_NUMBER() OVER (  PARTITION BY A.MBER_NO ,A.SPNSR_NO, A.SPNSR_BSNS_NO, LEFT( A.OCCRRNC_DE, 6) ORDER BY A.SER_NO DESC )  SNUM,
			       0 RAMT,  --증액과 항목 맞추기
                   0 AAMT,  --증액과 항목 맞추기
				   0 DAMT,  --증액과 항목 맞추기 
			       0 SAMT,  --증액과 항목 맞추기 
				   SUM( A.SPNSR_AMT) OVER ( PARTITION BY A.MBER_NO ,A.SPNSR_NO, A.SPNSR_BSNS_NO, LEFT( A.OCCRRNC_DE, 6) ) MAMT, 
				   LEFT( A.OCCRRNC_DE, 6) STRD_MT ,A.*
			FROM  MSTR_ODS.DBO.TM_MM_FDRM_MBER_DVLP_AMT      A 
			JOIN  ( SELECT DISTINCT  MBER_NO , SPNSR_DSCNTC_DE
			           FROM MSTR_ODS.DBO.TM_MM_FDRM_MBER_SPNSR_DSCNTC 
 				  ) B
			  ON  A.MBER_NO = B.MBER_NO 
			AND   A.OCCRRNC_DE = B.SPNSR_DSCNTC_DE 
			-- AND   A.SER_NO = B.SER_NO
			WHERE A.DVLP_DIV_CD IN ('5') 
		   ) C	
	WHERE SNUM = 1 
) T
WHERE STRD_MT <=  @STRD_MT 
GO
