-- Co-authored with CoCo
-- =====================================================================
-- 00. GN_DW.MSTR 스키마 생성 + 롤 매핑 (O197 · MSTR 1차 이관 PoC)
--   정본 패턴 = 02_GN_DW_building/07_ENVIRONMENT_RBAC_setup.sql (§B.5 · §D.2 · §D.3)
--   · 소유 = GN_DW_ADMIN (스키마·테이블·뷰·함수·프로시저 전부 ADMIN 이 처음부터 생성)
--   · 원천 = GN_DW.BRONZE_CRM 읽기 전용 (MSTR_ODS 직접 연결 없음)
--   · ENGINEER = 개발·적재(DML) / ANALYST·VIEWER·SERVICE = 조회
--   · 신규 롤 없음 — 기존 GN_DW 롤 체계를 그대로 쓴다
--   🔴 스키마를 드롭·재생성하면 FUTURE grant 까지 사라진다 ⇒ 이 파일 전량 재실행이 DoD (07 머리말 O91)
-- =====================================================================

-- [1] 스키마 생성 — GN_DW_ADMIN 소유
USE ROLE GN_DW_ADMIN;
CREATE SCHEMA IF NOT EXISTS GN_DW.MSTR
  COMMENT = 'MSTR(MicroStrategy) 이관 PoC — 구 SQL Server mart/dbo 객체의 Snowflake 전환본. 원천 = BRONZE_CRM. 중간 산출물 + 최종 마트';

-- [2] ADMIN 전체
GRANT ALL PRIVILEGES ON SCHEMA GN_DW.MSTR TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS     IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE VIEWS  IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_ADMIN;

-- [3] ENGINEER — 개발(뷰·함수·프로시저) + 적재 DML (SILVER §D.3 패턴)
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION
  ON SCHEMA GN_DW.MSTR TO ROLE GN_DW_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES    IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL VIEWS    IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_ENGINEER;

-- [4] 소비 3역할 — USAGE + SELECT (+ FUTURE) (GOLD §D.2 패턴)
GRANT USAGE ON SCHEMA GN_DW.MSTR TO ROLE GN_DW_ANALYST;
GRANT USAGE ON SCHEMA GN_DW.MSTR TO ROLE GN_DW_VIEWER;
GRANT USAGE ON SCHEMA GN_DW.MSTR TO ROLE GN_DW_SERVICE;
GRANT SELECT ON ALL TABLES    IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_ANALYST;
GRANT SELECT ON ALL VIEWS     IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_ANALYST;
GRANT SELECT ON ALL TABLES    IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_VIEWER;
GRANT SELECT ON ALL VIEWS     IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_VIEWER;
GRANT SELECT ON ALL TABLES    IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_SERVICE;
GRANT SELECT ON ALL VIEWS     IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_SERVICE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_VIEWER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_SERVICE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_SERVICE;

-- [5] 함수·프로시저 USAGE — FUTURE 로 ENGINEER 에 부여 (프로시저는 OWNER 권한으로 실행)
GRANT USAGE ON FUTURE FUNCTIONS  IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA GN_DW.MSTR TO ROLE GN_DW_ENGINEER;

-- [6] 원천 BRONZE_CRM 읽기 — 07 §D.4 에서 이미 부여(ENGINEER·ANALYST). 여기서는 재부여하지 않는다.
--     확인: SHOW GRANTS ON SCHEMA GN_DW.BRONZE_CRM;

-- [7] 실측 확인
SHOW GRANTS ON SCHEMA GN_DW.MSTR;
SHOW FUTURE GRANTS IN SCHEMA GN_DW.MSTR;
