-- Co-authored with CoCo
-- =====================================================================
-- 02. GN_DW.MSTR 뷰 DDL (O197) — 원본 = mstr DDL 원본/1차 이관대상 관련 추출/view_script.sql
--   변환 규칙: CONVERT(CHAR(8),d,112) → TO_CHAR(d,'YYYYMMDD') · CONVERT(CHAR(10),d,121) → TO_CHAR(d,'YYYY-MM-DD')
--             ISNULL → IFNULL · GETDATE() → CURRENT_DATE() · 문자열 + → || · MSTR_ODS.DBO → GN_DW.BRONZE_CRM
--   🔴 상수 행 UNION 은 Snowflake 에서 컬럼 이름이 첫 SELECT 를 따른다(원본과 동일) — 타입은 명시 CAST
--   🔴 실행 순서 = 01 테이블 → 이 파일 → 03 함수(D_SPNSR_BSNS_V 의존)
-- =====================================================================
USE ROLE GN_DW_ADMIN;
USE SCHEMA GN_DW.MSTR;

-- [1] 공통코드 파생 뷰 6종
CREATE OR REPLACE VIEW GN_DW.MSTR.D_DVLP_DIV_CD COMMENT = '개발구분(MM015)' AS
SELECT DTL_CD_ID AS DVLP_DIV_CD, DTL_CD_NM AS DVLP_DIV_NM, SORT_ORDR, USE_YN
FROM GN_DW.MSTR.D_CMMN_DTL_CD
WHERE CD_ID = 'MM015';

CREATE OR REPLACE VIEW GN_DW.MSTR.D_CPR_DIV_CD COMMENT = '법인구분(CM019)' AS
SELECT DTL_CD_ID AS CPR_DIV_CD, DTL_CD_NM AS CPR_DIV_NM, SORT_ORDR, USE_YN
FROM GN_DW.MSTR.D_CMMN_DTL_CD
WHERE CD_ID = 'CM019';

CREATE OR REPLACE VIEW GN_DW.MSTR.D_SEX_CD COMMENT = '성별(CM013)' AS
SELECT DTL_CD_ID AS SEX_CD, DTL_CD_NM AS SEX_NM, SORT_ORDR, USE_YN
FROM GN_DW.MSTR.D_CMMN_DTL_CD
WHERE CD_ID = 'CM013';

CREATE OR REPLACE VIEW GN_DW.MSTR.D_AGE_TERM_CD COMMENT = '연령대(CM014)' AS
SELECT DTL_CD_ID AS AGE_TERM_CD, DTL_CD_NM AS AGE_TERM_NM, SORT_ORDR, USE_YN
FROM GN_DW.MSTR.D_CMMN_DTL_CD
WHERE CD_ID = 'CM014';

CREATE OR REPLACE VIEW GN_DW.MSTR.D_PR_MTH_CD COMMENT = '홍보방법(CM008)' AS
SELECT DTL_CD_ID AS PR_MTH_CD, DTL_CD_NM AS PR_MTH_NM, SORT_ORDR, USE_YN
FROM GN_DW.MSTR.D_CMMN_DTL_CD
WHERE CD_ID = 'CM008';

-- [2] 달력 파생 뷰 2종
CREATE OR REPLACE VIEW GN_DW.MSTR.D_STRD_DE_CD COMMENT = '기준일자. 9999-12-31 은 STRD_NM=N/A' AS
SELECT
  YMD                                            AS STRD_DE,
  CASE WHEN YMD = '99991231' THEN 'N/A'
       ELSE TO_CHAR(SYMD, 'YYYY-MM-DD') END      AS STRD_NM,
  TO_CHAR(DATEADD(DAY,   -1, SYMD), 'YYYYMMDD')  AS STRD_PRE_DE,
  TO_CHAR(DATEADD(MONTH, -1, SYMD), 'YYYYMMDD')  AS STRD_PRE_MT_DE,
  TO_CHAR(DATEADD(YEAR,  -1, SYMD), 'YYYYMMDD')  AS STRD_PRE_YMT_DE,
  LEFT(YMD, 6)                                   AS STRD_MT,
  QQ                                             AS STRD_QT,
  YY                                             AS STRD_YY,
  MM                                             AS MT_ID,
  TO_CHAR(CURRENT_DATE(), 'YYYYMMDD')            AS WORK_DE
FROM GN_DW.MSTR.D_STRD_CAL_CD;

CREATE OR REPLACE VIEW GN_DW.MSTR.D_STRD_MT_CD COMMENT = '기준년월' AS
SELECT DISTINCT
  LEFT(YMD, 6)                                          AS STRD_MT,
  TO_CHAR(SYMD, 'YYYY-MM')                              AS STRD_NM,
  TO_CHAR(DATEADD(MONTH, -1, SYMD), 'YYYYMM')           AS PRE_STRD_MT,
  TO_CHAR(DATEADD(YEAR,  -1, SYMD), 'YYYYMM')           AS PRE_YY_STRD_MT,
  YY                                                    AS STRD_YY,
  QQ                                                    AS STRD_QT,
  MM                                                    AS STRD_MM,
  TO_CHAR(DATEADD(YEAR, -1, SYMD), 'YYYY') || '12'      AS PRE_YY_12_MT,
  TO_CHAR(DATEADD(YEAR, -2, SYMD), 'YYYY') || '12'      AS PPRE_YY_12_MT
FROM GN_DW.MSTR.D_STRD_CAL_CD;

-- [3] 부서 계층 뷰 4종 (ACMSLT_UPPER_DEPT_ID 체인 · 루트 UPPER_DEPT_ID = ZV000000)
CREATE OR REPLACE VIEW GN_DW.MSTR.D_DEPT4_CD COMMENT = '본부/지부(4레벨)' AS
SELECT
  B.DEPT_ID AS DEPT4_ID, B.DEPT_NM AS DEPT4_NM, A.DEPT_ID AS DEPT5_ID,
  B.SORT_ORDR, B.USE_YN, B.ACMSLT_DEPT_YN,
  IFNULL(TO_CHAR(B.FRST_REGIST_DT, 'YYYYMMDD'), '19000101') AS FST_DE,
  IFNULL(TO_CHAR(B.LAST_UPDT_DT,   'YYYYMMDD'), '99991231') AS LST_DE,
  TO_CHAR(CURRENT_DATE(), 'YYYYMMDD') AS WORK_DE
FROM GN_DW.MSTR.D_CM_DEPT_INFO A
JOIN GN_DW.MSTR.D_CM_DEPT_INFO B ON B.ACMSLT_UPPER_DEPT_ID = A.DEPT_ID
WHERE A.UPPER_DEPT_ID = 'ZV000000'
  AND A.USE_YN = 'Y'
UNION ALL
SELECT 'Z~', '없음', 'Z~', 999, 'Y', 'Y', '20191101', '99991231', TO_CHAR(CURRENT_DATE(), 'YYYYMMDD');

CREATE OR REPLACE VIEW GN_DW.MSTR.D_DEPT3_CD COMMENT = '실적부서3(3레벨)' AS
SELECT
  C.DEPT_ID AS DEPT3_ID, C.DEPT_NM AS DEPT3_NM, B.DEPT_ID AS DEPT4_ID, A.DEPT_ID AS DEPT5_ID,
  C.SORT_ORDR, C.USE_YN, C.ACMSLT_DEPT_YN,
  TO_CHAR(CURRENT_DATE(), 'YYYYMMDD') AS WORK_DE
FROM GN_DW.MSTR.D_CM_DEPT_INFO A
JOIN GN_DW.MSTR.D_CM_DEPT_INFO B ON B.ACMSLT_UPPER_DEPT_ID = A.DEPT_ID
JOIN GN_DW.MSTR.D_CM_DEPT_INFO C ON C.ACMSLT_UPPER_DEPT_ID = B.DEPT_ID
WHERE A.UPPER_DEPT_ID = 'ZV000000'
  AND A.USE_YN = 'Y'
  AND C.DEPT_ID != 'ZC000029'
UNION ALL
SELECT 'Z~', '없음', 'Z~', 'Z~', 999, 'Y', 'Y', TO_CHAR(CURRENT_DATE(), 'YYYYMMDD');

CREATE OR REPLACE VIEW GN_DW.MSTR.D_DEPT2_CD COMMENT = '팀/지부(2레벨)' AS
SELECT
  D.DEPT_ID AS DEPT2_ID, D.DEPT_NM AS DEPT2_NM, C.DEPT_ID AS DEPT3_ID,
  B.DEPT_ID AS DEPT4_ID, A.DEPT_ID AS DEPT5_ID,
  D.SORT_ORDR, D.USE_YN, D.ACMSLT_DEPT_YN,
  IFNULL(TO_CHAR(D.FRST_REGIST_DT, 'YYYYMMDD'), '19000101') AS FST_DE,
  IFNULL(TO_CHAR(D.LAST_UPDT_DT,   'YYYYMMDD'), '99991231') AS LST_DE,
  TO_CHAR(CURRENT_DATE(), 'YYYYMMDD') AS WORK_DE
FROM GN_DW.MSTR.D_CM_DEPT_INFO A
JOIN GN_DW.MSTR.D_CM_DEPT_INFO B ON B.ACMSLT_UPPER_DEPT_ID = A.DEPT_ID
JOIN GN_DW.MSTR.D_CM_DEPT_INFO C ON C.ACMSLT_UPPER_DEPT_ID = B.DEPT_ID
JOIN GN_DW.MSTR.D_CM_DEPT_INFO D ON D.ACMSLT_UPPER_DEPT_ID = C.DEPT_ID
WHERE A.UPPER_DEPT_ID = 'ZV000000'
  AND A.USE_YN = 'Y'
  AND C.DEPT_ID != 'ZC000029'
UNION ALL
SELECT 'Z~', '없음', 'Z~', 'Z~', 'Z~', 999, 'Y', 'Y', '20191101', '99991231', TO_CHAR(CURRENT_DATE(), 'YYYYMMDD');

CREATE OR REPLACE VIEW GN_DW.MSTR.D_DEPT_CD COMMENT = '부서(1레벨 · 상위 2~5 매핑)' AS
SELECT
  E.DEPT_ID, E.DEPT_NM, D.DEPT_ID AS DEPT2_ID, C.DEPT_ID AS DEPT3_ID,
  B.DEPT_ID AS DEPT4_ID, A.DEPT_ID AS DEPT5_ID,
  E.SORT_ORDR, E.USE_YN, E.ACMSLT_DEPT_YN,
  IFNULL(TO_CHAR(E.FRST_REGIST_DT, 'YYYYMMDD'), '19000101') AS FST_DE,
  IFNULL(TO_CHAR(E.LAST_UPDT_DT,   'YYYYMMDD'), '99991231') AS LST_DE,
  TO_CHAR(CURRENT_DATE(), 'YYYYMMDD') AS WORK_DE
FROM GN_DW.MSTR.D_CM_DEPT_INFO A
JOIN GN_DW.MSTR.D_CM_DEPT_INFO B ON B.ACMSLT_UPPER_DEPT_ID = A.DEPT_ID
JOIN GN_DW.MSTR.D_CM_DEPT_INFO C ON C.ACMSLT_UPPER_DEPT_ID = B.DEPT_ID
JOIN GN_DW.MSTR.D_CM_DEPT_INFO D ON D.ACMSLT_UPPER_DEPT_ID = C.DEPT_ID
JOIN GN_DW.MSTR.D_CM_DEPT_INFO E ON E.ACMSLT_UPPER_DEPT_ID = D.DEPT_ID
WHERE A.UPPER_DEPT_ID = 'ZV000000'
  AND A.USE_YN = 'Y'
  AND C.DEPT_ID != 'ZC000029'
UNION ALL
SELECT 'Z~', '없음', 'Z~', 'Z~', 'Z~', 'Z~', 999, 'Y', 'Y', '20191101', '99991231', TO_CHAR(CURRENT_DATE(), 'YYYYMMDD');

-- [4] 상위캠페인
CREATE OR REPLACE VIEW GN_DW.MSTR.D_UP_CMPGN_CD COMMENT = '상위캠페인(UPPER_CMPGN_YN=Y) + 없음' AS
SELECT
  CMPGN_CD AS UPPER_CMPGN_CD,
  CMPGN_NM AS UPPER_CMPGN_NM,
  ROW_NUMBER() OVER (ORDER BY CMPGN_CD) AS SORT_ORDR,
  USE_YN
FROM GN_DW.MSTR.D_CMPGN_CD
WHERE UPPER_CMPGN_YN = 'Y'
UNION ALL
SELECT 'Z~', '없음', 99999, 'Y';

-- [5] 후원사업 원장 뷰 (BRONZE 직접 참조 · 함수 2종이 사용)
CREATE OR REPLACE VIEW GN_DW.MSTR.D_SPNSR_BSNS_V COMMENT = '후원·후원사업 결합. DSC_DE 미중단 = 99991231' AS
SELECT
  TO_CHAR(A.FRST_REGIST_DT, 'YYYYMM')   AS STRD_MT,
  A.SPNSR_NO,
  B.SPNSR_BSNS_NO,
  B.SPNSR_BSNS_ID,
  A.MBER_NO,
  A.CMPGN_CD,
  A.ACMSLT_DEPT_CD,
  A.JOIN_PATH_CD,
  A.FRST_RGSTR_ID,
  TO_CHAR(A.FRST_REGIST_DT, 'YYYYMMDD') AS FST_DE,
  B.SPNSR_AMT,
  IFNULL(B.SPNSR_DSCNTC_DE, '99991231') AS DSC_DE,
  B.SPNSR_DSCNTC_YN,
  B.SPNSR_DSCNTC_RSN_CD
FROM GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_SPNSR A
JOIN GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_SPNSR_BSNS B
  ON A.SPNSR_NO = B.SPNSR_NO;
