-- Co-authored with CoCo
-- =====================================================================
-- 03. GN_DW.MSTR 함수 (O197) — 원본 = mstr DDL 원본/1차 이관대상 관련 추출/function_script.sql
--   T-SQL Inline TVF → Snowflake SQL UDTF (RETURNS TABLE · 반환 컬럼 명시)
--   🔴 원본은 UNION ALL 분기마다 SELECT * 로 **위치 기준** 정렬한다 ⇒ 분기별 컬럼 순서를 명시 목록으로 고정
--      (분기 앞 9컬럼 = ACMSLT_DEPT_CD2·DVLP_DIV_CD2·RNUM(감액·중단 = SNUM)·RAMT·AAMT·DAMT·SAMT·MAMT·STRD_MT)
--   🔴 BRONZE 테이블의 메타 컬럼(_LOAD_DT·_BATCH_ID·_STDR_YM)은 SELECT * 로 끌어오지 않도록 명시 컬럼만 사용
--   선행 = 02 의 GN_DW.MSTR.D_SPNSR_BSNS_V
-- =====================================================================
USE ROLE GN_DW_ADMIN;
USE SCHEMA GN_DW.MSTR;

-- [1] FN_MM_ACT_DATE — 기준월 말일에 활동 중인 정기회원과 실제 활동종료일
--     ⚠️ 현재 USP_F_MM_SPNSR_DVLP_SUM 에서는 호출부가 주석 처리돼 있다(원본 동일) — 정의만 이관
CREATE OR REPLACE FUNCTION GN_DW.MSTR.FN_MM_ACT_DATE(STRD_MT VARCHAR)
RETURNS TABLE (
  MBER_NO          VARCHAR,
  STDR_DE          DATE,
  FRST_REGIST_DT   TIMESTAMP_NTZ,
  SPNSR_DSCNTC_DE  VARCHAR,
  RE_SPNSR_DE      VARCHAR,
  ACTUALDT         DATE
)
COMMENT = 'MSTR 이관 — 기준월 활동 정기회원 + 실제활동종료일. 원천 BRONZE_CRM'
AS
$$
  SELECT
    T1.MBER_NO,
    T1.STDR_DE,
    T1.FRST_REGIST_DT,
    T2.SPNSR_DSCNTC_DE,
    T2.RE_SPNSR_DE,
    T2.ACTUALDT
  FROM GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_INFO T1
  JOIN (
    SELECT DISTINCT MBER_NO
    FROM GN_DW.MSTR.D_SPNSR_BSNS_V
    WHERE FST_DE <= STRD_MT || '31'
      AND (DSC_DE IS NULL OR DSC_DE > STRD_MT || '31')
  ) T3
    ON T1.MBER_NO = T3.MBER_NO
  LEFT JOIN (
    SELECT
      D.MBER_NO,
      D.SPNSR_DSCNTC_DE,
      R.RE_SPNSR_DE,
      CASE
        WHEN R.RE_SPNSR_DE IS NULL THEN DATEADD(DAY, -1, TO_DATE(D.SPNSR_DSCNTC_DE, 'YYYYMMDD'))
        WHEN D.SPNSR_DSCNTC_DE > R.RE_SPNSR_DE THEN DATEADD(DAY, -1, TO_DATE(D.SPNSR_DSCNTC_DE, 'YYYYMMDD'))
        WHEN TO_DATE(R.RE_SPNSR_DE, 'YYYYMMDD') < LAST_DAY(TO_DATE(STRD_MT || '01', 'YYYYMMDD'))
          THEN LAST_DAY(TO_DATE(STRD_MT || '01', 'YYYYMMDD'))
        ELSE TO_DATE(R.RE_SPNSR_DE, 'YYYYMMDD')
      END AS ACTUALDT
    FROM (
      SELECT MBER_NO, SPNSR_DSCNTC_DE
      FROM GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_SPNSR_DSCNTC
      WHERE SPNSR_DSCNTC_DE <= STRD_MT || '31'
      QUALIFY ROW_NUMBER() OVER (PARTITION BY MBER_NO ORDER BY SPNSR_DSCNTC_DE DESC) = 1
    ) D
    LEFT JOIN (
      SELECT MBER_NO, RE_SPNSR_DE
      FROM GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_RE_SPNSR
      WHERE RE_SPNSR_DE <= STRD_MT || '31'
      QUALIFY ROW_NUMBER() OVER (PARTITION BY MBER_NO ORDER BY RE_SPNSR_DE DESC) = 1
    ) R
      ON D.MBER_NO = R.MBER_NO
  ) T2
    ON T1.MBER_NO = T2.MBER_NO
  WHERE LAST_DAY(TO_DATE(STRD_MT || '01', 'YYYYMMDD'))
        BETWEEN T1.FRST_REGIST_DT::DATE AND IFNULL(T2.ACTUALDT, '9999-12-31'::DATE)
$$;

-- [2] FN_MM_SPNSR_DVLP — 기준월까지의 개발 실적(신규/재후원 · 증액 · 감액 · 중단)
CREATE OR REPLACE FUNCTION GN_DW.MSTR.FN_MM_SPNSR_DVLP(P_STRD_MT VARCHAR)
RETURNS TABLE (
  ACMSLT_DEPT_CD2      VARCHAR,
  DVLP_DIV_CD2         VARCHAR,
  RNUM                 NUMBER,
  SAMT                 NUMBER,
  MAMT                 NUMBER,
  STRD_MT              VARCHAR,
  SPNSR_NO             VARCHAR,
  SPNSR_BSNS_NO        NUMBER,
  OCCRRNC_DE           VARCHAR,
  SER_NO               NUMBER,
  MBER_NO              VARCHAR,
  ACT_DEPT_CD          VARCHAR,
  ACMSLT_DEPT_CD       VARCHAR,
  CMPGN_CD             VARCHAR,
  SETLE_CD             VARCHAR,
  MBER_DIV_CD          VARCHAR,
  SEX                  VARCHAR,
  AREA_CD              VARCHAR,
  AGE                  NUMBER,
  SPNSR_TIME_CO        NUMBER,
  SPNSR_AMT_CD         VARCHAR,
  SPNSR_BSNS_ID        VARCHAR,
  CANCL_RDCAMT_RSN_CD  VARCHAR,
  SPNSR_AMT            NUMBER,
  DVLP_DIV_CD          VARCHAR,
  FRST_RGSTR_ID        VARCHAR,
  FRST_RGSTR_NM        VARCHAR,
  PRE_CMPGN_CD         VARCHAR
)
COMMENT = 'MSTR 이관 — 기준월 이하 개발실적(1·4 신규재후원 / 2 증액 / 3 감액 / 5 중단). 원천 BRONZE_CRM.TM_MM_FDRM_MBER_DVLP_AMT'
AS
$$
  WITH BASE AS (
    -- 🔴 STRD_MT 를 맨 앞에 둔다: 분기 B1·B3·B4 의 「…, MAMT, A.*」 가 B2 의 「…, MAMT, STRD_MT, 원천」 과 위치 일치
    SELECT
      LEFT(OCCRRNC_DE, 6) AS STRD_MT,
      SPNSR_NO, SPNSR_BSNS_NO, OCCRRNC_DE, SER_NO, MBER_NO, ACT_DEPT_CD, ACMSLT_DEPT_CD,
      CMPGN_CD, SETLE_CD, MBER_DIV_CD, SEX, AREA_CD, AGE, SPNSR_TIME_CO, SPNSR_AMT_CD,
      SPNSR_BSNS_ID, CANCL_RDCAMT_RSN_CD, SPNSR_AMT, DVLP_DIV_CD, FRST_RGSTR_ID, FRST_RGSTR_NM
    FROM GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_DVLP_AMT
  ),
  -- (1) 신규 / 재후원 (DVLP_DIV_CD 1·4 · 미중단 후원사업)
  B1 AS (
    SELECT
      A.ACMSLT_DEPT_CD AS ACMSLT_DEPT_CD2, A.DVLP_DIV_CD AS DVLP_DIV_CD2, 1 AS RNUM,
      0 AS RAMT, 0 AS AAMT, 0 AS DAMT, 0 AS SAMT,
      SUM(A.SPNSR_AMT) OVER (PARTITION BY A.SPNSR_NO, A.SPNSR_BSNS_NO, A.STRD_MT) AS MAMT,
      A.*
    FROM BASE A
    JOIN GN_DW.MSTR.D_SPNSR_BSNS_V B
      ON A.SPNSR_NO = B.SPNSR_NO
     AND A.SPNSR_BSNS_NO = B.SPNSR_BSNS_NO
     AND B.DSC_DE > A.STRD_MT || '31'
    WHERE A.DVLP_DIV_CD IN ('1', '4')
    QUALIFY MAMT > 0
  ),
  -- (2) 증액: 회원 월 SUM > 0 · 후원사업 SUM 증액 · 누적 - |감액| > 0 · 최소값 선택
  B2_A AS (
    SELECT
      SUM(CASE WHEN DVLP_DIV_CD IN ('2', '3') THEN SPNSR_AMT ELSE 0 END)
        OVER (PARTITION BY SPNSR_NO, SPNSR_BSNS_NO, STRD_MT) AS SAMT,
      SUM(SPNSR_AMT) OVER (PARTITION BY MBER_NO, STRD_MT) AS MAMT,
      BASE.*
    FROM BASE
    WHERE DVLP_DIV_CD IN ('2', '3', '5')
  ),
  B2_B AS (
    SELECT
      SUM(CASE WHEN DVLP_DIV_CD = '3' THEN SPNSR_AMT ELSE 0 END)
        OVER (PARTITION BY MBER_NO, STRD_MT) AS DAMT,
      B2_A.*
    FROM B2_A
    WHERE MAMT > 0
      AND ((SAMT > 0 AND DVLP_DIV_CD = '2') OR (SAMT < 0 AND DVLP_DIV_CD = '3'))
  ),
  B2_C AS (
    SELECT
      -- 프레임 미지정 = RANGE UNBOUNDED PRECEDING(동순위 합산) — SQL Server 원본 기본값과 동일
      SUM(SAMT) OVER (PARTITION BY MBER_NO, STRD_MT ORDER BY OCCRRNC_DE, SER_NO) AS AAMT,
      B2_B.*
    FROM B2_B
    WHERE DVLP_DIV_CD = '2'
  ),
  B2 AS (
    SELECT DISTINCT
      ACMSLT_DEPT_CD AS ACMSLT_DEPT_CD2, '2' AS DVLP_DIV_CD2,
      ROW_NUMBER() OVER (PARTITION BY STRD_MT, SPNSR_NO, SPNSR_BSNS_NO ORDER BY SER_NO) AS RNUM,
      CASE
        WHEN MAMT <= SAMT AND AAMT + DAMT <= MAMT THEN AAMT + DAMT
        WHEN MAMT >  SAMT AND AAMT + DAMT <= SAMT THEN AAMT + DAMT
        WHEN MAMT <= SAMT THEN MAMT
        ELSE SAMT
      END AS RAMT,
      AAMT, DAMT, SAMT, MAMT, STRD_MT,
      SPNSR_NO, SPNSR_BSNS_NO, OCCRRNC_DE, SER_NO, MBER_NO, ACT_DEPT_CD, ACMSLT_DEPT_CD,
      CMPGN_CD, SETLE_CD, MBER_DIV_CD, SEX, AREA_CD, AGE, SPNSR_TIME_CO, SPNSR_AMT_CD,
      SPNSR_BSNS_ID, CANCL_RDCAMT_RSN_CD, SPNSR_AMT, DVLP_DIV_CD, FRST_RGSTR_ID, FRST_RGSTR_NM
    FROM B2_C
    WHERE AAMT - ABS(DAMT) > 0
  ),
  -- (3) 감액: 회원 월 SUM < 0 · 후원번호 역순 1건
  B3 AS (
    SELECT
      ACMSLT_DEPT_CD AS ACMSLT_DEPT_CD2, '3' AS DVLP_DIV_CD2,
      ROW_NUMBER() OVER (PARTITION BY MBER_NO, STRD_MT ORDER BY SPNSR_NO DESC) AS RNUM,
      0 AS RAMT, 0 AS AAMT, 0 AS DAMT, 0 AS SAMT,
      SUM(SPNSR_AMT) OVER (PARTITION BY MBER_NO, STRD_MT) AS MAMT,
      BASE.*
    FROM BASE
    WHERE DVLP_DIV_CD IN ('2', '3')
    QUALIFY MAMT < 0 AND RNUM = 1
  ),
  -- (4) 중단: 중단일자와 일치하는 DVLP_DIV_CD 5 · 일련번호 역순 1건
  B4 AS (
    SELECT
      A.ACMSLT_DEPT_CD AS ACMSLT_DEPT_CD2, A.DVLP_DIV_CD AS DVLP_DIV_CD2,
      ROW_NUMBER() OVER (PARTITION BY A.MBER_NO, A.SPNSR_NO, A.SPNSR_BSNS_NO, A.STRD_MT
                         ORDER BY A.SER_NO DESC) AS RNUM,
      0 AS RAMT, 0 AS AAMT, 0 AS DAMT, 0 AS SAMT,
      SUM(A.SPNSR_AMT) OVER (PARTITION BY A.MBER_NO, A.SPNSR_NO, A.SPNSR_BSNS_NO, A.STRD_MT) AS MAMT,
      A.*
    FROM BASE A
    JOIN (
      SELECT DISTINCT MBER_NO, SPNSR_DSCNTC_DE
      FROM GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_SPNSR_DSCNTC
    ) B
      ON A.MBER_NO = B.MBER_NO
     AND A.OCCRRNC_DE = B.SPNSR_DSCNTC_DE
    WHERE A.DVLP_DIV_CD = '5'
    QUALIFY RNUM = 1
  ),
  T AS (
    SELECT * FROM B1 UNION ALL
    SELECT * FROM B2 UNION ALL
    SELECT * FROM B3 UNION ALL
    SELECT * FROM B4
  )
  SELECT
    ACMSLT_DEPT_CD2,
    DVLP_DIV_CD2,
    RNUM,
    SAMT,
    MAMT,
    STRD_MT,
    SPNSR_NO,
    SPNSR_BSNS_NO,
    OCCRRNC_DE,
    SER_NO,
    MBER_NO,
    ACT_DEPT_CD,
    IFNULL(ACMSLT_DEPT_CD2, 'Z~') AS ACMSLT_DEPT_CD,
    CMPGN_CD,
    SETLE_CD,
    MBER_DIV_CD,
    SEX,
    AREA_CD,
    AGE,
    SPNSR_TIME_CO,
    SPNSR_AMT_CD,
    SPNSR_BSNS_ID,
    CANCL_RDCAMT_RSN_CD,
    CASE WHEN DVLP_DIV_CD2 = '2' THEN RAMT
         WHEN DVLP_DIV_CD2 IN ('3', '5') THEN MAMT
         ELSE SPNSR_AMT END AS SPNSR_AMT,
    DVLP_DIV_CD2 AS DVLP_DIV_CD,
    FRST_RGSTR_ID,
    FRST_RGSTR_NM,
    LAG(CMPGN_CD, 1) OVER (PARTITION BY SPNSR_NO, SPNSR_BSNS_NO ORDER BY OCCRRNC_DE) AS PRE_CMPGN_CD
  FROM T
  WHERE STRD_MT <= P_STRD_MT
$$;
