use role gn_dw_admin;
-- Co-authored with CoCo
-- =====================================================================
-- 05. MSTR 1차 이관 대상 리포트 쿼리 — Snowflake 전환본 (O197)
--   원본 = mstr DDL 원본/1차 이관대상 관련 추출/mstr 1차 이관 대상 쿼리.sql
--   변환: mart.X → GN_DW.MSTR.X (SELECT·JOIN·GROUP BY 는 ANSI 그대로)
--   🟢 ExplCampList 영향 없음 — 이 쿼리는 SPCL_CMPGN_YN · CMPGN_CLS1~3_CD 를 쓰지 않는다
--   선행 = CALL GN_DW.MSTR.USP_RUN_MSTR_1ST('202601', 'POC', TRUE);
-- =====================================================================

-- [1] 원본 SQL (일별 · 2026-01 · 개발구분 1·2·4)
SELECT
  a11.STRD_MT              AS STRD_MT,
  MAX(a117.STRD_NM)        AS STRD_NM,
  a11.OCCRRNC_DE           AS STRD_DE,
  MAX(a13.STRD_NM)         AS STRD_NM0,
  a11.ACMSLT_DEPT4_CD      AS DEPT4_ID,
  MAX(a15.DEPT4_NM)        AS DEPT4_NM,
  MAX(a15.SORT_ORDR)       AS SORT_ORDR,
  a11.ACMSLT_DEPT3_CD      AS DEPT3_ID,
  MAX(a18.DEPT3_NM)        AS DEPT3_NM,
  MAX(a18.SORT_ORDR)       AS SORT_ORDR0,
  a11.ACMSLT_DEPT2_CD      AS DEPT2_ID,
  MAX(a113.DEPT2_NM)       AS DEPT2_NM,
  MAX(a113.SORT_ORDR)      AS SORT_ORDR1,
  a11.DVLP_DIV_CD          AS DVLP_DIV_CD,
  MAX(a12.DVLP_DIV_NM)     AS DVLP_DIV_NM,
  MAX(a12.SORT_ORDR)       AS SORT_ORDR2,
  a11.BRND_ID              AS BRND_ID,
  MAX(a17.BRND_NM)         AS BRND_NM,
  a11.CMPGN_CD             AS CMPGN_CD,
  MAX(a112.CMPGN_NM)       AS CMPGN_NM,
  a11.UPPER_CMPGN_CD       AS UPPER_CMPGN_CD,
  MAX(a19.UPPER_CMPGN_NM)  AS UPPER_CMPGN_NM,
  MAX(a19.SORT_ORDR)       AS SORT_ORDR3,
  a11.PR_MTH_CD            AS PR_MTH_CD,
  MAX(a114.PR_MTH_NM)      AS PR_MTH_NM,
  a11.CPR_DIV_CD           AS CPR_DIV_CD,
  MAX(a14.CPR_DIV_NM)      AS CPR_DIV_NM,
  a11.SPNSR_BSNS_ID        AS SPNSR_BSNS_ID,
  MAX(a115.SPNSR_BSNS_NM)  AS SPNSR_BSNS_NM,
  MAX(a115.SORT_ORDR)      AS SORT_ORDR4,
  a11.SPNSR_BSNS2_ID       AS SPNSR_BSNS2_ID,
  MAX(a116.SPNSR_BSNS_NM)  AS SPNSR_BSNS_NM0,
  MAX(a116.SORT_ORDR)      AS SORT_ORDR5,
  a11.ACMSLT_DEPT_CD       AS DEPT_ID,
  MAX(a16.DEPT_NM)         AS DEPT_NM,
  a11.SEX                  AS SEX_CD,
  MAX(a110.SEX_NM)         AS SEX_NM,
  MAX(a110.SORT_ORDR)      AS SORT_ORDR6,
  a11.AGE_TERM_CD          AS AGE_TERM_CD,
  MAX(a111.AGE_TERM_NM)    AS AGE_TERM_NM,
  MAX(a111.SORT_ORDR)      AS SORT_ORDR7,
  SUM(a11.SPNSR_AMT_CNT)   AS WJXBFS1,
  COUNT(DISTINCT a11.MBER_NO) AS WJXBFS2,
  SUM(a11.SPNSR_AMT)       AS WJXBFS3
FROM GN_DW.MSTR.F_MM_SPNSR_DVLP_SUM a11
LEFT JOIN GN_DW.MSTR.D_DVLP_DIV_CD     a12  ON a11.DVLP_DIV_CD     = a12.DVLP_DIV_CD
LEFT JOIN GN_DW.MSTR.D_STRD_DE_CD      a13  ON a11.OCCRRNC_DE      = a13.STRD_DE
LEFT JOIN GN_DW.MSTR.D_CPR_DIV_CD      a14  ON a11.CPR_DIV_CD      = a14.CPR_DIV_CD
LEFT JOIN GN_DW.MSTR.D_DEPT4_CD        a15  ON a11.ACMSLT_DEPT4_CD = a15.DEPT4_ID
LEFT JOIN GN_DW.MSTR.D_DEPT_CD         a16  ON a11.ACMSLT_DEPT_CD  = a16.DEPT_ID
LEFT JOIN GN_DW.MSTR.D_BRND_CD         a17  ON a11.BRND_ID         = a17.BRND_ID
LEFT JOIN GN_DW.MSTR.D_DEPT3_CD        a18  ON a11.ACMSLT_DEPT3_CD = a18.DEPT3_ID
LEFT JOIN GN_DW.MSTR.D_UP_CMPGN_CD     a19  ON a11.UPPER_CMPGN_CD  = a19.UPPER_CMPGN_CD
LEFT JOIN GN_DW.MSTR.D_SEX_CD          a110 ON a11.SEX             = a110.SEX_CD
LEFT JOIN GN_DW.MSTR.D_AGE_TERM_CD     a111 ON a11.AGE_TERM_CD     = a111.AGE_TERM_CD
LEFT JOIN GN_DW.MSTR.D_CMPGN_CD        a112 ON a11.CMPGN_CD        = a112.CMPGN_CD
LEFT JOIN GN_DW.MSTR.D_DEPT2_CD        a113 ON a11.ACMSLT_DEPT2_CD = a113.DEPT2_ID
LEFT JOIN GN_DW.MSTR.D_PR_MTH_CD       a114 ON a11.PR_MTH_CD       = a114.PR_MTH_CD
LEFT JOIN GN_DW.MSTR.D_SPNSR_BSNS_INFO a115 ON a11.SPNSR_BSNS_ID   = a115.SPNSR_BSNS_ID
LEFT JOIN GN_DW.MSTR.D_SPNSR_BSNS_INFO a116 ON a11.SPNSR_BSNS2_ID  = a116.SPNSR_BSNS_ID
LEFT JOIN GN_DW.MSTR.D_STRD_MT_CD      a117 ON a11.STRD_MT         = a117.STRD_MT
WHERE a11.OCCRRNC_DE >= '20260101'
  AND a11.OCCRRNC_DE <= '20260131'
  AND a11.DVLP_DIV_CD IN ('1', '2', '4')
GROUP BY
  a11.STRD_MT, a11.OCCRRNC_DE, a11.ACMSLT_DEPT4_CD, a11.ACMSLT_DEPT3_CD, a11.ACMSLT_DEPT2_CD,
  a11.DVLP_DIV_CD, a11.BRND_ID, a11.CMPGN_CD, a11.UPPER_CMPGN_CD, a11.PR_MTH_CD, a11.CPR_DIV_CD,
  a11.SPNSR_BSNS_ID, a11.SPNSR_BSNS2_ID, a11.ACMSLT_DEPT_CD, a11.SEX, a11.AGE_TERM_CD;

-- [2] MSTR 분석엔진 계산 단계 (원본 [분석엔진 계산 단계] 블록 — SQL 이 아니므로 아래로 대체)
--   1) 동적 집계: <사업부/시도권역, 홍보방법, 후원사업> 을 제외한 12개 속성으로 재집계
--   2) cross-tab: MSTR 화면 렌더링 — Snowflake 에서는 결과셋까지만 제공
--   🔴 [개발(명)] = COUNT(DISTINCT MBER_NO) 는 비가산이라 [1] 결과를 다시 SUM 하면 틀린다
--      ⇒ 원천 팩트에서 12개 속성으로 직접 재집계한다(MSTR 엔진 결과와의 차이는 검증 대상)
SELECT
  a11.DVLP_DIV_CD, MAX(a12.DVLP_DIV_NM) AS DVLP_DIV_NM, MAX(a12.SORT_ORDR) AS DVLP_SORT,
  a11.STRD_MT, MAX(a117.STRD_NM) AS STRD_MT_NM,
  a11.OCCRRNC_DE AS STRD_DE, MAX(a13.STRD_NM) AS STRD_DE_NM,
  a11.CPR_DIV_CD, MAX(a14.CPR_DIV_NM) AS CPR_DIV_NM,
  a11.ACMSLT_DEPT4_CD AS DEPT4_ID, MAX(a15.DEPT4_NM) AS DEPT4_NM, MAX(a15.SORT_ORDR) AS DEPT4_SORT,
  a11.ACMSLT_DEPT_CD AS DEPT_ID, MAX(a16.DEPT_NM) AS DEPT_NM,
  a11.BRND_ID, MAX(a17.BRND_NM) AS BRND_NM,
  a11.UPPER_CMPGN_CD, MAX(a19.UPPER_CMPGN_NM) AS UPPER_CMPGN_NM, MAX(a19.SORT_ORDR) AS UPPER_CMPGN_SORT,
  a11.SEX AS SEX_CD, MAX(a110.SEX_NM) AS SEX_NM, MAX(a110.SORT_ORDR) AS SEX_SORT,
  a11.AGE_TERM_CD, MAX(a111.AGE_TERM_NM) AS AGE_TERM_NM, MAX(a111.SORT_ORDR) AS AGE_TERM_SORT,
  a11.CMPGN_CD, MAX(a112.CMPGN_NM) AS CMPGN_NM,
  a11.ACMSLT_DEPT2_CD AS DEPT2_ID, MAX(a113.DEPT2_NM) AS DEPT2_NM, MAX(a113.SORT_ORDR) AS DEPT2_SORT,
  a11.SPNSR_BSNS2_ID, MAX(a116.SPNSR_BSNS_NM) AS SPNSR_BSNS2_NM, MAX(a116.SORT_ORDR) AS SPNSR_BSNS2_SORT,
  SUM(a11.SPNSR_AMT_CNT)      AS "개발(건)",
  COUNT(DISTINCT a11.MBER_NO) AS "개발(명)"
FROM GN_DW.MSTR.F_MM_SPNSR_DVLP_SUM a11
LEFT JOIN GN_DW.MSTR.D_DVLP_DIV_CD     a12  ON a11.DVLP_DIV_CD     = a12.DVLP_DIV_CD
LEFT JOIN GN_DW.MSTR.D_STRD_DE_CD      a13  ON a11.OCCRRNC_DE      = a13.STRD_DE
LEFT JOIN GN_DW.MSTR.D_CPR_DIV_CD      a14  ON a11.CPR_DIV_CD      = a14.CPR_DIV_CD
LEFT JOIN GN_DW.MSTR.D_DEPT4_CD        a15  ON a11.ACMSLT_DEPT4_CD = a15.DEPT4_ID
LEFT JOIN GN_DW.MSTR.D_DEPT_CD         a16  ON a11.ACMSLT_DEPT_CD  = a16.DEPT_ID
LEFT JOIN GN_DW.MSTR.D_BRND_CD         a17  ON a11.BRND_ID         = a17.BRND_ID
LEFT JOIN GN_DW.MSTR.D_UP_CMPGN_CD     a19  ON a11.UPPER_CMPGN_CD  = a19.UPPER_CMPGN_CD
LEFT JOIN GN_DW.MSTR.D_SEX_CD          a110 ON a11.SEX             = a110.SEX_CD
LEFT JOIN GN_DW.MSTR.D_AGE_TERM_CD     a111 ON a11.AGE_TERM_CD     = a111.AGE_TERM_CD
LEFT JOIN GN_DW.MSTR.D_CMPGN_CD        a112 ON a11.CMPGN_CD        = a112.CMPGN_CD
LEFT JOIN GN_DW.MSTR.D_DEPT2_CD        a113 ON a11.ACMSLT_DEPT2_CD = a113.DEPT2_ID
LEFT JOIN GN_DW.MSTR.D_SPNSR_BSNS_INFO a116 ON a11.SPNSR_BSNS2_ID  = a116.SPNSR_BSNS_ID
LEFT JOIN GN_DW.MSTR.D_STRD_MT_CD      a117 ON a11.STRD_MT         = a117.STRD_MT
WHERE a11.OCCRRNC_DE BETWEEN '20260101' AND '20260131'
  AND a11.DVLP_DIV_CD IN ('1', '2', '4')
GROUP BY
  a11.DVLP_DIV_CD, a11.STRD_MT, a11.OCCRRNC_DE, a11.CPR_DIV_CD, a11.ACMSLT_DEPT4_CD,
  a11.ACMSLT_DEPT_CD, a11.BRND_ID, a11.UPPER_CMPGN_CD, a11.SEX, a11.AGE_TERM_CD,
  a11.CMPGN_CD, a11.ACMSLT_DEPT2_CD, a11.SPNSR_BSNS2_ID;
