-- ERP_BUDGET: 월별 예산 wide→long 언피벗 (12개월 UNION ALL, MD5 키로 ERP_BUDGET_ITEM FK 정합), 정본 09 STEP4.
-- Co-authored with CoCo
-- FK: BUDGET_ITEM_DK → ERP_BUDGET_ITEM (동일 MD5 식). Snowflake LATERAL VALUES 상관제약 회피 위해 CTE+UNION.
WITH B AS (
  SELECT
    MD5(COALESCE(TO_VARCHAR(YEAR),'')||'|'||COALESCE(INCOME_EXPS_DIV_NM,'')||'|'||COALESCE(BDGT_UNIT_NM,'')||'|'||
        COALESCE(JANG_NM,'')||'|'||COALESCE(KWAN_NM,'')||'|'||COALESCE(HANG_NM,'')||'|'||
        COALESCE(MOK_NM,'')||'|'||COALESCE(DTL_ITEM_NM,'')||'|'||COALESCE(SUBDTL_ITEM_NM,'')||'|'||COALESCE(FUND_SOURCE_NM,'')) AS BUDGET_ITEM_DK,
    TRY_TO_NUMBER(YEAR) AS BUDGET_YEAR, TO_VARCHAR(YEAR) AS YEAR_TXT, *
  FROM {{ source('bronze_erp','BDGT_ACMSLT_LEDGER') }}
  WHERE INCOME_EXPS_DIV_NM <> 'TOTAL'
),
U AS (
  SELECT BUDGET_ITEM_DK,BUDGET_YEAR,1 MONTH_NO,YEAR_BDGT_AMT_1 YB,CHN_BDGT_AMT_1 CB,ADJ_BDGT_AMT_1 AB,EXEC_AMT_1 EX,YEAR_TXT FROM B
  UNION ALL SELECT BUDGET_ITEM_DK,BUDGET_YEAR,2,YEAR_BDGT_AMT_2,CHN_BDGT_AMT_2,ADJ_BDGT_AMT_2,EXEC_AMT_2,YEAR_TXT FROM B
  UNION ALL SELECT BUDGET_ITEM_DK,BUDGET_YEAR,3,YEAR_BDGT_AMT_3,CHN_BDGT_AMT_3,ADJ_BDGT_AMT_3,EXEC_AMT_3,YEAR_TXT FROM B
  UNION ALL SELECT BUDGET_ITEM_DK,BUDGET_YEAR,4,YEAR_BDGT_AMT_4,CHN_BDGT_AMT_4,ADJ_BDGT_AMT_4,EXEC_AMT_4,YEAR_TXT FROM B
  UNION ALL SELECT BUDGET_ITEM_DK,BUDGET_YEAR,5,YEAR_BDGT_AMT_5,CHN_BDGT_AMT_5,ADJ_BDGT_AMT_5,EXEC_AMT_5,YEAR_TXT FROM B
  UNION ALL SELECT BUDGET_ITEM_DK,BUDGET_YEAR,6,YEAR_BDGT_AMT_6,CHN_BDGT_AMT_6,ADJ_BDGT_AMT_6,EXEC_AMT_6,YEAR_TXT FROM B
  UNION ALL SELECT BUDGET_ITEM_DK,BUDGET_YEAR,7,YEAR_BDGT_AMT_7,CHN_BDGT_AMT_7,ADJ_BDGT_AMT_7,EXEC_AMT_7,YEAR_TXT FROM B
  UNION ALL SELECT BUDGET_ITEM_DK,BUDGET_YEAR,8,YEAR_BDGT_AMT_8,CHN_BDGT_AMT_8,ADJ_BDGT_AMT_8,EXEC_AMT_8,YEAR_TXT FROM B
  UNION ALL SELECT BUDGET_ITEM_DK,BUDGET_YEAR,9,YEAR_BDGT_AMT_9,CHN_BDGT_AMT_9,ADJ_BDGT_AMT_9,EXEC_AMT_9,YEAR_TXT FROM B
  UNION ALL SELECT BUDGET_ITEM_DK,BUDGET_YEAR,10,YEAR_BDGT_AMT_10,CHN_BDGT_AMT_10,ADJ_BDGT_AMT_10,EXEC_AMT_10,YEAR_TXT FROM B
  UNION ALL SELECT BUDGET_ITEM_DK,BUDGET_YEAR,11,YEAR_BDGT_AMT_11,CHN_BDGT_AMT_11,ADJ_BDGT_AMT_11,EXEC_AMT_11,YEAR_TXT FROM B
  UNION ALL SELECT BUDGET_ITEM_DK,BUDGET_YEAR,12,YEAR_BDGT_AMT_12,CHN_BDGT_AMT_12,ADJ_BDGT_AMT_12,EXEC_AMT_12,YEAR_TXT FROM B
)
SELECT
  BUDGET_ITEM_DK                          AS BUDGET_ITEM_DK,
  BUDGET_YEAR                             AS BUDGET_YEAR,
  MONTH_NO                                AS MONTH_NO,
  YEAR_TXT||LPAD(TO_VARCHAR(MONTH_NO),2,'0') AS MONTH_KEY,
  YB                                      AS YEAR_BUDGET_AMT,
  CB                                      AS CHN_BUDGET_AMT,
  AB                                      AS ADJ_BUDGET_AMT,
  EX                                      AS EXEC_AMT,
  'ERP'                                   AS DW_SOURCE_SYSTEM,
  'BRONZE_ERP.BDGT_ACMSLT_LEDGER'         AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP()                     AS DW_LOAD_TS,
  CURRENT_TIMESTAMP()                     AS DW_UPDATE_TS,
  NULL                                    AS DW_BATCH_ID
FROM U
