create or replace view DIM_MEMBER_CURRENT(
	MEMBER_SK,
	MEMBER_DK,
	SEX,
	SEX_NM,
	GENDER_NAME,
	REGION,
	AGE_BAND,
	MBER_STAT_CD,
	MBER_DIV_CD,
	MEMBER_TYPE_NAME,
	MEMBER_STATUS_NAME,
	MEMBER_STATUS_GROUP,
	FIRST_JOIN_DATE,
	FIRST_CAMPAIGN,
	JOIN_PATH_CD,
	ENROLL_PATH_NAME,
	FIRST_SPONSORSHIP,
	LAST_STOP_DATE,
	EFFECTIVE_FROM
) COMMENT='GOLD.DIM_MEMBER SCD2 현재행(IS_CURRENT=TRUE)만 추출 — 1:1 회원조인(fan-out 차단). PK=MEMBER_DK. SV 전용 — 분석가용은 GOLD.DIM_MEMBER_CURRENT.'
 as
SELECT
    MEMBER_SK,
    MEMBER_DK,
    -- [2026-08-03 O26] 코드=BRONZE 원천명 / 라벨=분석 용어. GENDER→SEX · MEMBER_STATUS→MBER_STAT_CD
    --   · MEMBER_TYPE→MBER_DIV_CD · ENROLL_PATH→JOIN_PATH_CD. SEX_NM(CM013 원천 라벨) 신설.
    SEX,
    SEX_NM,
    GENDER_NAME,
    REGION,
    AGE_BAND,
    MBER_STAT_CD,
    MBER_DIV_CD,
    MEMBER_TYPE_NAME,
    MEMBER_STATUS_NAME,
    MEMBER_STATUS_GROUP,
    FIRST_JOIN_DATE,
    FIRST_CAMPAIGN,
    JOIN_PATH_CD,
    ENROLL_PATH_NAME,
    FIRST_SPONSORSHIP,
    LAST_STOP_DATE,
    EFFECTIVE_FROM
FROM GN_DW.GOLD.DIM_MEMBER
WHERE IS_CURRENT = TRUE;
