create or replace view FACT_AD_COMBINED(
	AD_PERF_DK,
	PERF_DATE_SK,
	CAMPAIGN_SK,
	MKTG_CAMPAIGN_SK,
	AD_CREATIVE_SK,
	DEVICE_SK,
	AD_COST,
	IMPRESSIONS,
	CLICKS,
	INBOUND_CALL,
	GA_CONV_MEMBERS,
	GA_CONV_CNT,
	DAY_OF_WEEK,
	WEEK_OF_YEAR,
	AD_SOURCE_TYPE,
	PAGE_TYPE,
	AD_GROUP_NM,
	GROUP_DIV,
	CREATIVE_TYPE,
	AD_TYPE_NM,
	READ_CNT,
	MEDIA_POTENTIAL_CUST_CNT,
	CRM_DEV_CNT,
	CTR_SRC,
	CVR_SRC,
	CPC_SRC,
	CPM_SRC,
	CPA_SRC,
	DEV_UNIT_PRICE_SRC,
	VTR_SRC,
	TIME_BAND,
	CM_POSITION,
	RT_TYPE,
	PROGRAM_NM,
	CHANNEL_COMPANY,
	CHANNEL_COMPANY_TYPE,
	SPOT_TYPE,
	DURATION_SEC,
	DAY_DIV,
	BRDC_DIV,
	CTV_DIV,
	AD_CNT,
	CONV_CALL_CNT,
	DVLP_MEMBER_CNT,
	DVLP_CNT,
	BRDC_AD_VIEW_RT_SRC,
	BRDC_CPC_SRC
) COMMENT='GOLD 광고 팩트 3종(FAP 코어 + FAD 디지털·FAB 방송 위성)을 AD_PERF_DK 로 1:1 pre-join — SV_AD 의 단일 base. PK=AD_PERF_DK(전건 유일, fan-out 0). 위성은 원천유형별 완전분할이라 LEFT JOIN 이 행수를 늘리지 않는다(디지털행=방송컬럼 NULL, 방송행=디지털컬럼 NULL — 결측이 아니라 원천 부재). 존재 이유: semantic view metric 식은 자기 logical table 컬럼만 참조 가능해 개발단가(AD_COST÷CRM_DEV_CNT) 등 cross-satellite 비율을 SV 에서 직접 계산할 수 없다.'
 as
SELECT
  -- FAP core
  fap.AD_PERF_DK,
  fap.PERF_DATE_SK,
  fap.CAMPAIGN_SK,
  -- [2026-08-06 O45] 마케팅캠페인 conformed 축 — 광고↔개발실적을 잇는 유일한 키다.
  --   🔴 `CAMPAIGN_SK`(개발캠페인)는 전건 센티넬이지만 이 축은 살아 있다(연결키 부재가 아니라 grain 문제였다).
  fap.MKTG_CAMPAIGN_SK,
  fap.AD_CREATIVE_SK,
  fap.DEVICE_SK,
  fap.AD_COST,
  fap.IMPRESSIONS,
  fap.CLICKS,
  fap.INBOUND_CALL,
  fap.GA_CONV_MEMBERS,
  fap.GA_CONV_CNT,
  fap.DAY_OF_WEEK,
  fap.WEEK_OF_YEAR,
  fap.AD_SOURCE_TYPE,
  -- FAD (digital satellite) — NULL for broadcast rows
  dig.PAGE_TYPE,
  dig.AD_GROUP_NM,
  dig.GROUP_DIV,
  dig.CREATIVE_TYPE,
  dig.AD_TYPE_NM,
  dig.READ_CNT,
  dig.MEDIA_POTENTIAL_CUST_CNT,
  dig.CRM_DEV_CNT,
  dig.CTR_SRC,
  dig.CVR_SRC,
  dig.CPC_SRC,
  dig.CPM_SRC,
  dig.CPA_SRC,
  dig.DEV_UNIT_PRICE_SRC,
  dig.VTR_SRC,
  -- FAB (broadcast satellite) — NULL for digital rows
  brc.TIME_BAND,
  brc.CM_POSITION,
  brc.RT_TYPE,
  brc.PROGRAM_NM,
  brc.CHANNEL_COMPANY,
  brc.CHANNEL_COMPANY_TYPE,
  brc.SPOT_TYPE,
  brc.DURATION_SEC,
  brc.DAY_DIV,
  brc.BRDC_DIV,
  brc.CTV_DIV,
  brc.AD_CNT,
  brc.CONV_CALL_CNT,
  brc.DVLP_MEMBER_CNT,
  brc.DVLP_CNT,
  brc.AD_VIEW_RT_SRC  AS BRDC_AD_VIEW_RT_SRC,
  brc.CPC_SRC         AS BRDC_CPC_SRC
FROM GN_DW.GOLD.FACT_AD_PERFORMANCE fap
LEFT JOIN GN_DW.GOLD.FACT_AD_DIGITAL dig ON fap.AD_PERF_DK = dig.AD_PERF_DK
LEFT JOIN GN_DW.GOLD.FACT_AD_BROADCAST brc ON fap.AD_PERF_DK = brc.AD_PERF_DK;
