-- SILVER/GOLD 코드컬럼 전파 — G3 조치 (BRONZE 코드체계 → SILVER 보존율 37.6%→100% 경로 확보)
-- Co-authored with CoCo
-- 🔴 CREATE OR REPLACE 금지(정보성 FK 38개·GRANT 파괴). ALTER TABLE ADD COLUMN 만 사용.
-- 컬럼명 = BRONZE 원천명 그대로(O24 확립 원칙 — 현업이 BRONZE 를 직접 조회 중이라 신개념 도입 금지).

-- SILVER.CRM_CAMPAIGN (+3)
ALTER TABLE GN_DW.SILVER.CRM_CAMPAIGN ADD COLUMN IF NOT EXISTS CMPGN_TRGET_CD VARCHAR COMMENT '캠페인대상 코드 raw — 원천 TM_CM_CMPGN_MNG.CMPGN_TRGET_CD(정본 코드그룹 CM002). 라벨 미배선(G3 조치 2026-08-03)';
ALTER TABLE GN_DW.SILVER.CRM_CAMPAIGN ADD COLUMN IF NOT EXISTS CPR_DIV_CD VARCHAR COMMENT '법인구분 코드 raw — 원천 TM_CM_CMPGN_MNG.CPR_DIV_CD(정본 CM019: I=사단/S=사복/A=통합). 라벨 미배선(G3 조치 2026-08-03)';
ALTER TABLE GN_DW.SILVER.CRM_CAMPAIGN ADD COLUMN IF NOT EXISTS SPNSR_DIV_CD VARCHAR COMMENT '후원구분 코드 raw — 원천 TM_CM_CMPGN_MNG.SPNSR_DIV_CD(정본 CM035). 라벨 미배선(G3 조치 2026-08-03)';

-- SILVER.CRM_MEMBER (+9)
ALTER TABLE GN_DW.SILVER.CRM_MEMBER ADD COLUMN IF NOT EXISTS EMAIL_STAT_CD VARCHAR COMMENT '이메일상태 코드 raw — 원천 TM_MM_FDRM_MBER_INFO.EMAIL_STAT_CD(정본 MM009). ONCE 원천엔 컬럼 부재 → NULL. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_MEMBER ADD COLUMN IF NOT EXISTS ETC_CTTPC_REL_CD VARCHAR COMMENT '기타연락처 관계 코드 raw — 원천 TM_MM_FDRM_MBER_INFO(정본 MM008). ⚠️사전 심각 불완전(활성 3 vs 원천 distinct 14) → 라벨 불가·현업 사전보완 대기. ONCE 부재 → NULL';
ALTER TABLE GN_DW.SILVER.CRM_MEMBER ADD COLUMN IF NOT EXISTS ETC_CTTPC_STAT_CD VARCHAR COMMENT '기타연락처 상태 코드 raw — 원천 TM_MM_FDRM_MBER_INFO(정본 MM008). ONCE 부재 → NULL. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_MEMBER ADD COLUMN IF NOT EXISTS ETC_TSTM_DIV_CD VARCHAR COMMENT '기타 증서구분 코드 raw — 원천 ETC_TSTM_DIV_CD(정본 MS026). 원천 타입 NUMBER → TO_VARCHAR 정규화(CRM_CODE.DTL_CD_ID 가 VARCHAR). FDRM∪ONCE 양쪽 존재. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_MEMBER ADD COLUMN IF NOT EXISTS MOBLPHON_STAT_CD VARCHAR COMMENT '휴대폰상태 코드 raw — 원천 TM_MM_FDRM_MBER_INFO(정본 MM008). ONCE 부재 → NULL. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_MEMBER ADD COLUMN IF NOT EXISTS REL_CD VARCHAR COMMENT '관계 코드 raw — 원천 TM_MM_ONCE_MBER_INFO.REL_CD(정본 CM009). FDRM 원천엔 컬럼 부재 → NULL. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_MEMBER ADD COLUMN IF NOT EXISTS RELATNSP_DIV_CD VARCHAR COMMENT '결연구분 코드 raw — 원천 TM_MM_FDRM_MBER_INFO(정본 MM019). ONCE 부재 → NULL. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_MEMBER ADD COLUMN IF NOT EXISTS SLRCLD_LRR_CD VARCHAR COMMENT '급여공제 코드 raw — 원천 TM_MM_FDRM_MBER_INFO(정본 CM029). ⚠️폐지코드 사용중(활성2·폐지1) → 라벨 조인시 USE_YN 무필터 필수. ONCE 부재 → NULL';
ALTER TABLE GN_DW.SILVER.CRM_MEMBER ADD COLUMN IF NOT EXISTS TSTM_DIV_CD VARCHAR COMMENT '증서구분 코드 raw — 원천 TSTM_DIV_CD(정본 MS026). 원천 타입 NUMBER → TO_VARCHAR 정규화. FDRM∪ONCE 양쪽 존재. G3 조치 2026-08-03';

-- SILVER.CRM_MEMBER_AMT_CHANGE (+4)
ALTER TABLE GN_DW.SILVER.CRM_MEMBER_AMT_CHANGE ADD COLUMN IF NOT EXISTS MBER_DIV_CD VARCHAR COMMENT '회원구분 코드 raw — 원천 TM_MM_FDRM_MBER_IRSD.MBER_DIV_CD(정본 MM018: 1개인/2기업/3단체). 라벨 미배선. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_MEMBER_AMT_CHANGE ADD COLUMN IF NOT EXISTS SETLE_CD VARCHAR COMMENT '결제수단 코드 raw — 원천 TM_MM_FDRM_MBER_IRSD.SETLE_CD(정본 PM040). 라벨 미배선. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_MEMBER_AMT_CHANGE ADD COLUMN IF NOT EXISTS SEX VARCHAR COMMENT '성별 코드 raw — 원천 TM_MM_FDRM_MBER_IRSD.SEX(정본 CM013, 1~4 등). 🔴 CRM_MEMBER.SEX 는 M/F/U 로 정규화된 값이므로 동명이의 — 직접 비교·UNION 금지. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_MEMBER_AMT_CHANGE ADD COLUMN IF NOT EXISTS SPNSR_AMT_CD VARCHAR COMMENT '후원금액구분 코드 raw — 원천 TM_MM_FDRM_MBER_IRSD.SPNSR_AMT_CD(정본 CM012). 금액 원값은 SPNSR_AMT. G3 조치 2026-08-03';

-- SILVER.CRM_MEMBER_DEV (+4)
ALTER TABLE GN_DW.SILVER.CRM_MEMBER_DEV ADD COLUMN IF NOT EXISTS CANCL_RDCAMT_RSN_CD VARCHAR COMMENT '취소·감액사유 코드 raw — 원천 TM_MM_FDRM_MBER_DVLP_AMT(정본 MM002). ⚠️31종 중 18종이 폐지코드 → 라벨 조인시 USE_YN 무필터 필수. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_MEMBER_DEV ADD COLUMN IF NOT EXISTS MBER_DIV_CD VARCHAR COMMENT '회원구분 코드 raw — 원천 TM_MM_FDRM_MBER_DVLP_AMT(정본 MM018). 라벨 미배선. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_MEMBER_DEV ADD COLUMN IF NOT EXISTS SEX VARCHAR COMMENT '성별 코드 raw — 원천 TM_MM_FDRM_MBER_DVLP_AMT.SEX(정본 CM013). 🔴 CRM_MEMBER.SEX 는 M/F/U 정규화값이므로 동명이의 — 직접 비교·UNION 금지. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_MEMBER_DEV ADD COLUMN IF NOT EXISTS SPNSR_AMT_CD VARCHAR COMMENT '후원금액구분 코드 raw — 원천 TM_MM_FDRM_MBER_DVLP_AMT(정본 CM012). 금액 원값은 SPNSR_AMT. G3 조치 2026-08-03';

-- SILVER.CRM_PAYMENT_BILLING (+7)
ALTER TABLE GN_DW.SILVER.CRM_PAYMENT_BILLING ADD COLUMN IF NOT EXISTS CPR_DIV_CD VARCHAR COMMENT '법인구분 코드 raw — 회비 TM_PM_MBRFEE_ACMSLT ∪ 기부금 TM_PM_DNTN_DTLS 양쪽 존재(정본 CM019). G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_PAYMENT_BILLING ADD COLUMN IF NOT EXISTS MBER_DIV_CD VARCHAR COMMENT '회원구분 코드 raw — 회비 원천만 보유(정본 MM018). 기부금 원천 컬럼 부재 → NULL. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_PAYMENT_BILLING ADD COLUMN IF NOT EXISTS MBRFEE_DIV_CD VARCHAR COMMENT '회비구분 코드 raw — 회비 원천만 보유(정본 PM010). 기부금 부재 → NULL. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_PAYMENT_BILLING ADD COLUMN IF NOT EXISTS OPERT_DIV_CD VARCHAR COMMENT '작업구분 코드 raw — 회비 원천만 보유(정본 MM014). 기부금 부재 → NULL. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_PAYMENT_BILLING ADD COLUMN IF NOT EXISTS PRCS_STAT_CD VARCHAR COMMENT '처리상태 코드 raw — 🔴 회비(TM_PM_MBRFEE_ACMSLT) 전용, 정본 PM013. 기부금 원천에도 동명 컬럼이 있으나 정본이 코드그룹을 지정하지 않아 의미혼입(O16형) 방지를 위해 NULL 유지 — 코드그룹 확정 후 배선. 미납 판정은 PAY_STAT_CD(DEC-3) 불변';
ALTER TABLE GN_DW.SILVER.CRM_PAYMENT_BILLING ADD COLUMN IF NOT EXISTS RETUN_RSN_CD VARCHAR COMMENT '반환사유 코드 raw — 회비 ∪ 기부금 양쪽 존재(정본 PM042). G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_PAYMENT_BILLING ADD COLUMN IF NOT EXISTS RQEST_DIV_CD VARCHAR COMMENT '청구구분 코드 raw — 회비 원천만 보유(정본 PM024). 기부금 부재 → NULL. G3 조치 2026-08-03';

-- SILVER.CRM_PAYMENT_METHOD (+6)
ALTER TABLE GN_DW.SILVER.CRM_PAYMENT_METHOD ADD COLUMN IF NOT EXISTS APPLCNT_MBER_REL_CD VARCHAR COMMENT '신청자-회원 관계 코드 raw — 원천 TM_PM_SETLE_INFO(정본 CM009). G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_PAYMENT_METHOD ADD COLUMN IF NOT EXISTS CPR_DIV_CD VARCHAR COMMENT '법인구분 코드 raw — 원천 TM_PM_SETLE_INFO(정본 CM019). G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_PAYMENT_METHOD ADD COLUMN IF NOT EXISTS CRTFC_MTH_CD VARCHAR COMMENT '인증방법 코드 raw — 원천 TM_PM_SETLE_INFO(정본 MM014). G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_PAYMENT_METHOD ADD COLUMN IF NOT EXISTS FNLT_DIV_CD VARCHAR COMMENT '금융기관구분 코드 raw — 원천 TM_PM_SETLE_INFO(정본 PM050). 기관코드 원값은 FNLT_CD. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_PAYMENT_METHOD ADD COLUMN IF NOT EXISTS RCEPT_DIV_CD VARCHAR COMMENT '접수구분 코드 raw — 원천 TM_PM_SETLE_INFO(정본 PM003). G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_PAYMENT_METHOD ADD COLUMN IF NOT EXISTS RQST_DIV_CD VARCHAR COMMENT '요청구분 코드 raw — 원천 TM_PM_SETLE_INFO(정본 PM004). G3 조치 2026-08-03';

-- SILVER.CRM_SEND_REQUEST (+3)
ALTER TABLE GN_DW.SILVER.CRM_SEND_REQUEST ADD COLUMN IF NOT EXISTS MSG_DIV_CD VARCHAR COMMENT '메시지구분 코드 raw — MSG_AT 채널(TM_MS_MSG_AT_SNDNG)만 보유(정본 MS010). EMAIL·PSTMTR·SND 원천 컬럼 부재 → NULL. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_SEND_REQUEST ADD COLUMN IF NOT EXISTS PRCS_STAT_CD VARCHAR COMMENT '처리상태 코드 raw — PSTMTR 채널(TM_MS_PSTMTR_SNDNG)만 보유(정본 MS061). 그 외 채널 부재 → NULL. G3 조치 2026-08-03';
ALTER TABLE GN_DW.SILVER.CRM_SEND_REQUEST ADD COLUMN IF NOT EXISTS SNDNG_TIME_DIV_CD VARCHAR COMMENT '발송시간구분 코드 raw — MSG_AT 채널만 보유(정본 MS267). 그 외 채널 부재 → NULL. G3 조치 2026-08-03';

-- SILVER.CRM_SPONSOR_RELATION (+1)
ALTER TABLE GN_DW.SILVER.CRM_SPONSOR_RELATION ADD COLUMN IF NOT EXISTS RELATNSP_DSCNTC_RSN_CD VARCHAR COMMENT '결연중단사유 코드 raw — 원천 TM_RM_RELATNSP_MSTR_INFO(정본 MM002). 원천 타입 NUMBER → TO_VARCHAR 정규화(CRM_CODE.DTL_CD_ID 가 VARCHAR). ⚠️30종 중 16종 폐지코드 → 라벨 조인시 USE_YN 무필터 필수';

-- GOLD.FACT_MEMBER_EVENT (+2)
ALTER TABLE GN_DW.GOLD.FACT_MEMBER_EVENT ADD COLUMN IF NOT EXISTS STOP_REASON_NM VARCHAR COMMENT '중단사유명 — 정본 공#162. MM005 라벨(SILVER CRM_MEMBER_DISCONTINUE.DSCNTC_RSN_NM 전파). 코드는 STOP_REASON. ⚠️USE_YN 무필터 조인 — 실측 20종 중 6종(366행)이 폐지코드이며 필터를 걸면 라벨이 사라진다. dev 브랜치는 개념 부재로 NULL(O25, 2026-08-03)';
ALTER TABLE GN_DW.GOLD.FACT_MEMBER_EVENT ADD COLUMN IF NOT EXISTS STOP_CHANNEL_NM VARCHAR COMMENT '중단경로명 — MM287 라벨(SYSTEM/CRM/홈페이지). 코드는 STOP_CHANNEL(1/2/3). dev 브랜치는 개념 부재로 NULL. 215지표 밖 — 현업 수요 확인 대상(O25, 2026-08-03)';
