-- GN_DW 0단계 부트스트랩: 환경(웨어하우스)·RBAC(역할·계층·권한)·DATABASE·스키마 9종·CoWork object·helper 뷰 생성
-- Co-authored with CoCo
--
-- ★ 정본(canonical) 실행 스크립트 — 2026-07-22 05_SV-Agent_ai/02_SERVING_setup.sql 에서 이관.
--   01_환경 Role.md(설계) 와 짝이 되는 프로젝트 전역 환경/RBAC 부트스트랩. 원위치는 포인터 스텁만 유지.
--
-- 정본 근거:
--   02_GN_DW_building/01_환경 Role.md    §1.2 웨어하우스 · §2 role_hierarchy/roles
--   02_GN_DW_building/03_GOLD_SERVING.md §3.8 grants (schema_grants) · P7 serving_separation
--   05_SV-Agent_ai/01_SV-Agent 작업계획.md §0단계 · §7 거버넌스
--   Snowflake docs: Snowflake CoWork object (CREATE SNOWFLAKE INTELLIGENCE)
--
-- 실행 순서(권장): A~C(WH·역할·WH grant) → B.5(DB 생성 → 소유권 ADMIN 이관 → 9스키마 GN_DW_ADMIN 생성)
--                  → BRONZE/SILVER/GOLD DDL(ADMIN 적재) → D~F(스키마 grant·SERVING·CoWork)
--                  → dbt build → 08_After_Deploy_DBT.sql §G(helper 뷰 2종) → 05_SV_DDL.sql
--                  → 09_1_AGENT_생성.sql → 09_2_AGENT_버전업.sql
--   🔴 [2026-08-04 O36 교정] 종전 이 줄은 `09_AGENT_spec_구현.sql`(DEPRECATED 스텁)을 지목하고
--      **helper 뷰를 이 파일(G절)이 만든다고 적었으나 이 파일에는 DIM_MONTH·DIM_MEMBER_CURRENT 가 없다.**
--      실행 정본은 `08_After_Deploy_DBT.sql` §G 다. 전체 순서 정본 = 06_RUNBOOK.md §11.2-C
--   ※ B.5 로 DB·9스키마가 처음부터 ADMIN 소유로 생성됨(개별 OWNERSHIP 이관 불요). D 의 ALL TABLES grant 는 DDL 후 실행 권장(FUTURE grant 병행).
-- 소유 모델: GN_DW DB 트리(DB·스키마·테이블/뷰·SV·Agent·DBT PROJECT) = GN_DW_ADMIN 소유(SYSADMIN 하위).
--            커스텀 롤은 적재·조회만. 계정 레벨(네트워크/인증 정책·Resource Monitor·CoWork·CORTEX)은 ACCOUNTADMIN 유지.
-- 멱등: 전 구간 IF NOT EXISTS / OR REPLACE / OWNERSHIP 재이관 안전. 반복 실행 가능.

/* =====================================================================
   A. 웨어하우스 (01_환경 Role.md §1.2)
   ===================================================================== */
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS GN_DW_ETL_WH
  WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = 'ETL / 데이터 적재 (프로시저·태스크 전용)';

CREATE WAREHOUSE IF NOT EXISTS GN_DW_ANALYTICS_WH
  WAREHOUSE_SIZE = 'MEDIUM' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = '분석가 쿼리 / SV·Agent 소비 (Analyst·Viewer·Service)';

CREATE WAREHOUSE IF NOT EXISTS GN_DW_DEV_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
  COMMENT = '개발/테스트 (Engineer·Admin 기본)';

/* =====================================================================
   B. 역할 생성 + 계층 (01_환경 Role.md §2.1 role_hierarchy, P4: 최종 SYSADMIN 귀속)
      SYSADMIN
        └ GN_DW_ADMIN
             ├ GN_DW_ENGINEER
             ├ GN_DW_ANALYST ─ GN_DW_VIEWER
             ├ GN_DW_LOADER
             └ GN_DW_SERVICE
   ===================================================================== */
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS GN_DW_ADMIN    COMMENT = 'GN_DW DB/스키마 관리·DDL·SV/Agent 소유';
CREATE ROLE IF NOT EXISTS GN_DW_ENGINEER COMMENT = 'ETL 개발·프로시저/태스크';
CREATE ROLE IF NOT EXISTS GN_DW_ANALYST  COMMENT = '분석 쿼리(SELECT)·SV/Agent 소비';
CREATE ROLE IF NOT EXISTS GN_DW_VIEWER   COMMENT = '읽기 전용·SV/Agent/Streamlit 소비';
CREATE ROLE IF NOT EXISTS GN_DW_LOADER   COMMENT = '외부팀 BRONZE 적재';
CREATE ROLE IF NOT EXISTS GN_DW_SERVICE  COMMENT = '서비스 계정(API·Streamlit)';

-- 계층 (자식 role → 부모 role)
GRANT ROLE GN_DW_ADMIN    TO ROLE SYSADMIN;
GRANT ROLE GN_DW_ENGINEER TO ROLE GN_DW_ADMIN;
GRANT ROLE GN_DW_ANALYST  TO ROLE GN_DW_ADMIN;
GRANT ROLE GN_DW_LOADER   TO ROLE GN_DW_ADMIN;
GRANT ROLE GN_DW_SERVICE  TO ROLE GN_DW_ADMIN;
GRANT ROLE GN_DW_VIEWER   TO ROLE GN_DW_ANALYST;

/* =====================================================================
   C. 웨어하우스 USAGE 부여 (01_환경 Role.md §2.2 warehouse 매핑)
   ===================================================================== */
USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE GN_DW_DEV_WH       TO ROLE GN_DW_ADMIN;
GRANT USAGE ON WAREHOUSE GN_DW_ETL_WH       TO ROLE GN_DW_ADMIN;
GRANT USAGE ON WAREHOUSE GN_DW_ANALYTICS_WH TO ROLE GN_DW_ADMIN;

GRANT USAGE ON WAREHOUSE GN_DW_ETL_WH       TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON WAREHOUSE GN_DW_DEV_WH       TO ROLE GN_DW_ENGINEER;

GRANT USAGE ON WAREHOUSE GN_DW_ANALYTICS_WH TO ROLE GN_DW_ANALYST;
GRANT USAGE ON WAREHOUSE GN_DW_ANALYTICS_WH TO ROLE GN_DW_VIEWER;
GRANT USAGE ON WAREHOUSE GN_DW_ETL_WH       TO ROLE GN_DW_LOADER;
GRANT USAGE ON WAREHOUSE GN_DW_ANALYTICS_WH TO ROLE GN_DW_SERVICE;

/* =====================================================================
   B.5 DATABASE 생성 + 소유권 이관 + 스키마 전체 생성 (SoD 설계 핵심)
      원칙: 커스텀 롤엔 계정 레벨 CREATE DATABASE 가 없다 → DB 는 SYSADMIN 이 생성하고
             DB 소유권만 GN_DW_ADMIN 에 이관한다. 이후 모든 스키마·테이블·뷰·SV·Agent·
             DBT PROJECT 는 GN_DW_ADMIN 이 "처음부터 직접 생성" → 생성 시점부터 ADMIN 소유(개별 이관 불요).
      효과: DB 트리 전체가 ADMIN 소유로 정합. MANAGED ACCESS 스키마의 grant 발급 주체 = 소유자 GN_DW_ADMIN.
             커스텀 롤(ENGINEER/ANALYST/VIEWER/LOADER/SERVICE)은 적재·조회만(소유 없음).
      ⚠️ ACCOUNTADMIN 전용으로 남는 것(이관 대상 아님, 계정 레벨):
             네트워크/인증 정책(ALTER ACCOUNT SET ...), Resource Monitor, CoWork object(§F), SNOWFLAKE.CORTEX_* 부여.
      스키마 정본: 02_DB_BRONZE_SILVER.md §3.2 · 03_GOLD_SERVING.md §3.8.
             BRONZE_*·SECURITY = MANAGED ACCESS. SILVER/GOLD/SERVING/OPS = 일반. PUBLIC 은 자동 존재.
             INFORMATION_SCHEMA 는 시스템 소유 → 관리 대상 아님(무관).
      멱등: CREATE ... IF NOT EXISTS · COPY CURRENT GRANTS 로 반복 실행 안전.
      비고: dbt(ENGINEER)가 만드는 WIDE view 는 생성 롤(ENGINEER) 소유 — dbt 산출물로 허용(구조 base table 은 ADMIN 소유 유지).
   ===================================================================== */

-- (1) DATABASE — SYSADMIN 이 생성 (커스텀 롤엔 CREATE DATABASE 권한 없음)
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS GN_DW
  DATA_RETENTION_TIME_IN_DAYS = 1
  COMMENT = '굿네이버스 데이터웨어하우스';

-- (2) DB 소유권 → GN_DW_ADMIN. 이후 스키마/객체를 ADMIN 이 직접 CREATE → 생성 시점부터 ADMIN 소유
USE ROLE ACCOUNTADMIN;
GRANT OWNERSHIP ON DATABASE GN_DW TO ROLE GN_DW_ADMIN COPY CURRENT GRANTS;

-- (3) 스키마 9종 — GN_DW_ADMIN 이 처음부터 생성 (개별 OWNERSHIP 이관 불필요)
USE ROLE GN_DW_ADMIN;
-- BRONZE: 원천별 물리 분리 (MANAGED ACCESS — LOADER 쓰기)
CREATE SCHEMA IF NOT EXISTS GN_DW.BRONZE_CRM    WITH MANAGED ACCESS COMMENT = '원천 적재 — CRM(회원/납입/캠페인). 43테이블';
CREATE SCHEMA IF NOT EXISTS GN_DW.BRONZE_AGENCY WITH MANAGED ACCESS COMMENT = '원천 적재 — 대행사 광고 성과. 3테이블';
CREATE SCHEMA IF NOT EXISTS GN_DW.BRONZE_ERP    WITH MANAGED ACCESS COMMENT = '원천 적재 — ERP 예산 실적 원장. 1테이블';
CREATE SCHEMA IF NOT EXISTS GN_DW.BRONZE_GA4    WITH MANAGED ACCESS COMMENT = '원천 적재 — GA4 웹/앱 방문. 1테이블(일 샤드)';
-- 정제·분석·소비·운영·거버넌스
-- [2026-07-28 순서9-I] AGENCY 광고 팩트군 재설계(DEC-8) 반영: SILVER 32→38 · GOLD star 24→27 · WIDE 9→12
CREATE SCHEMA IF NOT EXISTS GN_DW.SILVER   COMMENT = '정제/통합 레이어 — dbt 38테이블(CRM 22+GA4 5+ERP 2+AGENCY 8+bridge 1)';
CREATE SCHEMA IF NOT EXISTS GN_DW.GOLD     COMMENT = '분석 계층 — star schema 27(15 DIM+12 FACT) + 평탄화 WIDE VIEW 12. 지표 215개 귀속';
CREATE SCHEMA IF NOT EXISTS GN_DW.SERVING  COMMENT = 'Serving 계층 — Semantic View·Cortex Agent·Streamlit 배치(P7). GOLD DIM/FACT cross-schema 참조';
CREATE SCHEMA IF NOT EXISTS GN_DW.OPS      COMMENT = 'ETL 운영 인프라 — dbt 프로젝트(DBT PROJECT DW_PIPELINE)';
CREATE SCHEMA IF NOT EXISTS GN_DW.SECURITY WITH MANAGED ACCESS COMMENT = '거버넌스 정책 격리 — 마스킹/네트워크 정책';
-- 기존 배포본 재실행 시 COMMENT 갱신 (IF NOT EXISTS 는 기존 스키마의 COMMENT 를 덮지 않음)
ALTER SCHEMA GN_DW.SILVER SET COMMENT = '정제/통합 레이어 — dbt 38테이블(CRM 22+GA4 5+ERP 2+AGENCY 8+bridge 1)';
ALTER SCHEMA GN_DW.GOLD   SET COMMENT = '분석 계층 — star schema 27(15 DIM+12 FACT) + 평탄화 WIDE VIEW 12. 지표 215개 귀속';

/* =====================================================================
   D. 스키마 권한 (03_GOLD_SERVING.md §3.8 schema_grants)
      스키마 소유자 = GN_DW_ADMIN(ADMIN 이 처음부터 생성) → ADMIN 이 발급.
   ===================================================================== */
USE ROLE GN_DW_ADMIN;

-- D.1 DATABASE USAGE (6개 역할 전부)
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_ADMIN;
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_ANALYST;
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_VIEWER;
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_LOADER;
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_SERVICE;

-- D.2 GOLD (분석 소비 정본 — SV base = GOLD DIM/FACT; Cortex Analyst는 caller로 GOLD 직접 실행)
--   ADMIN: 전체
GRANT ALL PRIVILEGES ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS   IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE VIEWS  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ADMIN;
--   ENGINEER: USAGE + SELECT + CREATE VIEW
GRANT USAGE, CREATE VIEW ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL TABLES  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL VIEWS   IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
--   소비 3역할(ANALYST/VIEWER/SERVICE): USAGE + SELECT (+ FUTURE)
GRANT USAGE ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT USAGE ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT USAGE ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;
GRANT SELECT ON ALL TABLES  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT SELECT ON ALL VIEWS   IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT SELECT ON ALL TABLES  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT SELECT ON ALL VIEWS   IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT SELECT ON ALL TABLES  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;
GRANT SELECT ON ALL VIEWS   IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;

-- D.3 SILVER (ENGINEER 개발 + ANALYST 읽기)
GRANT ALL PRIVILEGES ON SCHEMA GN_DW.SILVER TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL VIEWS  IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ADMIN;
GRANT USAGE, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION ON SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON SCHEMA GN_DW.SILVER TO ROLE GN_DW_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ANALYST;
GRANT SELECT ON ALL VIEWS  IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ANALYST;

-- D.4 BRONZE_* 4종 (ADMIN 전체 / ENGINEER 읽기 / LOADER 적재)
--   BRONZE_CRM
GRANT ALL PRIVILEGES ON SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_ADMIN;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_CRM TO ROLE GN_DW_LOADER;
--   BRONZE_ERP
GRANT ALL PRIVILEGES ON SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_ADMIN;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_ERP TO ROLE GN_DW_LOADER;
--   BRONZE_AGENCY
GRANT ALL PRIVILEGES ON SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_ADMIN;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_AGENCY TO ROLE GN_DW_LOADER;
--   BRONZE_GA4
GRANT ALL PRIVILEGES ON SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_ADMIN;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_LOADER;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE_GA4 TO ROLE GN_DW_LOADER;

/* =====================================================================
   D.5 dbt 적재 실행 권한 — GN_DW_ENGINEER (최소권한; CREATE TABLE 불요)
      근거: dbt(GN_DW.OPS.DW_PIPELINE)는 06/08 DDL이 만든 테이블에 "적재만" 한다.
            - GOLD dim = incremental merge (INSERT/UPDATE/DELETE)
            - GOLD fact · SILVER = incremental append + pre-hook TRUNCATE
            - GOLD WIDE = view (CREATE VIEW — ENGINEER 기보유)
            구조·컬럼 COMMENT·FK 는 06_DDL/08_DDL(소유=GN_DW_ADMIN)이 보존 → dbt 롤은 CREATE TABLE 불요.
      권한 사실: TRUNCATE 는 개별 grant 가능한 TABLE 권한(docs: GRANT ... ON TABLE {INSERT|DELETE|TRUNCATE|UPDATE|...}).
                 EXECUTE DBT PROJECT = USAGE ON DBT PROJECT(docs). → 소유권 없이 실행 가능.
      결정: 별도 GN_DW_DBT 롤 불필요(01_환경 Role.md §3 트리거 미충족). ADMIN 은 OWNERSHIP 만 유지.
   ===================================================================== */
USE ROLE GN_DW_ADMIN;  -- GOLD/SILVER/OPS 소유자 = GN_DW_ADMIN(처음부터 생성) → ADMIN 이 발급

-- GOLD: dim merge(INSERT/UPDATE/DELETE) + fact pre-hook TRUNCATE. (USAGE·CREATE VIEW·SELECT 는 D.2 기보유)
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES    IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;

-- SILVER: append(INSERT) + pre-hook TRUNCATE. (merge 없음 → UPDATE/DELETE 불요. USAGE·SELECT·CREATE TABLE 는 D.3 기보유)
GRANT INSERT, TRUNCATE ON ALL TABLES    IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT INSERT, TRUNCATE ON FUTURE TABLES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;


