------------------------------------------------------
-- 3.8 권한 부여 (GRANT / Future Grants)
-- ※ 03_01에서 DB/스키마 생성 및 OWNERSHIP 이관 완료 후 실행할 것
------------------------------------------------------
USE ROLE GN_DW_ADMIN;

------------------------------------------------------
-- Database 레벨
------------------------------------------------------
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_ANALYST;
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_VIEWER;
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_LOADER;
GRANT USAGE ON DATABASE GN_DW TO ROLE GN_DW_SERVICE;

------------------------------------------------------
-- Schema 레벨
------------------------------------------------------
-- BRONZE
GRANT USAGE ON SCHEMA GN_DW.BRONZE TO ROLE GN_DW_ENGINEER;
GRANT CREATE TABLE ON SCHEMA GN_DW.BRONZE TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON SCHEMA GN_DW.BRONZE TO ROLE GN_DW_LOADER;

-- SILVER
GRANT USAGE ON SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT CREATE TABLE ON SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT CREATE PROCEDURE ON SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON SCHEMA GN_DW.SILVER TO ROLE GN_DW_ANALYST;

-- GOLD
GRANT USAGE ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
GRANT CREATE TABLE ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
GRANT CREATE PROCEDURE ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
GRANT USAGE ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT USAGE ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT USAGE ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;

-- PUBLIC (공유용 워크스페이스 위치)
GRANT USAGE ON SCHEMA GN_DW.PUBLIC TO ROLE GN_DW_ADMIN;

------------------------------------------------------
-- 테이블/뷰 권한 (현재 + Future)
------------------------------------------------------
-- BRONZE: LOADER = INSERT/UPDATE, ENGINEER = SELECT
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.BRONZE TO ROLE GN_DW_ENGINEER;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA GN_DW.BRONZE TO ROLE GN_DW_LOADER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE TO ROLE GN_DW_ENGINEER;
GRANT INSERT, UPDATE ON FUTURE TABLES IN SCHEMA GN_DW.BRONZE TO ROLE GN_DW_LOADER;

-- SILVER: ENGINEER = ALL, ANALYST = SELECT
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ANALYST;
GRANT ALL ON ALL TABLES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT ALL ON ALL VIEWS IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ANALYST;
GRANT ALL ON FUTURE TABLES IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;
GRANT ALL ON FUTURE VIEWS IN SCHEMA GN_DW.SILVER TO ROLE GN_DW_ENGINEER;

-- GOLD: ENGINEER = SELECT+CREATE VIEW, ANALYST/VIEWER/SERVICE = SELECT
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;
GRANT SELECT ON ALL VIEWS IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;
GRANT SELECT ON ALL TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;
GRANT CREATE VIEW ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;

------------------------------------------------------
-- Semantic View & Agent 권한
------------------------------------------------------
-- ANALYST, VIEWER, SERVICE가 Semantic View + Agent 사용 가능
GRANT SELECT ON ALL SEMANTIC VIEWS IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_ANALYST;
GRANT SELECT ON ALL SEMANTIC VIEWS IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_VIEWER;
GRANT SELECT ON ALL SEMANTIC VIEWS IN SCHEMA GN_DW.GOLD TO ROLE GN_DW_SERVICE;

GRANT USAGE ON AGENT GN_DW.GOLD.GN_DW_AGENT TO ROLE GN_DW_ANALYST;
GRANT USAGE ON AGENT GN_DW.GOLD.GN_DW_AGENT TO ROLE GN_DW_VIEWER;
GRANT USAGE ON AGENT GN_DW.GOLD.GN_DW_AGENT TO ROLE GN_DW_SERVICE;

-- Agent 생성 권한 (ENGINEER)
GRANT CREATE AGENT ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;

-- ML 예측 모델 생성 권한 (ENGINEER) - SP_REFRESH_FORECAST_DATA가 SNOWFLAKE.ML.FORECAST 생성
GRANT CREATE SNOWFLAKE.ML.FORECAST ON SCHEMA GN_DW.GOLD TO ROLE GN_DW_ENGINEER;

------------------------------------------------------
-- Cortex Agent 사용을 위한 Database Role
------------------------------------------------------
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE GN_DW_ANALYST;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE GN_DW_VIEWER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE GN_DW_SERVICE;
