-- Co-authored with CoCo
-- =====================================================================
-- 답안체크용 쿼리 (O197) — MSTR 원 리포트 답안 ↔ GN_DW.MSTR 이관 결과 대조
--   답안 원문 = 15_MSTR 이관 PoC/mstr-answer.csv
--     → GN_DW.MSTR.CHK_MSTR_ANSWER (적재 = tools/mstr_load_answer.py · 원문 문자열 그대로)
--   비교 grain = MSTR 분석엔진 1단계 동적집계(사업부/시도권역·홍보방법·후원사업 제외) + 캠페인코드(CP)
--   판정 규칙
--     · 답안 개발(건) '-' = MSTR 표시상 0 ⇒ 0 으로 비교
--     · BRAND_LIVE_CHANGED = 브랜드명만 다르고 나머지 키·값 일치 → 캠페인 브랜드가 MSTR 동결 이후
--       라이브에서 바뀐 경우(실측: CP 4882·4890 브랜드 48 PC광고마케팅 → 33 PC홈페이지, 2026-03-19)
-- =====================================================================
use role gn_dw_admin;
USE SCHEMA GN_DW.MSTR;   -- TEMPORARY VIEW 생성 위치(세션 종료 시 자동 삭제)
SET BATCH = '1차';
SET YM    = '202601';

-- [0] 공통: 우리 결과(답안 grain) · 답안 정규화
CREATE OR REPLACE TEMPORARY VIEW CHK_OURS AS
SELECT
  a11.OCCRRNC_DE                AS STRD_DE,
  a14.CPR_DIV_NM,
  a15.DEPT4_NM,
  a113.DEPT2_NM,
  a16.DEPT_NM,
  a17.BRND_NM,
  a19.UPPER_CMPGN_NM,
  a112.CMPGN_NM,
  a11.CMPGN_CD,
  a12.DVLP_DIV_NM,
  a116.SPNSR_BSNS_NM            AS SPNSR_BSNS2_NM,
  a110.SEX_NM,
  a111.AGE_TERM_NM,
  SUM(a11.SPNSR_AMT_CNT)        AS CNT,
  COUNT(DISTINCT a11.MBER_NO)   AS MBR
FROM GN_DW.MSTR.F_MM_SPNSR_DVLP_SUM a11
LEFT JOIN GN_DW.MSTR.D_DVLP_DIV_CD     a12  ON a11.DVLP_DIV_CD     = a12.DVLP_DIV_CD
LEFT JOIN GN_DW.MSTR.D_CPR_DIV_CD      a14  ON a11.CPR_DIV_CD      = a14.CPR_DIV_CD
LEFT JOIN GN_DW.MSTR.D_DEPT4_CD        a15  ON a11.ACMSLT_DEPT4_CD = a15.DEPT4_ID
LEFT JOIN GN_DW.MSTR.D_DEPT_CD         a16  ON a11.ACMSLT_DEPT_CD  = a16.DEPT_ID
LEFT JOIN GN_DW.MSTR.D_BRND_CD         a17  ON a11.BRND_ID         = a17.BRND_ID
LEFT JOIN GN_DW.MSTR.D_UP_CMPGN_CD     a19  ON a11.UPPER_CMPGN_CD  = a19.UPPER_CMPGN_CD
LEFT JOIN GN_DW.MSTR.D_SEX_CD          a110 ON a11.SEX             = a110.SEX_CD
LEFT JOIN GN_DW.MSTR.D_AGE_TERM_CD     a111 ON a11.AGE_TERM_CD     = a111.AGE_TERM_CD
LEFT JOIN GN_DW.MSTR.D_CMPGN_CD        a112 ON a11.CMPGN_CD        = a112.CMPGN_CD
LEFT JOIN GN_DW.MSTR.D_DEPT2_CD        a113 ON a11.ACMSLT_DEPT2_CD = a113.DEPT2_ID
LEFT JOIN GN_DW.MSTR.D_SPNSR_BSNS_INFO a116 ON a11.SPNSR_BSNS2_ID  = a116.SPNSR_BSNS_ID
WHERE a11.STRD_MT = $YM
  AND a11.DVLP_DIV_CD IN ('1', '2', '4')
GROUP BY ALL;

CREATE OR REPLACE TEMPORARY VIEW CHK_ANS AS
SELECT
  ROW_NO,
  TO_CHAR(TO_DATE(STRD_DE_NM), 'YYYYMMDD')                       AS STRD_DE,
  CPR_DIV_NM, DEPT4_NM, DEPT2_NM, DEPT_NM, BRND_NM, UPPER_CMPGN_NM, CMPGN_NM, CMPGN_CD,
  DVLP_DIV_NM, SPNSR_BSNS2_NM, SEX_NM, AGE_TERM_NM,
  DVLP_CNT_TXT,
  IFF(DVLP_CNT_TXT = '-', 0, TRY_TO_NUMBER(REPLACE(DVLP_CNT_TXT, ',', ''), 18, 4)) AS CNT,
  TRY_TO_NUMBER(DVLP_MBR_TXT)                                    AS MBR
FROM GN_DW.MSTR.CHK_MSTR_ANSWER
WHERE BATCH = $BATCH;

USE ROLE GN_DW_ANALYST;
USE WAREHOUSE GN_DW_ANALYTICS_WH;

-- [1] 행 단위 판정 — 답안 1행마다 상태
CREATE OR REPLACE TEMPORARY VIEW CHK_RESULT AS
SELECT
  A.ROW_NO, A.STRD_DE, A.DEPT_NM, A.CMPGN_CD, A.DVLP_DIV_NM, A.SPNSR_BSNS2_NM, A.SEX_NM, A.AGE_TERM_NM,
  A.BRND_NM AS ANS_BRND_NM, COALESCE(F.BRND_NM, B.BRND_NM) AS OUR_BRND_NM,
  A.DVLP_CNT_TXT AS ANS_CNT_TXT, A.CNT AS ANS_CNT, A.MBR AS ANS_MBR,
  COALESCE(F.CNT, B.CNT) AS OUR_CNT, COALESCE(F.MBR, B.MBR) AS OUR_MBR,
  CASE
    WHEN F.STRD_DE IS NOT NULL AND A.CNT = F.CNT AND A.MBR = F.MBR THEN 'MATCH'
    WHEN F.STRD_DE IS NOT NULL                                     THEN 'VALUE_DIFF'
    WHEN B.STRD_DE IS NOT NULL AND A.CNT = B.CNT AND A.MBR = B.MBR THEN 'BRAND_LIVE_CHANGED'
    WHEN B.STRD_DE IS NOT NULL                                     THEN 'BRAND_CHANGED_VALUE_DIFF'
    ELSE 'NOT_FOUND'
  END AS STATUS
FROM CHK_ANS A
LEFT JOIN CHK_OURS F                                   -- 전체 키 일치
  ON  A.STRD_DE = F.STRD_DE AND A.CMPGN_CD = F.CMPGN_CD AND A.DEPT_NM = F.DEPT_NM
  AND A.DVLP_DIV_NM = F.DVLP_DIV_NM AND A.SPNSR_BSNS2_NM = F.SPNSR_BSNS2_NM
  AND A.SEX_NM = F.SEX_NM AND A.AGE_TERM_NM = F.AGE_TERM_NM AND A.CPR_DIV_NM = F.CPR_DIV_NM
  AND A.BRND_NM = F.BRND_NM AND A.UPPER_CMPGN_NM = F.UPPER_CMPGN_NM
  AND A.DEPT4_NM = F.DEPT4_NM AND A.DEPT2_NM = F.DEPT2_NM
LEFT JOIN CHK_OURS B                                   -- 브랜드만 제외한 키 일치
  ON  F.STRD_DE IS NULL
  AND A.STRD_DE = B.STRD_DE AND A.CMPGN_CD = B.CMPGN_CD AND A.DEPT_NM = B.DEPT_NM
  AND A.DVLP_DIV_NM = B.DVLP_DIV_NM AND A.SPNSR_BSNS2_NM = B.SPNSR_BSNS2_NM
  AND A.SEX_NM = B.SEX_NM AND A.AGE_TERM_NM = B.AGE_TERM_NM AND A.CPR_DIV_NM = B.CPR_DIV_NM
  AND A.UPPER_CMPGN_NM = B.UPPER_CMPGN_NM
  AND A.DEPT4_NM = B.DEPT4_NM AND A.DEPT2_NM = B.DEPT2_NM;

-- [2] 요약 — 상태별 행수 · 합계
SELECT
  STATUS,
  COUNT(*)        AS ANS_ROWS,
  SUM(ANS_CNT)    AS ANS_CNT,
  SUM(OUR_CNT)    AS OUR_CNT,
  SUM(ANS_MBR)    AS ANS_MBR,
  SUM(OUR_MBR)    AS OUR_MBR
FROM CHK_RESULT
GROUP BY ROLLUP (STATUS)
ORDER BY STATUS NULLS LAST;

-- [3] 불일치 상세 (MATCH 제외)
SELECT *
FROM CHK_RESULT
WHERE STATUS <> 'MATCH'
ORDER BY STATUS, ROW_NO;

-- [4] 브랜드 차이 근거 — 해당 캠페인의 라이브 브랜드와 최종수정일
SELECT
  C.CMPGN_CD, C.CMPGN_NM, C.BRND_ID, BR.BRND_NM AS LIVE_BRND_NM, C.LAST_UPDT_DT,
  LISTAGG(DISTINCT R.ANS_BRND_NM, ', ') AS ANS_BRND_NM,
  COUNT(*) AS ANS_ROWS
FROM CHK_RESULT R
JOIN GN_DW.BRONZE_CRM.TM_CM_CMPGN_MNG C ON C.CMPGN_CD = R.CMPGN_CD
LEFT JOIN GN_DW.BRONZE_CRM.TM_CM_BRND_MNG BR ON BR.BRND_ID = C.BRND_ID
WHERE R.STATUS LIKE 'BRAND%'
GROUP BY ALL
ORDER BY C.CMPGN_CD;

-- [5] (참고) 답안 범위 밖 — 같은 부서·일자·캠페인인데 답안에 없는 우리 행
--     답안이 「일부」이므로 0 이 아니어도 이상이 아니다. 답안 전체본을 받으면 0 이어야 한다.
SELECT COUNT(*) AS OUR_ROWS_NOT_IN_ANSWER, SUM(O.CNT) AS OUR_CNT
FROM CHK_OURS O
WHERE O.DEPT_NM IN (SELECT DISTINCT DEPT_NM FROM CHK_ANS)
  AND O.STRD_DE IN (SELECT DISTINCT STRD_DE FROM CHK_ANS)
  AND NOT EXISTS (
    SELECT 1 FROM CHK_ANS A
    WHERE A.STRD_DE = O.STRD_DE AND A.CMPGN_CD = O.CMPGN_CD AND A.DEPT_NM = O.DEPT_NM
      AND A.DVLP_DIV_NM = O.DVLP_DIV_NM AND A.SPNSR_BSNS2_NM = O.SPNSR_BSNS2_NM
      AND A.SEX_NM = O.SEX_NM AND A.AGE_TERM_NM = O.AGE_TERM_NM);
