-- Co-authored with CoCo
-- =====================================================================
-- 스킬_MSTR_검증쿼리.sql — `스킬_MSTR_비교항목.md` 의 V01~V09 검증
--   스킬 측 = BRONZE_CRM 원천 + 스킬 로직(mstr_dept_member_development_to_crm_final_202606.sql) 재계산
--   MSTR 측 = GN_DW.MSTR.F_MM_SPNSR_DVLP_SUM / F_MM_SPNSR_DVLP
--   각 @CHECK 의 결과는 「차이 요약」 이다. 판정 컬럼 RESULT = PASS / FAIL
--   임시 테이블만 만든다(세션 종료 시 삭제).
-- =====================================================================
USE SCHEMA GN_DW.MSTR;

-- ---------------------------------------------------------------------
-- [S0] 스킬 측 차원 — #DEPT_DIM · #BUSINESS_DIM
-- ---------------------------------------------------------------------
CREATE OR REPLACE TEMPORARY TABLE SK_DEPT AS
SELECT E.DEPT_ID, D.DEPT_ID AS DEPT2_ID, C.DEPT_ID AS DEPT3_ID, B.DEPT_ID AS DEPT4_ID
FROM GN_DW.BRONZE_CRM.TM_CM_DEPT_INFO A
JOIN GN_DW.BRONZE_CRM.TM_CM_DEPT_INFO B ON B.ACMSLT_UPPER_DEPT_ID = A.DEPT_ID
JOIN GN_DW.BRONZE_CRM.TM_CM_DEPT_INFO C ON C.ACMSLT_UPPER_DEPT_ID = B.DEPT_ID
JOIN GN_DW.BRONZE_CRM.TM_CM_DEPT_INFO D ON D.ACMSLT_UPPER_DEPT_ID = C.DEPT_ID
JOIN GN_DW.BRONZE_CRM.TM_CM_DEPT_INFO E ON E.ACMSLT_UPPER_DEPT_ID = D.DEPT_ID
WHERE A.UPPER_DEPT_ID = 'ZV000000' AND C.DEPT_ID <> 'ZC000029'
UNION ALL SELECT 'Z~', 'Z~', 'Z~', 'Z~';

CREATE OR REPLACE TEMPORARY TABLE SK_BSNS AS
SELECT SPNSR_BSNS_ID, SPNSR_BSNS_ABRV_CD,
       CASE CPR_DIV_CD WHEN '1' THEN 'I' WHEN '2' THEN 'S' ELSE CPR_DIV_CD END AS CPR_DIV_CD
FROM GN_DW.BRONZE_CRM.TM_CM_SPNSR_BSNS_INFO;

-- ---------------------------------------------------------------------
-- [S1] 스킬 측 원장 — #DVLP_SOURCE + #DVLP_FACT (+ 캠페인 · 상위캠페인)
-- ---------------------------------------------------------------------
CREATE OR REPLACE TEMPORARY TABLE SK_F AS
WITH NEW_REJOIN_BASE AS (
  SELECT LEFT(A.OCCRRNC_DE, 6) AS STRD_MT,
         SUM(A.SPNSR_AMT) OVER (PARTITION BY A.SPNSR_NO, A.SPNSR_BSNS_NO, LEFT(A.OCCRRNC_DE, 6)) AS MAMT,
         A.*
  FROM GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_DVLP_AMT A
  JOIN GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_SPNSR_BSNS B
    ON A.SPNSR_NO = B.SPNSR_NO AND A.SPNSR_BSNS_NO = B.SPNSR_BSNS_NO
   AND COALESCE(NULLIF(B.SPNSR_DSCNTC_DE, ''), '99991231') > LEFT(A.OCCRRNC_DE, 6) || '31'
  WHERE A.OCCRRNC_DE BETWEEN '20260101' AND TO_CHAR(CURRENT_DATE(), 'YYYYMM') || '31'
    AND A.DVLP_DIV_CD IN ('1', '4')
),
NEW_REJOIN AS (
  SELECT STRD_MT, SPNSR_NO, SPNSR_BSNS_NO, OCCRRNC_DE, SER_NO, MBER_NO,
         COALESCE(ACMSLT_DEPT_CD, 'Z~') AS DEPT_ID, SPNSR_BSNS_ID, CMPGN_CD, DVLP_DIV_CD, SPNSR_AMT
  FROM NEW_REJOIN_BASE WHERE MAMT > 0
),
CHANGE_BASE AS (
  SELECT LEFT(A.OCCRRNC_DE, 6) AS STRD_MT,
         SUM(IFF(A.DVLP_DIV_CD IN ('2', '3'), A.SPNSR_AMT, 0))
           OVER (PARTITION BY A.SPNSR_NO, A.SPNSR_BSNS_NO, LEFT(A.OCCRRNC_DE, 6)) AS SAMT,
         SUM(A.SPNSR_AMT) OVER (PARTITION BY A.MBER_NO, LEFT(A.OCCRRNC_DE, 6)) AS MAMT,
         A.SPNSR_NO, A.SPNSR_BSNS_NO, A.OCCRRNC_DE, A.SER_NO, A.MBER_NO, A.ACMSLT_DEPT_CD,
         A.SPNSR_BSNS_ID, A.CMPGN_CD, A.SPNSR_AMT, A.DVLP_DIV_CD
  FROM GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_DVLP_AMT A
  WHERE A.OCCRRNC_DE BETWEEN '20260101' AND TO_CHAR(CURRENT_DATE(), 'YYYYMM') || '31'
    AND A.DVLP_DIV_CD IN ('2', '3', '5')
),
CHANGE_MEMBER AS (
  SELECT SUM(IFF(C.DVLP_DIV_CD = '3', C.SPNSR_AMT, 0)) OVER (PARTITION BY C.MBER_NO, C.STRD_MT) AS DAMT, C.*
  FROM CHANGE_BASE C
  WHERE C.MAMT > 0
    AND ((C.SAMT > 0 AND C.DVLP_DIV_CD = '2') OR (C.SAMT < 0 AND C.DVLP_DIV_CD = '3'))
),
CHANGE_RUNNING AS (
  SELECT SUM(C.SAMT) OVER (PARTITION BY C.MBER_NO, C.STRD_MT ORDER BY C.OCCRRNC_DE, C.SER_NO
                           ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS AAMT, C.*
  FROM CHANGE_MEMBER C WHERE C.DVLP_DIV_CD = '2'
),
CHANGE_ALLOC AS (
  SELECT ROW_NUMBER() OVER (PARTITION BY C.STRD_MT, C.SPNSR_NO, C.SPNSR_BSNS_NO ORDER BY C.SER_NO) AS RNUM,
         CASE WHEN C.MAMT <= C.SAMT AND C.AAMT + C.DAMT <= C.MAMT THEN C.AAMT + C.DAMT
              WHEN C.MAMT >  C.SAMT AND C.AAMT + C.DAMT <= C.SAMT THEN C.AAMT + C.DAMT
              WHEN C.MAMT <= C.SAMT THEN C.MAMT
              ELSE C.SAMT END AS RAMT,
         C.*
  FROM CHANGE_RUNNING C WHERE C.AAMT - ABS(C.DAMT) > 0
),
SRC AS (
  SELECT * FROM NEW_REJOIN
  UNION ALL
  SELECT STRD_MT, SPNSR_NO, SPNSR_BSNS_NO, OCCRRNC_DE, SER_NO, MBER_NO, COALESCE(ACMSLT_DEPT_CD, 'Z~'),
         SPNSR_BSNS_ID, CMPGN_CD, '2', RAMT
  FROM CHANGE_ALLOC WHERE RNUM = 1
)
SELECT S.*,
       D.DEPT2_ID, D.DEPT3_ID, D.DEPT4_ID,
       COALESCE(B.SPNSR_BSNS_ABRV_CD, '0') AS SPNSR_BSNS_ABRV_CD,
       COALESCE(B.CPR_DIV_CD, '0')         AS CPR_DIV_CD,
       CM.UPPER_CMPGN_CD,
       S.SPNSR_AMT / 10000.0               AS SPNSR_AMT_CNT
FROM SRC S
LEFT JOIN SK_DEPT D ON S.DEPT_ID = D.DEPT_ID
LEFT JOIN SK_BSNS B ON S.SPNSR_BSNS_ID = B.SPNSR_BSNS_ID
LEFT JOIN GN_DW.BRONZE_CRM.TM_CM_CMPGN_MNG CM ON S.CMPGN_CD = CM.CMPGN_CD;

-- ---------------------------------------------------------------------
-- [S2] MSTR 측 원장
-- ---------------------------------------------------------------------
CREATE OR REPLACE TEMPORARY TABLE MS_F AS
SELECT STRD_MT, SPNSR_NO, SPNSR_BSNS_NO, OCCRRNC_DE, SER_NO, MBER_NO,
       COALESCE(ACMSLT_DEPT_CD, 'Z~') AS DEPT_ID, SPNSR_BSNS_ID, CMPGN_CD, DVLP_DIV_CD, SPNSR_AMT,
       ACMSLT_DEPT2_CD AS DEPT2_ID, ACMSLT_DEPT3_CD AS DEPT3_ID, ACMSLT_DEPT4_CD AS DEPT4_ID,
       SPNSR_BSNS_ABRV_CD, CPR_DIV_CD, UPPER_CMPGN_CD, SPNSR_AMT_CNT
FROM GN_DW.MSTR.F_MM_SPNSR_DVLP_SUM
WHERE DVLP_DIV_CD IN ('1', '2', '4') AND STRD_MT >= '202601';

-- ---------------------------------------------------------------------
-- @CHECK V01 개발구분별 기본 Fact — 월 × 개발구분
-- ---------------------------------------------------------------------
WITH S AS (SELECT STRD_MT, DVLP_DIV_CD, COUNT(*) N, COUNT(DISTINCT MBER_NO) MBR, SUM(SPNSR_AMT_CNT) CNT, SUM(SPNSR_AMT) AMT FROM SK_F GROUP BY 1, 2),
     M AS (SELECT STRD_MT, DVLP_DIV_CD, COUNT(*) N, COUNT(DISTINCT MBER_NO) MBR, SUM(SPNSR_AMT_CNT) CNT, SUM(SPNSR_AMT) AMT FROM MS_F GROUP BY 1, 2)
SELECT COALESCE(S.STRD_MT, M.STRD_MT) STRD_MT, COALESCE(S.DVLP_DIV_CD, M.DVLP_DIV_CD) DVLP_DIV_CD,
       S.N SK_N, M.N MS_N, S.MBR SK_MBR, M.MBR MS_MBR,
       ROUND(S.CNT, 4) SK_CNT, ROUND(M.CNT, 4) MS_CNT, S.AMT SK_AMT, M.AMT MS_AMT,
       IFF(EQUAL_NULL(S.N, M.N) AND EQUAL_NULL(S.MBR, M.MBR) AND ROUND(S.CNT, 4) = ROUND(M.CNT, 4)
           AND EQUAL_NULL(S.AMT, M.AMT), 'PASS', 'FAIL') RESULT
FROM S FULL JOIN M ON S.STRD_MT = M.STRD_MT AND S.DVLP_DIV_CD = M.DVLP_DIV_CD
ORDER BY 1, 2;

-- ---------------------------------------------------------------------
-- @CHECK V02 스킬 고정 기준값 게이트 — 202606 전체법인 (04_VALIDATION_GATES.yaml)
-- ---------------------------------------------------------------------
WITH G (DVLP_DIV_CD, N, MBR, CNT, AMT) AS (
  SELECT * FROM VALUES ('1', 12832, 11969, 25713.8900, 257138900),
                       ('2',  2318,  2014,  4999.9501,  49999501),
                       ('4',  1605,  1465,  3350.7500,  33507500)),
     X AS (SELECT 'SKILL' SIDE, DVLP_DIV_CD, COUNT(*) N, COUNT(DISTINCT MBER_NO) MBR, SUM(SPNSR_AMT_CNT) CNT, SUM(SPNSR_AMT) AMT FROM SK_F WHERE STRD_MT = '202606' GROUP BY 1, 2
           UNION ALL
           SELECT 'MSTR',  DVLP_DIV_CD, COUNT(*), COUNT(DISTINCT MBER_NO), SUM(SPNSR_AMT_CNT), SUM(SPNSR_AMT) FROM MS_F WHERE STRD_MT = '202606' GROUP BY 1, 2)
SELECT X.SIDE, G.DVLP_DIV_CD, G.N GATE_N, X.N, G.MBR GATE_MBR, X.MBR, G.CNT GATE_CNT, ROUND(X.CNT, 4) CNT, G.AMT GATE_AMT, X.AMT,
       IFF(X.N = G.N AND X.MBR = G.MBR AND ROUND(X.CNT, 4) = G.CNT AND X.AMT = G.AMT, 'PASS', 'FAIL') RESULT
FROM G LEFT JOIN X ON G.DVLP_DIV_CD = X.DVLP_DIV_CD
ORDER BY 1, 2;

-- ---------------------------------------------------------------------
-- @CHECK V03 원장 행 단위 대사
-- ---------------------------------------------------------------------
SELECT COALESCE(S.STRD_MT, M.STRD_MT) STRD_MT,
       CASE WHEN M.SPNSR_NO IS NULL THEN 'SKILL_ONLY'
            WHEN S.SPNSR_NO IS NULL THEN 'MSTR_ONLY'
            WHEN S.SPNSR_AMT <> M.SPNSR_AMT THEN 'AMT_DIFF'
            WHEN S.MBER_NO <> M.MBER_NO OR S.DEPT_ID <> M.DEPT_ID OR S.SPNSR_BSNS_ID <> M.SPNSR_BSNS_ID
              OR S.CPR_DIV_CD <> M.CPR_DIV_CD OR NOT EQUAL_NULL(S.CMPGN_CD, M.CMPGN_CD) THEN 'ATTR_DIFF'
            ELSE 'MATCH' END ST,
       COUNT(*) ROWS_CNT,
       IFF(ST = 'MATCH', 'PASS', 'FAIL') RESULT
FROM SK_F S
FULL JOIN MS_F M
  ON S.SPNSR_NO = M.SPNSR_NO AND S.SPNSR_BSNS_NO = M.SPNSR_BSNS_NO AND S.OCCRRNC_DE = M.OCCRRNC_DE
 AND S.SER_NO = M.SER_NO AND S.DVLP_DIV_CD = M.DVLP_DIV_CD
GROUP BY 1, 2
ORDER BY 1, 2;

-- ---------------------------------------------------------------------
-- @CHECK V04 DEV_1_1 부서별 회원개발(당월) — 스킬 #MONTH_AGG grain
-- ---------------------------------------------------------------------
WITH S AS (SELECT STRD_MT, CPR_DIV_CD, DEPT4_ID, DEPT3_ID, DEPT_ID, SPNSR_BSNS_ABRV_CD, SPNSR_BSNS_ID, DVLP_DIV_CD,
                  SUM(SPNSR_AMT_CNT) W1, COUNT(DISTINCT MBER_NO) W2, SUM(SPNSR_AMT) W3 FROM SK_F GROUP BY ALL),
     M AS (SELECT STRD_MT, CPR_DIV_CD, DEPT4_ID, DEPT3_ID, DEPT_ID, SPNSR_BSNS_ABRV_CD, SPNSR_BSNS_ID, DVLP_DIV_CD,
                  SUM(SPNSR_AMT_CNT) W1, COUNT(DISTINCT MBER_NO) W2, SUM(SPNSR_AMT) W3 FROM MS_F GROUP BY ALL),
     J AS (SELECT COALESCE(S.STRD_MT, M.STRD_MT) STRD_MT,
                  CASE WHEN M.STRD_MT IS NULL THEN 'MISSING_IN_MSTR'
                       WHEN S.STRD_MT IS NULL THEN 'EXTRA_IN_MSTR'
                       WHEN ROUND(S.W1, 4) <> ROUND(M.W1, 4) OR S.W2 <> M.W2 OR S.W3 <> M.W3 THEN 'METRIC_DIFF'
                       ELSE 'MATCH' END ST
           FROM S FULL JOIN M
             ON S.STRD_MT = M.STRD_MT AND EQUAL_NULL(S.CPR_DIV_CD, M.CPR_DIV_CD) AND EQUAL_NULL(S.DEPT4_ID, M.DEPT4_ID)
            AND EQUAL_NULL(S.DEPT3_ID, M.DEPT3_ID) AND S.DEPT_ID = M.DEPT_ID
            AND EQUAL_NULL(S.SPNSR_BSNS_ABRV_CD, M.SPNSR_BSNS_ABRV_CD) AND S.SPNSR_BSNS_ID = M.SPNSR_BSNS_ID
            AND S.DVLP_DIV_CD = M.DVLP_DIV_CD)
SELECT STRD_MT, ST, COUNT(*) KEY_CNT, IFF(ST = 'MATCH', 'PASS', 'FAIL') RESULT
FROM J GROUP BY 1, 2 ORDER BY 1, 2;

-- ---------------------------------------------------------------------
-- @CHECK V05 DEV_1_2 부서별 회원개발(누계) — 기준월별 1월~기준월
-- ---------------------------------------------------------------------
WITH MT AS (SELECT DISTINCT STRD_MT FROM SK_F),
     S AS (SELECT MT.STRD_MT BASE_MT, F.CPR_DIV_CD, F.DEPT4_ID, F.DEPT3_ID, F.DEPT_ID, F.SPNSR_BSNS_ABRV_CD, F.SPNSR_BSNS_ID, F.DVLP_DIV_CD,
                  SUM(F.SPNSR_AMT_CNT) W4, COUNT(DISTINCT F.MBER_NO) W5
           FROM MT JOIN SK_F F ON F.STRD_MT BETWEEN LEFT(MT.STRD_MT, 4) || '01' AND MT.STRD_MT GROUP BY ALL),
     M AS (SELECT MT.STRD_MT BASE_MT, F.CPR_DIV_CD, F.DEPT4_ID, F.DEPT3_ID, F.DEPT_ID, F.SPNSR_BSNS_ABRV_CD, F.SPNSR_BSNS_ID, F.DVLP_DIV_CD,
                  SUM(F.SPNSR_AMT_CNT) W4, COUNT(DISTINCT F.MBER_NO) W5
           FROM MT JOIN MS_F F ON F.STRD_MT BETWEEN LEFT(MT.STRD_MT, 4) || '01' AND MT.STRD_MT GROUP BY ALL),
     J AS (SELECT COALESCE(S.BASE_MT, M.BASE_MT) BASE_MT,
                  CASE WHEN M.BASE_MT IS NULL THEN 'MISSING_IN_MSTR'
                       WHEN S.BASE_MT IS NULL THEN 'EXTRA_IN_MSTR'
                       WHEN ROUND(S.W4, 4) <> ROUND(M.W4, 4) OR S.W5 <> M.W5 THEN 'METRIC_DIFF'
                       ELSE 'MATCH' END ST,
                  S.W4 SK_W4, M.W4 MS_W4
           FROM S FULL JOIN M
             ON S.BASE_MT = M.BASE_MT AND EQUAL_NULL(S.CPR_DIV_CD, M.CPR_DIV_CD) AND EQUAL_NULL(S.DEPT4_ID, M.DEPT4_ID)
            AND EQUAL_NULL(S.DEPT3_ID, M.DEPT3_ID) AND S.DEPT_ID = M.DEPT_ID
            AND EQUAL_NULL(S.SPNSR_BSNS_ABRV_CD, M.SPNSR_BSNS_ABRV_CD) AND S.SPNSR_BSNS_ID = M.SPNSR_BSNS_ID
            AND S.DVLP_DIV_CD = M.DVLP_DIV_CD)
SELECT BASE_MT, ST, COUNT(*) KEY_CNT, ROUND(SUM(SK_W4), 4) SK_W4, ROUND(SUM(MS_W4), 4) MS_W4,
       IFF(ST = 'MATCH', 'PASS', 'FAIL') RESULT
FROM J GROUP BY 1, 2 ORDER BY 1, 2;

-- ---------------------------------------------------------------------
-- @CHECK V06 DEV_1_3 / DEV_1_4 회원구분(신규/기존)별 개발 — 당월 · 누계
--   스킬: 원천 전체 DVLP_DIV_CD='1' MIN(OCCRRNC_DE) >= 기준연도 0101 → 신규
--   MSTR: 원장 F_MM_SPNSR_DVLP(전 이력) DVLP_DIV_CD='1' MIN(OCCRRNC_DE) 기준
-- ---------------------------------------------------------------------
WITH SK_FIRST AS (SELECT MBER_NO, MIN(OCCRRNC_DE) FIRST_NEW_DE FROM GN_DW.BRONZE_CRM.TM_MM_FDRM_MBER_DVLP_AMT WHERE DVLP_DIV_CD = '1' GROUP BY 1),
     MS_FIRST AS (SELECT MBER_NO, MIN(OCCRRNC_DE) FIRST_NEW_DE FROM GN_DW.MSTR.F_MM_SPNSR_DVLP WHERE DVLP_DIV_CD = '1' GROUP BY 1),
     SB AS (SELECT F.STRD_MT, F.DVLP_DIV_CD, F.MBER_NO, F.SPNSR_AMT_CNT,
                   IFF(X.FIRST_NEW_DE >= LEFT(F.STRD_MT, 4) || '0101', '신규회원', '기존회원') MBR_TY
            FROM SK_F F LEFT JOIN SK_FIRST X ON F.MBER_NO = X.MBER_NO),
     MB AS (SELECT F.STRD_MT, F.DVLP_DIV_CD, F.MBER_NO, F.SPNSR_AMT_CNT,
                   IFF(X.FIRST_NEW_DE >= LEFT(F.STRD_MT, 4) || '0101', '신규회원', '기존회원') MBR_TY
            FROM MS_F F LEFT JOIN MS_FIRST X ON F.MBER_NO = X.MBER_NO),
     MT AS (SELECT DISTINCT STRD_MT FROM SK_F),
     S AS (SELECT 'MONTH' PRD, STRD_MT BASE_MT, DVLP_DIV_CD, MBR_TY, SUM(SPNSR_AMT_CNT) CNT, COUNT(DISTINCT MBER_NO) MBR FROM SB GROUP BY ALL
           UNION ALL
           SELECT 'YTD', MT.STRD_MT, B.DVLP_DIV_CD, B.MBR_TY, SUM(B.SPNSR_AMT_CNT), COUNT(DISTINCT B.MBER_NO)
           FROM MT JOIN SB B ON B.STRD_MT BETWEEN LEFT(MT.STRD_MT, 4) || '01' AND MT.STRD_MT GROUP BY ALL),
     M AS (SELECT 'MONTH' PRD, STRD_MT BASE_MT, DVLP_DIV_CD, MBR_TY, SUM(SPNSR_AMT_CNT) CNT, COUNT(DISTINCT MBER_NO) MBR FROM MB GROUP BY ALL
           UNION ALL
           SELECT 'YTD', MT.STRD_MT, B.DVLP_DIV_CD, B.MBR_TY, SUM(B.SPNSR_AMT_CNT), COUNT(DISTINCT B.MBER_NO)
           FROM MT JOIN MB B ON B.STRD_MT BETWEEN LEFT(MT.STRD_MT, 4) || '01' AND MT.STRD_MT GROUP BY ALL)
SELECT COALESCE(S.PRD, M.PRD) PRD, COALESCE(S.BASE_MT, M.BASE_MT) BASE_MT, COALESCE(S.DVLP_DIV_CD, M.DVLP_DIV_CD) DVLP_DIV_CD,
       COALESCE(S.MBR_TY, M.MBR_TY) MBR_TY,
       ROUND(S.CNT, 4) SK_CNT, ROUND(M.CNT, 4) MS_CNT, S.MBR SK_MBR, M.MBR MS_MBR,
       IFF(EQUAL_NULL(ROUND(S.CNT, 4), ROUND(M.CNT, 4)) AND EQUAL_NULL(S.MBR, M.MBR), 'PASS', 'FAIL') RESULT
FROM S FULL JOIN M ON S.PRD = M.PRD AND S.BASE_MT = M.BASE_MT AND S.DVLP_DIV_CD = M.DVLP_DIV_CD AND S.MBR_TY = M.MBR_TY
ORDER BY 1, 2, 3, 4;

-- ---------------------------------------------------------------------
-- @CHECK V07 DEV_1_5 캠페인 / 상위캠페인 + TOP10 순위
-- ---------------------------------------------------------------------
WITH S AS (SELECT 'CMPGN' LVL, STRD_MT, CMPGN_CD CD, SUM(SPNSR_AMT_CNT) CNT, COUNT(DISTINCT MBER_NO) MBR FROM SK_F GROUP BY ALL
           UNION ALL
           SELECT 'UPPER', STRD_MT, UPPER_CMPGN_CD, SUM(SPNSR_AMT_CNT), COUNT(DISTINCT MBER_NO) FROM SK_F GROUP BY ALL),
     M AS (SELECT 'CMPGN' LVL, STRD_MT, CMPGN_CD CD, SUM(SPNSR_AMT_CNT) CNT, COUNT(DISTINCT MBER_NO) MBR FROM MS_F GROUP BY ALL
           UNION ALL
           SELECT 'UPPER', STRD_MT, UPPER_CMPGN_CD, SUM(SPNSR_AMT_CNT), COUNT(DISTINCT MBER_NO) FROM MS_F GROUP BY ALL),
     SR AS (SELECT *, RANK() OVER (PARTITION BY LVL, STRD_MT ORDER BY CNT DESC) RK FROM S),
     MR AS (SELECT *, RANK() OVER (PARTITION BY LVL, STRD_MT ORDER BY CNT DESC) RK FROM M),
     J AS (SELECT COALESCE(SR.LVL, MR.LVL) LVL, COALESCE(SR.STRD_MT, MR.STRD_MT) STRD_MT,
                  CASE WHEN MR.STRD_MT IS NULL THEN 'MISSING_IN_MSTR'
                       WHEN SR.STRD_MT IS NULL THEN 'EXTRA_IN_MSTR'
                       WHEN ROUND(SR.CNT, 4) <> ROUND(MR.CNT, 4) OR SR.MBR <> MR.MBR THEN 'METRIC_DIFF'
                       ELSE 'MATCH' END ST,
                  IFF(LEAST(COALESCE(SR.RK, 999), COALESCE(MR.RK, 999)) <= 10 AND NOT EQUAL_NULL(SR.RK, MR.RK), 1, 0) TOP10_RANK_DIFF
           FROM SR FULL JOIN MR ON SR.LVL = MR.LVL AND SR.STRD_MT = MR.STRD_MT AND EQUAL_NULL(SR.CD, MR.CD))
SELECT LVL, STRD_MT, ST, COUNT(*) KEY_CNT, SUM(TOP10_RANK_DIFF) TOP10_RANK_DIFF,
       IFF(ST = 'MATCH' AND SUM(TOP10_RANK_DIFF) = 0, 'PASS', 'FAIL') RESULT
FROM J GROUP BY 1, 2, 3 ORDER BY 1, 2, 3;

-- ---------------------------------------------------------------------
-- @CHECK V08 차원 매핑 — 부서 계층 · 법인 · 사업약어 · 상위캠페인 (행 단위)
-- ---------------------------------------------------------------------
SELECT S.STRD_MT,
       SUM(IFF(NOT EQUAL_NULL(S.DEPT2_ID, M.DEPT2_ID), 1, 0)) DEPT2_DIFF,
       SUM(IFF(NOT EQUAL_NULL(S.DEPT3_ID, M.DEPT3_ID), 1, 0)) DEPT3_DIFF,
       SUM(IFF(NOT EQUAL_NULL(S.DEPT4_ID, M.DEPT4_ID), 1, 0)) DEPT4_DIFF,
       SUM(IFF(NOT EQUAL_NULL(S.CPR_DIV_CD, M.CPR_DIV_CD), 1, 0)) CPR_DIFF,
       SUM(IFF(NOT EQUAL_NULL(S.SPNSR_BSNS_ABRV_CD, M.SPNSR_BSNS_ABRV_CD), 1, 0)) ABRV_DIFF,
       SUM(IFF(NOT EQUAL_NULL(S.UPPER_CMPGN_CD, M.UPPER_CMPGN_CD), 1, 0)) UPPER_CMPGN_DIFF,
       SUM(IFF(S.DEPT4_ID IS NULL OR S.DEPT_ID = 'Z~', 1, 0)) SK_DEPT_UNMAPPED,
       SUM(IFF(M.DEPT4_ID IS NULL OR M.DEPT_ID = 'Z~', 1, 0)) MS_DEPT_UNMAPPED,
       IFF(DEPT2_DIFF + DEPT3_DIFF + DEPT4_DIFF + CPR_DIFF + ABRV_DIFF + UPPER_CMPGN_DIFF = 0
           AND SK_DEPT_UNMAPPED = MS_DEPT_UNMAPPED, 'PASS', 'FAIL') RESULT
FROM SK_F S
JOIN MS_F M
  ON S.SPNSR_NO = M.SPNSR_NO AND S.SPNSR_BSNS_NO = M.SPNSR_BSNS_NO AND S.OCCRRNC_DE = M.OCCRRNC_DE
 AND S.SER_NO = M.SER_NO AND S.DVLP_DIV_CD = M.DVLP_DIV_CD
GROUP BY 1 ORDER BY 1;

-- ---------------------------------------------------------------------
-- @CHECK V09 회원합계 규칙 — 전체 DISTINCT vs 부서별 명 단순합
-- ---------------------------------------------------------------------
WITH S AS (SELECT STRD_MT, COUNT(DISTINCT MBER_NO) GRAND FROM SK_F GROUP BY 1),
     SD AS (SELECT STRD_MT, SUM(C) DEPT_SUM FROM (SELECT STRD_MT, DEPT_ID, COUNT(DISTINCT MBER_NO) C FROM SK_F GROUP BY 1, 2) GROUP BY 1),
     M AS (SELECT STRD_MT, COUNT(DISTINCT MBER_NO) GRAND FROM MS_F GROUP BY 1),
     MD AS (SELECT STRD_MT, SUM(C) DEPT_SUM FROM (SELECT STRD_MT, DEPT_ID, COUNT(DISTINCT MBER_NO) C FROM MS_F GROUP BY 1, 2) GROUP BY 1)
SELECT S.STRD_MT, S.GRAND SK_GRAND, M.GRAND MS_GRAND, SD.DEPT_SUM SK_DEPT_SUM, MD.DEPT_SUM MS_DEPT_SUM,
       SD.DEPT_SUM - S.GRAND OVERCOUNT_IF_SUMMED,
       IFF(S.GRAND = M.GRAND AND SD.DEPT_SUM = MD.DEPT_SUM, 'PASS', 'FAIL') RESULT
FROM S JOIN SD USING (STRD_MT) LEFT JOIN M USING (STRD_MT) LEFT JOIN MD USING (STRD_MT)
ORDER BY 1;
