-- CRM_MSG_TEMPLATE: 발송 템플릿 마스터 = 알림톡 ∪ 이메일 (BRONZE → SILVER) · 🆕 O188-F 2차-A 신설
-- Co-authored with CoCo
-- grain = SEND_CHANNEL × TEMPLATE_KEY (📏 xf98254 알림톡 TMPLAT_ID 6,562 · 이메일 TMPLAT_KEY 449 유일)
-- 🟢 이메일 템플릿 마스터는 SNAPSHOT(SNP_CRM_TM_MS_EMAIL_TMPLAT_MNG)으로만 흘렀다 ⇒ SILVER·GOLD 에 처음 올린다.
-- ⚠️ 알림톡 전용 컬럼(승인·대체메시지 등)은 이메일 행에서 NULL = 원천 개념 부재.
SELECT
  'MSG_AT'                              AS SEND_CHANNEL,
  NULLIF(TRIM(TMPLAT_ID),'')            AS TEMPLATE_KEY,
  NULLIF(TRIM(CPR_DIV_CD),'')           AS CPR_DIV_CD,
  NULLIF(TRIM(SNDNG_CD_ID),'')          AS SNDNG_CD_ID,
  NULLIF(TRIM(SNDNG_DTL_CD_ID),'')      AS SNDNG_DTL_CD_ID,
  NULLIF(TRIM(ATMC_YN),'')              AS ATMC_YN,
  NULLIF(TRIM(TIT),'')                  AS TIT,
  TMPLAT_CTNT                           AS TEMPLATE_CTNT,
  NULLIF(TRIM(WRITNG_DEPT_ID),'')       AS WRITNG_DEPT_ID,
  NULLIF(TRIM(WRITNG_DEPT_NM),'')       AS WRITNG_DEPT_NM,
  NULLIF(TRIM(CHRG_DEPT_ID),'')         AS CHRG_DEPT_ID,
  NULLIF(TRIM(APRV_STAT_CD),'')         AS APRV_STAT_CD,
  APRV_FAILR_CTNT                       AS APRV_FAILR_CTNT,
  TMPLAT_RM                             AS TEMPLATE_RM,
  NULLIF(TRIM(ALTRTV_MSG_SNDNG_YN),'')  AS ALTRTV_MSG_SNDNG_YN,
  ALTRTV_MSG_TMPLAT_KEY                 AS ALTRTV_MSG_TMPLAT_KEY,
  ALTRTV_MSG_CTNT                       AS ALTRTV_MSG_CTNT,
  NULLIF(TRIM(ALTRTV_MSG_ATCHFL_ID),'') AS ALTRTV_MSG_ATCHFL_ID,
  NULLIF(TRIM(WRITNG_GUIDE_ATCHFL_ID),'') AS WRITNG_GUIDE_ATCHFL_ID,
  NULLIF(TRIM(USE_YN),'')               AS USE_YN,
  FRST_REGIST_DT                        AS FRST_REGIST_DT,
  LAST_UPDT_DT                          AS LAST_UPDT_DT,
  'CRM'                                 AS DW_SOURCE_SYSTEM,
  'BRONZE_CRM.TM_MS_AT_TMPLAT_MNG'      AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP()                   AS DW_LOAD_TS,
  CURRENT_TIMESTAMP()                   AS DW_UPDATE_TS,
  NULL                                  AS DW_BATCH_ID
FROM {{ source('bronze_crm','TM_MS_AT_TMPLAT_MNG') }}
WHERE TMPLAT_ID IS NOT NULL
UNION ALL
SELECT
  'EMAIL', TO_VARCHAR(TMPLAT_KEY),
  NULLIF(TRIM(CPR_DIV_CD),''), NULLIF(TRIM(SNDNG_CD_ID),''), NULLIF(TRIM(SNDNG_DTL_CD_ID),''),
  NULLIF(TRIM(ATMC_YN),''), NULLIF(TRIM(TIT),''), EMAIL_CTNT,
  NULLIF(TRIM(WRITNG_DEPT_ID),''), NULLIF(TRIM(WRITNG_DEPT_NM),''), NULLIF(TRIM(CHRG_DEPT_ID),''),
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
  FRST_REGIST_DT, LAST_UPDT_DT,
  'CRM', 'BRONZE_CRM.TM_MS_EMAIL_TMPLAT_MNG', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM {{ source('bronze_crm','TM_MS_EMAIL_TMPLAT_MNG') }}
WHERE TMPLAT_KEY IS NOT NULL
