-- CRM_RELATION_DEV: 결연 개발금액 사건(결연 개발·상태 전이) (BRONZE TM_MM_FDRM_MBER_RELATNSP_DVLP_AMT → SILVER) · 🆕 O188-F 2차-A 신설(종전 미연결 원천)
-- Co-authored with CoCo
-- grain = OCCRRNC_DE, SER_NO (📏 xf98254 유일 실측)
SELECT
  NULLIF(TRIM(OCCRRNC_DE),'') AS OCCRRNC_DE,
  SER_NO AS SER_NO,
  SPNSR_NO AS SPNSR_NO,
  SPNSR_BSNS_NO AS SPNSR_BSNS_NO,
  NULLIF(TRIM(MBER_NO),'') AS MBER_NO,
  SPNSR_AMT AS SPNSR_AMT,
  NULLIF(TRIM(BF_STAT_CD),'') AS BF_STAT_CD,
  NULLIF(TRIM(AF_STAT_CD),'') AS AF_STAT_CD,
  NULLIF(TRIM(RELATNSP_DVLP_DIV_CD),'') AS RELATNSP_DVLP_DIV_CD,
  NULLIF(TRIM(ACCNUT_STATS_CD),'') AS ACCNUT_STATS_CD,
  NULLIF(TRIM(CHILD_STATS_CD),'') AS CHILD_STATS_CD,
  'CRM'                          AS DW_SOURCE_SYSTEM,
  'BRONZE_CRM.TM_MM_FDRM_MBER_RELATNSP_DVLP_AMT' AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP()            AS DW_LOAD_TS,
  CURRENT_TIMESTAMP()            AS DW_UPDATE_TS,
  NULL                           AS DW_BATCH_ID
FROM {{ source('bronze_crm','TM_MM_FDRM_MBER_RELATNSP_DVLP_AMT') }}
WHERE OCCRRNC_DE IS NOT NULL AND SER_NO IS NOT NULL
  -- 🔴 O179 이슈 B · 회원 마스터 미실재(고아) 제거 — 정의 = macros/gn_member_master_filter.sql
  AND {{ gn_member_master_filter("NULLIF(TRIM(MBER_NO),'')") }}
