-- CRM_MEMBER: 회원 마스터 = 정기(FDRM) ∪ 일시(ONCE), SEX/MBER_DIV_NM/상태 라벨·수신동의 정규화, 정본 09 STEP3 배치4.
-- Co-authored with CoCo
SELECT
  NULLIF(TRIM(f.MBER_NO),'')       AS MEMBER_DK,
  'FDRM'                           AS MEMBER_TYPE,
  NULLIF(TRIM(f.MBER_DIV_CD),'')   AS MBER_DIV_CD,
  md.DTL_CD_NM                     AS MBER_DIV_NM,
  NULLIF(TRIM(f.CPR_DIV_CD),'')    AS CPR_DIV_CD,
  CASE WHEN f.SEX IN ('1','3') THEN 'M' WHEN f.SEX IN ('2','4') THEN 'F' WHEN NULLIF(TRIM(f.SEX),'') IS NULL THEN NULL ELSE 'U' END AS SEX,
  NULLIF(TRIM(f.MBER_STAT_CD),'')  AS MBER_STAT_CD,
  st.DTL_CD_NM                     AS MBER_STAT_NM,
  NULLIF(TRIM(f.CMPGN_CD),'')      AS CMPGN_CD,
  NULLIF(TRIM(f.ACT_DEPT_CD),'')   AS ACT_DEPT_CD,
  NULLIF(TRIM(f.REGIST_DEPT_CD),'')AS REGIST_DEPT_CD,
  NULLIF(TRIM(f.JOIN_PATH_CD),'')  AS JOIN_PATH_CD,
  NULLIF(TRIM(f.HMPG_ID),'')       AS HMPG_ID,
  NULL                             AS ENTRPS_NM,
  CASE WHEN NULLIF(TRIM(f.EMAIL_RECPTN_CD),'') IS NULL THEN NULL
       ELSE ARRAY_TO_STRING(ARRAY_SORT(ARRAY_DISTINCT(ARRAY_REMOVE(SPLIT(REPLACE(TRIM(f.EMAIL_RECPTN_CD),' ',''),','),TO_VARIANT('')))),',') END AS EMAIL_RECPTN,
  CASE WHEN NULLIF(TRIM(f.PSTMTR_RECPTN_CD),'') IS NULL THEN NULL
       ELSE ARRAY_TO_STRING(ARRAY_SORT(ARRAY_DISTINCT(ARRAY_REMOVE(SPLIT(REPLACE(TRIM(f.PSTMTR_RECPTN_CD),' ',''),','),TO_VARIANT('')))),',') END AS PSTMTR_RECPTN,
  f.FRST_REGIST_DT                 AS JOIN_DT,
  'CRM'                            AS DW_SOURCE_SYSTEM,
  'BRONZE_CRM.TM_MM_FDRM_MBER_INFO' AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP()              AS DW_LOAD_TS,
  CURRENT_TIMESTAMP()              AS DW_UPDATE_TS,
  NULL                             AS DW_BATCH_ID
FROM {{ source('bronze_crm','TM_MM_FDRM_MBER_INFO') }} f
LEFT JOIN {{ ref('CRM_CODE') }} st ON st.CD_ID='MM010' AND st.DTL_CD_ID = NULLIF(TRIM(f.MBER_STAT_CD),'')
LEFT JOIN {{ ref('CRM_CODE') }} md ON md.CD_ID='MM018' AND md.DTL_CD_ID = NULLIF(TRIM(f.MBER_DIV_CD),'')
WHERE f.MBER_NO IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY NULLIF(TRIM(f.MBER_NO),'') ORDER BY f.FRST_REGIST_DT DESC NULLS LAST)=1
UNION ALL
SELECT
  NULLIF(TRIM(o.ONCE_MBER_NO),''), 'ONCE', NULLIF(TRIM(o.MBER_DIV_CD),''), md.DTL_CD_NM, NULLIF(TRIM(o.CPR_DIV_CD),''),
  CASE WHEN o.SEX IN ('1','3') THEN 'M' WHEN o.SEX IN ('2','4') THEN 'F' WHEN NULLIF(TRIM(o.SEX),'') IS NULL THEN NULL ELSE 'U' END,
  NULL, NULL,
  NULL, NULL, NULLIF(TRIM(o.REGIST_DEPT_CD),''),
  NULL, NULLIF(TRIM(o.HMPG_ID),''), NULLIF(TRIM(o.ENTRPS_NM),''),
  NULLIF(TRIM(o.EMAIL_RECPTN_YN),''), NULLIF(TRIM(o.PSTMTR_RECPTN_YN),''),
  o.FRST_REGIST_DT,
  'CRM','BRONZE_CRM.TM_MM_ONCE_MBER_INFO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM {{ source('bronze_crm','TM_MM_ONCE_MBER_INFO') }} o
LEFT JOIN {{ ref('CRM_CODE') }} md ON md.CD_ID='MM018' AND md.DTL_CD_ID = NULLIF(TRIM(o.MBER_DIV_CD),'')
WHERE o.ONCE_MBER_NO IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY NULLIF(TRIM(o.ONCE_MBER_NO),'') ORDER BY o.FRST_REGIST_DT DESC NULLS LAST)=1
