-- CRM_BIZ_PLACE: 결연 사업장 마스터 (BRONZE TM_RM_BPLC_MNG → SILVER) · 🆕 O188-F 2차-A 신설(종전 미연결 원천)
-- Co-authored with CoCo
-- grain = BPLC_CD (📏 xf98254 유일 실측)
SELECT
  NULLIF(TRIM(BPLC_CD),'') AS BPLC_CD,
  NULLIF(TRIM(NATION_CD),'') AS NATION_CD,
  NULLIF(TRIM(BPLC_KORNM),'') AS BPLC_KORNM,
  NULLIF(TRIM(BPLC_ENGNM),'') AS BPLC_ENGNM,
  BSNS_STRT_DE AS BSNS_STRT_DE,
  BSNS_END_DE AS BSNS_END_DE,
  NULLIF(TRIM(RELATNSP_BSNS_YN),'') AS RELATNSP_BSNS_YN,
  RELATNSP_BSNS_DSCNTC_DE AS RELATNSP_BSNS_DSCNTC_DE,
  NULLIF(TRIM(GFTMNEY_PSBL_YN),'') AS GFTMNEY_PSBL_YN,
  NULLIF(TRIM(LETTER_PSBL_YN),'') AS LETTER_PSBL_YN,
  NULLIF(TRIM(BPLC_DC),'') AS BPLC_DC,
  WTWK_FROM_DSTNC AS WTWK_FROM_DSTNC,
  NULLIF(TRIM(CNCSN_RSN),'') AS CNCSN_RSN,
  NULLIF(TRIM(BPLC_MTCHG_MNG_YN),'') AS BPLC_MTCHG_MNG_YN,
  FRST_REGIST_DT AS FRST_REGIST_DT,
  LAST_UPDT_DT AS LAST_UPDT_DT,
  'CRM'                          AS DW_SOURCE_SYSTEM,
  'BRONZE_CRM.TM_RM_BPLC_MNG' AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP()            AS DW_LOAD_TS,
  CURRENT_TIMESTAMP()            AS DW_UPDATE_TS,
  NULL                           AS DW_BATCH_ID
FROM {{ source('bronze_crm','TM_RM_BPLC_MNG') }}
WHERE BPLC_CD IS NOT NULL
