-- CRM_EVENT_PARTICIPATION: 행사 참여 = EVENT ∪ CRMN 참여자 (PK dedup), 정본 09 STEP3.
-- Co-authored with CoCo
SELECT 'EVENT_'||EVENT_CD          AS EVENT_KEY,
  NULLIF(TRIM(MBER_NO),'')         AS MBER_NO,
  PARTCPT_SEQ                      AS PARTCPT_SEQ,
  NULLIF(TRIM(PARTCPT_STAT_CD),'') AS PARTCPT_STAT_CD,
  NULLIF(TRIM(PARTCPT_CHNNL_CD),'')AS PARTCPT_CHNNL_CD,
  NULLIF(TRIM(PARTCPT_PATH_CD),'') AS PARTCPT_PATH_CD,
  PRZWIN_CD                        AS PRZWIN_CD,
  NULL                             AS RCPMNY_AMT,
  PARTCPT_DT                       AS PARTCPT_DT,
  'CRM'                            AS DW_SOURCE_SYSTEM,
  'BRONZE_CRM.TD_MS_EVENT_PRTCPNT_DTL' AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP()              AS DW_LOAD_TS,
  CURRENT_TIMESTAMP()              AS DW_UPDATE_TS,
  NULL                             AS DW_BATCH_ID
FROM {{ source('bronze_crm','TD_MS_EVENT_PRTCPNT_DTL') }} WHERE MBER_NO IS NOT NULL AND PARTCPT_SEQ IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY EVENT_CD, MBER_NO, PARTCPT_SEQ ORDER BY PARTCPT_DT DESC NULLS LAST)=1
UNION ALL
SELECT 'CRMN_'||CRMN_CD, NULLIF(TRIM(MBER_NO),''), PRTCPNT_KEY, NULLIF(TRIM(PARTCPT_STAT_CD),''),
  NULL, NULLIF(TRIM(RQST_PATH_CD),''), NULL, RCPMNY_AMT, TRY_TO_TIMESTAMP(PARTCPT_DATE),
  'CRM','BRONZE_CRM.TD_MS_CRMN_PRTCPNT', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
FROM {{ source('bronze_crm','TD_MS_CRMN_PRTCPNT') }} WHERE MBER_NO IS NOT NULL AND PRTCPNT_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY CRMN_CD, MBER_NO, PRTCPNT_KEY ORDER BY TRY_TO_TIMESTAMP(PARTCPT_DATE) DESC NULLS LAST)=1
