-- CRM_RELATION_CHANGE: 결연 교체 이력 (BRONZE TM_RM_RELATNSP_CHG_INFO → SILVER) · 🆕 O188-F 2차-A 신설(종전 미연결 원천)
-- Co-authored with CoCo
-- grain = RELATNSP_KEY (📏 xf98254 유일 실측)
SELECT
  RELATNSP_KEY AS RELATNSP_KEY,
  NULLIF(TRIM(CHG_YN),'') AS CHG_YN,
  CHG_RSN_CD AS CHG_RSN_CD,
  CHG_RST_CD AS CHG_RST_CD,
  NULLIF(TRIM(CHG_PERSON_ID),'') AS CHG_PERSON_ID,
  CHG_DE AS CHG_DE,
  CHG_RELATNSP_KEY AS CHG_RELATNSP_KEY,
  'CRM'                          AS DW_SOURCE_SYSTEM,
  'BRONZE_CRM.TM_RM_RELATNSP_CHG_INFO' AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP()            AS DW_LOAD_TS,
  CURRENT_TIMESTAMP()            AS DW_UPDATE_TS,
  NULL                           AS DW_BATCH_ID
FROM {{ source('bronze_crm','TM_RM_RELATNSP_CHG_INFO') }}
WHERE RELATNSP_KEY IS NOT NULL
