-- CRM_SETLE_CMPNY_ACCOUNT: 결제사 계정 (BRONZE TM_PM_SETLE_CMPNY_ACNT → SILVER) · 🆕 O188-F 2차-A 신설(종전 미연결 원천)
-- Co-authored with CoCo
-- grain = SETLE_CMPNY_ACNT_NO (📏 xf98254 유일 실측)
SELECT
  SETLE_CMPNY_ACNT_NO AS SETLE_CMPNY_ACNT_NO,
  NULLIF(TRIM(SETLE_CMPNY_ACNT_DIV_CD),'') AS SETLE_CMPNY_ACNT_DIV_CD,
  NULLIF(TRIM(SETLE_CMPNY_ACNT_ID),'') AS SETLE_CMPNY_ACNT_ID,
  NULLIF(TRIM(CPR_DIV_CD),'') AS CPR_DIV_CD,
  NULLIF(TRIM(ACNT_PRP),'') AS ACNT_PRP,
  ACNUT_SER_NO AS ACNUT_SER_NO,
  NULLIF(TRIM(RM),'') AS RM,
  NULLIF(TRIM(USE_YN),'') AS USE_YN,
  FRST_REGIST_DT AS FRST_REGIST_DT,
  LAST_UPDT_DT AS LAST_UPDT_DT,
  'CRM'                          AS DW_SOURCE_SYSTEM,
  'BRONZE_CRM.TM_PM_SETLE_CMPNY_ACNT' AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP()            AS DW_LOAD_TS,
  CURRENT_TIMESTAMP()            AS DW_UPDATE_TS,
  NULL                           AS DW_BATCH_ID
FROM {{ source('bronze_crm','TM_PM_SETLE_CMPNY_ACNT') }}
WHERE SETLE_CMPNY_ACNT_NO IS NOT NULL
