-- CRM_RELATION_ACTIVITY: 결연활동 = 서신 ∪ 선물금 (EHGT 제외, PK dedup), 정본 09 STEP3.
-- Co-authored with CoCo
SELECT 'LETTER_'||RELATNSP_KEY||'_'||COALESCE(NULLIF(TRIM(MNG_NO),''),'') AS ACTIVITY_KEY,
  '서신'                           AS ACTIVITY_TYPE,
  RELATNSP_KEY                     AS RELATNSP_KEY,
  NULLIF(TRIM(MNG_NO),'')          AS MNG_NO,
  NULL                             AS GFTMNEY,
  LETTER_DIV_CD                    AS LETTER_DIV_CD,
  RCEPT_DE                         AS RCEPT_DE,
  SNDNG_DE                         AS SNDNG_DE,
  'CRM'                            AS DW_SOURCE_SYSTEM,
  'BRONZE_CRM.TM_RM_RELATNSP_LETTER_INFO' AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP()              AS DW_LOAD_TS,
  CURRENT_TIMESTAMP()              AS DW_UPDATE_TS,
  NULL                             AS DW_BATCH_ID
  -- [2026-09-30 O191-F 2차-B 2단 2묶음] 누락 컬럼(원천별 분기 · 비해당 원천 = 형 맞춘 NULL · 감사컬럼 뒤)
  ,LETTER_STAT_CD AS LETTER_STAT_CD
  ,NULLIF(TRIM(LANG_CD),'') AS LANG_CD
  ,NULLIF(TRIM(ONLINE_POST_WRITNG_YN),'') AS ONLINE_POST_WRITNG_YN
  ,ONLINE_INFLOW_CD AS ONLINE_INFLOW_CD
  ,UNREPLY_RSN_CD AS UNREPLY_RSN_CD
  ,CAST(NULL AS NUMBER(10,0)) AS MBRFEE_KEY
  ,CAST(NULL AS DATE) AS SETLE_DE
  ,CAST(NULL AS VARCHAR(3)) AS SETLE_CD
  ,CAST(NULL AS VARCHAR(3)) AS GFT_DIV_CD
  ,CAST(NULL AS VARCHAR(30)) AS GFTMNEY_DOLLAR_AMT
  ,CAST(NULL AS DATE) AS APRV_DE
  ,CAST(NULL AS VARCHAR(1)) AS TRNSFER_YN
  ,CAST(NULL AS VARCHAR(10)) AS SETLE_BANK_CD   -- 🆕 [O213-F Y3-J] 선물금 전용 · 서신 = 원천 개념 없음
FROM {{ source('bronze_crm','TM_RM_RELATNSP_LETTER_INFO') }} WHERE RELATNSP_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY RELATNSP_KEY, MNG_NO ORDER BY RCEPT_DE DESC NULLS LAST)=1
UNION ALL
SELECT 'GFT_'||RELATNSP_KEY||'_'||COALESCE(NULLIF(TRIM(MNG_NO),''),''), '선물금', RELATNSP_KEY, NULLIF(TRIM(MNG_NO),''),
  GFTMNEY, NULL, NULL, SNDNG_DE,
  'CRM','BRONZE_CRM.TM_RM_RELATNSP_GFTMNEY_INFO', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), NULL
  ,CAST(NULL AS NUMBER(3,0))
  ,CAST(NULL AS VARCHAR(10))
  ,CAST(NULL AS VARCHAR(1))
  ,CAST(NULL AS NUMBER(10,0))
  ,UNREPLY_RSN_CD
  ,MBRFEE_KEY
  ,SETLE_DE
  ,NULLIF(TRIM(SETLE_CD),'')
  ,NULLIF(TRIM(GFT_DIV_CD),'')
  ,GFTMNEY_DOLLAR_AMT
  ,APRV_DE
  ,NULLIF(TRIM(TRNSFER_YN),'')
  ,NULLIF(TRIM(SETLE_BANK_CD),'')                -- 🆕 [O213-F Y3-J] 선물금 정산은행(PM039)
FROM {{ source('bronze_crm','TM_RM_RELATNSP_GFTMNEY_INFO') }} WHERE RELATNSP_KEY IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY RELATNSP_KEY, MNG_NO ORDER BY SNDNG_DE DESC NULLS LAST)=1
