-- CRM_CHILD: 결연 아동 마스터 (BRONZE TM_RM_CHILD_MSTR_INFO → SILVER) · 🆕 O188-F 2차-A 신설(종전 미연결 원천)
-- Co-authored with CoCo
-- grain = CHILD_CD (📏 xf98254 유일 실측)
SELECT
  CHILD_CD AS CHILD_CD,
  NULLIF(TRIM(CHILD_NO),'') AS CHILD_NO,
  NULLIF(TRIM(BPLC_CD),'') AS BPLC_CD,
  NULLIF(TRIM(SEX),'') AS SEX,
  NULLIF(TRIM(RELATNSP_STAT_CD),'') AS RELATNSP_STAT_CD,
  NULLIF(TRIM(CHILD_STAT_CD),'') AS CHILD_STAT_CD,
  NULLIF(TRIM(CHILD_DTL_STAT_CD),'') AS CHILD_DTL_STAT_CD,
  NULLIF(TRIM(REGIST_DIV_CD),'') AS REGIST_DIV_CD,
  FRST_REGIST_DT AS FRST_REGIST_DT,
  LAST_REGIST_DT AS LAST_REGIST_DT,
  RE_UPDT_DT AS RE_UPDT_DT,
  NULLIF(TRIM(MNYRS_NATION_CD),'') AS MNYRS_NATION_CD,
  NULLIF(TRIM(CMS_CHILD_NO),'') AS CMS_CHILD_NO,
  'CRM'                          AS DW_SOURCE_SYSTEM,
  'BRONZE_CRM.TM_RM_CHILD_MSTR_INFO' AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP()            AS DW_LOAD_TS,
  CURRENT_TIMESTAMP()            AS DW_UPDATE_TS,
  NULL                           AS DW_BATCH_ID
FROM {{ source('bronze_crm','TM_RM_CHILD_MSTR_INFO') }}
WHERE CHILD_CD IS NOT NULL
