-- CRM_MSG_TEMPLATE_BUTTON: 알림톡 템플릿 버튼 (BRONZE TD_MS_AT_TMPLAT_BTN_LIST → SILVER) · 🆕 O188-F 2차-A 신설(종전 미연결 원천)
-- Co-authored with CoCo
-- grain = TMPLAT_ID, BTN_SEQ (📏 xf98254 유일 실측)
SELECT
  NULLIF(TRIM(TMPLAT_ID),'') AS TMPLAT_ID,
  BTN_SEQ AS BTN_SEQ,
  NULLIF(TRIM(BTN_TY_CD),'') AS BTN_TY_CD,
  NULLIF(TRIM(BTN_NM),'') AS BTN_NM,
  NULLIF(TRIM(ANDROID_URL),'') AS ANDROID_URL,
  NULLIF(TRIM(IOS_URL),'') AS IOS_URL,
  NULLIF(TRIM(MOBILE_URL),'') AS MOBILE_URL,
  NULLIF(TRIM(PC_URL),'') AS PC_URL,
  FRST_REGIST_DT AS FRST_REGIST_DT,
  LAST_UPDT_DT AS LAST_UPDT_DT,
  'CRM'                          AS DW_SOURCE_SYSTEM,
  'BRONZE_CRM.TD_MS_AT_TMPLAT_BTN_LIST' AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP()            AS DW_LOAD_TS,
  CURRENT_TIMESTAMP()            AS DW_UPDATE_TS,
  NULL                           AS DW_BATCH_ID
FROM {{ source('bronze_crm','TD_MS_AT_TMPLAT_BTN_LIST') }}
WHERE TMPLAT_ID IS NOT NULL AND BTN_SEQ IS NOT NULL
