-- CRM_PAYMENT_METHOD_HIST: 결제수단 변경 이력 (BRONZE TH_PM_SETLE_INFO_HIST → SILVER) · 🆕 O188-F 2차-A 신설(종전 미연결 원천)
-- Co-authored with CoCo
-- grain = SETLE_KEY, UPDT_DT (📏 xf98254 유일 실측)
-- 🔴 민감 컬럼 제외(개인·결제 식별정보 · 분석 가치 없음 · 노출 위험): CARD_TRMVT, PAYER_NM, ETC_CTTPC, CRTFC_FILE_NM, CRTFC_DATA_CTNT, BILLKEY, APPLCNT_NM, APPLCNT_ETC_CTTPC, UPDUSR_NM, RGSTR_NM
SELECT
  SETLE_KEY AS SETLE_KEY,
  UPDT_DT AS UPDT_DT,
  NULLIF(TRIM(MBER_NO),'') AS MBER_NO,
  NULLIF(TRIM(CPR_DIV_CD),'') AS CPR_DIV_CD,
  NULLIF(TRIM(SETLE_CD),'') AS SETLE_CD,
  WTDRW_STRT_DE AS WTDRW_STRT_DE,
  WTDRW_ASMT_SQNC AS WTDRW_ASMT_SQNC,
  NULLIF(TRIM(FNLT_DIV_CD),'') AS FNLT_DIV_CD,
  NULLIF(TRIM(FNLT_CD),'') AS FNLT_CD,
  NULLIF(TRIM(SETLE_ENTRPS_CD),'') AS SETLE_ENTRPS_CD,
  ACNUT_SER_NO AS ACNUT_SER_NO,
  NULLIF(TRIM(CARD_DIV_CD),'') AS CARD_DIV_CD,
  NULLIF(TRIM(ETC_CTTPC_REL_CD),'') AS ETC_CTTPC_REL_CD,
  NULLIF(TRIM(PAYER_MBER_REL_CD),'') AS PAYER_MBER_REL_CD,
  NULLIF(TRIM(CRTFC_MTH_CD),'') AS CRTFC_MTH_CD,
  CRTFC_DE AS CRTFC_DE,
  FILE_SIZE AS FILE_SIZE,
  NULLIF(TRIM(SETLE_STAT_CD),'') AS SETLE_STAT_CD,
  NULLIF(TRIM(BF_SETLE_STAT_CD),'') AS BF_SETLE_STAT_CD,
  NULLIF(TRIM(RQST_DIV_CD),'') AS RQST_DIV_CD,
  NULLIF(TRIM(RCEPT_DIV_CD),'') AS RCEPT_DIV_CD,
  NULLIF(TRIM(APRV_YN),'') AS APRV_YN,
  APRV_REQUST_KEY AS APRV_REQUST_KEY,
  APRV_RST_KEY AS APRV_RST_KEY,
  FRST_BEGIN_DE AS FRST_BEGIN_DE,
  NULLIF(TRIM(RQEST_EXCL_YN),'') AS RQEST_EXCL_YN,
  RQEST_EXCL_STRT_DE AS RQEST_EXCL_STRT_DE,
  RQEST_EXCL_END_DE AS RQEST_EXCL_END_DE,
  NULLIF(TRIM(APPLCNT_ETC_CTTPC_REL_CD),'') AS APPLCNT_ETC_CTTPC_REL_CD,
  NULLIF(TRIM(APPLCNT_MBER_REL_CD),'') AS APPLCNT_MBER_REL_CD,
  BF_SETLE_KEY AS BF_SETLE_KEY,
  NULLIF(TRIM(OPERT_DIV_CD),'') AS OPERT_DIV_CD,
  NULLIF(TRIM(CRTFC_TY_CD),'') AS CRTFC_TY_CD,
  NULLIF(TRIM(USE_YN),'') AS USE_YN,
  REGIST_DT AS REGIST_DT,
  'CRM'                          AS DW_SOURCE_SYSTEM,
  'BRONZE_CRM.TH_PM_SETLE_INFO_HIST' AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP()            AS DW_LOAD_TS,
  CURRENT_TIMESTAMP()            AS DW_UPDATE_TS,
  NULL                           AS DW_BATCH_ID
FROM {{ source('bronze_crm','TH_PM_SETLE_INFO_HIST') }}
WHERE SETLE_KEY IS NOT NULL AND UPDT_DT IS NOT NULL
  -- 🔴 O179 이슈 B · 회원 마스터 미실재(고아) 제거 — 정의 = macros/gn_member_master_filter.sql
  AND {{ gn_member_master_filter("NULLIF(TRIM(MBER_NO),'')") }}
