-- CRM_INSTT_ACCOUNT: 기관 입금 계좌 (BRONZE TM_PM_INSTT_ACNUT → SILVER) · 🆕 O188-F 2차-A 신설(종전 미연결 원천)
-- Co-authored with CoCo
-- grain = ACNUT_SER_NO (📏 xf98254 유일 실측)
-- 🔴 민감 컬럼 제외(개인·결제 식별정보 · 분석 가치 없음 · 노출 위험): ACCTNO
SELECT
  ACNUT_SER_NO AS ACNUT_SER_NO,
  NULLIF(TRIM(CPR_DIV_CD),'') AS CPR_DIV_CD,
  NULLIF(TRIM(ACNUT_DIV_CD),'') AS ACNUT_DIV_CD,
  NULLIF(TRIM(BANK_CD),'') AS BANK_CD,
  NULLIF(TRIM(ACNUT_PRP),'') AS ACNUT_PRP,
  NULLIF(TRIM(ACNUT_ABRV),'') AS ACNUT_ABRV,
  NULLIF(TRIM(CHRG_DEPT_CD),'') AS CHRG_DEPT_CD,
  NULLIF(TRIM(REGIST_USE_YN),'') AS REGIST_USE_YN,
  NULLIF(TRIM(USE_YN),'') AS USE_YN,
  FRST_REGIST_DT AS FRST_REGIST_DT,
  LAST_UPDT_DT AS LAST_UPDT_DT,
  'CRM'                          AS DW_SOURCE_SYSTEM,
  'BRONZE_CRM.TM_PM_INSTT_ACNUT' AS DW_SOURCE_TABLE,
  CURRENT_TIMESTAMP()            AS DW_LOAD_TS,
  CURRENT_TIMESTAMP()            AS DW_UPDATE_TS,
  NULL                           AS DW_BATCH_ID
FROM {{ source('bronze_crm','TM_PM_INSTT_ACNUT') }}
WHERE ACNUT_SER_NO IS NOT NULL
